### ISSUE TITLE
Styleguide |  Fixed sidebar navigation for current links and scroll through

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1002]
As a developer I want to always be able to see the sidebar when I'm using the Styleguide so I can navigate around easily.
 
# Technical Notes
This could involve creating a react component

**Comment by gnakm** [comment]
The side nav will be outside the canvas so that it is sticky and canvas is the only thing scrolling. Also ignore all the white space below. 

For v1. we won't have _branding,_ _typography_ and _colors_ ready. 

![side nav closed](https://cloud.githubusercontent.com/assets/13420618/23722404/3dfb4ef0-0413-11e7-89d3-78b5e5f43f6d.png)

![side nav open](https://cloud.githubusercontent.com/assets/13420618/23722408/48171928-0413-11e7-84dd-c9a984e31213.png)

Menu items listed out:

- Introduction
- Typography
  - Headings and body
  - Styles
- Colors
- Buttons
- Search
- Dropdown menus
  - Searchable dropdown 
- Checkboxes and radio buttons
  - Vertical checkboxes
  - Horizontal checkboxes
  - Vertical radio buttons
  - Horizontal radio buttons
- Data input
- Tables
- Tab
- Accordions
- Text input
  - Text input errors
- Required fields
- Loading indicators
- Alerts
- Layout
  - Navigation bar
  - App canvas
  - Actions
  - Footer
  - Messages
    - Success
    - Alert
    - Status
- Branding
- Dashboard
- Modals

**Comment by gnakm** [comment]
@shanear Could we add a section called` Link buttons` under buttons? It is will a subsection under button but as planned for now, it will be flat.

**Comment by mmlumba** [comment]
@gnakm Where would the link go for the sections that don't currently exist in the living style guide?

**Comment by gnakm** [comment]
@mmlumba I was thinking of adding Links under the Buttons sections (but nested as a subcategory if that makes sense).

**Comment by mmlumba** [comment]
@gnakm Just to clarify, I wanted to know where the link would "jump" to in the style guide if the section doesn't exist yet (ie if the link would not go anywhere, lead to a "coming soon" section, etc).

**Comment by gnakm** [comment]
@mmlumba gotcha! How about title of the component and in body "This component is not ready yet. Stay tuned! :) "

**Comment by gnakm** [comment]
@mmlumba Let me know if this makes sense. If it does, I will add it to the AC on top
The body scroll will always be longer than the side navigation so, 
- The page should be anchored at the top of canvas before allowing scrolling within the canvas
- Side navigation scroll should only scroll to the last component listed on the left (in this case modal)
- Body scroll goes all the way to the bottom of the page
- In order to get to the bottom of the page, passed the canvas and to footer, you can only do it from scrolling from the body section.

**Comment by mmlumba** [comment]
Shorter nav sections (for iteration 1):
- Introduction
- Typography
- Colors
- Buttons
- Search
- Dropdown Menus
- Checkboxes and Radio Buttons
- Date Input
- Tables
- Tabs
- Accordions
- Forms fields
- Loading indicators
- Alerts
- Layout
- Messages
- Branding
- Dashboard
- Modals

**Comment by astewarttistatech** [comment]
Current view on the right vs. the mocks on the left
<img width="1133" alt="screen shot 2017-04-24 at 8 54 53 am" src="https://cloud.githubusercontent.com/assets/23038505/25338004/c5661ffa-28cb-11e7-812c-5160272e9032.png">

@mmlumba Could you take a look at the Style Guide and make the appropriate changes.

**Comment by mmlumba** [comment]
@astewarttistatech the navigation is scrollable on the left side so you can scroll on the nav to see the rest of the items in the navigation

**Comment by gnakm** [comment]
It's scrollable and there will be a 2nd version for sidenav with more specific ACs for length of the horizontal bars and spacing.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod
Browsers: FF and Chrome

Steps to Validate: 
1. Go to living style guide 
2. Scroll over the navbar

Screenshots: 
![styleguidescroll](https://cloud.githubusercontent.com/assets/23038505/25441318/d5ac52c6-2a6f-11e7-8e6f-ab01cb384afb.gif)
