### ISSUE TITLE
Unify individual queue table view titles

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10043]
[Attorney](https://github.com/department-of-veterans-affairs/caseflow/blob/e7b449a3cfa29a6a5992cad4f8e0ae92cc45303b/client/app/queue/AttorneyTaskListView.jsx#L101) and [generic queues](https://github.com/department-of-veterans-affairs/caseflow/blob/e7b449a3cfa29a6a5992cad4f8e0ae92cc45303b/client/app/queue/ColocatedTaskListView.jsx#L63) are both titled "Your cases" (they have [different](https://github.com/department-of-veterans-affairs/caseflow/blob/e7b449a3cfa29a6a5992cad4f8e0ae92cc45303b/client/COPY.json#L103) [constants](https://github.com/department-of-veterans-affairs/caseflow/blob/e7b449a3cfa29a6a5992cad4f8e0ae92cc45303b/client/COPY.json#L118), but both constants result in the same string) while the judge queue reads "Review x cases". This ticket exists to unify the handling of the individual queue table view titles.

Let's first decide whether we can change the title to match what we have for attorneys and the generic queue (cc @sneha-pai @allyceh), but if we cannot then let's explore other ways to unify how we determine what the title will be without relying on the user's role on the front-end (perhaps by passing the title from the back-end?) in preparation for [consolidating the three queues](https://github.com/department-of-veterans-affairs/caseflow/issues/10032) into a single component for all three. When we [add tabs for the judge queue view](https://github.com/department-of-veterans-affairs/caseflow/issues/10044) we will show the count of cases just below the title that currently shows the number of cases they have to review so that count may be redundant.

Attorney queue | Judge review cases view | Generic (Colocated) queue
--- | --- | ---
![image](https://user-images.githubusercontent.com/32683958/54574472-d6f14880-49c6-11e9-9888-787752e27c60.png) | ![image](https://user-images.githubusercontent.com/32683958/54574495-ea041880-49c6-11e9-8bf2-2cb101935cfe.png) | ![image](https://user-images.githubusercontent.com/32683958/54574475-d953a280-49c6-11e9-8103-713a93577459.png)

## Acceptance criteria
* [ ] Use the same COPY.json constant for the attorney and generic queue titles.
* [ ] Determine whether we can re-title the judge queue to "Your cases".
* [ ] Build the queue table view title the same way for all three individual queues.

**Comment by laurjpeterson** [comment]
@sneha-pai and I connected. We agree with changing the Judge Review queue to say "Your cases" especially because they will have more task types than just reviewing cases for decision signing. 

Just a question - Is it possible to add the # of tasks in a person's queue to the Your cases title? like: "Your cases (x)" Reasoning:
- I could see judges asking for the total # cases in their queue back in the title because it was convenient to see their case load
- I think other teams also benefit from seeing the # of cases in their queue at a glance

Or, would that number still rely user's role on the front-end?

Moving this out of Design and into Backlog.

**Comment by araposo-tistatech** [comment]
@lomky based on Demo it appears this was completed. Can this one be closed?

**Comment by lomky** [comment]
yup!
