### ISSUE TITLE
Intake | User not authorized error, same RO

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10087]
EP creation fails with "User not authorized" error.
Alternate error message: An error occurred while establishing the claim: Claim not established; Veteran is employed by this station.

VBMS investigation reveals that a User may not perform an Intake for a veteran who is an employee in the same RO as the User.

However, the sensitivity check performed early in the intake process does not catch this case.

I have reached out the user in question to find a work around for now. The VBMS suggestion was to use a different CSS account tied to a different RO, but after checking with support, most users do not have multiple accounts.

#10030 is related alert fix. See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3467/events/277130/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3467/events/294187/

**Comment by pkarman** [comment]
cc @msj0nes

**Comment by pkarman** [comment]
Moving this to the backlog as I think there are still actionable steps here but this particular issue has been turned over to support.

**Comment by pkarman** [comment]
More of these:

* [ ] Supplemental Claim 1484
* [ ] Supplemental Claim 5754
* [ ] Higher Level Review 2208

We should see if another EP was created to work around in the meantime, and either way, cancel these async jobs. TBD how best to contact the relevant users.

**Comment by pkarman** [comment]
Assigned the EPE of each affected claim to user BVAMBRASWELL and was able to establish that way.

**Comment by pkarman** [comment]
According to Nate Carlson, BGS may have a service that can correlate whether user and veteran share a RO.

**Comment by leikkisa** [comment]
When I try the bgs version of can_access? directly with use_find_veteran_info set to false instead of true, it returns the correct error that the user cannot access the veteran.  I believe there was another ticket affected by this bug (unless it was the same issue!).

**Comment by pkarman** [comment]
You may have been thinking of #11042 

It sounds like we might want to try both checks? Or revert to the BGS version? I'm not sure of the background on why the toggle-able option was added.

**Comment by pkarman** [comment]
I think what's interesting is that `veteran.find_by_file_number` does not seem as strict about what the user can *write/modify* the veteran record. Whereas `claimants.find_flashes` is the more strict/accurate when it comes to whether the user can *write/modify*.

https://github.com/department-of-veterans-affairs/ruby-bgs/blob/2d0e08ea4157b725242777a6f876fc199f503b61/lib/bgs/services.rb#L72

What do you think about adding a new method called `may_modify?` that wraps around the `find_flashes` call, and using that instead at the front end of the Intake process? It seems more accurate for the purposes of Intake, and having that small level of indirection should make it possible to improve on what call/logic we use in the future (if that should change upstream).

**Comment by leikkisa** [comment]
I think that's a good idea, that way we don't have to mess with where can_access is being used elsewhere.

**Comment by pkarman** [comment]
I notice that we can find a user by participant_id as well, so that might help us identify the edge case where the user and the veteran are the same person.

**Comment by leikkisa** [comment]
Some notes from David Hamilton, in case we decide to use these (not sure if it's necessary).

There are two services you will need to call to determine if a veteran or a relative is employed at the station. First you will need to call

http://bepwebtest.vba.va.gov/PersonWebServiceBean/PersonWebService?wsdl
findEmployeeByFileNumber (or ParticipantId)

This will return an EmployeeDTO with a List of EmployeeStnDTOs. Just because something is returned in this list does not necessarily mean it must be restricted.

If the list of EmployeeStnDTO contains an EmployeeStnDTO with relationship type “Veteran” then the veteran’s Sensitivity level must be evaluated by making the next service call. *No need to make the second call if there is no DTO with type “Veteran”


http://bepwebtest.vba.va.gov/SecurityWebServiceBean/SecurityWebService?wsdl

findSntvtyLevelByFileNumber (or ParticipantId)

This one is a little tricky. You do not want the bdnStnNbr for this, you want the fcltyTypeCd + cd. You may see something like this
bdnStnNbr=349
cd=17
fcltyTypeCd=3
So in this case the potentially station is actually 317, not 349.
 
When you’ve gathered your list of EmployeeStnDTOs to evaluate, for each dto, you will need to check the following to determine if the station should be restricted: 
 
1.       If the Relationship Type is not “Veteran” the station should be restricted
2.  OR If the Sensitivity Reason is in the following list: 
Relative of Local VA Employee
VBA Employee
Veteran 
Work Study
**The following 2 reasons are not reasons to restrict access to a station:
Non-VBA Employee
Veteran Service 
3.  OR if the current user’s subjectId matches the participant Id of the DTO

**Comment by pkarman** [comment]
I tried the `find_flashes` BGS call for SC 69929 and it returned true (can_access) so in this case it didn't help. I am going to code up this suggest from David to see if that helps.

**Comment by leikkisa** [comment]
@pkarman You have to spoof the user on the intake, and set use_find_veteran_info to false.  That works for me anyway

**Comment by pkarman** [comment]
@leikkisa you tried that for SC 69929? That's what I thought I did and it returned the flashes w/ no error.

**Comment by leikkisa** [comment]
@pkarman Yeah, can access returned false, and this is in there:
```<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>This is an employee record at your station</faultstring><detail><ns2:ShareException xmlns:ns2="http://services.share.benefits.vba.va.gov/"><message>This is an employee record at your station</message></ns2:ShareException></detail></S:Fault></S:Body></S:Envelope>```

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/ruby-bgs/pull/79

**Comment by pkarman** [comment]
@leikkisa I started on #11411 and will try and finish this week.

**Comment by pkarman** [comment]
The sensitivity check is failing on this case in production:
```
RequestStore[:current_user] = User.find 3309
conflict = ExternalApi::BgsVeteranStationUserConflict.new(veteran_participant_id: 4012373)
conflict.call
```
presumably because the Veteran Service Officer case is slipping through. Re-opening this and working on fix in #11749

**Comment by pkarman** [comment]
David clarified via email:
> The sensitivity level call needs to be made if the station does NOT contain a veteran station DTO.
and that fixes the outlier. I have updated the main algorithm comment above.

**Comment by leikkisa** [comment]
Closing this issue, I believe it has been resolved thanks to @pkarman beefing up the access checks during intake with a few more checks.
