### ISSUE TITLE
How should we deploy code with migrations? (Discussion on 3/6)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1011]
Right now, if we deploy code that adds columns to certain tables, it can cause a stream of 500's and possibly data inconsistencies between VBMS, VACOLS.

How should we:
1) Be aware that a deployment contains a problematic DB migration?
2) Deploy code that contains problematic DB migration?

It should be noted that we can almost entirely alleviate this problem if:
a) We refactor these long lived PSQL transactions to be much shorter
b) We add a more robust transactional framework around operations that touch multiple systems. This might include a retry queue or something like that. (This is important for more than just DB migrations)

## Outcomes
1) Start daily deploys now
2) Only backwards compatible DB changes
3) Audit certification and dispatch for big writes and create a retry mechanism for them (captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/1077)

**Comment by askldjd** [comment]
"We refactor these long lived PSQL transactions to be much shorter"

I think this will resolve one of the issue, but doesn't resolve everything entirely. Since we deploy during business hours, our changes needs to allow for _hot compatibility_. And in order to achieve this, development side needs to ensure all changes are future compatible. [See video](https://www.youtube.com/watch?v=R6bVTthtnZ0).

Personally, I only see two ways out of this:

1. Change our development process to ensure hot compatibility, and also deploy more frequently.
2. Change our deployment schedule to deploy during off-hours (e.g. 9pm EST).

**Comment by shanear** [comment]
## Outcomes
1) Start daily deploys now
2) Only backwards compatible DB changes
3) Audit certification and dispatch for big writes and create a retry mechanism for them (captured here: https://github.com/department-of-veterans-affairs/caseflow/issues/1077)
