### ISSUE TITLE
Intake | PIF exists for EP code

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10147]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4203/events/281412/

PIF already in use

**Comment by pkarman** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4386/events/293420/

**Comment by leikkisa** [comment]
There was an end product canceled on 3/1/2019, and it takes some time for the modifier to become available again (I don't know how long), so this should eventually succeed.

Another issue altogether is that the user has created 4 Supplemental Claims for the same veteran/receipt_date/benefit_type etc.  Although it's possible that there were 4 different forms, they all have one request issue, and all are for PTSD.  So it seems like they should be editing the first SC, because making more will exacerbate the reporting of this bug since it's trying to establish more claims simultaneously.  It doesn't look like these were accidentally automatically created because of the intake completion times.

Further, there is a pending SC end product for this veteran, but it looks like it was created without Caseflow or something weird (we don't have it in our EPE table, and the RequestIssue isn't in our table either).  The claim_id is 71337294, the contention id is 88039042, neither is stored in our tables, and the contention text differs from all of the request issues in the above 4 SCs.

Lastly, the one successfully established SC is missing an end product establishment, so that could be for the canceled end product, or the pending one, don't know.

**Comment by pkarman** [comment]
This makes me wonder if we need some kind of validation code during intake that tries to identify and prevent "duplicate" intakes, as if the user was just "trying it again because it didn't seem to work."

**Comment by pkarman** [comment]
SC 4244 has a EPE w/o a reference_id but with the same code (040SCR) and claim date (3/27/2019) as the EP 71337294.

It's as if the EP got created but the EPE and Request Issue never got updated.

**Comment by pkarman** [comment]
SC 4240 (the one missing at EPE) has one request issue marked `duplicate_of_rating_issue_in_active_review` so I wonder if that ineligible effort blocked the user and they started multiple times to try and work around.

**Comment by pkarman** [comment]
> There was an end product canceled on 3/1/2019

I see one for 4/1/2019 -- could that comment be a typo?

**Comment by pkarman** [comment]
Here's what I think happened.

The veteran (participant id 33649580) has duplicate file numbers. The initial SC 4238 was intaken under one file number, and then the EP was manually canceled and then attempted under the other file number. However, the EPE had not yet synced, so the SC 4240 was marked as an ineligible duplicate.

Then the user tried again a couple times (4318, 4407) to work around, using a nonrating (4318) and a different contested rating issue (4407).

Then the user got frustrated and went into VBMS directly and created the EP.

I think we need to clean up manually.

* delete 4318 and 4407
* manually connect 4240's EPE and Request Issue with the claim 71337294 and contention 88039042
* update the contention text on 88039042 to match rating issue 84702991

@leikkisa thoughts?

**Comment by leikkisa** [comment]
Oh, that explains this behavior.  I agree with the manual data update plan.  I don't think we can update the contention text in VBMS, but we can remove the other contention and add a new one, which we can still do.  I wonder if we can prevent this in the future with some training/FAQ information about how long certain processes take so folks know that they can wait to resolve problems like this.

The 3/1/2019 was totally a typo, I meant to say the same day basically.

**Comment by pkarman** [comment]
Data clean up is complete.
