### ISSUE TITLE
Improve copy for when to email CorporateDB to add a claimant

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#10202]
Jennifer is getting requests that she is unable to support, such as that we're not listing POAs in claimants, or getting a message that someone got a not found error when searching for a Veteran (but without any more information such as an ID).

If Jennifer continues to mostly gets Caseflow requests, and not requests to make changes to the Corporate DB, then we may want to consider directing users to the support form and funneling the appropriate requests to her from there.

**Comment by leikkisa** [comment]
@carolaponce I think information about POAs would also be good to add to the FAQ. Pasting in a Slack comment from Rachel Sauter:

...sometimes the POA fills out a form for the veteran, but in that scenario, they are standing in the shoes of the veteran - just filling out the form doesn't make them the claimant. The only other thing I can think of is the fee agreement case. In those cases, the rep would have held POA in the veteran's claim for benefits, but then once that claim becomes contested, the rep cannot hold the POA anymore.

**Comment by carolaponce** [comment]
@leikkisa I don't understand the use case fully but, I do agree if this this a clarification users need to understand it should be documented somewhere.  The FAQs as we have them, explain how to use intake.  This might be more of a procedural documentations.  

I will follow up in Slack about where to house this documentation with Sadia who I think is updating caseflow and AMA documentation.

**Comment by carolaponce** [comment]
@leikkisa Per Sadia's response, your original recommendation to include in the FAQs is better.  I'll review with Rachel and Will. I don't understand the use case fully, so I'll figure out what information should go on the help page.

**Comment by carolaponce** [comment]
Todo: 

- Reach to Rachel Sauter to better understand copy for FAQ
- Coordinate including traning material with @Will
- Request copy modification in help page

**Comment by will** [comment]
I don’t have any training material ready, sorry :(

**Comment by carolaponce** [comment]
Sorry @will I tagged you by mistake.

**Comment by carolaponce** [comment]
Contacted Rachel Sauter to make sure I understand the right information to include in our training materials + FAQs.

**Comment by carolaponce** [comment]
Clarified with Sally about the FAQ content needed.

Use Case: Power of Attorney holders often fill out an appeal, HLR or SC for a Veteran, they mistakenly use their name and ID instead of the Veterans.  Caseflow assistants don’t know how to intake this information since the POA is not in the list of Claimants.

Solutions: Users need to process these intakes under the Veteran’s name and ID

How to achieve this: Training/FAQA

**Questions:**

- To Jennifer - how often are you seeing this problem?
- Is there an additional form necessary to indicate Veteran is using a POA
- Does the POA/Veteran need to be sent any communication to let them form was processed under the Veteran info and not the POA
- Besides FAQs and Training, how do we share the fact that a POA needs to fill out review/appeal forms under Veteran’s info? VA.gov
- Do we need more specifications in the forms themselves?

Next steps:

- [ ] Consult with Jennifer about her experience
- [ ] Consult with Rachel S about right copy for FAQs
- [ ] Consult with Jane about forms
- [ ] Review info in va.gov + propose any changes

**Comment by carolaponce** [comment]
Pasting in a Slack comment from Rachel Sauter:

...sometimes the POA fills out a form for the veteran, but in that scenario, they are standing in the shoes of the veteran - just filling out the form doesn't make them the claimant. The only other thing I can think of is the fee agreement case. In those cases, the rep would have held POA in the veteran's claim for benefits, but then once that claim becomes contested, the rep cannot hold the POA anymore.

**Comment by leikkisa** [comment]
I am closing this ticket, we have another ticket open to stop sending an email and figure out another system (such as YourIT).
