### ISSUE TITLE
Tech spec | How might we store 1+ decision documents per appeal?

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#10210]
Currently the logic that processes outcoding for appeals uses the decision document as the central piece of data that connects and manages outcoding related actions. It assumes that each appeal has exactly one decision document (the decision document to be mailed to the veteran).

However, there are instances when the Veteran may have a second decision document mailed to them, and therefore a second instance of "outcoding". For example, there can be a second decision document if a Motion to Vacate is granted. 

Currently, the DB schema allows for an AMA appeal to have more than one decision document (row in the `decision_document`s table). However, if the decision document creation is attempted via the `idt/api/v1/appeals/:appeal_id/outcode` endpoint, it will fail if the following conditions are not met: 

- if `BvaDispatchTask` is already completed, outcoding will fail ***

## Scenarios
- "Closed"/Post-decisional appeals with Motions to Vacate MailTasks
   - Note: we need to advise what Motion to Vacate task to use. Judge Motion to Vacate task?
-  "Closed"/Post-decisional appeals with Motions to Reconsideration MailTasks

## AC
- [x] Investigate how IDT calls this endpoint
- [x] Investigate whether the current implementation was written in a way to prevent errors, like accidentally multiple BvaDispatchTasks
- [ ] (blocked) Write tech spec to suggest ways to change the current checks (see above) to support a second "outcoding" and create a second row in the `decision_documents` table for that appeal

## Notes
- Need to know that the outcoding is related to a motion to vacate 
   - Could be a new method on the BVA dispatch task?
   - Or, we could look up if the appeal has a motion to vacate task
- Identify places in the code where one decision document is assumed

**Comment by laurjpeterson** [comment]
Adding this to post-decisional motions workflows because they could have multiple decision documents.

**Comment by monfresh** [comment]
The current check to see if there are multiple BvaDispatchTasks for the appeal being outcoded was added as a defensive measure, which was a good thing because about a month later on October 30, we noticed instances of duplicate tasks being created due to a bug, which was fixed that day: https://github.com/department-of-veterans-affairs/caseflow/pull/7603

I don't see any instances of this bug in Sentry, so presumably we can remove this check. Either way, it doesn't seem to be related to this tech spec since the creation of BvaDispatchTasks doesn't happen during outcoding. 

For our purposes, I think we only need to figure out how we can identify that a second decision document is allowed for an appeal, such as the presence of a Motion to Vacate task.

**Comment by monfresh** [comment]
Other questions that came up after talking with @aroltsch:
- Are there subsequent actions that need to happen in Caseflow after the document upload? For example, during outcoding, we currently create board grant effectuations and EPs. We also close all the appeal's request issues as decided.
- Does the decision document need to have some attribute to differentiate it from other BvaDispatch outcoded documents? The current attributes for decision documents are:
  - citation_number 
  - decision_date 
  - redacted_document_location
  - file

If the subsequent actions are different in the Motion to Vacate scenario, then it probably makes sense to create a separate endpoint to process these types of requests rather than having complicated logic to add on to the existing endpoint. That way, we know that if a request came to this endpoint, it is only for the Motion to Vacate or Motion to Reconsideration scenarios. 

A related question that came up was "are these scenarios considered `outcoding`?" In other words, is there a particular reason we are thinking about this specifically in connection with the current outcoding endpoint?

**Comment by laurjpeterson** [comment]
@laurjpeterson to connect with Paul Saindon. and to connect @geronimoramos with Corey Benjamin re: BVA dispatch questions.

**Comment by jimruggiero** [comment]
@msj0nes Apologies, I thought this was a different issue when we were talking the other day. This one is foxtrot.

**Comment by leikkisa** [comment]
I am closing this ticket because for Motions to Vacate, we've learned that this will be handled through creating a new appeal stream, so there will still be a 1:1 relationship between Appeal and DecisionDocument.
