### ISSUE TITLE
App Canvas | Header | Update Route Claim page titles

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1033]
As a Product Owner, I would like to have the tiltes on the Route Claim pages updated to include the words "Route Claim" and/or added description so that the tile reflects the process stage and clear activity for the current claim.

# Acceptance Criteria
1. Verify that the following Route Claim pages have been updated with the new title: 

| Page | Current Page Title | New Page Title |
| --- | --- | --- |
| EP Creation | Create End Product | Route Claim: Create End Product
| Existing EP | Create End Product | Route Claim: Existing End Product(s)
| Route Claim - VBMS Note | Route Claim | Route Claim: Add VBMS Note
| Route Claim - Send Email | Route Claim | Route Claim: Send Email Notification
| Route Claim - VACOLS Note | Route Claim | Route Claim: VACOLS Updated
| Route Claim - Unsupported | Route Claim | Route Claim: Process Outside of Caseflow
| Route Claim - VBMS/VACOLS | Route Claim | Route Claim: VACOLS Updated, Add VBMS Note

## Mock(s)
<img width="567" alt="screen shot 2017-03-10 at 8 08 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819076/a08a626e-05cf-11e7-9265-c8a5dfef8675.png">
<img width="552" alt="screen shot 2017-03-10 at 7 43 51 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819083/b89bb11e-05cf-11e7-8660-f938786f1e3c.png">
<img width="582" alt="screen shot 2017-03-10 at 8 08 48 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819089/cb53d5c0-05cf-11e7-9fff-7d3e8cd70e0d.png">
<img width="726" alt="screen shot 2017-03-10 at 8 09 01 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819094/d74aea1c-05cf-11e7-916a-cfa9dfec27f7.png">
<img width="637" alt="screen shot 2017-03-10 at 8 09 11 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819109/ea0f9094-05cf-11e7-92ec-6cad56a0c5c3.png">
<img width="634" alt="screen shot 2017-03-10 at 8 18 41 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819118/f7051abc-05cf-11e7-838d-8babf646044e.png">
<img width="776" alt="screen shot 2017-03-10 at 8 09 26 pm" src="https://cloud.githubusercontent.com/assets/4975959/23819127/13c86e88-05d0-11e7-88bd-515e6e939811.png">

# Reference Stories
n/a

**Comment by ariperez-gov** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/1171

**Comment by ariperez-gov** [comment]
https://github.com/department-of-veterans-affairs/caseflow/pull/1171

**Comment by astewarttistatech** [comment]
@lakohl do you know how to get to the "Route Claim: Process outside of claim", because of now, the National Cemetery Administration (which has a typo on the mocks) doesn't route to that page.

**Comment by astewarttistatech** [comment]
**PASSED**
Validated in: UAT
Steps to Validate:
1. Go to Dispatch as a caseworker and select several special issue categories in order to route EPs to different places. 
2. Verify the titles in each of the route claim pages. 

Screenshots: 
<img width="1263" alt="screen shot 2017-03-15 at 9 13 03 am" src="https://cloud.githubusercontent.com/assets/23038505/23951431/67db6aa6-0964-11e7-9179-037876b7e850.png">
<img width="1349" alt="screen shot 2017-03-15 at 9 23 18 am" src="https://cloud.githubusercontent.com/assets/23038505/23951430/67d8d534-0964-11e7-9cda-acbe7fd80ce8.png">
<img width="1239" alt="screen shot 2017-03-15 at 9 25 25 am" src="https://cloud.githubusercontent.com/assets/23038505/23951436/67e2f6d6-0964-11e7-84e4-12ceb0b7f24a.png">
<img width="1297" alt="screen shot 2017-03-15 at 9 29 03 am" src="https://cloud.githubusercontent.com/assets/23038505/23951432/67dfcd58-0964-11e7-830d-75a83ecd86b0.png">
<img width="1340" alt="screen shot 2017-03-15 at 9 30 04 am" src="https://cloud.githubusercontent.com/assets/23038505/23951435/67e19674-0964-11e7-8f99-7b20ab440236.png">
<img width="1180" alt="screen shot 2017-03-15 at 9 35 42 am" src="https://cloud.githubusercontent.com/assets/23038505/23951433/67e058ae-0964-11e7-942a-bd6e5766114c.png">
<img width="1310" alt="screen shot 2017-03-15 at 9 42 30 am" src="https://cloud.githubusercontent.com/assets/23038505/23951434/67e05656-0964-11e7-8a75-d7597969cf7e.png">
