### ISSUE TITLE
Stop creating duplicate ColocatedTasks

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#10337]
We [recently discovered](https://github.com/department-of-veterans-affairs/caseflow/issues/10335) that we have created a few dozen duplicate `ColocatedTask`s over the past few months at the rate of a few per week. Duplicate `ColocatedTask`s can result in delays to decisions being dispatched, redundant work being performed by the VLJ support staff (especially if a different administrator is assigned to work on the second task), and confusion to users of the Caseflow application. This ticket exists to prevent the creation of duplicate `ColocatedTask`s.

```sql
select
  appeal_type,
  appeal_id,
  type,
  assigned_to_id,
  assigned_to_type,
  action,
  parent_id,
  max(created_at),
  count(*)
from tasks
  where assigned_to_type = 'Organization'
  and status in ('assigned', 'in_progress', 'on_hold')
  and type = 'ColocatedTask'
group by 1, 2, 3, 4, 5, 6, 7
having count(*) > 1;
```

## Acceptance criteria
* [x] Understand how we've been creating duplicate `ColocatedTask`s
* [x] Update application code to prevent the creation of duplicate `ColocatedTask`s
* [ ] Remove (delete or cancel) duplicated `ColocatedTask`s

**Comment by laurjpeterson** [comment]
Support ticket related to this: https://github.com/department-of-veterans-affairs/appeals-support/issues/4428

**Comment by tomas-nava** [comment]
I've dug into this and it's my conclusion that **this is not a bug in our code.**

## How I investigated

I modified Lowell's query to give me task `id`s and `created_at`s and ran it in Looker:
```sql
SELECT appeal_type, appeal_id, type, assigned_to_id, assigned_to_type, action, parent_id, LISTAGG(created_at, ', ') AS agg_created_at, LISTAGG(id, ', '), max(created_at) AS max_created_at, count(*) FROM tasks WHERE assigned_to_type = 'Organization' AND status IN ('assigned', 'in_progress', 'on_hold') AND type = 'ColocatedTask' GROUP BY 1, 2, 3, 4, 5, 6, 7 HAVING count(*) > 1 ORDER BY max_created_at DESC;
```

That returned **20** groups of "duplicate" `ColocatedTask`s created between January 9th and June 11th. Almost all of these are not actually duplicates, but tasks created with the "Submit admin action" form which, [as of January 2nd](https://github.com/department-of-veterans-affairs/caseflow/pull/8140), allows you to create multiple tasks with a single form submission.

I discovered this by examining timestamps, instructions, and application logs to see how and why the tasks were created.

## Results of investigation

All but **2** of the 20 groups of duplicate tasks were either created by a single `POST` request to the `/tasks` endpoint, or created multiple days apart. Also, most of the duplicate tasks have instructions that clearly differentiate them.

### A: Groups of identical tasks created with separate requests (2)

2 groups of tasks were created with multiple `POST` requests within seconds of each other:

|  | Task ids | Created on | Time between first and last request | Action | Child task statuses | Application logs |
| --- | -------- | ---------- | ----------------------------------- | ------- | ------------------- | ---------------- |
| A01 | 157038, 157040 | 03/28 | 61 seconds | `other` | `in_progress`, `assigned` | [one](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-05dc5a4acc7e0e471;filter=%228ab3edc2-acf5-4f9c-af4b-2ac514a8e7ce%22), [two](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-00f61ea731847f650;filter=%2237de7bae-b6d0-4e60-a0a8-423ccd498c5a%22) |
| A02 | 31803, 31805, 31807 | 02/05 | 17 seconds | `hearing_clarification` | `cancelled`, `assigned`, `in_progress` | [one](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-09f0fbacd2e594cfc;filter=%22ecdb590a-26a4-41de-80b2-82914de61f0e%22), [two](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-09f0fbacd2e594cfc;filter=%22ecdb590a-26a4-41de-80b2-82914de61f0e%22), [three](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-05e89dabff22697b3;filter=%221411a048-8a48-4c2c-ba27-8e8dffe73cc9%22) |

### B: Groups of similar tasks created with separate requests, days apart (5)

5 groups of tasks were created with multiple `POST` requests days apart:

|  | Task ids | Created on | Time between first and last request | Action | Child task statuses | Application logs |
| --- | -------- | ---------- | ----------------------------------- | ------- | ------------------- | ---------------- |
| B01 | 164637, 174593 | 04/03, 04/16 | 13 days | `hearing_clarification` | `assigned` | |
| B02 | 162978, 163722 | 04/02, 04/03 | 1 day | `extension` | `on_hold` | |
| B03 | 159285, 160498 | 03/29, 04/01 | 3 days | `poa_clarification` | `assigned` | |
| B04 | 140855, 146367 | 03/13, 03/19 | 6 days | `extension` | `on_hold` | |
| B05 | 11358,51574 | 12/21, 02/15 | 56 days | `missing_records` | `on_hold` | |

### C: Groups of similar tasks created with one request (13)

13 groups of tasks were created with a single `POST` request:

|  | Task ids | Created on | Time between first and last request | Action | Child task statuses | Application logs |
| --- | -------- | ---------- | ----------------------------------- | ------- | ------------------- | ---------------- |
| C01 | 232388, 232386 | 06/11 | 2 seconds | `foia` | `on_hold` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-00f61ea731847f650;filter=%2237de7bae-b6d0-4e60-a0a8-423ccd498c5a%22) |
| C02 | 230974, 230978 | 06/10 | 3 seconds | `other` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;filter=%22cc3fe064-84d8-4a16-80a1-7536863cc013%22;start=2019-06-10T16:00:00Z;end=2019-06-10T19:00:00Z) |
| C03 | 202650, 202652 | 05/14 | 2 seconds | `other` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0e6935a71880c6607;filter=%2299473dff-896b-4e5d-9388-5aacd1debe3b%22) |
| C04 | 190689, 190691 | 05/01 | 1 second | `other` | `assigned` | |
| C05 | 174282, 174284 | 04/16 | 1 second | `other` | `assigned` | |
| C06 | 165418, 165420 | 04/04 | 1 second | `hearing_clarification` | `assigned` | |
| C07 | 149279, 149281 | 03/22 | 0 seconds | `hearing_clarification` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-08640191f941e79af;filter=%22dd34ca36-bcad-4efc-8b5c-f15caaad21bc%22)
| C08 | 147955, 147964 | 03/21 | 2 seconds | `other` | `assigned` | |
| C09 | 147544, 147546 | 03/20 | 1 second | `ihp` | `assigned` | |
| C10 | 144411, 144413 | 03/18 | 1 second | `other` | `assigned` | |
| C11 | 133941, 133945 | 03/05 | 1 second | `other` | `assigned` | |
| C12 | 85267, 85269, 85271 | 02/22 | 0 seconds | `other` | `assigned` | |
| C13 | 16557, 16559 | 01/09 | 0 seconds | `other` | `on_hold` | |

## recommended actions

**Comment by tomas-nava** [comment]
I've dug into this and it's my conclusion that **this is not a bug in our code.**

## How I investigated

I modified Lowell's query to give me task `id`s and `created_at`s and ran it in Looker:
```sql
SELECT appeal_type, appeal_id, type, assigned_to_id, assigned_to_type, action, parent_id, LISTAGG(created_at, ', ') AS agg_created_at, LISTAGG(id, ', '), max(created_at) AS max_created_at, count(*) FROM tasks WHERE assigned_to_type = 'Organization' AND status IN ('assigned', 'in_progress', 'on_hold') AND type = 'ColocatedTask' GROUP BY 1, 2, 3, 4, 5, 6, 7 HAVING count(*) > 1 ORDER BY max_created_at DESC;
```

That returned **20** groups of "duplicate" `ColocatedTask`s created between January 9th and June 11th. Almost all of these are not actually duplicates, but tasks created with the "Submit admin action" form which, [as of January 2nd](https://github.com/department-of-veterans-affairs/caseflow/pull/8140), allows you to create multiple tasks with a single form submission.

I discovered this by examining timestamps, instructions, and application logs to see how and why the tasks were created.

## Results of investigation

All but **2** of the 20 groups of duplicate tasks were either created by a single `POST` request to the `/tasks` endpoint, or created days apart. Also, most of the duplicate tasks have instructions that clearly differentiate them.

### A: Groups of identical tasks created with separate requests (2)

2 groups of tasks were created with multiple `POST` requests within seconds of each other:

|  | Task ids | Created on | Time between first and last request | Action | Child status | Logs |
| --- | --- | --- | --- | --- | --- | --- |
| A01 | 157038, 157040 | 03/28 | 61 seconds | `other` | `in_progress`, `assigned` | [one](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-05dc5a4acc7e0e471;filter=%228ab3edc2-acf5-4f9c-af4b-2ac514a8e7ce%22), [two](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-00f61ea731847f650;filter=%2237de7bae-b6d0-4e60-a0a8-423ccd498c5a%22) |
| A02 | 31803, 31805, 31807 | 02/05 | 17 seconds | `hearing_clarification` | `cancelled`, `assigned`, `in_progress` | [one](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-09f0fbacd2e594cfc;filter=%22ecdb590a-26a4-41de-80b2-82914de61f0e%22), [two](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-09f0fbacd2e594cfc;filter=%22ecdb590a-26a4-41de-80b2-82914de61f0e%22), [three](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-05e89dabff22697b3;filter=%221411a048-8a48-4c2c-ba27-8e8dffe73cc9%22) |

Each of these requests originated from a different IP address, which indicates a network or routing error (as opposed to someone unintentionally submitting a form more than once).

### B: Groups of similar tasks created with separate requests, days apart (5)

5 groups of tasks were created with multiple `POST` requests days apart:

|  | Task ids | Created on | Time between first and last request | Action | Child status | Logs |
| --- | --- | --- | --- | --- | --- | --- |
| B01 | 164637, 174593 | 04/03, 04/16 | 13 days | `hearing_clarification` | `assigned` | |
| B02 | 162978, 163722 | 04/02, 04/03 | 1 day | `extension` | `on_hold` | |
| B03 | 159285, 160498 | 03/29, 04/01 | 3 days | `poa_clarification` | `assigned` | |
| B04 | 140855, 146367 | 03/13, 03/19 | 6 days | `extension` | `on_hold` | |
| B05 | 11358, 51574 | 12/21, 02/15 | 56 days | `missing_records` | `on_hold` | |

In two of these groups (B03, B05), the instructions on the tasks are different but identical or similar in intention. Tasks in the other three groups are clearly different tasks.

### C: Groups of similar tasks created with one request (13)

13 groups of tasks were created with a single `POST` request:

|  | Task ids | Created on | Time between first and last request | Action | Child status | Logs |
| --- | --- | --- | --- | --- | --- | --- |
| C01 | 232388, 232386 | 06/11 | 2 seconds | `foia` | `on_hold` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-00f61ea731847f650;filter=%2237de7bae-b6d0-4e60-a0a8-423ccd498c5a%22) |
| C02 | 230974, 230978 | 06/10 | 3 seconds | `other` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;filter=%22cc3fe064-84d8-4a16-80a1-7536863cc013%22;start=2019-06-10T16:00:00Z;end=2019-06-10T19:00:00Z) |
| C03 | 202650, 202652 | 05/14 | 2 seconds | `other` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0e6935a71880c6607;filter=%2299473dff-896b-4e5d-9388-5aacd1debe3b%22) |
| C04 | 190689, 190691 | 05/01 | 1 second | `other` | `assigned` | |
| C05 | 174282, 174284 | 04/16 | 1 second | `other` | `assigned` | |
| C06 | 165418, 165420 | 04/04 | 1 second | `hearing_clarification` | `assigned` | |
| C07 | 149279, 149281 | 03/22 | 0 seconds | `hearing_clarification` | `assigned` | [log](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-08640191f941e79af;filter=%22dd34ca36-bcad-4efc-8b5c-f15caaad21bc%22)
| C08 | 147955, 147964 | 03/21 | 2 seconds | `other` | `assigned` | |
| C09 | 147544, 147546 | 03/20 | 1 second | `ihp` | `assigned` | |
| C10 | 144411, 144413 | 03/18 | 1 second | `other` | `assigned` | |
| C11 | 133941, 133945 | 03/05 | 1 second | `other` | `assigned` | |
| C12 | 85267, 85269, 85271 | 02/22 | 0 seconds | `other` | `assigned` | |
| C13 | 16557, 16559 | 01/09 | 0 seconds | `other` | `on_hold` | |

In one of these groups (C07) the instructions on the tasks are identical. In another group (C06), the instructions on the tasks are different but identical in intention. Tasks in the remaining eleven groups are clearly different tasks.

## recommended actions

### Changes to production data

1. Groups _A01_ and _A02_ contain tasks that are identical to each other and were created due to computer error. We should cancel the tasks that are assigned and leave the ones that are in progress.
1. Groups _B03_, _B05_, _C06_, and _C07_ contain tasks that were created intentionally, but have identical (C07) or very similar (B03, B05, C06) instruction text. We should confirm with the task creator if necessary, and cancel the tasks that are duplicates.

### Possible changes to functionality

1. If we try to create a task that has identical: appeal, type, assigned_to, action, parent, _and instructions_; raise an error and don't create the task.
1. Have a nightly job that collects tasks that have identical: appeal, type, assigned_to, action, and parent; flag them for review.

**Comment by pkarman** [comment]
+1 to those changes and actions. Nice research!

**Comment by laurjpeterson** [comment]
Reviewed Tomas' notes on my VA computer. 

## Do not need to clarify with user and can go ahead in deleting tasks
- Group 3 - I agree with deleting the earlier task (159285) in favor of the more recent task (160498). We don't need to contact the user because they are v identical.
- Group 5 - Let's cancel the later task (165420) in favor of the earlier task (165418). We don't need to contact the user because they are v identical.
- Group 6 - I agree with cancelling the earlier task (149279) in favor of the later task (149281)

## I will email the users to clarify
- Group 4 - I want to clarify this with the user because they mention different numbers of paper folders

**Comment by tomas-nava** [comment]
I just paired with @lowellrex to make the following changes:

**GROUP 1**
```
irb(main)> pp Task.where(id: [157038, 157040]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["157038: on_hold (157039: in_progress)",
 "157040: on_hold (157041: assigned)"]

irb(main)> task = Task.find(157041)
irb(main)> task.update!(status: Constants.TASK_STATUSES.cancelled)
=> true

irb(main)> pp Task.where(id: [157038, 157040]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["157038: on_hold (157039: in_progress)",
 "157040: completed (157041: cancelled)"]
```

**GROUP 2**
```
irb(main)> pp Task.where(id: [31803, 31805, 31807]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["31803: completed (152065: cancelled, 31804: cancelled)",
 "31805: on_hold (152066: assigned, 31806: cancelled)",
 "31807: on_hold (152067: in_progress, 31808: cancelled)"]

irb(main)> task = Task.find(152066)
irb(main)> task.update!(status: Constants.TASK_STATUSES.cancelled)
=> true

irb(main)> pp Task.where(id: [31803, 31805, 31807]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["31803: completed (152065: cancelled, 31804: cancelled)",
 "31805: completed (152066: cancelled, 31806: cancelled)",
 "31807: on_hold (152067: in_progress, 31808: cancelled)"]
```

**GROUP 3**
```
irb(main)> pp Task.where(id: [159285, 160498]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["159285: on_hold (159286: assigned)",
 "160498: on_hold (160499: assigned)"]

irb(main)> task = Task.find(159286)
irb(main)> task.update!(status: Constants.TASK_STATUSES.cancelled)
=> true

irb(main)> pp Task.where(id: [159285, 160498]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["159285: completed (159286: cancelled)",
 "160498: on_hold (160499: assigned)"]
```

**GROUP 5**
```
irb(main)> pp Task.where(id: [165418, 165420]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["165418: on_hold (165419: assigned)",
 "165420: on_hold (165421: assigned)"]

irb(main)> task = Task.find(165421)
irb(main)> task.update!(status: Constants.TASK_STATUSES.cancelled)
=> true

irb(main)> pp Task.where(id: [165418, 165420]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["165418: on_hold (165419: assigned)",
 "165420: completed (165421: cancelled)"]
```

**GROUP 6**
```
irb(main)> pp Task.where(id: [149279, 149281]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["149279: on_hold (149280: assigned)",
 "149281: on_hold (149282: assigned)"]

irb(main)> task = Task.find(149280)
irb(main)> task.update!(status: Constants.TASK_STATUSES.cancelled)
=> true

irb(main)> pp Task.where(id: [149279, 149281]).order(:id).map { |t| children = t.children.map { |c| "#{c.id}: #{c.status}" }; "#{t.id}: #{t.status} (#{children.join(', ')})" }
["149279: completed (149280: cancelled)",
 "149281: on_hold (149282: assigned)"]
```

I will act (or not) on the tasks in group 4 when we hear back from the user.

**Comment by laurjpeterson** [comment]
@tomas-nava - Corey Benjamin, VLJ Support Staff lead, cancelled one of the tasks in group 4 so there is only one task left. No action needed from you, and I think this ticket could be closed!
