### ISSUE TITLE
Monthly job: AMA Appeals that are in Docket Range

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#10411]
[See here](https://github.com/department-of-veterans-affairs/caseflow/pull/10392#discussion_r274579371). We need to keep track of how many appeals should be scheduled up to the current month (aka in docket range)

AC:
- [ ] Add a (date? boolean?) column on Appeal to designate that appeal is `in_docket_range`
- [ ] Write a script that backfills Appeals currently in docket range (through the end of April) using @MeredithStewart's list
- [ ] Write a job that runs at the end of every month that marks new appeals to add to the docket range:
```ruby
days_in_month = Time.days_in_month(month, year)
dc = DocketCoordinator.new
target = dc.target_number_of_ama_hearings(days_in_month.days)
appeals_to_mark = dc.dockets[:hearing].appeals(priority: false).where(in_docket_range: false).limit(target)
```

**Comment by MeredithStewart** [comment]
@cmgiven -- You were saying something today about making sure that this accounts for withdrawn hearing requests so that they don't get distributed prematurely.  Please add that here!

**Comment by cmgiven** [comment]
Yup! This is great, because it should make that additional feature pretty simple to add. We might want to bounce this out to another issue.

When a hearing request is withdrawn, the appeal should remain on the Hearings docket, and should not be assigned a DistributionTask. This is because Hearing docket appeals are distributed as soon as they are ready, and that would allow the appeal to short-circuit docket order by requesting the Hearings docket and then withdrawing the hearing request, getting an immediate decision.

Instead, what we want to do is leave them where they are, and when they become `in_docket_range` according to this job, at that point is when we want to assign the DistributionTask.

Alternatively, we could assign the task, and block them from being distributed unless they are `in_docket_range`, but there would be additional considerations there such as how to deal with AOD appeals, etc.

Happy to discuss or further flesh out a spec.
