### ISSUE TITLE
Manually move case from "case storage" to VLJ

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10413]
## AC
- Re-open the JudgeDecisionReviewTask for this case -  https://appeals.cf.ds.va.gov/queue/appeals/c78dae73-7630-49a0-a752-d4f18b1bda7c - and assign to VLJ Thomas O'Shay
- all decision issue data should be unchanged
- all remand reason data should be unchanged

Support ticket context: https://github.com/department-of-veterans-affairs/appeals-support/issues/4964#event-2269684875

We have to do this manually, because this ticket has not been defined/implemented yet - https://github.com/department-of-veterans-affairs/caseflow/issues/7601

**Comment by aroltsch** [comment]
That's interesting that this case is missing JudgeAssignTask: 
["BvaDispatchTask", "BvaDispatchTask", "AttorneyRewriteTask", "JudgeDecisionReviewTask", "AttorneyTask", "RootTask"]


Here is what I did:
1. I deleted all BvaDispatchTasks associated with this appeal because we have to fix this first: https://github.com/department-of-veterans-affairs/caseflow/issues/10216
2. I set status to in_progress for JudgeDecisionReviewTask
3. I checked that all decision issues are present

**Comment by aroltsch** [comment]
@laurjpeterson do we want to update the count for days waiting or is it not a big deal?

![image](https://user-images.githubusercontent.com/3811786/56059602-6eca2400-5d32-11e9-98df-0196e9dadaff.png)

**Comment by laurjpeterson** [comment]
I don't think we need to update the count for days waiting because it's just a few days, and the case had to be sent back to the judge anyway. Plus, 15 days is much less than the 30-60 day time frame that cases usually take.

**Comment by aroltsch** [comment]
Ok, it is done then.
