### ISSUE TITLE
Non ARC Partial Grants/Remands with EP: Add VBMS Note & VACOLS Update

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1043]
There was a request from the Dispatch ARC folks to add a VBMS note to all EPs that ARC creates for the field (ROs). We already add a VBMS note for Full Grants with EPs not worked at ARC. This ticket is to add a VBMS Note to (non-ARC) Special Issue Partial Grants and Remands for whom we create an EP.
Based on the discussion below we will create a single page titled 'Route Claim: Update VACOLS and VBMS' which will include both the VACOLS Diary Note and instructions for the caseworker to add the VBMS Note to the EP.

**AC**
1. Verify the page title at the page is 'Route Claim: Update VACOLS and VBMS'.
1. Verify the top half of the page shows information about Caseflow updating VACOLS (see mock).
1. Verify the lower half of the page shows information about the user adding a note to VBMS (see mock).
1. Verify that the button at the bottom of the page has the label 'Finish routing claim'.
1. Verify that the button at the bottom of the page is inactive when the checkbox is empty.
1. Verify that once the checkbox has been checked the 'Finish routing claim' button becomes active.
1. Verify that the word required appears in red italic next to the phrase 'I confirm that I have created a note in VBMS to help route this claim.' 

**Mocks**
![screen shot 2017-03-07 at 12 48 12 pm](https://cloud.githubusercontent.com/assets/4975959/23670052/6d6a1a70-0334-11e7-962e-e87370f4e7e9.png)

![screen shot 2017-03-07 at 12 48 18 pm](https://cloud.githubusercontent.com/assets/4975959/23670062/737271ba-0334-11e7-99fe-d8450792629e.png)

**Comment by joofsh** [comment]
The problem is for each permutation of Dispatch, what is the point of "submit" and the point of no return. Dispatch is approaching the point of unmaintainable complexity with the number of permutations and the number of submission points.

#### Scenario 1: Partial Grant & create EP
Steps:
Decision Review -> Route Claim: Create EP -> Add VBMS Note -> Update VACOLS -> Confirmation

In this flow we create the Ep, update VACOLS, and save special issues when the user clicks submit on page 2. This is the point of no return for this flow (we don't allow browser back button)

#### Scenario 2: Partial Grant & no EP
Decision Review -> Update VACOLS -> Confirmation

In this flow, since we do not create an EP, at what point are we officially updating VACOLS? At what point can the user no longer go back? On the "Update VACOLS" page, are they allowed to exit and return to that page later (is this a "state" we need to officially support)?

#### Scenario 3: Full Grant & create EP
Decision Review -> Route Claim: Create EP -> Add VBMS Note -> Confirmation

Similar to scenario 1, we submit the EP on page 2, this is the point of no return. We also require user interaction on page 3, so this flow requires 2 points of data submit and 2 points of no return. 

I won't go through every scenario but some other notable ones 

#### Scenario 4: Existing EPs to associate

#### Scenario 5: Full grant & email to complete

### Potential Solutions (in order of technical simplicity)

- Merge VACOLS & VBMS note pages into 1. This better aligns with how the system currently functions with 1 "review page" and would greatly reduce complexity. The downside is that this is a non-ideal UX, however this is temporary while the user must manually create the VBMS note. In the future it will make more sense to combine these pages, when both notes are automatically created in their respective systems. 

- Merge VACOLS note & Confirmation page. Since we are simply informing the user that a note is being created, it may make sense to show this as part of the checklist of "things that have happened". For scenario 2 above, this would mean we may need to add "confirm" modal to the Review Decision page, as this now becomes the submission and point-of-no-return.

**Comment by lakohl** [comment]
New Mock for RO EP, PArtial Grants and Remands is here: https://invis.io/V8AMYN32D

**Comment by lakohl** [comment]
I just re-ordered a couple words in the 'Add VBMS Note instructions' for consistency. Mocks above are updated.

**Comment by lakohl** [comment]
this is done
