### ISSUE TITLE
Investigation | Contention cannot be deleted because it is connected to a rating issue

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10571]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4669/events/310757/

Exact error message: `contention cannot be deleted because it is connected to a rating issue`

We thought this was fixed by syncing EPs at Claim Review edit time but apparently not. See #10102

**Comment by pkarman** [comment]
This is happening because the contention has already received a rating issue.

We can resolve this in one of two ways:

1. prevent editing of a Claim Review where one or more request issues have already received a related rating issue on their contention. We do something similar when EPs are closed.
2. automatically close the relevant request issues with a `decided` status and otherwise allow editing of other issues.

See also #11348 for similar pattern.

**Comment by pkarman** [comment]
@jimruggiero @rutvigupta-design @leikkisa @Sjones352 curious as to your thoughts on this one. The pattern we are following in #11348 is to silently fix the data so that the user can proceed. I'm slightly uncomfortable with that in the sense that it assumes what the "fix" is w/o the user's input. OTOH, it seems to be the correct data intent and poses the least friction for the user.

**Comment by leikkisa** [comment]
@pkarman 
If a request issue is decided, we can remove the "Remove or withdraw" option, and replace it with a "correct" option.  Right now we are only set up to handle that for cleared claims, and working on decided issues is next in line.  One thing I would be curious about is if these have a disposition or not when they have a rating issue but not a cleared claim.  There might be a period where the issues are in some sort of in between state.

**Comment by pkarman** [comment]
@leikkisa I like that -- makes it more visible to the user that the issue is present but no longer modifiable (but "correctable"!)

**Comment by aroltsch** [comment]
I personally like the approach you are taking to silently fix the data. I'd like to make sure I understand. The latest problem here is that a valid contention is deleted from VBMS and it is valid because it already has a rating. And @pkarman WIP PR is supposed to mark the request issue as `decided` if it already has a rating in VBMS, correct? 

Just to confirm I understand @leikkisa suggestion:
1. If a request issue is decided and has a missing contention but has a rating, we would still show that request issue on the edit page and allow only one action to "Correct". 
2. If the user selects "correct", we would create an EP 930 for that issue

**Comment by pkarman** [comment]
> WIP PR is supposed to mark the request issue as decided if it already has a rating in VBMS, correct?

yes

> If a request issue is decided and has a missing contention but has a rating, we would still show that request issue on the edit page and allow only one action to "Correct".

yes

> If the user selects "correct", we would create an EP 930 for that issue

Not sure about this, but whatever works for the current EP 930 flows you have planned.

**Comment by leikkisa** [comment]
> I personally like the approach you are taking to silently fix the data. I'd like to make sure I understand. The latest problem here is that a valid contention is deleted from VBMS and it is valid because it already has a rating. And @pkarman WIP PR is supposed to mark the request issue as `decided` if it already has a rating in VBMS, correct?

So the contention is never actually deleted. The user is trying to delete it, but deleting it is prevented because it already has a rating.

> 
> Just to confirm I understand @leikkisa suggestion:
> 
> 1. If a request issue is decided and has a missing contention but has a rating, we would still show that request issue on the edit page and allow only one action to "Correct".
> 2. If the user selects "correct", we would create an EP 930 for that issue

Yes, and this is compatible with the 930 work planned right now (to show decided issues).  The main change is that we would allow it to be corrected if hasClearedEP is true OR if it's decided.

I think Peter's solution makes sense (that we mark it as decided), as long as we understand that it's not in some sort of limbo state and really is decided (it also has a disposition). Then we can go ahead and create the decision issue for it too.  Otherwise we might want to mark it as something else - decision_in_progress ?

**Comment by leikkisa** [comment]
The two suggested approaches are compatible too, we could silently mark it as decided now as a first step, and then add showing decided issues later.

**Comment by jimruggiero** [comment]
Looping in @Carolyn Dew <carolyn@navapbc.com> for awareness so we both can
learn from the three oracles :)

**Comment by carodew** [comment]
Happy to be looped in and render a Design Opinion(tm) ... is that what is being asked of me?

**Comment by jimruggiero** [comment]
Nope, just passive awareness and context in case this touches something
you/your team will will take up near-term.

**Comment by aroltsch** [comment]
> The two suggested approaches are compatible too, we could silently mark it as decided now as a first step, and then add showing decided issues later.

**Comment by aroltsch** [comment]
```
#<VBMSError::CannotDeleteContention: status_code=500, body=<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Removing Contention failed. System error. GUID: cbcf16f8-d9df-4d57-967a-8d0e7beaf3e2</faultstring><detail><ns2:serviceException xmlns:part="http://vbms.vba.va.gov/cdm/participant/v5" xmlns:ns2="http://vbms.vba.va.gov/external/ClaimService/v5" xmlns:doc="http://vbms.vba.va.gov/cdm/document/v5" xmlns:com="http://vbms.vba.va.gov/cdm/common/v5" xmlns:claim="http://vbms.vba.va.gov/cdm/claim/v5" xmlns:aw="http://vbms.vba.va.gov/cdm/award/v4"><ns2:exception>The contention is connected to an issue in ratings and cannot be deleted.</ns2:exception><ns2:message>Removing Contention failed. System error.</ns2:message></ns2:serviceException></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::RemoveContention:0x00007fc7c576fc20 @contention=#<VBMS::Responses::Contention id="91806807", text="cyst of tailbone", start_date=Tue, 30 Jul 2019, submit_date=Wed, 05 Jun 2019, actionable_item="false", awaiting_response="unknown", claim_id="73426470", classification_cd="8950", contention_category=nil, file_number="xxxxx", level_status_code=nil, medical="true", participant_contention="unknown", secondary_to_contention_id="83636", type_code="REP", working_contention="unknown">, @v5=true, @send_userid=true>>
```

**Comment by leikkisa** [comment]
Some notes after investigating:
This is happening for request issues that are on EPs that are not yet cleared. While a majority of them do get cleared that day or at a later date, not all of them do. It looks like they DO have dispositions.

If the EP gets canceled, both the rating issue and the disposition should be considered invalid.  Here are a couple of options:

1. Mark these as decided, and create decision issues for these, but mark the decision as pending or something so that users can't intake them again. If the EP gets canceled, mark the decision issue as voided, if it gets cleared then remove the "pending" indicator.

2. Mark the request issues as "decision_pending" or "decision_in_progress" or something to that effect, and if the EP is cleared, then update them to "decided" and create the decision issues. If the EP is cleared, create voided decision issues.

The reason I want to create decision issues for these is because we need to be able to filter out the invalid rating issues :-(.  So we need to capture the rating_issue_reference_id somewhere, where we can also indicate that it's invalid.

**Comment by pkarman** [comment]
Based on that approach @leikkisa does it make sense to refactor `RequestIssue` to call something like `create_decision_issues` as part of the `ClaimReview.validate_prior_to_edit` method, so that we sync EPs and decisions just-in-time before edit?

Then the UI changes to prevent editing of any decided request issue is straightforward.

**Comment by leikkisa** [comment]
@pkarman I think that makes sense.

Here's more of a breakdown of option 1 above.  Feedback of course welcome.

1. Add some sort of "status" column to decision issues to mark them as pending or void. We can also use this in the 930 flow.  TBD - determine if we want different void statuses for "corrected" and this situation.
2. Add create_pending_decision_issues that is like create_decision_issues, but doesn't raise an error if there's no rating profile yet, and creates decision issues with the pending status
3. call create_pending_decision_issues in validate_prior_to_edit
4. Add logic when an EP is cleared to update pending decision issues to not be pending
5. Add logic when an EP is canceled to update pending decision issues to be void
6. Filter contestable issues to not include pending decision issues, or rating issues that are connected to pending or void decision issues
7. Check if we need to filter decision issues elsewhere
8. Mark the request issue decision_sync as processed

Questions
* if an EP gets canceled, do we want to leave the request_issue closed_status to "decided" or update it to "end_product_canceled"?
* should we just check the rating issues when we sync EPs? That way we might be able to get some of it done before the user navigates to Edit (so as not to slow it down).

I am double checking with VBMS if the "decisions" on these pending EPs can change between when they're created and when the EP gets cleared.

**Comment by leikkisa** [comment]
Adding a note from VBMS:
The rating issue/disposition can still change until the EP is closed.

Asking:
Will the rating issue be on a locked rating profile until the EP is cleared?

**Comment by aroltsch** [comment]
Ok, here is what I understand the logic is based on the @leikkisa approach 2. 

* If a request issue has a rating and if EP is not cleared, mark request issue as `decision_in_progress`
* If a request issue has a rating and if EP is cleared, mark request issue as `decided`
* If a request issue has a rating and if EP is cancelled, mark request issue as ???? and create `voided` decision issues. 
* If a request issue is `decided` or `decision_in_progress`, hide these from the edit UI

And @pkarman is suggesting to implement 1-3 bullet points as part of the ClaimReview.validate_prior_to_edit method. 

Is that correct?

**Comment by pkarman** [comment]
> should we just check the rating issues when we sync EPs? That way we might be able to get some of it done before the user navigates to Edit (so as not to slow it down).

do you mean when we sync via regular scheduled job? or on-demand in `ClaimReview.validate_prior_to_edit`? I would definitely vote yes for the latter. Not for the former.

**Comment by pkarman** [comment]
I'm hesitant about `decision_in_progress`. The reason is that I don't want things to ever get stuck in that state.

The problem we are trying to solve is users attempting to delete contentions that have already been decided. I don't think that requires that we change the `closed_status` of a request issue. We just need to check at edit time and prevent the UI from presenting the option of removing or otherwise altering the request issue.

**Comment by leikkisa** [comment]
@aroltsch Yep! And if it's cancelled, we can mark is as "end_product_canceled".  Decided and decision_in_progress would already automatically be hidden.

@pkarman I agree we should check before edit. I am just wondering if we can skip making the rating BGS calls again after we know a request issue has a rating issue.

Let's talk when we get a chance to make sure we're on the same page.  The issues aren't technically decided yet, so if we mark them as decided, we should make sure we can identify them and update them again after the EP is closed.

I'm realizing creating decision issues is technically for another problem (but how we handle this ticket impacts that).  Basically we need to be able to filter out the rating issues that aren't on cleared EPs.  So we can worry about that later, we should consider it to make sure our solution here is compatible.

**Comment by pkarman** [comment]
@leikkisa and I talked this through. I realize there has been some back and forth here that is confusing. Part of that stems from the slow evolution of our understanding of what the actual problem is. We think we have a clearer shared understanding now.

We do *not* want to set a `closed_status` on these request issues that cannot be edited. The reason is that something like `decision_in_progress` is not a final state, and `closed_status` should be a final state. Sally has determined that `closed_status: decided` is not always appropriate either.

Instead, we want to delineate 2 different state categories for a request issue: whether it is open/closed (which we already do), and whether it is editable or not. There seems to be a slow-motion process on the VBMS side with regard to when decisions get made on contentions and when the resulting rating issue is finally promulgated and the request issue is finally `closed_status: decision`. It's the grey area we are trying to reflect in Caseflow, when a request issue cannot be edited but may still be "open" (w/o a `closed_status`) because the dominos have not all fallen on the VBMS side.

So, we want to add an `editable?` method to `RequestIssue` and use that to trigger on the UI whether an issue can have actions taken on it (withdrawal or removal). Instead of the dropdown action menu we want to show some read-only text e.g. `Rating in process` to indicate to the user that they may not act on the issue but it is still present.

@aroltsch I hope this clarifies enough. Please ask if not. And sorry it took so long to reach consensus.

**Comment by aroltsch** [comment]
Perfect, thank you both.

**Comment by pkarman** [comment]
We are still seeing this happen in production:

https://appeals.cf.ds.va.gov/asyncable_jobs/RequestIssuesUpdate/jobs/11758
https://appeals.cf.ds.va.gov/asyncable_jobs/RequestIssuesUpdate/jobs/11333
https://appeals.cf.ds.va.gov/asyncable_jobs/RequestIssuesUpdate/jobs/11128

etc.

**Comment by tomas-nava** [comment]
Seeing [~10 Sentry issues on this per day](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6079/) raised during the `DecisionReviewProcessJob` with error message ```The contention is connected to an issue in ratings and cannot be deleted```

**Comment by leikkisa** [comment]
Some of the contentions may be connected to a locked rating.  If a rating has been started for it but not decided and promulgated yet, I would say there's a high chance of it being "locked" since that means someone is working on it.

Right now we suppress the locked ratings error, because if we don't then we can't get any of the ratings.  We do this via the allowLockedRatings flag in rating.find_by_participant_id_and_date_range (in the ruby bgs library), which is hardcoded right now.

Setting it to "Y" means we won't get the locked rating error if there's a locked rating, and we'll still get the rest of the promulgated ratings.  Setting it to "N" means we won't get any ratings, and instead we'll get the LockedRating error.

I wish I had a nice solution to propose! But I hope that's at least some useful info.

**Comment by leikkisa** [comment]
The only thing I can think of is if you're checking these, you could check it with the flag set to "N" and if there's a locked rating you could give it the "rating may be in progress" status, which I think would affect all of the contentions at once.

**Comment by leikkisa** [comment]
We believe this can be solved through using a new rating data endpoint BGS created for us which allows us to see the in-progress ratings. Work to implement this is in:
https://github.com/department-of-veterans-affairs/caseflow/issues/13977

Closing this version of the ticket.
