### ISSUE TITLE
Error merging appeals in Hearings

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#10820]
This appeal along with quite a few others are taking the merged appeal out of 99 complete status and in turn making them workable in caseflow when they've already been merged with another appeal. Resulting in erroneous hearings being scheduled.

https://github.com/department-of-veterans-affairs/appeals-support/issues/5120

**Comment by Chingujo** [comment]
### Some context on my end 

@pshahVA 

Mmmm interesting. When an appeal is merged if legacy, the newer appeal is usually merged into the older. So one is closed and the other is kept active while maintaining the older docket

If we are pulling closed appeals as a result of a legacy merge either into the location or assigning tasks, then it would be a Caseflow thing.

So for example, —-> appeal merged —-> the merged gets set to complete ——> caseflow pulls it —-> this appeal that should be closed has a hearing —-> we assign it a hearing task —-> and then they schedule

Might be a flow, otherwise not sure how they are scheduling once closed appeals (edited)

The key to this is figuring out what’s causing these Caseflow to pull in the merged appeal. It can be a queue thing that’s doing it and then we are detecting a hearing or something that hearings side is doing.

- ex: are these happening to hearing only appeals

Would flag as a higher priority since user mentioned this is causing wrong hearings to be scheduled at a higher volume

**Comment by lomaxap** [comment]
It could be because we are not limiting ScheduleHearingTasks that could be scheduled to appeals charged to CASEFLOW [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/tasks/schedule_hearing_task.rb#L13). We should make sure that only cases charged to CASEFLOW are returned.

**Comment by pshahVA** [comment]
I talked to Ivy yesterday and they said that they merge appeals all the time.  I tried to get a screen share with her so she could show me, but there were technical difficulties.  I asked her for the ID of the claims she was appealing and I didn't get any response.  We need to follow up with her.

**Comment by pshahVA** [comment]
@lomaxap, with regards to recent bat team work, do you think this is still relevant?

**Comment by jimruggiero** [comment]
@lomaxap @pshahVA Can this one be closed?

**Comment by pshahVA** [comment]
closing. This ticket has been open for and we have not been able to reproduce it.
