### ISSUE TITLE
Investigate: Allow certain users to move tasks to any team/person at any time

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10928]
Some BVA users need to "move cases" from any organization/person to any organization/person. This could be for a variety of reasons - someone is out on leave and a case needs to be moved; a Veteran is terminally ill and is allowed to quickly move from case storage to a judge; or other extenuating circumstances.

How might we support this request from the Board within the task model? Where does it break?

**Comment by laurjpeterson** [comment]
Related - allowing users to move cases from "case storage" outside of auto-case distribution - https://github.com/department-of-veterans-affairs/caseflow/issues/10878

**Comment by lowellrex** [comment]
One key aspect of modeling the set of work tasks as a tree (with interconnected organizations) instead of a linear set of owners (as it is with VACOLS locations) was to ensure that cases proceed through some defined set of checkpoint (branches of the task tree). In order to understand how we could accomodate this request within that model (or if, perhaps, that model needs to be reconsidered), I think it would be valuable to describe precisely the scenarios folks this ability in. That is _what action_ does _which group_ of folks at the Board want to take on tasks in _what state_. For some of the examples above we support some actions for tasks in some states.

> someone is out on leave and a case needs to be moved

For AMA cases, anybody on the same team (QR, Dispatch, etc.) can reassign a case to themselves and team admins can reassign a case to anybody else on that team. Attorneys cannot reassign drafting decisions to themselves if they are on the same team but their judges can reassign the cases to other attorneys on the judge team. A similar constraint exists for tasks assigned to VLJ support staff, though we have written a [ticket to allow them to reassign tasks](https://github.com/department-of-veterans-affairs/caseflow/issues/7999) to themselves.

> quickly move from case storage to a judge

As mentioned in [a previous comment](https://github.com/department-of-veterans-affairs/caseflow/issues/10928#issuecomment-497204717) this has [been ticketed](https://github.com/department-of-veterans-affairs/caseflow/issues/10878) and is very much possible.

Changes like allowing current task assignees to reassign tasks to other members of their team or giving DVC team admins the ability to [distribute specific cases](https://github.com/department-of-veterans-affairs/caseflow/issues/10878), are relatively easy (though they would be aided by the improvements suggested in #10894). I haven't done extensive research into alternatives but my intuition is that giving Board employees the ability to reassign cases in an uninhibited manner will be a significant undertaking and likely result in reconsidering organizing tasks in a tree.

**Comment by laurjpeterson** [comment]
Additional information from Jennifer. Initially, she thinks that DVC team admins (she refers to them as staff assistants) would be the ones who would make various case moves. 

Some case management scenarios I remember from judge research:
- Moving a JudgeDecisionReviewTask from one judge to another while that judge is on leave (I think this was addressed above)
- Moving a JudgeAssignTask from one judge to another while that judge is on leave (I think this was addressed above)

**Comment by laurjpeterson** [comment]
Closing this ticket because the design work is captured in #11380 and there are multiple tech specs capturing this work. cc: @lomky just in case seeing this ticket is useful at all anymore
