### ISSUE TITLE
Business Line | Search bug when veteran has both in-progress and completed intake

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11010]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5242/

Context: https://dsva.slack.com/archives/CHX8FMP28/p1559676613045300

**Comment by leikkisa** [comment]
Another instance of this:
User VBAMUSLEEJ, station 351 can't use the search bar for "In progress" tasks for the Education business line.
The in progress page works fine without using the search. The search bar works fine on the completed tasks tab. They tried on two browsers, and Martina also impersonated the user and noticed the same issue for this user, but not for other users, so it seems like it's not a browser issue.

It looks like the problem related to the binding of "this" in the onSearch function, because "this" is undefined in the function when we hit the error.  It's very strange that it happens for in progress, and not complete, and for this user and not others.
