### ISSUE TITLE
Consider modifiers on recently closed claims "taken"

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11043]
Some VBMS modifiers look like they ought to be available (are on canceled EPs) but still throw errors when attempting to establish new EPs.

Update the EndProductModifierFinder workflow to consider a modifier taken if its end product was canceled or cleared within the last day or two.

## AC

* If a veteran's has an end product that was canceled or cleared recently, do not attempt to use it for establishing a new claim of the same type for that veteran. For example, if a veteran has a claim with the modifier 040 that was cleared today, and another with modifier 041 that is pending, try establishing the claim with modifier 042.

**Comment by leikkisa** [comment]
Response from BGS on why this is happening:
This happens when the BDN PIF is still present although the corporate claim has been cleared or cancelled (PCLR or PCAN).  This will ALWAYS happen within a timing window but may happen due to other situations/scenarios.

The timing window is best illustrated via a scenario:

The starting point is when a claim is created on both the BDN and on corporate with a CEST.
A PCAN or PCLR is done off some corporate app (Share, VBMS, etc). Now the claim is no longer active and is basically invisible on corporate. However, the BDN PIF has been marked inactive BUT apps still treat it as active just due to its existence.

The state/status of the PIF on the BDN is not considered.

A second (supplemental) CEST is done with the same EPC etc. This works on corporate and should work on the BDN except for the timing window. Technically, a new claim should be able to be created with the same attributes as one recently cleared or cancelled. That workson corporate. However, on the BDN, the claim still exists until WIPP runs and all apps consider it still “active”. Thus, the error occurs thatan attempt is being made to create a duplicate claim – because on corporate it is no longer there, but it still is on the BDN until WIPP runsand removes it.

That’s the story and has been for many, many years. If a user does a PCAN or PCLR and then tries to re-CEST the same claim before WIPP runs on theBDN, this error will occur. Usually, this means that the user must PCAN or PCLR and attempt re-CEST on the same day, because I believe WIPP runseach night.

**Comment by leikkisa** [comment]
It sounds like this is due to manually canceling or clearing EPs "off corporate", so we can expect CLR and CAN eps to have their modifiers be available again if they are properly closed.  CAN seems more common, but the example I see in prod right now looks like it's from a CLR claim. We may want to respond to that specific error with incrementing the modifier instead of filtering out CLR and CAN from the beginning.

Examples of claim IDs with tied up modifiers:
72466355 (CLR)
71055107 (CAN)

**Comment by pkarman** [comment]
This ultimately feels like a BGS data management problem, and not something Caseflow can work around in some cases (where all the modifiers are used up, as we have for some stuck jobs). I will work on escalation.

**Comment by leikkisa** [comment]
I agree. I was hoping it wouldn't happen this fast, but here we are! I will also bring it up in the BGS meeting tomorrow and ask if we can have a manual clean up done for the manually cleared and canceled claims.

They are working on removing a reliance on the PIF (seems to be another word for the modifier), but that is 6-8 months out.
