### ISSUE TITLE
Preview Form 8 | Hide page and proceed to Confirmation

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1104]
As an RO Caseworker, I would like to no longer see the `Preview Form 8` page and go directly to the `Confirmation` page so that my process is streamlined since I am not using the Form 8.
 
# Acceptance Criteria
1. Verify that after clicking the **_Certify appeal_** button on the `Sign & Certify` page, the `Confirmation` page is displayed instead of the `Preview Form 8` page.
2. The radio buttons on the `Sign & Certify` page will not be functional yet.

## Mock(s)
**_View 1 - Sign & Appeal - Certify appeal_**
In the mock below, disregard the state of the continue button. It should be disabled and gray, because the user has not filled out their name or selected their role.

![v2_screenshot_sign](https://cloud.githubusercontent.com/assets/1178390/24970187/63fa0bd0-1f81-11e7-9f35-8bd71ef3c6b0.png)

**_View 2 - Confirmation page - comes after Sign & Appeal_**
For this ticket, the `Confirmation` page content does not have to match the mock. It is important for the` Confirmation` page to appear and not the `Preview Form 8` page.
![v2_screenshot_confirmation](https://cloud.githubusercontent.com/assets/1178390/24970233/95ab2ec0-1f81-11e7-8776-361055014c3a.png)

# Related Stories
Sign & Certify | Remove no longer needed questions and propagate information to PDF #1115

**Comment by nikitarockz** [comment]
### Original Comment
 
Context: we're removing the Form 8 preview page in certification v2 because we're phasing out the Form 8.

We want to go straight from this page:
![image](https://cloud.githubusercontent.com/assets/3781835/23626752/fe8abf0a-027b-11e7-9325-8db7382fb08a.png)
to this page:
![image](https://cloud.githubusercontent.com/assets/3781835/23626778/0b060122-027c-11e7-9f72-dc97f232d53a.png)

All code that changes functionality should be wrapped in a feature toggle like so:
```
if FeatureToggle.enabled(:certification_v2, current_user)`
  # code here
end
```

The below code will probably work, but we should figure out a way to do this that will improve the clarity of the codebase, and that will make it easy to remove the certification v1 code path when it comes time.

```
  def show
    if FeatureToggle.enabled(:certification_v2, current_user)`
      # TODO remove this after we enable it for all ROs.
      @certification = Certification.find_by(vacols_id: vacols_id)
      @certification.complete!(current_user.id)
      render "confirm", layout: "application"
      return
    end

    render "confirm", layout: "application" if params[:confirm]
  end
```

**Comment by astewarttistatech** [comment]
@nikitarockz or @amprokop the progress bar on the mocks are not consistent with the stories recently done. I do not know them off the top of my head and they have since been archived. The progress bar should match the page that is currently being viewed. (Ex. Review Decision page / Review Decision progress indicator bolded)
Current View:
![caseflow certification](https://cloud.githubusercontent.com/assets/23038505/24861750/ce002e6c-1dc7-11e7-9582-cbc7b919d9cb.png)

Also the buttons on the Sign and Certify page are not functioning. Is this in scope?

**Comment by amprokop** [comment]
> Also should the success page have a bullet for Form 8 since we are doing away with it or is that to be done in another story?

@astewarttistatech and @shellicious and i just talked— we're not going to add the confirmation page on the progress bar unless anyone else raises hell about it.

**Comment by amprokop** [comment]
> The progress bar should match the page that is currently being viewed. (Ex. Review Decision page / Review Decision progress indicator bolded)
> Current View (which is to be expected):

This resulted from an inconsistency between the mocks and the style guide. The style guide currently suggests that the page currently being viewed has its progress bar section bolded/dark.

**Comment by astewarttistatech** [comment]
Waiting for UI in AC to be updated to match. Functionality is present.

**Comment by shellicious** [comment]
Updated UI @astewarttistatech

**Comment by astewarttistatech** [comment]
Thanks @shellicious !

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: UAT
Browser: FF and Chrome

Steps to Validate:
1. In Certification V2, go through the flow of certifying an appeal (that has all needed forms).
2. The Sign and Certify page should show up without having a viewable Form8 generated. (this should only be done backend)
3. Select Continue from this page to see the success page. 

Screenshots: 
![caseflow certification](https://cloud.githubusercontent.com/assets/23038505/24861750/ce002e6c-1dc7-11e7-9582-cbc7b919d9cb.png)
<img width="1041" alt="screen shot 2017-04-10 at 8 51 12 am" src="https://cloud.githubusercontent.com/assets/23038505/24862610/3a1d88ee-1dcb-11e7-9e2e-e54ec6e27208.png">
