### ISSUE TITLE
Claimant address validation during intake

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11040]
We should be validating claimant address is complete on initial Intake. Some examples where Supplemental Claims fail to establish: 5611 and 1571

**Comment by leikkisa** [comment]
Jennifer checked on these two claims, and for both of them said that the spouses shouldn't be the claimants, and therefore aren't required to have an address.  The veteran gets paid, but their benefit is increased due to having a spouse.

This might require clarification with the veteran/claimant.  We may also want to check if this is a "contested claimant" situation.

This still should have been prevented by validation.

**Comment by leikkisa** [comment]
SC 1571's claimant has an address of nil, but it happened before the claimant address validation code was merged on March 22nd, so I think that's why that went through.

SC 5611 has an address that looks like this:
`{:address_line_1=>nil, :address_line_2=>nil, :address_line_3=>nil, :city=>nil, :country=>nil, :state=>nil, :zip=>nil}`

This is different than the address just being nil and wasn't being checked for before.

**Comment by leikkisa** [comment]
I canceled the above two claims. According to Jane SC 60137 was established for one of the above veterans (I believe this replaces SC 5611), and the other one was ineligible.
