### ISSUE TITLE
SSC tech spec

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#11118]
SSCs fit relatively well into the existing JudgeTeam organization structure, but have some additional capability.                                           

SSCs need to be able to                                                                                             
  - Reassign JudgeTasks from _any_ judge to _another_ judge                                                           
  - Act as a Judge                                                                                                    
    - Assign cases to Attorneys                                                                                       
    - Act as Acting Judges to Review Decisions                                                                        
  - Act as an Attorney                                                                                                

Possible we will either update JudgeTeam to encompasses SSCs, or subclass Judges to handle SSCs. 

Spun out of #10551. See also #9704, #5385

**Comment by lomky** [comment]
This issue may have implications with regards to reliance on VACOLs for role and the possible  deprecation of DAS

**Comment by lomky** [comment]
Are there ever cases where an Attorney would be designated an Acting Judge, but not be an SSC? @laurjpeterson

**Comment by laurjpeterson** [comment]
Yes!

**Comment by laurjpeterson** [comment]
I think I'm going to move this back to `Define` pipeline, because I think there's more problem definition work to determine whether there needs to be any specific functionality for Supervisory Senior Counsel. Plus, after we make progress on #11801, we may find that this is not necessary.

**Comment by araposo-tistatech** [comment]
@lomky I noticed you flagged a potential issue on this ticket around DAS deprecation and our reliance on determining roles via VACOLS. There has been a significant amount of work completed for DAS deprecation since can you provide information how we are or plan to determine the roles after deprecation? Also, is there anything you saw at the time that distinguished an SSC from an attorney? 

We've been getting a number of inquiries around SSCs in Caseflow (since they are VLJs in Caseflow it is causing quite a bit of confusion). So I believe this ticket is something we will want to eventually continue looking into.
