### ISSUE TITLE
Allow Intake for Veteran without a SSN

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11257]
A Veteran may legitimately not have a SSN and that should not prevent Intake.

During the initial Intake search, a missing SSN on the BGS record currently prevents the user from proceeding.

Contact @pkarman for an example file number.

**Comment by leikkisa** [comment]
Some notes:
We have some Veterans who seem to be missing a file number (there is an SR to BGS to backfill these if possible), and now a Veteran who is legitimately missing an SSN because they are from the Philippines (this ticket).  

Peter has added SSN to the Veteran table.   Currently many of our tables use file_number as a point of reference, so that would probably be preferred for now (eventually I think we want to move as much as we can to participant_id since that seems to be the most reliable identifier).  We discussed during sprint planning to add a method that can pick to use the SSN if file_number is missing.

@moncef This didn't come up during sprint planning.  During intake we have validation on the Veteran's record requiring that the SSN be present in order to proceed.  For this ticket, I think the primary work would be to remove this validation.  I don't know if we want to remove it altogether, or if there is a way to detect veterans who legitimately won't have a ssn.

**Comment by monfresh** [comment]
Could you please point me at the code where we specifically check for SSN in BGS? I've been looking at the path via `IntakesController#create`, which led me to `Veteran.find_by_file_number_or_ssn` and `Veteran.find_or_create_by_file_number`. From what I can tell, the validations are based on the `file_number` that is passed in as a param in the controller, which might or might not be an SSN, right?

In the methods that call BGS, we are passing in the `file_number` param, and it seems like there are legitimate reasons for a file number not being found in BGS and that we want to handle that appropriately.

My question is, how do we tell the difference between a valid file number that is not found in BGS and a veteran that does not have an SSN at all? How do we know that there is a missing SSN on the BGS record?

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/veteran.rb#L218

Here's the logical flow:

* for any string of length 9, we assume it is a SSN and ask BGS to tell us the corresponding file_number for that SSN.
* often, BGS will return the same string (the SSN) which is being used as the file number in BGS/VBMS. So we store it as the file_number on the veteran record
* in some cases, BGS returns a different string than the SSN and we store that as the file_number. Either way, we store what BGS returns for `fetch_file_number_by_ssn`

If we want to know if the veteran has a SSN or not, we can check the `Veteran.bgs_record[:ssn]` attribute.

**Comment by leikkisa** [comment]
@monfresh And here is where the validation happens for intake:
https://github.com/department-of-veterans-affairs/caseflow/blob/2bc4fd2d04b65ee0a5565a4bb12b182c3ea5a99e/app/models/veteran.rb#L19

**Comment by monfresh** [comment]
Is there a stack trace for this particular veteran? I'd like to see the entire flow leading up to the error if possible. Otherwise, do we know the answers to these questions?

- Was the file number submitted 9 digits long?
- Did BGS return anything for that file number?
- If BGS returned something, was it the same as the string that was supplied?
- Was there already a Veteran record in Caseflow for this veteran?

In addition to requiring that BGS returns something for that file number, we also require that the BGS record has an SSN, and for this particular veteran, the former check passed, but not the latter. Is that correct?

It sounds like we can remove the SSN presence validation, and I have a PR out for that, but I'd like to write a test case that matches the actual scenario as closely as possible to make sure it's fixed.

**Comment by pkarman** [comment]
> Was the file number submitted 9 digits long?

No. Typicaly 8 digit file number.

> Did BGS return anything for that file number?

Yes. There is a veteran record in caseflow, id 274602

> If BGS returned something, was it the same as the string that was supplied?

I assume you mean the `fetch_file_number_by_ssn` BGS call? That was not attempted because the file number is 8 digits.

> Was there already a Veteran record in Caseflow for this veteran?

Yes.

If you find the veteran in production with the id above, you can see the BGS ssn is nil with

```ruby
veteran.bgs_record[:ssn]
```
