### ISSUE TITLE
Hearing Location request timing out

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#11383]
An invalid address is making it through the vets.gov address validator. We're then making hundreds of requests to the API to try to find a matching regional office. Meanwhile, the frontend times out and we don't catch the error on the frontend. 

Appeal vacols_id: 3842003
Sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5691/

**Comment by lomaxap** [comment]
The address for this appeal is valid. This is happening with all facility locator queries for Louisville, KY (RO27) which has 23 facility ids associated with it. This appears to be a new issue since there are many appeals in RO27 that have distances to all AHLs.

[VADotGovService pages through results](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/external_api/va_dot_gov_service.rb#L139-L141) until all ids are found or no pages are left. I'm able to find each facility id individually, so it's not an issue with locator not finding a distance. I suspect there's something wrong with the logic that results in an infinite loop here.

**Comment by lomaxap** [comment]
confirmed pagination works. not immediately obvious to me why requests don't stop after all pages are found.
