### ISSUE TITLE
"Correct Issues" button availability

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11388]
There are instances where it would be helpful to correct an Intake immediately after clicking Save. How/where could we make available an "Edit Issues" or "Correct Issues" button that uses the same "Edit in Caseflow" URL that appears in VBMS, but for all Decision Reviews in Caseflow.

* What users should see that button?

**Comment by laurjpeterson** [comment]
We've enabled this for members of the "Case Review" organization (BVA Intake), because they will need the Correct issues link to withdraw appeals. 

https://github.com/department-of-veterans-affairs/caseflow/issues/11167

If we need a stopgap right now, we can add other users to it now.

We also need to allow judges to correct issues for Veterans that they're holding a hearing for, documented but not yet worked on here - https://github.com/department-of-veterans-affairs/caseflow/issues/10562

**Comment by pkarman** [comment]
![Screen Shot 2019-09-03 at 5 04 44 PM](https://user-images.githubusercontent.com/1205061/64212389-ca768480-ce6e-11e9-8850-4743f9a58dcd.png)

We can add a link to the Confirmation page on all intakes.
