### ISSUE TITLE
Use Veteran address when Veteran is appellant

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11432]
From https://dsva.slack.com/archives/CD5DAQNCU/p1563284371076900

For the IDT appeals API endpoint, if the Veteran is the appellant, the address should be obtained from the Veteran BGS endpoint rather than the appellant BGS endpoint. BGS can report different addresses for the same participant id, and we should prefer the Veteran's address.

## AC

- [x] Prefer the Mailing address, then the most recently effective address, for any participant.

**Comment by leikkisa** [comment]
For appeal d8f2e0c6-560e-4ff2-b59c-e1903001f53b, the claimant address is more recent. It is listed as the residence, and the other address (the one on the Veteran) is listed as a mailing address.

For appeal a78328ea-6e78-4bd9-903c-ce00979211ff, the veteran has three addresses - FMS Payment, VRE Mailing, and Mailing.  The "Mailing" address matches the Veteran's address.

So instead of preferring the Veteran's version of the address I am fixing the person address call to get all addresses, and prefer the mailing address if available.

**Comment by laurjpeterson** [comment]
Open questions:
- Is Caseflow Hearings using a different data source for Veteran address than this?
- Why does John Dell not want us to use Vet360 for this?

**Comment by pkarman** [comment]
A fix was deployed. Waiting for confirmation from IDT that it resolves the problem.
