### ISSUE TITLE
Modify UpdateCachedAppealsAttributesJob to cache all appeals for which open tasks exist.

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#11666]
Pursuant to [ticket 11311](https://github.com/department-of-veterans-affairs/caseflow/issues/11311), the `UpdateCachedAppealsAttributesJob` was implemented. However, testing has shown that the last existing batch of LegacyAppeals data (i.e. whatever the last batch that is not an even 1000 appeals to import, which is Oracle's limit for batch imports) is not being cached.  This ticket exists to diagnose and remedy that problem.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | |
      2 | |||||
      3 | |||
      5 | 
      8 | 
```

Estimating at a 3. Could be a 1 if the fix is super-obvious and simple, like if we need exactly 1000. Could be a 3 if it turns out we have a complicated rewrite with Oracle weirdness.

**Comment by lowellrex** [comment]
The instrumentation we added in #12047 suggests that this bug is no longer occurring.

![image](https://user-images.githubusercontent.com/32683958/64886835-22627780-d635-11e9-8796-1a53d6a83f03.png)
[_Source: Datadog_](https://app.datadoghq.com/metric/explorer?live=true&page=0&is_auto=false&from_ts=1568396744351&to_ts=1568400344351&tile_size=m&exp_metric=dsva_appeals.update_cached_appeals_attributes_job.vacols_cases_cached&exp_agg=avg&exp_row_type=metric)

@kevmo can you confirm that this is no longer happening so we can close this ticket out, or share any other indication we have that this bug is still happening and we can keep it open.

**Comment by kevmo** [comment]
This bug appears to have been solved.
