### ISSUE TITLE
Fix search results UX

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11738]
Context: https://github.com/department-of-veterans-affairs/caseflow/issues/11440#issuecomment-519937833

## Description 

When a user searches for an appeal with the search box and gets results, they see results. This is good so far!
 
But if they search again and there are no results, the previous search's results still show on the screen. This is not so good! In fact it's kind of strange and confusing. 

![image](https://user-images.githubusercontent.com/10144074/62785680-237d1380-ba8f-11e9-8d6f-70ce05bece52.png)

## Design scope 

- [ ] Design (or locate an existing) mock up of a search results page with no results. Usability testing not needed, let's keep this as lightweight as possible. 

## Mock ups
(add mock ups here before sending to eng)

**Comment by geronimoramos** [comment]
@jcq I recall us having a conversation around this months ago, did you have ideas for this?

**Comment by jcq** [comment]
@geronimoramos I think the major improvement would be to clear the existing search results whenever a new search is performed. It already will show a message stating that "No cases are found" if there aren't any that match the search, so that's covered. The core issue here is just that it's really unintuitive for the prior search results to remain on screen when a new search is performed.

**Comment by msj0nes** [comment]
Caseflow search is part of Queue. Updated labels.
