### ISSUE TITLE
Duplicate Veteran Records found on Corporate

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11742]
### Story
We cannot establish claims for veterans who have another duplicate record under a different participant ID.

Documentation for finding the other duplicate record is located here:
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/how-to-resolve-duplicate-veteran-records-corpdb.md

Here's another ticket for preventing future occurrences in Caseflow: 
related: https://github.com/department-of-veterans-affairs/caseflow/issues/12077

### Asyncable processing instructions
If you find a new veteran with this error, please add them to the table below with the status of "New". If you can't find the second participant ID, please leave that blank.

### Impacted veterans
_updated 2019-10-07_

Veterans where the duplicate has been found

veteran_id | participant_id | participant_id2 | status
--- | --- | --- | --- 
254051 | "12116894" | "2230270" | Established
272811 | "31828443" | "27882241" | Established
410599 | "51745485" | "569688" | Established
437329 | "52407937" | "1226720" | Established
518233 | "51870936" | "1212574" | Established
285560 | "46528578" | "2042726" | Established
348934 | "42803945" | "35421953" | Established
350980 | "2006329" | "51363014" | Established
380436 | "47289851" | "2662732" | Waiting for external response
548954 | "10509807" | "40391985" | Waiting for external response
553304 | "30727641" | "2251987" | Waiting for external response
556381 | "39843331" | "1562283" | Waiting for external response
560061 | "53326586" | Not found | Established
733481 | "2911903" | Not found | Waiting for external response
687782 | "37926414" | Not found | Waiting for external response

**Comment by pkarman** [comment]
Service Request # SR-002132 has been submitted.

**Comment by pkarman** [comment]
Instructions for resolving Duplicate Veteran Error:

YourIT doesn’t want PII in their system:

You can use the following format for the ticket attachment:

Full name
File number, just last 4 digits
SSN just last 4 digits
Complete date of birth
Both PIDs 
Incorrect File Number, just last 4 digits

All 6 elements should be provided.

**Comment by leikkisa** [comment]
We sent detailed information about one of these veterans, but didn't have information about the duplicate record.  Jack Goldberg, with the Data Architecture team, said that they need some information about the duplicate record, and made a request to VBMS to include both participant IDs in the error message.

**Comment by leikkisa** [comment]
I was able to find the other participant_id for most of these by looking at the veteran's bgs record's soc_sec_number field.  We are getting our ssn from the (separate) ssn field.  This didn't work for one of them, and that veteran had two records in our own DB.

Here's an example:
```
sc=SupplementalClaim.find(115212)
ssn=sc.veteran.bgs_record[:soc_sec_number]
duplicate_participant_id=BGSService.new.client.people.find_by_ssn(ssn)[:ptcpnt_id]
```

**Comment by leikkisa** [comment]
I am saving this data from the summary, but we've been instructed to stop sending YourIT tickets for these and to email someone directly.  The instructions have been updated above.

veteran_id | participant_id | participant_id2 | YourIT Incident number | YourIT INC Link | YourIT ticket resolved? | Veteran data fixed in Caseflow? | Establishment reattempted?
--- | --- | --- | --- | --- | --- | --- | ---
254051 | "12116894" | "2230270" | INC7691264 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=ef1d8d90db9404d4ceac76740f961920
272811 | "31828443" | "27882241" | INC7691351 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=804e4d5cdb9404d4ceac76740f961926
285560 | "46528578" | "2042726" | INC7691410 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=e55f4158dbd404d4ceac76740f9619eb
348934 | "42803945" | "35421953" | INC7691484 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=dc805d10db1804d4ceac76740f9619fe
350980 | "2006329" | "51363014" | INC7691512 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=341115d0db1804d4ceac76740f9619b1
380436 | "47289851" | "2662732" | INC7691556 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=6ec195d0db1804d4ceac76740f9619df
410599 | "51745485" | "569688" | INC7691585 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=44521918db1804d4ceac76740f96194b
437329 | "52407937" | "1226720" | INC7691624 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=d0c2dd58db1804d4ceac76740f96192b

**Comment by leikkisa** [comment]
Adding a comment from discussion that has a YourIT article about this. It mainly affirms that these are handled through YourIT, but mentions a Corporate Trouble Ticket Request Form, which I couldn't find.  I added the escalation number to all of the duplicate veteran record INC reports.

https://yourit.va.gov/kb_view.do?sysparm_article=KB0012827

**Comment by leikkisa** [comment]
Folks said they were ready to merge the records after a demo from me, which was last Thursday.  The PIDs that will be retained are shown in green in the following screenshot.  The row that doesn't have a green highlight is actually the same veteran as the row above it.  I haven't heard a timeline yet on when the records will actually be merged.

![image (11).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/d83ac757-7dd2-4d4d-beb4-f620aaa3ad02)

**Comment by leikkisa** [comment]
Email sent to Jack Goldberg, CC John Dell, Dustin Ware, and Dwight Whitted with the information for the remaining Duplicate Veterans.

**Comment by msj0nes** [comment]
@leikkisa is this safe to close now. Considering duplicate vets is resolved outside of Caseflow (business process based) and the latest error https://app.zenhub.com/workspaces/caseflow-5915dd178f67e20b5553ba0c/issues/department-of-veterans-affairs/caseflow/13240 message provides clear instructions, was there anything additional engineering had remaining to complete.

**Comment by leikkisa** [comment]
@msj0nes There's still 4 left that need to get resolved before we should close this ticket.

**Comment by leikkisa** [comment]
One more YourIT ticket for the last 3:
INC9671124
https://yourit.va.gov/va?id=ticket&table=incident&sys_id=49533cccdb978450f37af50d0f96193d
