### ISSUE TITLE
Tech Spec: Handle tasks assigned to users that become inactive or are removed from organizations

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#11811]
As noted in #11631, when a user becomes inactive or when a user is removed from an organization, there may be tasks assigned to them left in limbo. Currently, a team admin or caseflow support need to be notified of a user's inactive status to manually reassign or cancel all tasks in limbo. This ticket exists to tech spec the automation for handling these tasks

## Blocked by 🚳 
 - [x] Add active status for users #11810

## AC
- [ ]  When a user is removed from an organization or marked as inactive, how do we automatically cancel or reassign the tasks assigned to them
  - Default case?
  - block with message if there are open tasks assigned to them?

**Comment by lowellrex** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
      1 | |
      2 | ||
      3 | |||||
      5 | ||||
      8 | 
```

Will likely need input from design since there will be enough edge cases that user interaction will often be required.

Estimating this at 3. Possible 1 because the decision about how we want to handle this could be simple (always assign to team admin when somebody leaves). Possible 2 because even if the implementation is simple we will need exhaustive test coverage. Possible 5 because this may require changes to the task model (new status? new workflow?) as a result of design and user research considerations.

Will need release notes.

**Comment by lomky** [comment]
Morphed into Tech Spec task for next sprint, in collab with Product design

**Comment by lomky** [comment]
@lowellrex @hschallhorn I see a finished PR for the tech spec and an issue for implementation spun out from there. Is this task complete?

**Comment by lowellrex** [comment]
I think the only thing left is to connect the script (added in #12483) with the front-end that removes folks and a back-end hook (or regular job monitor?) that re-assigns tasks when somebody leaves an organization. Do we have a ticket written to do this work?
