### ISSUE TITLE
BSE 65150 - Capability for Caseflow to Capture Data Related to Medical Opinion Requests

### ISSUE THREAD

**Issue by geoffreystienblock** [department-of-veterans-affairs/caseflow#11998]
**Requirement:**  PA&I needs ability to track remands based on medical opinion advisory from Board

**Value Statement:**  As a Board Caseflow user I need the ability to capture various data related to an advisory medical opinion (AMO) at an issue level, so that the system is able to adequately capture metrics related to AMOs for reporting purposes under Section 5 of the Appeals Modernization Act.

**Definition of Done:**  Tracking of advisory medical opinions from Board will become more robust and reduce claims processors’ reliance on legacy systems. 

**Acceptance Criteria:**  1.Board Users are able to manually capture the date they requested an AMO.
2.Board Users are able to manually capture the date the results of the AMA were received by VA.
3.Board Users are able to indicate whether the AMO was factored into the decision.
4.Board users are able to indicate that an issue is being remanded for an AMO.

**Comment by msj0nes** [comment]
# Update
Per @carolinejavornisky @geoffreystienblock lets discuss topic mentioned by BVA. BVA mentioned they already track this information and have reports with PAI available and are willing to share. Lets facilitate a conversation between BVA and AMO to confirm BVA PAI reporting available meets AMO needs or if anything additional is needed.

**Comment by janechi1** [comment]
For the Section 5, Congressional Mandated Reporting per PUBLIC LAW 115–55:  here's the needed information for this report.   The metrics are for these sections:  Part 1, Sections H and I.  VBA's data business division - PA&I is unable to code this because Caseflow data does not store document receipt data for medical opinions.

(H) The Average Number of Days between date of Board Remand for an Advisory Medical Opinion and date on which the Advisory Medical Opinion is obtained (received).

(I) The Average Number of Days between date of Board Remand for an Advisory Medical Opinion and the date AOJ issues a decision taking into account the Advisory Medical Opinion.
