### ISSUE TITLE
Mask more exceptions from Sentry -> Slack alerts

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12158]
* ClaimReview::NotYetProcessed (filter in lambda code)
* BGS::ShareError (needs investigation)
* VBMS::HTTPError (needs investigation)
* HTTPClient::ConnectTimeoutError (update bgs and/or vbms libs to recognize this as `.ignorable?`)

Create a more specific error class for BGS::ShareError that are ignorable. Same for VBMS::HTTPError if that seems right after investigation.

Examples:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4110/

**Comment by leikkisa** [comment]
I want to ask more about masking ShareError and VBMS::HTTPError, I think those might be useful to keep.

**Comment by pkarman** [comment]
see #12103

**Comment by pkarman** [comment]
see #11482

**Comment by leikkisa** [comment]
I looked into the "no records returned" for the BGSShareError, and we have a different file number and SSN stored for that participant ID :-/.  I think this is related to the great de-duping effort happening externally, but do still think it's useful to get alerted to this with the BGSShareError rather than silencing it.

**Comment by leikkisa** [comment]
Here's one for the VBMS::HTTPError that I don't think we should ignore:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5436/events/471146/
