### ISSUE TITLE
Investigate why a blocking MailTask was created as the child of a RootTask

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12156]
As of #11845, we have been creating blocking `MailTasks` as children of `DistributionTasks` in an effort to simplify how blocking tasks are implemented. BUT, [we found](https://github.com/department-of-veterans-affairs/caseflow/issues/11590#issuecomment-532720053) an errant blocking `MailTask` that is a child of a `RootTask` that has been created since this code's implementation. This ticket exists to investigate how this happened and implement a fix if need be.

**Comment by kevmo** [comment]
1 |
2 | |||
3 | ||||||||
5 | |
8 |

Seems pretty open-ended - should we put an upper limit on this? 🤔  Has only been one of these so far, so not super-high priority.  If we cannot figure it out, a data integrity alert is sufficient.

3.  Try to limit to a 3's worth of effort. Potential 2 because this _could_ be pretty straight-forward. 5 because it's an investigation task. 🕵️‍♀️
