### ISSUE TITLE
Add Virtual Hearing Links to Daily Docket and Hearing Details

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12347]
Hearing Details
![Screenshot 2019-10-09 16.46.32.png](https://images.zenhubusercontent.com/5cd05a11cdc0ba05ef4f13f6/8d40f5b6-de02-4aa6-91cf-89b5763765c5)
https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391733361

Daily Docket
![Screenshot 2019-10-09 16.45.25.png](https://images.zenhubusercontent.com/5cd05a11cdc0ba05ef4f13f6/c1ce0986-f828-4823-a5fe-6c8cc84fcb6d)
https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731332

The Daily Docket displays the VLJ Virtual Hearing Link in the Actions column. Clicking the link/label opens the virtual hearing URL in a new tab.

**Comment by nicholer** [comment]
@lomaxap @pshahVA 

1. For VSO users, we don't want the VLJ Virtual Hearing Link to display on their Daily Docket. Should we note that here?
2. Should I create a separate ticket if we want the regular participant link (i.e. the link emailed to Veterans and Representatives) to display on the VSO Daily Docket?

**Comment by nicholer** [comment]
@lomaxap @pshahVA 

Also, since we now have an in-progress state for the VLJ Virtual Hearing Link, should that go in this ticket as well?

Hearing Details: https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731030
Daily Docket: https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731333
