### ISSUE TITLE
RemandReasonRepositoryError

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#12350]
### Description
We getting RemandReasonRepositoryError when attempting to establish a claim.  This ticket is to investigate what is causing this, and to fix it if possible.

### Impacted reviews
HLR 35327 - Resolved
HLR 57317 - Resolved
HLR 152006 - Resolved
HLR 153395 - Resolved
HLR 147776 - Resolved
HLR 511618 - Resolved

### Tech notes
The EPs are being established just fine, but it is failing on the legacy issue optin. See comment below.

**Comment by leikkisa** [comment]
Closing this ticket. Something got into a weird state, maybe the first time it ran it partially succeeded and then got disconnected.  Adding notes here in case it ever happens again.

First the remanded issue is opted in to AMA.  After it was opted in, we checked and there were no other active issues and determined the entire legacy appeal could be closed as an AMA opt in. So the remanded issue needed to get reverted back to remanded, and the entire appeal closed (with the AMA opt in disposition).

When code was being done to revert the issue opt-in, it runs `perform_actions_if_disposition_changes`, which updates the remand reasons.  That code has a return statement if either the old or new disposition are for an AMA opt-in.  The return statement was being skipped because both the issue's old and new disposition were set to remanded (one of them should still have been set to the AMA opt in disposition), so it was trying to update the remand reasons, which failed because we don't provide any.

To fix this, I manually opted in the remanded issue, and then ran `establish!` again.

**Comment by yoomlam** [comment]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7685
`Caseflow::Error::RemandReasonRepositoryError: Remand reasons must be present when issue disposition is remanded`
Please make Sentry alert message actionable.

**Comment by leikkisa** [comment]
@leikkisa Convert to an engineering fix ticket instead of investigation

**Comment by wdrougas-tista** [comment]
Manual resolution ticket #[15801](https://app.zenhub.com/workspaces/foxtrot-5f075a9e28abd0001de67d7b/issues/department-of-veterans-affairs/caseflow/15801)
