### ISSUE TITLE
SCM: Extend the organizations_user with judge & attorney roles 

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12420]
In order to allow others to act on behalf of Judges, add clear roles to members of Judge Teams.

## Acceptance Criteria
 - [ ] `organizations_users` table has a column `judge_team_role`, valid values of nil, `judge`, and `attorney`
 - [ ] Judge teams can only have only have one judge

This ticket _does not_ include updating the code base to do anything with these fields, nor updating the existing teams.

Part of #11801

**Comment by kevmo** [comment]
Estimating at 1.

**Comment by lowellrex** [comment]
@lomky Love this idea! Super pumped to stop overloading the `admin` column for `JudgeTeam`s!

How do you feel about moving the new `judge_team_role` column into a different table since it will only apply to judge teams? That field will only have values for `OrganzationUser`s associated with `JudgeTeam`s and right now less than a third of the rows in that table are associated with `JudgeTeam`s. That proportion will likely decrease over time since we will add more teams and organizations, and judges and attorneys are already well populated in that table.

```ruby
rails c> OrganizationsUser.count
# 3144
rails c> OrganizationsUser.where(organization_id: JudgeTeam.pluck(:id)).count
# 954
```

What do you think of a table definition that looks like the following:
```sql
judge_team_users (
  organziations_users_id    int -- could instead use organization and user IDs
  role                      enum(judge, attorney)
)
```

Some advantages to this approach include:
1. Avoiding `null` roles. If a user is in a judge team they will have a role.
2. All column in `OrganizationsUser` are relevant to all rows. Currently there are only three columns in this table that are not used for linking the user and the organization. `created_at` and `updated_at` provide timestamps and `admin` is a boolean which describes whether someone is has administrative privileges or not. All organizations make use of administrative privileges in some way (user management), so this applies to all rows in the table.

**Comment by lowellrex** [comment]
We're going to proceed as follows:
1. Create new `JudgeTeamRole` single-table inheritance models (slightly modified approach described above).
2. Start creating these objects in the application code.
3. Backfill data where `JudgeTeamRole`s should exist.
4. Cut over to identifying judges and attorneys using `JudgeTeamRole`s (#12422)

**Comment by lomky** [comment]
@lowellrex number 3 is a follow-on ticket, as well. #12421

**Comment by lowellrex** [comment]
Closing this ticket since all remaining work will happen in #12481, #12421, and #12422.
