### ISSUE TITLE
Persistent Redux Store

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#12439]
### Background
Currently the entire contents of the Redux store is lost and regenerated if the user reloads the page. While this can have its advantages (guaranteeing that the page is using fresh data from the server), it can also have significant downsides. Reloading while on certain routes can end up without the requisite data in the store, losing state and pushing the user off of the route they were on.

### Notes
Not everything should necessarily be persisted. A good solution would likely choose to whitelist certain portions of the tree and not others

### Resources

- [redux-persist](https://github.com/rt2zz/redux-persist)

### Acceptance Criteria
- [ ] install `redux-persist`
- [ ] document where/how to whitelist certain items that are determined to be worthy of persistence

**Comment by pkarman** [comment]
This runs into the 2nd hardest problem in computer science, cache invalidation. Since we're talking about persisting data on the browser, presumably, that makes invalidation trickier, IMO.

I guess I'm feeling like "tread carefully" is important here. What specific routes cause problems on reload? If we're losing state that impacts UX I'd be interested in exploring how/why we've built the app the way we have. While there are SPA aspects to Caseflow, it's intentionally not a true SPA and we ought to be able to survive page reloads.
