### ISSUE TITLE
User is not authorized error

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#12593]
### Description
We are getting the "User is not authorized" error when attempting to establish a claim.  As the user, there are no sensitivity reasons being returned and may_modify? is returning true.

### Impacted reviews and incident report submitted
SCs impacted: [69929, 74256, 90312, 133310, 181842]
Users: [2321, 3309, 5290, 7739, 12788]

INC8206336
https://yourit.va.gov/va?id=ticket&table=incident&sys_id=48356e27dbb40c54587fff1e0f96193b

**Comment by leikkisa** [comment]
We've learned this is because the user is a relative of the veteran at the same station. The last one of these was in October, so maybe this has been fixed in the code.

For the outstanding ones if we can get a different user to establish them they should be able to succeed.

**Comment by msj0nes** [comment]
@leikkisa  for this ticket considering VBA does indeed have a same station policy and we've resolved it for BVA recently (to allow same station), is there any engineering intervention to resolve this when it occurs outside of providing clear error messaging.  

Error message, rather than displaying **not authorized**, provide 'Same station error' so user(s) know the specific reason? If there is a VBA team for same station users to contact internally about this (to arrange for another team to handle), we can obtain and add those details in messaging from AMO.

**Comment by leikkisa** [comment]
Moving this to comments:

**Comment by leikkisa** [comment]
These need to get switched to a different user.  Hopefully we don't see any more of these, but if we do, here's how to process them:

Cancel the establishment with the note that this intake needs to be processed by a different user due to permissions. See `ClaimReview.cancel_with_note!`

Other than that, this ticket can be closed.
