### ISSUE TITLE
Documents List | Show last read indicator

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1266]
**Story**
When returning to the Documents List page, I want to know where I left off, so I don't lose my place.

**Description**
When a user navigates to the Documents List page, a last read icon (see mock) is displayed next to the document last shown to the user.

## Mockup
![image](https://cloud.githubusercontent.com/assets/13420618/24181501/a518a226-0e91-11e7-951c-d87544f91223.png)

[Last read icon svg](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Caret%20right%20icon.svg) 

[Invision Prototype](https://projects.invisionapp.com/share/BVB8NSO49#/screens/228296697)

## Acceptance Criteria
- Validate that the last read indicator is displayed next to the most recently opened document, and only that document, on the Documents List page
- Validate that if no documents have been opened, no last read indicator is displayed on the Documents List page
- States resets on refresh

**Comment by abbyraskin** [comment]
@gnakm Do you think this icon should display if the user takes _any_ action on a page, or only if it was most recently opened? For example, if the user has multiple windows open...opens one document from the documents list, then adds a comment to a different document that was already opened, which one gets the indicator?

**Comment by gnakm** [comment]
@abbyraskin That's a really good question. I want to say takes any action, even if that includes just opening to read it. 

So scenario 1: I just clicked on a document, skimmed it for 10 seconds and when back to document list page. I want to see the indicator to in order to know which document I just viewed. 

scenario 2: I just opened 1 document so I can read it side by side with the 5 other documents I already have open. I need to add 2 comments on one of the documents I already had open. When I refresh any of the tabs, or go back to all docs, the indicator should be on that last action.

**Comment by abbyraskin** [comment]
@gnakm that was my instinct as well. 

@mdbenjam curious to hear your perspective; i believe our suggested implementation adds some complexity.

**Comment by mdbenjam** [comment]
Yeah, for the first round let's keep it at just most recently opened. What we're talking about here requires some level of syncing with the server to poll for new comments etc. Which we're not doing right now. This is also a concern since someone could add comments to a page and not see it if they have that same document open in another tab.

**Comment by abbyraskin** [comment]
OK - AC updated

**Comment by gnakm** [comment]
Keep state of last read in front end
Keep that state in back end for future

@mdbenjam

**Comment by abbyraskin** [comment]
@gnakm assigning to you to provide svg magic

**Comment by NickHeiner** [comment]
> @gnakm assigning to you to provide svg magic

![svg magic](https://media4.giphy.com/media/12NUbkX6p4xOO4/giphy.gif)

**Comment by gnakm** [comment]
@NickHeiner https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Caret%20right%20icon.svg

**Comment by NickHeiner** [comment]
Oh sorry for the confusion. Mark already have the SVG. I just wanted to make a joke about the phrase "svg magic". :smile:

**Comment by astewarttistatech** [comment]
**PASSED**

Validated In: Preprod
Browser: FF and Chrome

Steps to Validate: 
1. View a veteran's file with documents in Reader. 
2. Click on one of the documents in the list view. 
3. From the PDF viewer, navigate back to the list view of documents. 
4. Validate that the "last read icon" is placed on the last document accessed. 

Screenshots: 
![lastread_reader](https://cloud.githubusercontent.com/assets/23038505/25352319/a44accb6-28f9-11e7-818a-c8d7dfa36bde.gif)
