### ISSUE TITLE
Investigate How to Handle Appeal Merging in Caseflow

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#12681]
On occasion, a veteran will have a duplicate appeal in VACOLS and/or Caseflow. This often causes conflicts where the user needs to consolidate tasks between appeals and keep track of which appeal is stale and which is current

A few issues that arose as a result of merged appeals:
https://dsva.slack.com/archives/C42P25D6H/p1556804167161700
https://dsva.slack.com/archives/CHX8FMP28/p1573570446224600
https://dsva.slack.com/archives/CHX8FMP28/p1571672180189100
https://dsva.slack.com/archives/CHX8FMP28/p1561153799367300?thread_ts=1561037045.292900&cid=CHX8FMP28
https://dsva.slack.com/archives/C6E41RE92/p1551968010035800

At the very least I think we need to document the current, manual merging process that admins do in Caseflow and VACOLS. We could also consider providing a way to mark a merged appeal in Caseflow or, if we're feeling ambitious, handle merging completely in Caseflow.

**Comment by D-L-Ware** [comment]
Response for more background on merges (I am happy to talk about this in person or on a call if anyone is interested):

The most common reason for a merge to be need is when there are two separate legacy appeals for the same Veteran that arrive at the Board in close proximity.  

Example:
Vet applies for benefits and receives a Rating Decision in July 2015 denying Service Connection for right knee arthritis.  The Vet in turns appeals to the Board.  Development, for whatever reason, takes 4 years and the appeal ends up certified to the Board in November 2019.

Vet applies for benefits and receives a Rating Decision in August 2018 denying Service Connection for PTSD.  Development, for whatever reason, takes must less time.  The appeal ends up certified to the Board in November 2019.

The appeals are two separate records in VACOLS.  It is Board policy, because it is beneficial to the Veteran, to adjudicate all appeals that are for a single Vet that are within the jurisdiction of the Board at the same time in the same decision.  As such, the VACOLS records must be merged into one record containing both the knee arthritis and PTSD issues.  The record with the oldest docket number always becomes the record that continues on because an older docket number is more beneficial to a Veteran in the event of a remand by the Board or CAVC.  

The above scenario is a legacy scenario, however, similar scenarios can happen in AMA.  

I, regretfully, am ignorant as to how merging is occurring in Caseflow, that is, if it is happening in Caseflow at all.

**Comment by D-L-Ware** [comment]
Also worth mentioning, before anyone gets any ideas about automation, there is more to merging an appeal that simply having two different appeals for the same veteran before the Board at the same time.  Jurisdiction issues such as if one appeal was from VBA and the other from VHA would mean merging is unnecessary.

**Comment by kevmo** [comment]
Beginning point of this ticket:
> Document the current, manual merging process that admins do in Caseflow and VACOLS.

**Comment by kevmo** [comment]
# Estimation: 3

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | |||||||
5 | |||||
8 | 
```
Document manual process. Then investigate impacts and what we should do in the future.

Why could this be a 5? Lot of discovery re who we need to talk to, coordinate with --> overhead costs.  Why could this be a 2? Could already be a decent amount of discussion in Github/Slack as to how this is done --> could just be a matter of compiling that to get the starting work done.
