### ISSUE TITLE
BSE 66302: Ability to Create Supplemental Claim in Caseflow for Difference of Opinion Returns

### ISSUE THREAD

**Issue by SusanRKagan** [department-of-veterans-affairs/caseflow#12700]
As a Caseflow user, I need the system to automatically create an EP040 whenever a user in VBMS returns a rating or non-rating claim based on Difference of Opinion, so that I can ensure that the claim being returned is not lost.

## Acceptance criteria
• Caseflow supports the auto-creation and establishment of an EP040/930 whenever an EP030/930 is closed out as "Difference of Opinion" in VBMS.
• The following EP040/930s should be supported by Caseflow:
If the Claim being sent back is:	              The Claim that should be created is:
030 with a rating claim label	                       040 AMA Difference of Opinion - Rating
030 with a non-rating claim label	               040 AMA Difference of Opinion - NR
930 with a rating claim label	                       930 AMA Difference of Opinion - Rating
930 with a non-rating claim label	               930 AMA Difference of Opinion - NR
030 with a non-specific claim label	               040 AMA Difference of Opinion - Rating
930 with a non-specific claim label 	       930 AMA Difference of Opinion - Rating
030 with a PMC rating claim label	               040 PMC AMA Difference of Opinion - Rating
030 with a PMC non-rating claim label 	       040 PMC AMA Difference of Opinion - NR
930 with a PMC rating claim label	               930 PMC AMA Difference of Opinion - Rating
930 with a PMC non-rating claim label	       930 PMC AMA Difference of Opinion - NR
030 with a PMC non-specific claim label	040 PMC AMA Difference of Opinion - Rating
930 with a PMC non-specific claim label	930 PMC AMA Difference of Opinion - Rating

### Background/context
Users in VBMS currently have the ability to return a higher-level review/EP030 for two different reasons: 1. DTA Error, and 2. Difference of Opinion (DOO) with the prior decision. Presently, when a user returns an HLR for DTA error, Caseflow will create an 040 - HLR DTA Error so the claim is not lost.  This is not happening in Caseflow when users are returning a claim for DOO.  There is a critical business need for Caseflow to begin creating a corresponding EP040 whenever an HLR is returned for DOO, so that claims are not lost when they get closed out due to DOO.

**Comment by leikkisa** [comment]
We are waiting on the EP codes from VBMS before we can actually implement this.

One option is that we can start implementing this behind a feature toggle and "bogus" placeholder codes, so that when we do get the codes we can finish implementation quickly.

**Comment by jimruggiero** [comment]
@msj0nes This one just came in from VBA/AMO. We need to do a few things: 

1.) Validate that the labels above match the latest from Michael Palmer last week on 11/13. 
2.) Create two tickets to right-size the work for ENG
3.) Get EP claim label equivalents for these from VBMS

Ideally, we use this ticket for building the ability to add the EP codes. Then create a second ticket whose scope is establishing these EP codes when we see a DOO disposition (make the second ticket dependent on this one, so that it's blocked until work on this ticket is complete). 
[https://app.zenhub.com/files/51449239/0293f183-3519-48b7-aaaf-48eeee03a44e/download](https://app.zenhub.com/files/51449239/0293f183-3519-48b7-aaaf-48eeee03a44e/download)

**Comment by jimruggiero** [comment]
@leikkisa We should hold off until we get codes from VBMS.

**Comment by leikkisa** [comment]
Closing, this was completed by #10815
