### ISSUE TITLE
Stop Tasks from being `assign_to_type` `Vso`

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#12795]
## Description

Tasks should have the `assigned_to_type` value of either `User` or `Organization`, however we discovered a handful assigned to `Vso`. 

## Background/context/resources

 - [Slack thread fixing the previously found ones](https://dsva.slack.com/archives/CJL810329/p1574441390035500)

![image (3)](https://user-images.githubusercontent.com/6129479/69548202-e74dc000-0f64-11ea-9afa-9a36c5b76b0a.png)

## Acceptance Criteria
 - [ ] Integrity check created enforcing only `assign_to_type`s of `User` and `Organization`
   - [ ] If that is not possible, create an alert for any other value

**Comment by lowellrex** [comment]
We could alternatively put a constraint on the database to only those two values (`enum(Organization, User)`).

**Comment by yoomlam** [comment]
Example of need for #12773.

**Comment by hschallhorn** [comment]
Rather than a data integrity check, let's go [this](https://github.com/department-of-veterans-affairs/caseflow/issues/12795#issuecomment-558182189) route

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||
2 | |||||||||||
3 | 
5 | 
8 |  
```

Seems fairly straightforward. Could be as simple as adding one line to the model and a test. Kat is clutching her ~pearls~ ones. Triple check that all tasks have type `User` or `Org`.
