### ISSUE TITLE
remove success alert on any updates to virtual hearings

### ISSUE THREAD

**Issue by rubaiyat22** [department-of-veterans-affairs/caseflow#12832]
We're no longer using green success alerts for virtual hearings. Since any updates to virtual hearings are not saved until async job completes, we will not be showing this alert. However, this alert still shows for any other changes made to hearings like when user changes the assigned judge or hearing locations.

Design:
https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731030
https://va-gov.invisionapp.com/share/8AUO95JMRW7#/screens/391731329

![Screen Shot 2019-11-27 at 6.11.20 PM.png](https://images.zenhubusercontent.com/5d518fc3e04e3134e624281f/c3079f50-c39c-427c-ba28-24df7f0a2723)

**Comment by lomaxap** [comment]
had a brief discussion with @nicholer about this [here](https://dsva.slack.com/archives/C3EAF3Q15/p1574434774154300). She said this is fine for now, and we can wait for feedback from users if we want to remove it. @nicholer does this still work for you?

**Comment by nicholer** [comment]
I agree that if a user edits something unrelated to virtual hearings (like the judge), and also makes changes to the virtual hearing (like the POA email address), both alerts can display.

Above where it says "We're no longer using green success alerts for virtual hearings", I took that to mean we're not showing the success alert just because a virtual hearing async job finished. And that also sounds right.

**Comment by rubaiyat22** [comment]
I'm going to close this issue for now as it seems like we want to show both alerts in most cases. I feel like we should revisit this after some user feedback. Does that sound right to ya'll? @lomaxap & @nicholer

**Comment by nicholer** [comment]
Works for me!

**Comment by rubaiyat22** [comment]
reopening to address showing blue alerts only when virtual hearing related stuff is updated
