### ISSUE TITLE
Clean up task status code

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12916]
## Description

Implementation of `task.open?`, `task.active?`, `Task.closed_statuses`, and `Task.open_statuses` is convoluted and can be simplified. If additional status values were added, the code will be more susceptible to bugs. 

Once corrected, update https://github.com/department-of-veterans-affairs/caseflow/wiki/Tasks#task-status accordingly.

## Technical notes

  * Possible task status values (see `task.rb: enum status`): `assigned`, `in_progress`, `on_hold`, `completed`, `cancelled`. 
  * A task is `closed` if it is `completed` or `cancelled` (see `Task.closed_statuses`). 
  * `task.open?` is implemented as `!self.class.closed_statuses.include?(status)`.
  * A task is `active` (`task.active?`) if it is `assigned` or `in_progress` (see `Task.active_statuses`). 
  * Note that `Task.open_statuses` is implemented as `active_statuses.concat([Constants.TASK_STATUSES.on_hold])`, which corresponds with `task.open?` as long as no other status values are added. This implementation also does array modification when it should be constant, which is faster.

Possible correction:
  * `Task.open_statuses` should simply be all tasks that are not closed.
  * `active` tasks are a subset of `open` tasks that exclude `on_hold` tasks.

**Comment by hschallhorn** [comment]
Ensure we're using these scopes in the code as well. If we don't want to change anything, add some clarification comments._[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||
2 | ||||||
3 | ||||
5 | ||
8 |  
```
Possible one because this may be a few lines to change. We rely on this code basically everywhere. Need to ensure we're not breaking everything. `.STATUS` appears 700+ times. Tracking down where we should be using scopes instead could be a lift.
