### ISSUE TITLE
Ensure new tasks are only assigned to active users

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12943]
Since the ability to mark users inactive was deployed (#12212), we have removed inactive users from organizations that automatically assign tasks to their members (#12303) to ensure they do not get assigned more tasks. We will also remove them from all other organizations to cut down on ways they can be assigned tasks while inactive ( #12940). At task creation, we should validate that the assignee is actually active and task creation should fail if they are inactive.

## AC
- [ ] New tasks cannot be assigned to inactive users

**Comment by kevmo** [comment]
[Active Record Validations](https://guides.rubyonrails.org/active_record_validations.html)

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||||||
3 | |||||
5 | 
8 | 
```
Estimated at a 2, with precise uncertainty towards a 3.

Might be a 3 because new tests take a bit more lift than editing existing ones.

**Notes**

Validation at Task creation. What does the error path look like? Automatic assignment vs manual? For manual, reasonable error messaging. Ask product/design for what reasonable messaging is (lots of lead time!) give the context and what actions to take, then tag Product for insight!

Split into other ticket (#12949)
Limit the round robin assignee pool to the active scope for users. 
Limit any task assignment list to the list of active users.

Assignment of Org tasks to inactive orgs? Not in this scope; probably not relevent if/until JudgeTeams get org tasks.
