### ISSUE TITLE
Remove inactive users from all organizations

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12940]
As a followup to #12303, we would like to remove a user from their organizations when they are marked inactive. This excludes removing judges from their `JudgeTeam`s as that will be handled in another ticket

## AC
- [ ] When a user is made inactive, they are removed from every organization they are a member or admin of, other than judges from `JudgeTeam`s

## Notes
As judge teams are the only organization that somewhat rely on there being a dedicated admin (at least until SCM epic is finished), there should be no ill effects of an organization that loses an admin.

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_                   
```                                                                                                                
1 | ||
2 | |||||||||||
3 | || 
5 | 
8 | 
```
Estimated at a 2
**Notes**

Might be as simple as removing a caveat (only robin robin vs all) and updating tests. Some unfamiliarity.

**Comment by hschallhorn** [comment]
[Here](https://github.com/department-of-veterans-affairs/caseflow/pull/12319/files#diff-4676c008b11a5480d73d4a6de01e45b9R330) is where we select automatically assigned orgs

**Comment by yoomlam** [comment]
Since a `JudgeTeam` is not an organization that automatically assigns tasks to its members, it won't be included in `auto_assign_orgs`: https://github.com/department-of-veterans-affairs/caseflow/blob/a4d7590ba4beccb3031ce749a7d3fdeb8fba5e96/app/models/user.rb#L338-L342
and hence `remove_user_from_organization` won't be called for JudgeTeams regardless of whether the user is a judge or not. 

The inactive user is only removed from auto_assign_orgs:
https://github.com/department-of-veterans-affairs/caseflow/blob/a4d7590ba4beccb3031ce749a7d3fdeb8fba5e96/app/models/user.rb#L289-L294

What am I missing?

**Comment by yoomlam** [comment]
From Hunter: 
> This ticket exists to remove users from all organizations (other than JudgeTeams), not just the ones that do automatic assignment. Judge teams will be handled in Mark judge teams inactive when the judge becomes inactive #12942

I had a brain fart. I think I was down in the weeds and kept misreading/overlooking the first sentence of this ticket. 🥇
