### ISSUE TITLE
Mark judge teams inactive when the judge becomes inactive

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12942]
In an effort to remove a user from any organizations they are a part of (#12940), `JudgeTeam`s should be handled separately. Rather than removing an inactive judge from a `JudgeTeam`, we should mark these `JudgeTeam`s as inactive

## AC
- [ ] When a judge is made inactive, so is their corresponding `JudgeTeam`

**Comment by lomky** [comment]
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | |||||
2 | ||||||||||
3 |  
5 | 
8 | 
```
Estimated at a 2.

**Notes**

Do users have versioning? Not currently. Some disagreement on the team whether we want to track this in versions vs log analysis. Do we need to keep the entire version ledger in prods db? Later topic.

Inactive Organizations is new, just finishing PR. Two new fields on Orgs (`status` & `status_updated_at`), largely mirrors the inactive user. 

If a judge gets marked inactive, go update the status in their judge_team to inactive. This will need a couple tests, but otherwise straightforward. Do not empty inactive judge_teams of their atty/admin members.

Should we affect Atty task work ability if they belong to an inactive judge team? No, that should be handled elsewhere.

Its a little strange that we remove inactive users from active orgs, but not active users from inactive orgs.  We should follow up with the board what the preferred business process would be here. We could implement behavior if they do know what they want to happen.
