### ISSUE TITLE
No Calendar invites are sent in the virtual hearings emails

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#12974]
UAT Error
Problem: The virtual hearing emails for:
1.) Creation
2.) Update
3.) Cancellation
Don't have have calendar invites.

Acceptance Criteria:
Calendar invites are sent with the emails.

**Comment by ferristseng** [comment]
@nicholer There are some attributes we can set in the calendar invite that might need some design work. From what I could find, I didn't see these mentioned. I don't think any of these are required, but might be useful:

  - Summary: basically the event title that shows in the calendar
  - Description: detailed description of the event
  - Duration / End time: how long the hearing will take. how long are these usually scheduled for? 30 minutes?
  - Alarm: how far in advance, and what should the alarm be if any? I think this only gets used if the calendar application they open the invite with supports it (most probably do)
  - Organizer: this is an email address for the organizer. we could set it to make it easier to figure out who to contact if there's an issue?

**Comment by nicholer** [comment]
@ferristseng Thanks for the heads up! Since I'm updating the email copy overall in response to stakeholder feedback, I'll include another pass on the calendar invites too. There's overlap in the copy, so once it's finalized we can update both the emails and the invites.

In the meantime: in the email copy doc, at the end of each table, I included a section for calendar invite copy: https://docs.google.com/document/d/1u3x6KX5uu7V9G4jjctmuy8-AaXVgzo3t4Nm1C3AzMmE/edit?usp=sharing

I'm hoping what's already there will be sufficient in terms of moving this ticket forward. As far as duration / end time, hearings are scheduled to be 30 minutes (although in practice they can run longer).
