### ISSUE TITLE
Error in DuplicateVeteranParticipantIDFinder from Incorrect Data in BGS Record

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13184]
## Description
While doing intake, the user can get a "Something went wrong" error when doing lookup of veteran. This is due to `DuplicateVeteranParticipantIDFinder` doing lookup on multiple possible fields in the veteran's BGS record:
- ssn
- soc_sec_number
- ssn_nbr

In this case, the `ssn` field was correct, but the `soc_sec_number` was off by one on the final digit (`ssn_nbr` was `nil`). Performing the call to `BGSService` with the incorrect value triggered this error:
```
undefined method `[]' for nil:NilClass
```
While the ultimate problem is bad data in BGS, we should add better error handling to account for the possibility.

## Background/context/resources
- [Sentry Alert](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7677/)
- [Line that makes call to BGSService](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/services/duplicate_veteran_participant_id_finder.rb#L19)

**Comment by leikkisa** [comment]
I agree with this. A good fix would be not trying to access ptcpnt_id on a nil response, instead of error handling. The goal of this code is to get all of the available participant_ids for a veteran with duplicate records, so we just won't get one from the nil person record.

`BGSService.new.fetch_person_by_ssn(ssn)[:ptcpnt_id]`

**Comment by jcq** [comment]
YourIT ticket created:
INC9154840
