### ISSUE TITLE
Motion to Vacate | Allow AddressMotionToVacate Task to Appear in Judge Queue

### ISSUE THREAD

**Issue by jcq** [department-of-veterans-affairs/caseflow#13198]
## Description
By default, while a judge can act on an `AddressMotionToVacateTask` from the case details page, it does not show up in their queue due to existing filtering rules. We need to alter things so that these show up correctly.

## Background/context/resources
Existing Queue code filters this list to just a few specific task types instead of displaying all tasks that are assigned to a judge user. Why?

## Technical notes
- This is being filtered out in the [judgeDecisionReviewTasksSelector](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/selectors.js#L284
) redux code

**Comment by jcq** [comment]
@lomky or @hschallhorn, could one of you shed light upon the existing logic (link in tech notes above)? I can obviously just add `AddressMotionToVacateTask` to the list of allowed tasks in that filter, but I figure it's better to understand the purpose before just adding stuff willy-nilly.

**Comment by hschallhorn** [comment]
😄 This got lost in my emails. This selector exists because we technically have 2 queues for judges, their "assign" queue and their "decision" queue. Their assign page lists only judge assign tasks, both legacy and ama and their decision queue holds all other tasks they can take action on (reviewing and modifying decisions). `judgeDecisionReviewTasksSelector` grabs all tasks that should be shown in this second queue.

**Comment by jcq** [comment]
>`judgeDecisionReviewTasksSelector` grabs all tasks that should be shown in this second queue.

This makes sense. I wonder if it might make sense to refactor things a bit with the goal of being a bit more future proof, but that's not at all critical to do at the moment.
