### ISSUE TITLE
Manual Fix | Board Grant Effectuations | Update Issue/Contention Titles That Cannot Be Currently Edited 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13291]
## Description
**From AMO:**
Here’s an ongoing issue users have been struggling with.  Specifically, these are the claims coming over from the Board and the contentions cannot be edited.  Please see the screenshots below.  

Can you have a look at this to determine why Caseflow is establishing these contentions with those specific titles?  This is something that we have raised before and we will need to work toward resolution as it is preventing users from ordering exams and rendering decisions on these claims without manipulating VBMS or going into a legacy system to update the contention title and thus, breaking Caseflow’s data tracking ability.
### Claim Info
![image](https://user-images.githubusercontent.com/41164406/73342880-78833080-424d-11ea-87b0-f26efe9be4d0.png)

### Request: 
Manually resolve this issue with the information provided below. 

**Visible in VBMS**

![image](https://user-images.githubusercontent.com/41164406/73342115-f0505b80-424b-11ea-8b37-11417bbb419a.png)

**Actual issues are as follows…**

Service connection for an acquired psychiatric disorder, to include posttraumatic stress disorder and anxiety disorder, is remanded.
Service connection for pinguecula, bilateral eyes (claimed as eye condition) is remanded.
Service connection for hypertension is remanded.
Service connection for cataracts of both eyes (claimed as eye condition) is remanded.
Service connection for right knee degenerative joint disease to include as secondary to service-connected left knee is remanded.
Entitlement to individual unemployability is remanded.
Entitlement to a temporary 100 percent evaluation based on surgical or other treatment necessitating convalescence (Paragraph 30) is remanded.

## Background/context/resources
N/A

## Technical notes
N/A

**Comment by leikkisa** [comment]
@msj0nes I looked up this EP and it's actually a remand - these issues were already editable in Caseflow at their regular URL.  I had just assumed earlier it was a BGE, because those are not editable.

I went ahead and fixed these in the backend though, because there were 7 issues, and it wasn't possible to tell which one was which in the front end because their descriptions were bogus.  I checked the issue's history to match them to the new descriptions correctly.

Partial screenshot (with fixed data) attached from prod:
![image.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/a5e9c060-743f-49fc-8d6e-d37605ba7a74)
