### ISSUE TITLE
Investigate cases where the VEText and the daily docket don't match times

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/caseflow#13310]
## User or job story
There have been a handful of instances in production where the hearings branch is stating that the VEText sent a different time then what was scheduled.

## Acceptance criteria
- [ ] Investigate the issue.

## Background
https://appeals.cf.ds.va.gov/queue/appeals/2901779 , the 10/29/19 hearing was scheduled at 9:00 AM EST, but the message said 12:00 pm EST

https://appeals.cf.ds.va.gov/queue/appeals/3224311 ,The 11/26/19 was scheduled at 9:00 AM EST, but received this text message saying to report at 1200 instead.

**Comment by ferristseng** [comment]
https://appeals.cf.ds.va.gov/queue/appeals/3224311 

  * Veteran got text saying 12:00 AM
    * `LegacyHearing` record was updated `Tue, 26 Nov 2019 16:43:48 UTC +00:00` (after the hearing)
      * Do not know what this change was
      * Updated by a Hearings Coordinator
  * Rails console shows `scheduled_for` of `Tue, 26 Nov 2019 09:00:00 UTC +00:00` (matches time veteran got)
    * Raw date from VACOLS is `2019-11-26 09:00:00`

**Comment by ferristseng** [comment]
One discovery is that the timezone for the `/api/v2/hearings/:date` alternates in the local dev environment.

It's also possible to get the API controller in a situation where it thinks `Time.zone` is on the West Coast:

```
[6822dd88-4e06-409b-9f3e-c4c8b06155cd] [localhost] Started GET "/api/v2/hearings/2020-04-20" for ::1 at 2020-02-24 15:19:59 -0500
[2020-02-24 15:19:59 -0500] Processing by Api::V2::HearingsController#show as */*
[2020-02-24 15:19:59 -0500]   Parameters: {"hearing_day"=>"2020-04-20"}
[2020-02-24 15:19:59 -0500]   ApiKey Load (0.7ms)  SELECT  "api_keys".* FROM "api_keys" WHERE "api_keys"."key_digest" = $1 LIMIT $2  [["key_digest", "RJophVt+ZN0a+8V9LS/J5x7VdaCatYvmo+46/Y+YfLg="], ["LIMIT", 1]]
[localhost] [6822dd88-4e06-409b-9f3e-c4c8b06155cd] [localhost] API authenticated by Testing 123
TIMEZONE FOR /api/v2/hearings/:date IS (GMT-08:00) America/Los_Angeles
```

**Comment by ferristseng** [comment]
Including a fix for the issue of the timezone not being reset after any request to a route that inherits from `ApplicationController` in this PR: https://github.com/department-of-veterans-affairs/caseflow/pull/13187

**Comment by ferristseng** [comment]
Going to close this, since I spent ~2 days investigating the 2nd case. It did not seem like there were any updates to the hearing through Caseflow in the week prior to the hearing, and we could not confirm when the veteran received the text.

Feel free to reopen to investigate the first case. All my findings are in the comment I posted.

**Comment by chandracarney** [comment]
Though we can't confirm much about this through Caseflow, if it was in fact a wider problem, we have uncovered an issue outlined in #14577 that may have positive impact.

VEText has been turned off since March 20 when all non-virtual hearings were postponed until further notice so we won't know more for several months.
