### ISSUE TITLE
Give judge assign queues human readable urls

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13433]
After work on #12423, users will be able to view the judge assign page of a judge. This url is formed as "/queue/<user_id>/assign". Users cannot be expected to know the caseflow user id of a judge. We should use their css id instead.

## AC
- [ ] Judge Assign queue url is "/queue/<user_css_id>/assign"

**Comment by kevmo** [comment]
Make sure old URLs continue to workwhile defaulting to displaying new URLs.

**Comment by kevmo** [comment]
# Estimation: 3

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||||
5 | |
8 | 
```

Why a 2?  Straightforward!!!  This is what Rails does, "add one line, change another line, make a test..."

Why a 5? Could blow up because this URL is going through React Router.  Pass through many different components.  Front-end refactoring could dramatically expand the amount of work -- this is not just a backend change!

**Comment by yoomlam** [comment]
Since we're overloading `<user_css_id>` in the URL "/queue/<user_css_id>/assign", I'll have to assume that if `<user_css_id>` is an `integer?`, then it is a `<user_id>`. This means that a CSS_ID must **never** be an integer or coercible into an integer.
