### ISSUE TITLE
Research: new hearing type of virtual

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13431]
## Context
Engineering research needed for new hearing type of "virtual hearing." Hearing Coordinators need to be able to schedule a virtual hearing from the start of the scheduling process. 

Hearing branch's end goals: 
- Increase capacity to perform hearings with virtual hearing or Regional Office (no mixed dockets).
- The Intake form identifies whether the Veteran is willing to have a virtual hearing (the Board is responsible for requirements to update the form). 

Interim solution required for the Board:
- Personnel at the Board will need to mark Veterans as eligible for virtual hearings after contacting Veterans.
- So that we are not immediately dependent on the form, the interim solution is that Hearing Coordinators (or Intake personnel) are able to mark a Veteran as eligible for virtual hearings.

## Open questions to answer:
Hearing type:
- How does hearing type get edited?

Checkbox for interim solution:
- Would this be a flag on the Veteran or a flag on the particular case/appeal? (Might be at the appeal level because the intake form has to do with the appeal, not the Veteran.)
- Should this be a new task type "mark eligible for virtual hearings"?
- What options do we have?
- What additional information is needed from product, stakeholders, or other teams?
- Do we have any external dependencies?

**Comment by ferristseng** [comment]
## WIP WIP WIP WIP WIP WIP WIP WIP

### Research Findings

#### Ensure `HearingDay` can accurately represent a virtual hearing

The current `HearingDay` model looks as follows:

```
HearingDay(
  id: integer,
  bva_poc: string,
  created_at: datetime,
  created_by_id: integer,
  deleted_at: datetime,
  judge_id: integer,
  lock: boolean,
  notes: text,
  regional_office: string,
  request_type: string,
  room: string,
  scheduled_for: date,
  updated_at: datetime,
  updated_by_id: integer
)
```

The only thing I can think of that should probably not apply to virtual hearings is the `room` field. There is some automated logic to find an available room in https://github.com/department-of-veterans-affairs/caseflow/blob/1d5bbcf189b2e8c3088ed30da6676fd1b70c8fc0/app/services/hearing_day_room_assignment.rb#L3, which we will need to circumvent for virtual hearings. Outside of that, it doesn't look like `room` is used too much in a way that we'd need to change. 

#### Compatibility with legacy hearings

The request type for a legacy hearing is stored directly on the hearing, instead of on the hearing day. This means that we could potentially have to introduce a new hearing type to VACOLS, which I'm not sure is possible since we won't be able to get a good sense if that would affect logic in VACOLS. One possible way to work around this is by treating the `HearingDay` as the canonical source for scheduling data if the hearing is in Caseflow past a certain date (see https://github.com/department-of-veterans-affairs/caseflow/issues/13273). If there's a `HearingDay` associated with a legacy hearing, we can have the request type on that day override whatever is in VACOLS. 

#### Ensure conditional logic can handle "virtual" type

Probably one of the biggest parts to this would be ensuring that all of the conditional logic we have that depends on the hearing day request type would be able to handle a new `virtual` hearing type. There are a number of places where we assume `central` or `virtual` hearing types such as:

https://github.com/department-of-veterans-affairs/caseflow/blob/1d5bbcf189b2e8c3088ed30da6676fd1b70c8fc0/app/models/hearing.rb#L80-L85

There *shouldn't* ever be a location for virtual hearings, but the function still handles all non-central hearings similarly. I think instead we should refactor all code that has conditional logic dependent on the request type to be explicit about how different hearing types are handled using a case/switch statement:

```ruby
def readable_location
  case request_type
  when HearingDay::REQUEST_TYPES[:central]
    "Washington, DC"
  when HearingDay::REQUEST_TYPES[:video], HearingDay::REQUEST_TYPE[:travel]
    return "#{location.city}, #{location.state}" if location

    nil
  when HearingDay::REQUEST_TYPES[:virtual]
    nil
  else
    fail HearingRequestTypeInvalid, "invalid request type #{request_type}"
  end
end
```

I think all the relevant code should be adapted to [fail fast](https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so) if we aren't explicitly handling any cases to catch any bugs as quickly as possible.

**Comment by pshahVA** [comment]
@chandracarney, as we discussed earlier, would we like to investigate a veteran self selecting from their va.gov profile?  I can create a ticket with the VA.gov team to look into this.

**Comment by ferristseng** [comment]
Going to close this, since the research is done, and tickets have been created!
