### ISSUE TITLE
Investigate why appeals at a judge are in the redistribution pool

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13596]
## Description
We get [`RedistributedCase::CannotRedistribute`](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7524/?referrer=webhooks_plugin) errors that [have no actionable resolution](https://github.com/department-of-veterans-affairs/caseflow/wiki/Bat-Team#redistributedcasecannotredistribute-sentry-alert) because they are already where they are supposed to be (at a judge). Cases that are at a judge should not be in the pool to redistribute.

## Acceptance criteria
- [ ] Investigate why legacy appeals with a location code of a judge are in the redistribution pool
- [ ] Implement fix (or file ticket if outside of timebox)
- [ ] Update ACD documentation with any knowledge gained in the investigation

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | ||||||||
5 | ||||
8 | 
```

There is logic checking for location code to add things to the distribution pool. That's a good place to start looking. 
What does our ACD documentation looks like? When are things ready for distribution? AMA? Legacy? Let's create that documentation as an end product of this investigation.

Estimating at a 3.
Could be a 5 because its an unfamiliar part of the code base for many of us. Time to get bearings. Past experience with ACD has shown it to be complicated.
