### ISSUE TITLE
Judge Assign page should display the tasks of the user_id provided in the URL

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13597]
## Description
In "SCM: SCM Team can view Judge's Assign Queue #12423", we introduced the start of "viewing the queue of another user". Before this, although the url provided another user's id, a judge's assign queue would show the task of the _signed in_ user. Now, the judge's css_id is provided to show that judge's tasks. This is redundant as the provided user_id should match the provided css_id. Before work on "Give judge assign queues human readable urls #13433" can be completed, we should only be relying on the provided user id to determine what user's tasks to show on the page

## Acceptance criteria
- [ ] /queue/189/assign shows the tasks for user 189, regardless of who is signed in.

## Extra
Related to #13237

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | |||||||||
5 | 
8 | 
```

Estimating at a 3.

Might be a 2 because all we're doing is merging the ids to be used in the same way. Need to return the user css_id as needed on the front end.
Might be a 3 to refactor our existing solution.
