### ISSUE TITLE
Duplicate task in attorney on hold tab after adding admin action

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13600]
## Description
After assigning an admin action on a legacy appeal, a duplicate task will appear in the attorney's on hold tab.

## To replicate
1. Sign in as an attorney and go to their queue
2. Note the number of "assigned" and "on hold" cases
3. Click into a legacy appeal
4. Add a single admin action
5. Note the number of assigned cases decreases by one but the number of on hold cases increases by 2
6. Click into the on hold tab
7. Note there are two tasks for the appeal
8. Reload the page
9. Note that the numbers are now correct and there is only one task for the case in the on hold tab

![ezgif-2-f91007d671b9](https://user-images.githubusercontent.com/45575454/76239528-1df3d180-6208-11ea-9427-6bc5170bbc6f.gif)

## Acceptance criteria
- [ ] After an attorney assigns an admin action, there is only one task in the attorney's on hold tab without having to reload the page

## Technical notes
This is most likely caused by updating the redux store of tasks with all of the ones returned from the task creation (including the user task that is created immediately after it's parent org task). We only show org colocated tasks for legacy appeals in an attorney's queue, not user tasks.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||
3 | ||||||||||
5 | 
8 | 
```

Estimating at a 3.
A three because front end redux store.
We have documentation for front end debugging. [One](https://github.com/department-of-veterans-affairs/caseflow/wiki/Debugging-Tips) and [two](https://github.com/department-of-veterans-affairs/caseflow/wiki/Queue-Frontend-Development)
