### ISSUE TITLE
Deal with sensitivity when processing claims establishments.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1360]
If a user doesn't have the sensitivity level to deal with a case, then it will stop them cold in their tracks.
(see: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/126/)

We should either:
- Enforce sensitivity. (This will be complex and may introduce a lot of edge cases)

OR 

- Use the Caseflow system account to send BGS requests. (this could be problematic from a security perspective, but if they already do this, then we may want to allow it)

**Comment by sthenning** [comment]
@Sjones352 @department-of-veterans-affairs/dsva-appeals-caseflow 

Is this the issue with Dispatch where users are receiving errors when they try to access the record?  If so users have been able to use VBMS to access the record which would indicate they DO have a sufficient sensitivity level.  Need to validate user sensitivity level against record level to validate where the issue lies.

**Comment by shanear** [comment]
this was resolved by https://github.com/department-of-veterans-affairs/caseflow/issues/1429

closing
