### ISSUE TITLE
Motion to Vacate | Fix success banner for "Created Motion to Vacate"

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13615]
## Description
When the Motion to Vacate Mail task is created, it shows a success banner at the top of the app.  This success banner also shows up in subsequent modals, for example if the user is performing a task action.  It should only show up at the top of the page.

## Acceptance criteria
- [ ] Success banner for "Created Motion to Vacate" does not show up in modals

## Screenshot of current behavior
![Screen Shot 2020-03-04 at 12.52.53 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/19994a05-2e4f-4723-b622-3ddedef4b549)

## Technical notes
- This appears to be the [result of updates](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/components/QueueFlowModal.jsx#L81) to `QueueFlowModal` made in #11794. This made `QueueFlowModal` display the same success message as on the main Case Details and Queue pages when set in the Redux store. 
- This intended behavior (as it regards modals) might be highly specific to certain workflows (as seen in #11794); it makes sense to ask Echo about the intended usage, unintended consequences, and the most appropriate way to meet our requirements without negatively impacting other functionality.

**Comment by jcq** [comment]
@hschallhorn, do you have some context to provide on this? 
- What were the thoughts/requirements that led to adding the alert to be displayed in `QueueFlowModal`?
- What would be the "correct" way per your understanding as to how to show a "success" alert on the Case Details page but not have it show up in any modals that use `QueueFlowModal`?
- Would it perhaps make sense to add another property to the Redux store that is specifically for showing alerts in those modals, and then dispatching an action for that *only* in the certain cases for which it was specifically required?

**Comment by hschallhorn** [comment]
My thoughts on this!
- Modals that stay open after the action is performed
  - On an error
    - Should show the error alert within the modal
    - Should not display the error on the queue page itself
  - On success
    - Should show the success alert within the modal
    - Should not display the alert on the queue page itself
- Modals that close after the action is performed
   - On an error
     - Should keep the modal open
     - Should show the error alert within the modal
     - Should not display the error on the queue page itself
  - On success
    - Should close the modal
    - Should show the success alert on the queue page
    - Should not display the alert on the queue page itself

Withe the way queue handles routing, we may be able to inspect the url to determine if the modal is still open (and opt to not show the alert on the page itself)

As for historical context on this, we added what I think is the first queue modal that stays open on success in #11794 and it was odd to see the success alert on the queue page and not the modal. The reviewer apparently did not do thorough testing or notice that the success alert was appearing on both the modal and the page.

**Comment by jcq** [comment]
@hschallhorn Do you happen to know if the modal in question from #11794 (`LookupParticipantIdModal`) is the only instance where it was intended / deemed necessary to have the success alert show within a `QueueFlowModal`? If so, I propose we change the logic so that we can display some sort of success message within _that particular modal_ instead of having `QueueFlowModal` show an alert whenever it is set in Redux.

Thoughts between these options?

1. Dispatch a different Redux action that controls modal-specific alerts, thus separating them from the success/error alerts that display on the main views
2. Remove the linkage to Redux `success` / `error` properties from `QueueFlowModal` and instead implement conditional display of an `Alert` of the correct type within `LookupParticipantIdModal` based on the results of the actions taken within it.

Assuming this is the only place that uses it, I would strongly favor option 2, as it makes the correct component responsible for its own actions/contents and helps to remove reliance on global Redux state for a localized need.

cc @leikkisa

**Comment by hschallhorn** [comment]
To my knowledge this is the only place this is used. 2 sounds like a good option!
