### ISSUE TITLE
Missing Ratings | Investigation | Production Cases | Non-Ratings Inclusion

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13711]
## Description
VBA anticipates 'non-ratings' are covered in the missing ratings work being completed. If non-ratings are not included the requirement 'Missing Ratings' is considered incomplete. They have provided examples of non-ratings for further investigation. 

- Claim ID: 77553656
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761195-63af1d80-6765-11ea-8208-2771df500576.png)

- Claim ID: 77553805
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761169-509c4d80-6765-11ea-919b-11a8f935ca40.png)

- Claim ID: 77584408
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761135-3e221400-6765-11ea-8773-8576f4408f90.png)

- Claim ID: 77586617
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761089-277bbd00-6765-11ea-8cde-3fc8d2badf3b.png)

- Claim ID: 77571132
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761043-10d56600-6765-11ea-8acb-180c4bd4bedc.png)

- Claim ID: 77556695
040 - PMC Supplemental Claim Rating
![image](https://user-images.githubusercontent.com/41164406/76761342-a4a73200-6765-11ea-975e-d1c01d1a3de3.png)

**Comment by leikkisa** [comment]
Adding a couple of notes:
Currently, we are not aware of a data source for prior decisions on non-rating issues. Martina is going to ask OI&T about where VBMS may be getting data like that.

For pension issues, it's particularly unclear to me the difference between rating and non-rating issues, but I want to add that previous pension denials are a category we're aware of missing rating data for, so it's possible that some of these may be due to missing rating data.

**Comment by msj0nes** [comment]
## Status

Meetings scheduled for 3/26/20 to discuss AMO needs as it related to non-ratings.

**Comment by msj0nes** [comment]
# Status
Closing this investigation ticket. Our team reviewed the production cases above to help improve understanding of non-ratings visible between VBMS and Caseflow.
