### ISSUE TITLE
Intake | VBA COVID-19 Update | Allow timeliness exemptions for legacy issue opt-ins

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#13817]
## User or job story
User story: As a VBA user (claims assistant, VSR), I need timeliness exemptions to also apply to legacy issue opt-ins.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [covid_timeliness_exemption]
- [ ] The following changes only apply to higher level reviews and supplemental claims
- [ ] The list of matchable legacy issues shown on the decision review does not check SOC eligibility, it only checks the NOD date eligibility
- [ ] For Higher Level Reviews - If either the request issue or the connected legacy issue is untimely, show the untimely issue modal (see tech notes #1).
- [ ] For Supplemental Claims - If the connected legacy issue is untimely, show the untimely issue modal (see tech notes #2)
- [ ] Update the modal copy to reflect whether the request issue and/or the legacy issue are ineligible
- [ ] Update styling on Untimely modal to increase space between the copy and the radio button to ~25px (see Rutvi's comment below)

## Out of scope
- Updating the actual rules for legacy issue timeliness on the backend
- Updating the ineligibility message on the front-end

### Current copy
The issue requested isn't usually eligible because its decision date is older than what is allowed.

### New copy
**If the request issue is untimely:**
Please note: The issue requested isn't usually eligible because its decision date is older than what is allowed.
(same as current copy but with "Please Note" added)

**If only the legacy issue is ineligible:**
Please Note: The legacy issue isn't eligible for SOC/SSOC opt-in unless an exemption has been requested for reasons related to COVID-19.

**If both are ineligible:**
Please note: The issue isn't usually eligible because its decision date is older than what is allowed, and the legacy issue issue isn't eligible for SOC/SSOC opt-in unless an exemption has been requested for reasons related to COVID-19.

### Current design with original copy
![Screen Shot 2020-04-01 at 11.29.20 AM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/8ca15bc8-b56c-4c18-8474-62aee4886f04)

## Release notes
Timeliness exemptions will also apply to legacy issue opt-ins for Higher Level Reviews and Supplemental Claims.

### Technical notes
1. Currently the untimely issue modal isn't concerned about legacy issue data, so you will need to add code to be able to access a legacy issue's eligibility status before the user submits adding the issue. The specific ineligibility reason we're looking for is: legacy_appeal_not_eligible.  Currently, eligibility is checked on the front end in the `AddedIssue` component in `getEligibility`, which shows on the edit screen after a user has submitted their issue.

2. Currently, the untimely issue modal does not appear in supplemental claims at all

**Comment by leikkisa** [comment]
@rutvigupta-design Do you have any suggestions or feedback for the copy on this modal?

**Comment by rutvigupta-design** [comment]
@leikkisa is there a reason for saying "isn't usually eligible"? _Usually_ to me is a little confusing because it makes it seem like there are other use cases but there is no further information about them. Would it be inaccurate to simply say "The issue requested isn't eligible because its decision date is older than what is allowed."

I think showing the legacy text up front is okay! It's better for users to see all the information up front in one place, and they may not notice text that is added above after they select the checkbox. 

Two recommendations: 
1. Adding a "Please note:" before the instruction text. I think visually, it helps give the user context and separates that text from the issue above it. 
2. Increasing the space between the instructions and the "Did the applicant request an extension" question by 25px - I think overall, this is minor but can help the modal feel a bit more open. Please see an attached design for what this can look like. 
![Untimely Issue Modal](https://user-images.githubusercontent.com/51714306/78259100-d50b0200-74c1-11ea-982a-21cda1a0f7d4.jpg)

**Comment by leikkisa** [comment]
@rutvigupta-design I added a couple of AC to add the "Please note:" and increase the spacing.
