### ISSUE TITLE
Queue: Task returned to attorney as a 'review' VLJ task

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#13823]
Issue happens when users bounce between VACOLS and Caseflow functionality to assign legacy cases.

Scenario:

- VLJ assigns legacy case to an attorney in VACOLS [Doesnt show in timeline]
- Attorney uses Caseflow to then assign the case to a co-located team
- Co-located team cancels the task for whatever reason. 
- Expectation is the case gets returned to the attorney in the correct 'attorney' format so they can submit work to judge.
- The case is returned to attorney as a 'review' VLJ task instead. 
- Case doesn't show with any active tasks when its returned (external user view only - the attorney does see an active task for review) 

Sample case: BVADSCHECHT
https://appeals.cf.ds.va.gov/queue/appeals/3319837

AC: 

- [ ] Investigate why the following occurs: 
- The case is returned to attorney as a 'review' VLJ task instead. 
- Case doesn't show with any active tasks when its returned (external user view only - the attorney does see an active task for review) 
- [ ] Fix what is causing issue

**Comment by nanotone** [comment]
Links to Bat-team threads:
https://dsva.slack.com/archives/C6E41RE92/p1585342752008100
https://dsva.slack.com/archives/CHX8FMP28/p1585344050063300

**Comment by hschallhorn** [comment]
Seems to be an issue with how we determine legacy task types. Could the affected users have been AVLJs in these scenarios?

_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||
3 | ||||||||
5 | |
8 | 
```
Why 2?
- Believe it could be due to AVLJ issues that Stephen may have fixed already

Why 3?
- Investigation ticket, something about unknowns
- not clear even for folks who have dug into the area

Why 5?
- Investigating and creating a good solution may longer than 3.
