### ISSUE TITLE
eFolder: NoMethodError for HealthChecksController#show

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#14068]
## Description

```
NoMethodErrorHealthChecksController#show 
undefined method `alive?' for nil:NilClass
```

in this part of the code:

https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/dd05324d52356ece8203ad8ff489deaa1c51bf07/app/controllers/concerns/collect_data_dog_metrics.rb#L17

## Acceptance criteria
- investigate
- determine root cause 
  - if not affecting performance, mute alert

## Background/context/resources

Sentry Alert: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/9341/events/91963cea6ce14257bb73baad1f32ced4/

## Technical notes

N/A

**Comment by rubaiyat22** [comment]
My initial suspicious was that the issue may be caused  by storing the [connections in a variable](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/dd05324d52356ece8203ad8ff489deaa1c51bf07/app/controllers/concerns/collect_data_dog_metrics.rb#L15) and then [iterating over them](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/dd05324d52356ece8203ad8ff489deaa1c51bf07/app/controllers/concerns/collect_data_dog_metrics.rb#L17) which could be caused by race-conditions.

[But `in_use?` method is actually aliased from the `owner` object](https://github.com/rails/rails/blob/72005ad0e13cb83d0e5ed7f9af7e0537efcf8963/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L44) so it's very suspicious that it becomes `nil` when we `c.owner.alive?`

I'll write a pr for a small change that might fix this
