### ISSUE TITLE
Virtual not displaying in Type column of Hearing Schedule

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#14101]
#### Observed
The Type value for docket days before 4/24 on the Hearing Schedule page doesn't display Virtual, even when the dockets do in fact contain virtual hearings.

#### Steps to reproduce
1. Go to [Hearing Schedule ](https://appeals.cf.ds.va.gov/hearings/schedule)
1. Change "From" date in filter to 03/27/2020 (the first day virtual hearings were scheduled in Caseflow)
1. See that the Type of all docket days until 4/24 doesn't include Virtual
<img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/eb5689cb-c779-41d0-a31d-a3d3e96542af" border=1>
1. Open a docket day (like [3/27 Ft Harrison](https://appeals.cf.ds.va.gov/hearings/schedule/docket/4776) or [4/17 Atlanta](https://appeals.cf.ds.va.gov/hearings/schedule/docket/4954)) and see that the docket contains virtual hearings
<img src="https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/197fedc3-f555-4c2c-8ed9-cedd28839e5a" border=1>

#### Expected
Virtual displays in the Type column, and is a filterable value, for all docket days that contain virtual hearings.

**Comment by sahalliburton** [comment]
This appears to be due to the change made when cancelling a virtual hearing completed [here](https://github.com/department-of-veterans-affairs/caseflow/pull/14003). This ticket removes the status column and adds a request_cancelled column to calculate the status along with the pexip job. 

This works great for new virtual hearings as the coordinator will manually make the change when cancelling, however for existing virtual hearings, the status is no longer being calculated correctly as the status field is missing and the request_cancelled field has not been set.

The historical hearings (prior to 4/24/2020) will need to be updated with the request_cancelled as true for any hearings that previously had their status set to cancelled.

**Comment by ferristseng** [comment]
I think this is the offending line in the query:

https://github.com/department-of-veterans-affairs/caseflow/blob/632a0d36c03b60fe5bc27e77eb55ac1cdfc7c1b0/app/queries/video_hearing_day_request_type_query.rb#L52

It looks like this may have been a bug for awhile, and was not introduced in #14003. I believe I had checked to see if there were any cancelled requests in the database prior to #14003 being merged, and I didn't see any
