### ISSUE TITLE
Unexpected error response from saving hearing causes TypeError

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14187]
## Description
Via a recent uptick in occurrences of this [Sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/9992/):

Sometimes `POST /hearings/<ID>` returns http 422 (or occasionally 500) with an unexpected response body that doesn't contain an `alerts` property. This causes a line in DailyDocketRow's saveHearing() response handler

```
if (alerts.hearing) {
```
to throw the TypeError `Cannot read property 'hearing' of undefined`.

Although I can't see the request body, from perusing AWS logs it does seem that the user often retries and eventually succeeds (http 200), suggesting a transient root cause. However, it might still be worth doing a quick audit of DailyDocketRow's possible request payloads, to check that buggy behavior isn't being initiated earlier in the flow.

## Notes
- In the past when looking at logs, it looks like someone is leaving their browser open and coming back to it later and attempting to perform an action.
  - CSRF token expiring - if Rails does this automatically, which it might not, why isn't Rails performing redirect?
- [previous Slack discussion](https://dsva.slack.com/archives/CHX8FMP28/p1580835101178000)

**Comment by rubaiyat22** [comment]
I've confirmed that this is indeed caused by csrf token being expired. For example, you can see here the user tries to update hearing [here](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-0da9a7ba8df8ee3e2;refid=35455646394138487254662268629364907890549548132932714768;reftime=1589886171000) but can't because they get an error and about a minute later the user reloads the page (as directed by the [error message](https://github.com/department-of-veterans-affairs/caseflow/blob/65a9806a7cfa41521ea415ab0db524dc55736381/client/app/hearings/components/dailyDocket/DailyDocket.jsx#L49) and they try to do [update with the same parameters](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-023368bf7dd002ad6;refid=35455648579611516710663336619496860316590877694913741193;reftime=1589886269000) but succeed this time. I think especially since the daily docket page can be very slow at times users tend to leave it open so we get a mismatch of token in the page and token in the session cookie. 

That said, I don't think we want to skip this CSRF token check for security reasons. For now, i'll mute this error and ensure that frontend doesn't break when this error is thrown.

But there are few options we can consider going forward to treat the root problem such as redirecting to login (this would affect the entire application not just hearings) or reloading the page when the csrf token expires.

#### Investition notes
- Cookie session was set to expire after 12 hours instead of 24 in this [PR] (https://github.com/department-of-veterans-affairs/caseflow/pull/13758)
- good read on rails and csrf https://medium.com/rubyinside/a-deep-dive-into-csrf-protection-in-rails-19fa0a42c0ef

**Comment by tomas-nava** [comment]
Closing because @rubaiyat22's PRs address the critical aspects of the issue. We will work on speeding up the daily docket page so that people don't feel the need to leave it open for long periods of time without reloading.
