### ISSUE TITLE
Investigation: Discover any AMA appeal states that won't move forward automatically

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14307]
## Description
We recently had two appeals reported in an unexpected state where their Distribution Tasks were cancelled, but they had other trees open. We believe these were affected by a bug we corrected last year.

The goal of this ticket is to look into the state of current AMA appeals and discover any potential orphan path in our codebase currently, and if any are found.

## Acceptance criteria
- [ ]  Any extant Appeals in a bad state are either fixed, or grouped into new issues to be fixed immediately following on this.
 - [ ] Any issues discovered in our current task code flow have issues filed to address them

## Background/context/resources
 - [Recently discovered appeals in an unexpected state](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/119)
 - [Older bugfix for incorrect task cancellation cascading](https://github.com/department-of-veterans-affairs/caseflow/pull/10831)
 - [Possibly relevent Delta alert](https://github.com/department-of-veterans-affairs/caseflow/issues/14255)

**Comment by hschallhorn** [comment]
is this a delta ticket?

**Comment by yoomlam** [comment]
Timebox to 3.
Difference from StuckAppealsCheckerJob or OpenTasksWithClosedParentsCheckerJob?
How did appeals get here? What's their status? Where should they go?
May be relevant to RAMP appeals only, but should check if AMA appeals face similar problems.

**Comment by pkarman** [comment]
One pattern is that we have appeals with closed root tasks but open child tasks.

See https://dsva.slack.com/archives/CJL810329/p1590527026173900 and `AppealsWithClosedRootTaskOpenChildrenQuery`.

Appeals with open child tasks should have open root tasks.

**Comment by yoomlam** [comment]
### Related tickets
Some stuck-appeal scenarios are still being addressed/fixed: 
* Clean up open tasks with closed parents #13438
   * clean up open hearing tasks with closed parents on legacy appeals #14703
   * diagnose open HearingTasks on closed appeals #14748
   * Ensure original tasks are cancelled during bulk reassignment #14600

### Related jobs
These jobs send alerts to #appeals-job-alerts.

* Job `StuckAppealsChecker` performs the following queries:
   - `AppealsWithNoTasksOrAllTasksOnHoldQuery` finds:
      - active appeals with open (`assigned`, `in_progress`, `on_hold`) tasks that are all `on_hold`
      - active appeals with 0 or 1 task
      - active appeals with 2 tasks and no DistributionTask
      - dispatched appeals (`completed` BvaDispatchTask) with `on_hold` RootTask
   - `AppealsWithClosedRootTaskOpenChildrenQuery`: appeals with `closed` RootTask and `open` children tasks, ignoring tasks without parents
* Job `PendingIncompleteAndUncancelledTaskTimersChecker` finds pending and incomplete TaskTimers.
* Other jobs reviewed but do not indicate a stuck appeal (that Echo needs to address):
   - `OpenTasksWithClosedAtChecker`: task is `open` but `closed_at` is set or parent is `closed`
   - `StuckVirtualHearingsChecker`: if stuck for too long, then Tango is notified for manual intervention

### Related Sentry alerts
* `RedistributedCase::CannotRedistribute`: appeal can't be redistributed because
   - there are open tasks (excluding TrackVeteranTask and RootTask)
   - if appeal has already been distributed (in some cases, a legacy appeal should be redistributed -- see #14705
* [TypeError: app/establishClaim/util/index](https://dsva.slack.com/archives/CAP9C43E2/p1597320651000500) - 
   - due to [Legacy Appeal missing a veteran](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#legacy-appeal-missing-a-veteran) 
      - due to "a claimant (such as the veteran's spouse or child)'s ID is listed [in VACOLS case record] instead, which causes problems when searching for the veteran".
* [VACOLS::Case::InvalidLocationError](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#vacolscaseinvalidlocationerror-mixed-up-css_ids) 
   - "occurs when Caseflow cannot find the user-selected assignee in VACOLS due to a mix-up in CSS_IDs"
   - occurs rarely but will stall appeal processing.

**Comment by yoomlam** [comment]
### "Bad states"
"bad state" = "stuck" appeal that will not proceed without engineer intervention

#### Appeals
* with insufficient tasks
* with open tasks that are all `on_hold`
* with unexpected task tree structure
  * dispatched appeals with open tasks (i.e., RootTask)
  * `closed` RootTask with `open` children tasks
  * TODO: Job to check for `closed` parent with `open` children tasks. AKA: `open` child task should have `open` parents and ancestors. (Not sure if this could cause a stuck appeal, but it's a good data integrity check.) (Related data clean-up ticket #13438)
  * TODO: Detect other odd task trees
* with no updates in N days
  * TODO: What's a good value for N? Create statistics for length of time since last update (using the latest task `updated_at` or appeal `updated_at`) for active appeals.

#### Tasks
* with pending and incomplete TaskTimers
* assigned to inactive or incorrect users
  * manually fix [VACOLS::Case::InvalidLocationError](https://github.com/department-of-veterans-affairs/appeals-deployment/wiki/Bat-Team-Quick-Ref#vacolscaseinvalidlocationerror-mixed-up-css_ids)
* TODO: For org-tasks (those assigned to orgs) with a `def self.default_assignee`, get stats on tasks that aren't assigned to the `default_assignee`.

### "Good states"
* Task is assigned to an active user and assignee has actions to perform on task
  * TODO: Create job or validation to check that an assignee (excluding BVA org and probably others) is active and has actions to perform on their task -- `Task#available_actions(user).count > 0`. Has this ever been a problem?
  * TODO: Check that assigned user is part of the proper team that can complete the task:
    ```ruby
    LitigationSupport.singleton.users.include?(user)
    ```
  * Note: DistributionTask is not assigned to a user: SCM user could assign to any user
* tasks assigned to orgs with active admins should progress
  * TODO: Check that all relevant orgs have an _active_ admin
  * Some orgs don't have admins; members can assign tasks; e.g. VSOs
* As long as a blocking task is assigned to an active user (or org?), the appeal should progress.

## TODO: Analyze code
* verify in code when a child user-task completes, that the parent-task completes or is assigned (becomes active again)
* investigate what happens when each task type is cancelled or closed
  * enumerating all task types that trigger another task's status change
* Based on [MailTasks in prod](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md#mailtasks), 3 MailTasks (i.e., AppealWithdrawalMailTask, PrivacyActRequestMailTask, ClearAndUnmistakeableErrorMailTask) are assigned to orgs only - Why do they not have child user tasks? What task actions are available and do they make sense?

**Comment by yoomlam** [comment]
Whew!
