### ISSUE TITLE
Contested Claims | Attorney Fees | Update intake review endpoint

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/caseflow#14505]
## Description
Update implementation of `IntakesController#review` and related code to support intaking attorney claimants

## Acceptance criteria
- [ ] Intaking a known AttorneyClaimant (with participant_id) is supported, saving the participant ID and type of "AttorneyClaimant"
- [ ] Intaking an attorney OtherClaimant (with additional notes) is supported, and type of "OtherClaimant"
- [ ] Update controller schema for `IntakesController#review`

## Background/context/resources
With Claimant single-table inheritance fully supported at the storage layer, the intake controller's `#review` endpoint could use an update that more clearly distinguishes between the various claimant types. In addition, a new parameter for additional notes, in case the attorney was not found in the database, needs to be supported.

## Technical notes
Because the review endpoint has an associated controller schema, refer to this [wiki page](https://github.com/department-of-veterans-affairs/caseflow/wiki/Controller-Schemas) for guidance on updating the schema to support additional notes.

This pr https://github.com/department-of-veterans-affairs/caseflow/pull/14565 saves notes to the database therefore `Intaking an attorney OtherClaimant (with additional notes) is supported` is not applicable.

**Comment by jcq** [comment]
Questions:
- Do we want to implement storing the claimant type for things other than `Appeal` objects? The requirements would seem that we don't want to support `AttorneyClaimant` for anything other than appeals, but should we set `VeteranClaimant` / `DependentClaimant` for the SC/HLRs?
- If the user selects "Attorney" (currently only option) but checks the "not listed" box, does it make sense to have logic on the frontend switch to specifying "other" as the claimant type? (I'm mainly making sure I've got the flow correct, less so the choice of logic on the frontend vs the backend for that.)
- If type is "other", then we want to require there to be something in the notes, correct? While I think we already have logic on the frontend to force that, I want to make sure the schema enforces/documents as well.

**Comment by jcq** [comment]
Additional questions:

By default, the start_appeal method in IntakeHelpers creates a VeteranClaimant that is associated with the decision_review and obviously has the vet's participant_id

Currently, if we use that to start, then run through the review process and select another claimant, it will try to alter the existing claimant record, which might cause the type to change (something which causes problems with validation, etc in single-table inheritance)

As a result, my current plan is to change the lookup in Claimant.find_or_initialize_by to also utilize type, and destroy any prior associated claimant for that appeal that has a different type. Any objections to that?

---

Additionally, we currently get failures with saving `OtherClaimant` records due to the `participant_id` field being required in the DB schema. Was there a reason to keep that constraint, or was it just an oversight and we should go ahead and alter that?

**Comment by nanotone** [comment]
I need to familiarize myself with how the `start_appeal` helper is being used by tests, but it seems to me that if it's creating the appeal, intake, _and_ claimant all in one go, then the tests that use this method aren't really testing the claimant selection UI. Because at that point in time, the claimant record doesn't exist yet (hopefully I'm not completely wrong about all this?)

I'm inclined to say that `start_appeal`, if you're planning to use it, should just be updated to allow creating an attorney fee appeal. Again, my understanding is that we're never attempting to create a claimant for an appeal that already has a claimant.

**Comment by nanotone** [comment]
I think the most straightforward approach to the `participant_id` field is to fill it in with veteran participant IDs. This is the most common approach that's being used currently. And despite being "wrong", to me it feels like the preferred incremental change given that downstream data consumers might not be prepared for NULLs.
