### ISSUE TITLE
$ is undefined 

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1460]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/132/

Occurs in IE 11

`/certifications/new/2744290`

**Comment by askldjd** [comment]
This error is likely caused by prod deployment. I was able to trace back the last set of errors lining up with the ASG rolling deploy stage.

It is likely because we don't support client side hot compatibility. The JS is likely not loading correctly (because of hashed name), and jquery happens to be the victim of this issue.

![image](https://cloud.githubusercontent.com/assets/3258724/25629079/578da766-2f36-11e7-8997-5e5e468d8ccb.png)

**Comment by askldjd** [comment]
I think we might be able to resolve this by serving the previous version of assets. This way, the user will gracefully transition to the new version during the deployment.

Plan of attack, during deployment bake process, do the following:

1. After assets are compiled, save a copy in S3 under a version tag.
1. Query the prod EC2s to determine the current asset version tag.
1. Get the assets from S3 using the version returned from the previous step.
1. Merge the current assets with the previous version of assets. 
   - If file exists in both folder, use the latest one.
