### ISSUE TITLE
Understand any Caseflow constraints for creating new hearing day without a room associated

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#14614]
## Description
Investigate and understand if Caseflow adds constraints around building new (single) hearing days. Hearing Coordinator admins have the ability to add one-off hearing days, however, they have reported that they cannot add a new day and assign a new VLJ because:
- VLJs cannot be assigned to a docket unless a room is added
- All rooms are taken and a room cannot be double-booked
- Veterans cannot be added to rooms

Caseflow might need to 1) allow hearing day to be assigned a VLJ even if a room is not assigned, or 2) allow rooms to be double-booked. 

## Acceptance criteria
- [x] Document any constraints
- [ ] TBD: Write a new ticket to remove constraints

## Background/context/resources
As a Hearing Coordinator admin with schedule building capabilities, I need to be able to create an additional hearing day without a hearing room assignment, so that additional VLJs (outside the normal schedule) assigned to virtual and/or AMA-only cases can hold hearings.

After 3 months of postponements through the pandemic, the Board would like to boost hearing capacity by scheduling more virtual hearings to alleviate built up hearing inventory. Because AMA cases can be heard and decided by different VLJs (vs. Legacy which must be heard and decided by the same VLJ), building AMA-only dockets will allow the Board to start alleviating the inventory.

## Considerations
- Our end goal will be to have constraints for video/Central dockets to be associated with hearing rooms when we introduce fully virtual dockets.

**Comment by ferristseng** [comment]
### Constraints in Caseflow

I went through to confirm whether or not these constraints were enforced by Caseflow, and noticed that most of these things are possible, but not supported well in the UI. I noted some things in the UI that might be confusing in the 2nd section, but we might want to talk to some hearing coordinators to get further details about the limitations they are running into.

| Constraint | Verified | Comment |
| --- | --- | --- |
| VLJs cannot be assigned to a docket unless a room is added | ❌ | I was able to assign a VLJ to a day without a room both when I was adding the new day, and editing it <img width="625" alt="Screen Shot 2020-07-08 at 11 48 11 AM" src="https://user-images.githubusercontent.com/1298274/86948734-96699100-c11b-11ea-88d5-1861fa920160.png"> |
|All rooms are taken and a room cannot be double-booked | 🧐 | When you're adding a new hearing day, you don't have the option to double-book a room (create an identical hearing day), but you are able to edit an existing hearing day and assign it to the same room as another hearing day. This is a workaround, but it's not disallowed by any existing constraints in Caseflow  <img width="625" alt="Screen Shot 2020-07-08 at 12 00 34 PM" src="https://user-images.githubusercontent.com/1298274/86942055-b21c6980-c112-11ea-8550-67b1bc25d588.png">|
| Veterans cannot be added to rooms | 🧐 | I think the UI is confusing around if there are multiple rooms on the same day, but from what I could tell, Caseflow does not enforce any constraint that would prevent a veteran to be added to a room |

### Issues in Caseflow

I noted some issues that make working with multiple dockets on the same day very confusing:

| Issue | Screenshot |
| --- | --- |
| When scheduling a veteran, there is no way to distinguish multiple dockets on the same day from one another. This makes it difficult to select the intended hearing day. We could supply the room or VLJ here to clarify the HC's selection | <img width="508" alt="Screen Shot 2020-07-08 at 11 40 14 AM" src="https://user-images.githubusercontent.com/1298274/86939863-17229000-c110-11ea-8475-b9c1ff24c473.png"> |
| On the schedule veteran's screen, selecting a duplicate/double-booked docket highlights multiple entries on the sidebar. The room displays as `null`, and there is no way to distinguish multiple dockets on the same day from each other. | <img width="1220" alt="Screen Shot 2020-07-08 at 11 41 12 AM" src="https://user-images.githubusercontent.com/1298274/86939865-17bb2680-c110-11ea-8472-2aa2b7533edd.png"> |

### Comments

> Caseflow might need to 1) allow hearing day to be assigned a VLJ even if a room is not assigned, or 2) allow rooms to be double-booked.

I think both of these are currently enabled by Caseflow. For 2, there is a work-around to double-book rooms, but we should probably support it directly in the add hearing day modal (right now the room is automatically selected or can be left blank, but there is no way to select a room directly unless you go to the edit screen).

> As a Hearing Coordinator admin with schedule building capabilities, I need to be able to create an additional hearing day without a hearing room assignment, so that additional VLJs (outside the normal schedule) assigned to virtual and/or AMA-only cases can hold hearings.

Were the HC's thinking of leveraging the notes field to indicate that a docket should be virtual/AMA-only (since we don't have any way of marking that in Caseflow right now)? We would need to modify some of the UI to display those notes so they have that information while selecting a hearing date and time.

**Comment by ferristseng** [comment]
Closing in favor of the issues that came out of this

**Comment by chandracarney** [comment]
Issues created from this work: #14671, #14673, #14674
