### ISSUE TITLE
ActiveRecord::StaleObjectError on assignment race condition

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#1466]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/143/
app/models/task.rb in assign_user at line 129
ActiveRecord::StaleObjectError: Attempted to update a stale object: EstablishClaim

**Comment by shanear** [comment]
This is an okay exception. It's basically catching a race condition where two people tried to pick up a new task at the same time.

Maybe we should rescue the exception and try again?

**Comment by joofsh** [comment]
I was just looking at this this morning and trying to decide a course of action.

I don't personally feel 100% confident that this is a race condition with two people trying to assign the same task. It determines the "next task" _after_ you click the button (all server side). The odds of a two people clicking to assign in the same 100ms span on a small team like ARC dispatch seems highly unlikely to me.  

Since there is only 1 event in Sentry, I vote to leave this be until we see more events & can use the additional information to move forward.

**Comment by shanear** [comment]
Agreed. Moved to backlog

**Comment by joofsh** [comment]
5 events exist in sentry for this error. Too many to be a race condition. Someone should investigate this further

**Comment by shanear** [comment]
This is a dup of #1559 

closing.
