### ISSUE TITLE
Investigation: VACOLS POA being used for virtual emails and appeal routing

### ISSUE THREAD

**Issue by nicholer** [department-of-veterans-affairs/caseflow#14753]
## Description
A Hearing Coordinator reported:

1. "I had a virtual hearing with a private attorney this week, and ... Caseflow and VBMS showed an attorney. I sent the link, and when the attorney opened the email, it said 'Dear American Legion' - and that happened several times with that one agent."
    1. Link to **Hearing Details** for one of the virtual hearings (From Coordinator: "In most cases I hope I have corrected the VACOLS record"): https://appeals.cf.ds.va.gov/hearings/730059/details  
    1. Link to **Hearing Details** for another virtual hearing (From Coordinator: Have not yet changed the information in VACOLS to reflect the new attorney): https://appeals.cf.ds.va.gov/queue/appeals/3187794
1. "There was a POA that was a private attorney in VBMS and Caseflow; but VACOLS still showed American Legion, and they [the appeal] were sent to 55. And it should have gone to 81."

## Acceptance criteria
- [ ] Investigate the first issue reported above by looking at the content of emails sent for the linked hearing. Is the POA name in the email different from the POA in Caseflow / VBMS? 

## Technical notes

**Comment by ferristseng** [comment]
> Link to Hearing Details for one of the virtual hearings (From Coordinator: "In most cases I hope I have corrected the VACOLS record"): https://appeals.cf.ds.va.gov/hearings/730059/details

VACOLS has a service org, and VBMS has an attorney

> Link to Hearing Details for another virtual hearing (From Coordinator: Have not yet changed the information in VACOLS to reflect the new attorney): https://appeals.cf.ds.va.gov/queue/appeals/3187794

VACOLS has an attorney, and VBMS has a different attorney

**Comment by ferristseng** [comment]
I suspect this is an issue where the job is running with an "application name" that is causing this block of code to return the VACOLS representative instead of the VBMS representative:

https://github.com/department-of-veterans-affairs/caseflow/blob/3b84e37c330d05b4aaab5d5f387d8f762345254c/app/models/legacy_appeal_representative.rb#L21-L35

The source of truth is determined by the "application_name":

https://github.com/department-of-veterans-affairs/caseflow/blob/3b84e37c330d05b4aaab5d5f387d8f762345254c/app/models/legacy_appeal_representative.rb#L51-L55

which for jobs is always suffixed with `_job`:

https://github.com/department-of-veterans-affairs/caseflow/blob/3b84e37c330d05b4aaab5d5f387d8f762345254c/app/jobs/application_job.rb#L47-L54
