### ISSUE TITLE
Disable VLJ Support Auto Task Assignment

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14952]
## User or job story
User story: As a VLJ Support admin, I need all tasks to be routed to the organization as unassigned, so that I can manually assign the tasks to the appropriate team members as some team members are more experienced then others and should be assigned certain tasks. 

## Acceptance criteria
- [ ] VLJ Support tasks are no longer auto-assigned to VLJ Support organization members
- [ ] New tasks are routed to the organization unassigned queue for manual assignment by the organization admins
- [ ] Current assigned tasks are unassigned and moved to the unassigned queue
- [ ] All tasks currently on hold remain with the employee who is working the task

## Release notes
VLJ Support tasks are no longer auto-distributed to VLJ Support organization members. 

### Background/context
VLJ Support would like to begin using the bulk assignment feature to assign tasks to their team members. They are unable to do so at this time as their teams tasks are being auto-assigned.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||
5 | |||||
8 | 
```

Many tests rely on this auto creation of child tasks assigned to a colocated team member
Could update this to be done in a factory instead of removing code.
Look for any place we add someone to the colocated team in tests (this enables tasks to be auto assigned to users in testing)
Other tests may be defensive where we won't require it anymore (i.e. making sure colocated team exists)

Delete the ColocatedTaskDistributor :dagger_knife: 

#### Why 2?
* A clean factory update could make quick work of tests

#### Why 3?
* Handful of lines removed
* Should be pretty _straightforward_ to clean up the tests

#### Why 5?
* Oh my lord. The tests.
* :all-the-tests:!
