### ISSUE TITLE
Capture Stats on Legacy IHP Tasks

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15003]
## Description
Capture stats on tasks created for IHP tasks to include:

Task creation date
Task creation method (~automated via Caseflow or~ an admin action created by VLJ/Attorney)
Task instructions
Task placed on hold date
Number of days placed on hold
Task on hold end date
Task completion date

## Acceptance criteria
- [ ] Report with above information added to Metabase
- [ ] Can determine average number of days it takes to complete an IHP task for Legacy Cases

## Background/context/resources
Looking for baseline information on the average time it currently takes to complete IHP tasks on legacy cases. We will want to distinguish if the task was created by Caseflow or if it was initiated via a VLJ/Attorney. My assumption is the automated tasks are completed faster then manual task creation, but would like to gather evidence of that.

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | |
5 | 
8 | 
```

Only ihp tasks created for legacy appeals will be from admin actions, none created automatically
What do we mean by "instructions"? What would we like to see in metabase relating to instructions
Would like all information to be in a table with a column for each thing stipulated
Can ask for graphs showing changes over time in later tickets

We think all the information we need to gather here is to be pulled from Caseflow

#### Why 2?
* Should be a straightforward query, bumped from a 1 because _maybe_ VACOLS?

**Comment by hschallhorn** [comment]
Pair with @mkerns355 !

**Comment by lomky** [comment]
[Metabase dashboard](http://query.prod.appeals.va.gov/dashboard/11)

Added to a new dashboard with two versions, one with potential PII (instructions), one without.

**Comment by lomky** [comment]
Some clarifications from [discussion in Slack](https://dsva.slack.com/archives/CJL810329/p1599575253430300)

 - Only `closed` IHP tasks will be considered
 - Old style holds are not accounted for in this data, as we have no way to reconstruct that information accurately
 - 'Task placed on hold date' is the earliest `created_at` date of a child TimedHoldTask
 - 'Task on hold end date' is the latest `closed_at` date of a child TimedHoldTask
 - 'Number of days placed on hold' is the difference between the above two, _not_ to sum of all TimedHoldTasks created->closed. In other words, time between 'on hold' is assumed to also be on hold _in this particular use case_

**Comment by lomky** [comment]
I _believe_ this is complete - but final call is up to @araposo-tistatech! Feel free to close this and check it off on the sprint if so, but if not back into the team queue!

**Comment by araposo-tistatech** [comment]
This looks good! Closing.

**Comment by hschallhorn** [comment]
```sql
INNER JOIN tasks AS on_hold_tasks ON on_hold_tasks.parent_id = ihp_tasks.id
  WHERE on_hold_tasks.type = 'TimedHoldTask'
```

Don't think all of these tasks are put on hold. Think we may be filtering out some of our ihp tasks in this query

```ruby
IhpColocatedTask.completed.last.appeal.treee
                               ┌───────────────────────────────────────────────────────────────────────────┐
LegacyAppeal 1287154 (legacy)  │ ID      │ STATUS    │ ASGN_BY    │ ASGN_TO      │ UPDATED_AT              │
├── RootTask                   │ 1112709 │ assigned  │            │ Bva          │ 2020-08-25 19:54:26 UTC │
├── IhpColocatedTask           │ 1148333 │ completed │ VACODEBRUD │ Colocated    │ 2020-09-16 17:11:18 UTC │
│   └── IhpColocatedTask       │ 1148334 │ completed │ VACODEBRUD │ BVALLEWIS    │ 2020-09-16 17:11:18 UTC │
└── IhpColocatedTask           │ 1151889 │ on_hold   │ VACODEBRUD │ Colocated    │ 2020-09-16 19:25:19 UTC │
    └── IhpColocatedTask       │ 1151890 │ assigned  │ VACODEBRUD │ BVAANJOHNSON │ 2020-09-16 19:25:19 UTC │
                               └───────────────────────────────────────────────────────────────────────────┘
```

**Comment by yoomlam** [comment]
@araposo-tistatech says
* include IHP tasks that are not explicitly put on hold
* If there are multiple completed IHP tasks for an appeal, just pick the latest one

Given this statement above:
> Only ihp tasks created for legacy appeals will be from admin actions, none created automatically

If there is only 1 creation method for legacy appeals, is there a value to getting stats for legacy appeals to achieve this objective:
> We will want to distinguish if the task was created by Caseflow or if it was initiated via a VLJ/Attorney.

**Comment by araposo-tistatech** [comment]
@yoomlam you are correct for legacy appeals since we are not automating the IHP tasks for legacy appeals then the stats will not add value to that objective, but I do think it will provide us with baseline information on how long IHP tasks for legacy cases are taking to complete. I also think we can use that data and compare it with the AMA data (that is automated) and see what our differences are.

**Comment by yoomlam** [comment]
New [Metabase query](https://query.prod.appeals.va.gov/question/96) that also address AMA IHP tasks #14997.
You can download and explore it since it currently has no PII.
Once you're satisfied with it, I'll include the `instructions` columns, which may have PII.

Here's my understanding of the tasks:
* "IHP task" refers to `InformalHearingPresentationTask` or `IhpColocatedTask`
* `InformalHearingPresentationTask`s are created when IHP tasks is automatically created by Caseflow (and assigned to a specific VSO), while `IhpColocatedTask`s are created (and assigned to the `Colocated` team) when manually created by a user. See the `orgTask_CreationType` to distinguish the two.
* `InformalHearingPresentationTask` assigned to a user always has a parent `InformalHearingPresentationTask` assigned to an organization
   ```ruby
   InformalHearingPresentationTask.where(assigned_to_type: :User).map{|t| t.parent.type}.uniq
   => ["InformalHearingPresentationTask"]
   ```
* `IhpColocatedTask` assigned to a user always has a parent `IhpColocatedTask` assigned to an organization
   ```ruby
   IhpColocatedTask.where(assigned_to_type: :User).map{|t| t.parent.type}.uniq
   => ["IhpColocatedTask"]
   ```
* In the column names below, here are my definitions:
  * `orgTask` refers to a task assigned to an organization
  * `userTask` refers to a task assigned to a user; a `userTask` may optionally have `TimedHoldTask` as children tasks
  * `duration` refers to the time a task was open (`closed_at` - `created_at`)
  * `work_duration` refers to task `duration` minus total hold time

Column definitions (bolded columns are related to the original objective):
- orgTask_id: task id of orgTask (IHP task assigned to an organization)
- **orgTask_CreationType**: distinguishes automatic creation by Caseflow (`InformalHearingPresentationTask`) vs manual creation by a user (`IhpColocatedTask`)
- 
- appeal_id: appeal ID for record in DB
- appeal_type: Appeal(AMA) or LegacyAppeal
- orgTask_parent_id: task id of the orgTask's parent task
- org_ihp_child_num: refers to the Nth child of the orgTask's parent task
- 
- orgTask_status: status of orgTask
- orgTask_created_at: creation date of orgTask 
- orgTask_closed_at: close date of orgTask
- 
- userTask_status: status of userTask
- userTask_created_at: creation date of userTask 
- userTask_closed_at: close date of userTask 
-
- orgIhpTask_duration: duration of orgTask
- userIhpTask_duration: duration of userTask 
- dur_diff: `orgIhpTask_duration` - `userIhpTask_duration`
- holdtask_children_dur: total time spent on hold
- holdtask_children_count: total number of `TimedHoldTask` children under the userTask
- **orgTask_work_duration**: `work_duration` of orgTask, i.e., `orgIhpTask_duration` - `holdtask_children_dur`
- **userTask_work_duration**: `work_duration` of userTask, i.e., `userIhpTask_duration` - `holdtask_children_dur`

**Comment by yoomlam** [comment]
Out of curiosity: What are the parent task types of these IHP tasks?
```ruby
IhpColocatedTask.completed.where(assigned_to_type: "Organization", appeal_type: "Appeal").map(&:parent).group_by(&:type).keys
=> ["AttorneyTask", "JudgeDecisionReviewTask", "AttorneyRewriteTask", "JudgeAssignTask", "JudgeQualityReviewTask", "AttorneyQualityReviewTask"]

InformalHearingPresentationTask.completed.where(assigned_to_type: "Organization", appeal_type: "Appeal").map(&:parent).group_by(&:type).keys
=> ["DistributionTask", "RootTask"]
```
