### ISSUE TITLE
Caseworker Landing | No more assigned, claims in queue

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1501]
**Story**

As a caseworker, I want to know if I have completed all the claims assigned to me and still have the option to establish more claims. 

## Description
This is a case where x assigned, y completed numbers are the same and there are still more claims to be established in the queue. At this point, a caseworker can stop or continue establishing more claims. 

## Acceptance Criteria
- Verify that the congratulations copy above the work history matches the copy in the bottom 
- Verify that the assigned number matches the completed number.
- Verify that the `Establish next claim` button is enabled and in USWDS Primary
- Verify that there is a gray horizontal line dividing Congratulations messages and Work History section
- Verify that Congratulations! is in h1 and USWDS green. 
- Verify that `You have completed all the cases assigned to you.` is in hex#5B616B
- Verify that Congratulations!, You have completed all the cases assigned to you., assigned, completed cases, and work history are left-aligned.
- Verify that spacing in Congratulation section matches specs in 2nd mockup.

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/25053904/3e749dc8-2128-11e7-9c80-3989afdb7b23.png)

## Copy
Way to go!

You have completed all the claims assigned to you. Feel free to pick up another claim. 

## Related
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/129
#1562
#1564

**Comment by gnakm** [comment]
@lakohl I split up the issues in this repo. Can you review these?

**Comment by lakohl** [comment]
@gnakm @avrildavid lets keep the messaging consistent with #1562 (except for the No more claims left part)

**Comment by avrildavid** [comment]
@lakohl, outlining the copy for all three scenarios below:

- Scenario 1: All assigned claims completed. Still claims left in the queue.
**Way to go!** 
**Description:** You have completed all the claims assigned to you.  Feel free to pick up an another claim. _(suggesting this text because one user asked if he could continue working claims, so might be good to provide this direction)_
- Scenario 2: All assigned claims completed. No claims left in the queue.
**Way to go!** 
**Description:** You have completed all the claims assigned to you. There are no more claims to pick up.
- Scenario 3: No claims left to pick up in the queue.
(_Suggestion_) **All Claims Completed** 
**Description:** There are no more claims to pick up. Please come back later.

**Comment by gnakm** [comment]
@lakohl @avrildavid 
Mocks and copy are updated! 
Added Emojis
> the ARC team seemed to like the emojis as a way to indicate that they finished their daily assigned cases.

**Comment by lakohl** [comment]
@gnakm I love the emojis! Thanks for updating. 
I'm starting to have second thoughts about having 'Way to go!' in green on this page.  It makes the confirmation primary, when really the Work History should be the focus of the page. The emojis might serve the same purpose as the green. Wondering if we could try a version with 'Way to go' as a dark grey h2 (24 px). We can sit down an look at it together, or if you want to Slack me the file, I'd be happy to try out what I'm imaging to see if it makes any sense.

**Comment by gnakm** [comment]
Yes and when we discuss, let's talk about what size both Confirmation and Work History should be. That's a good point that both should be equal in hierarchy.

**Comment by gnakm** [comment]
Closing this because I consolidating this with issue #1562 and changed story. @lakohl Let me know if this makes sense! I leave it to you to add to ready for dev!
