### ISSUE TITLE
Guidance on test plan for PRs (4/19)

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1502]
As an additional way to ensure our PRs aren't breaking caseflow. We may want to introduce the practice of writing a test plan with each PRs, outlining the testing strategy for the code you wrote.

Discussion after standup on 4/19.

**Comment by kierachell** [comment]
There have been quite a few `dev`-breaking PRs recently; I totally understand if something breaks in `UAT` - that's why QA is here (I go through as many possible permutations of `as real as possible data` to validate new features/fixes). At last `UAT` is finally resembling `prod` in most functional ways - which has been my goal. 

However, if something breaks `dev` - I don't know how to help that. It should be the same as your local code and something was not tested/reviewed/validated right.

Do you want QA to validate `dev` as well? Currently, we live in `UAT` and `dev` just doesn't exist for us because there's no real parity between that and `prod` (aside from UI details). Almost every ticket that I've validated in `dev`-only has come back from `prod`.

**Comment by mmlumba** [comment]
Since we've been introducing a lot of npm packages too with the whole Redux conversion, it would be helpful to add which packages have been added (along with a brief summary of why they've been added) with each PR. This can also apply for new ruby gems that anyone decides to add.

**Comment by shanear** [comment]
- check that things look right (add a screenshot or .gif of the feature if relevant, http://www.cockos.com/licecap/)
- any integration cases that you ran (file numbers, test setup)
- Any additional assumptions have I made about why this doesn't break things?

**Comment by shanear** [comment]
Added guidance to:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/docs/pipeline.md
