### ISSUE TITLE
Litigation Support: Add Admin Actions to CAVC Remand Root Task

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#15140]
## User or job story
Job story: When I have a remand case, I should have a limited set of admin actions on the root task before the send 90 day letter task, so that I can get necessary actions done in order as ordered by the Court.

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: CAVC_Remand
- [ ] This feature should be accessible to the following user groups: Litigation Support
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] POA Clarification is listed on the submit admin actions page - blocks send 90 day letter task
- [ ] Provide Instructions and context for this action appears on the submit admin actions page

**Comment by araposo-tistatech** [comment]
@geronimoramos @mbaenatan I believe this is the ticket that is causing a bit of confusion for me. Do we really need a limited set of admin actions before the send 90 day letter task and then a different set after the 90 day letter task was sent? Can't we just have all of them on one task?

**Comment by geronimoramos** [comment]
> @geronimoramos @mbaenatan I believe this is the ticket that is causing a bit of confusion for me. Do we really need a limited set of admin actions before the send 90 day letter task and then a different set after the 90 day letter task was sent? Can't we just have all of them on one task?

The intention for the limited set of admin actions is to help reduce errors and potential confusion in the event they select the wrong admin action. Also, since these users are new to Caseflow, I think having all the admin actions available to them can be overwhelming/misleading. Curious to hear @mbaenatan thoughts!

**Comment by mbaenatan** [comment]
@araposo-tistatech Let's go with the full list of admin actions and have the full list for both before and after the 90-day letter is sent. We will confirm this full list on Thursday 9/17. 
You bring up a good point @geronimoramos around confusion and 1st time Caseflow users but since we've "co-created" this with them it shouldn't be too foreign. I'd rather they have a learning curve and have the all the actions they need rather than getting stuck and holding up the process

**Comment by geronimoramos** [comment]
Agreed. I like the idea of using what exists and deducting from there if necessary. I think specifics in the training materials will be helpful for the users.

**Comment by araposo-tistatech** [comment]
duplicate of #15286, closing
