### ISSUE TITLE
Pull Judge & DVC teams into new component

### ISSUE THREAD

**Issue by ajspotts** [department-of-veterans-affairs/caseflow#15162]
## Description
The `OrganizationUsers` component has become quite convoluted at this point with the additions of Judge & DVC teams.  There is an inordinate amount of logic (see [here](https://github.com/department-of-veterans-affairs/caseflow/blob/01aae9619d26d77a3ba3b4c76c31a0260be6d6f6/client/app/queue/OrganizationUsers.jsx#L250) & [here](https://github.com/department-of-veterans-affairs/caseflow/blob/01aae9619d26d77a3ba3b4c76c31a0260be6d6f6/client/app/queue/OrganizationUsers.jsx#L281)) determining what should be rendered, when instead the less confusing and more React-y way to go about this would be simply to pull these teams out into a separate component and make these decisions with props.

## Acceptance criteria
- [ ] Create new component for Judge & DVC teams

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | |||||||
5 | ||||||
8 | 
```

STORYBOOK

consider if both of these components (existing and new) should have a shared
parent component, or structure vs data, etc

come up with a term to encapsulate 'judgeteam like orgs', 'dvcteam like orgs'

Another way to determine the team type and what component to use on the front end:
update the org admin url of judge and dvc team to be judge_team and dvc_team rather than organizations?
https://github.com/department-of-veterans-affairs/caseflow/blob/d0d189ba1c99b40e8a37cd4b7b04918e6e81755b/app/models/organization.rb#L103-L110

Would allow us to remove conditionals here 
https://github.com/department-of-veterans-affairs/caseflow/blob/d0d189ba1c99b40e8a37cd4b7b04918e6e81755b/app/controllers/organizations/users_controller.rb#L12-L13


#### Why 1?
* 

#### Why 2?
* 

#### Why 3?
* ~Leaving space to learn storybook~
* Just a refactor, no test changes
* might split out a test?

#### Why 5?
* Leaving space to learn storybook
