### ISSUE TITLE
Add unit tests for the Redux store. [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1516]
This ticket will require some investigation into Redux testing best practices.

We don't currently have any unit tests for our Redux code in Certification V2. We should add some! These tests should cover:

- the global reducer
- specific actions (let's start with the actions that are more than one statement long)
- dispatch functions

Let's spend some time researching common Redux testing patterns and post some details here before we start implementing.

**Comment by astewarttistatech** [comment]
Should @amprokop the "Tech Improvement" label be added, in order for this ticket to follow through the Waffle board and QA doesn't have to "try and validate" this issue?

**Comment by sharonwarner** [comment]
I read through a lot of documentation of Redux/React testing this afternoon. It seems like there are two main paths we can take: Jest/Enzyme or Chai/Mocha/Enzyme. 

Redux's documentation recommends using Jest/Enzyme. It's definitely the cooler of the two options. It uses snapshot testing, so it compares the HTML output of the previous test run to the current test run. If the HTML doesn't match, the test fails. It's very easy to write tests for component rendering because you don't have to write any expect statements. 

Specifically for our project, though, I think Chai/Mocha/Enzyme makes more sense. Jest would be great for testing small component rendering, but we already have a ton of Chai/Mocha tests for our small components. For our larger components, comparing huge amounts of HTML output would be confusing. Also, Dispatch provides a pattern for testing reducers and actions with Chai. While Jest is super cool, I don't think it provides enough advantages to introduce it as a new dependency in the project. 

Let me know what you think. 

@joofsh @amprokop

**Comment by amprokop** [comment]
yeah i'm fine to stick with chai/mocha/enzyme. jest is definitely an interesting option though.

**Comment by kierachell** [comment]
Well,
the build doesn't fail, so, presumably, it's alright
