### ISSUE TITLE
(2) Handle case where `bgs_record` == `:not_found`

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15175]
## Description

`bgs_record` can return the symbol `:not_found`:
https://github.com/department-of-veterans-affairs/caseflow/blob/067a40e991e30f9f9b86c19eafd21231d41aa58b/app/models/concerns/associated_bgs_record.rb#L61-L63

This code: https://github.com/department-of-veterans-affairs/caseflow/blob/cd70fca70993c5176b3ef451367d285bd0ab2b24/app/models/veteran.rb#L180
does not handle that scenario.

## Acceptance criteria
- [ ] Understand why we're returning `:not_found` instead of `nil` here?
- [ ] Handle case where `bgs_record` == `:not_found`

## Background/context/resources
When testing https://github.com/department-of-veterans-affairs/caseflow/pull/15167, I ran across this error after clicking "Correct issues" in the Case Details page:
![image](https://user-images.githubusercontent.com/55255674/92181150-38e97c00-ee0e-11ea-942f-6f2fc22fe76f.png)

**Comment by charleyf** [comment]
The fix I've pushed here should resolve this error. It uses the same pattern found elsewhere in the file of checking `bgs_record_found?` and returning `nil` if it's not.

I spent some time working on this and my conclusions as to the 'why' of this are:
- I couldn't find it, but it seems likely to me that, somewhere, this `:not_found` symbol is used as a render status like this:
`render json: { error: "Task #{task_id} not found" }, status: :not_found`
- There are a lot of different pieces of code that depend on the `bgs_record` variable. Changing it to be `nil` rather than `:not_found` when there isn't an associated `bgs_record` seems both high risk (since it deals with data access) and complicated. I made several attempts without much success.

I found related code in these six files:
`caseflow/app/mappers/power_of_attorney_mapper.rb`, line 16-17
`caseflow/app/models/bgs_related_claimant.rb`, line 15-19
`caseflow/app/models/bgs_power_of_attorney.rb`, line 124-127
`caseflow/app/models/person.rb`line 112-116, line 130-132
`caseflow/app/models/veteran.rb` line 149-151 , line 181, line 390-394
`caseflow/app/models/concerns/associated_bgs_record.rb` line 51-53, line 61-63, line 103-105

**Comment by yoomlam** [comment]
I think `bgs_record` returning `:not_found` makes it obvious, compared to returning `nil`. In which case, other parts of the code that call  `bgs_record` should handle a `:not_found` return value.

Another option is to throw an exception and have callers handle that instead.
cc: @n1zyy
