### ISSUE TITLE
Attorney Fees | Bug Fix | Allow adding attorney claimant when veteran has no relationships

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15200]
## Description
This is a result of UAT testing of Attorney Fees.  During Intake, when a veteran has no relationships, I am able to click the "Add claimant" button, but after adding either a listed or unlisted attorney, they do not appear on the page and the submit button is disabled.

Also the copy should be updated, and match another update we made.

![image (5).png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/8e8e974a-a1b4-48e5-a094-28e3cd9ec8e3)

## Acceptance criteria
- [ ] After an attorney claimant is added, they appear as the claimant on review page, even when the veteran has no relationships
- [ ] Update "No relationships" copy (see below)

## Copy
This copy got updated for veterans with relationships, but we missed a spot in COPY.JSON's `NO_RELATIONSHIPS`. Please update it to match: `CLAIMANT_NOT_FOUND_START`:
> This Veteran currently has no known relationships. If you do not see the claimant in the options below or if the claimant's information needs to be updated, please 

## Background/context/resources
[The other copy update issue](https://github.com/department-of-veterans-affairs/caseflow/issues/10586)

## Technical notes
The `SelectClaimant` Intake component may be a good place to start.
Feel free to combine the copy or insert the email using markdown, see the `AddClaimantModal` for an example.

**Comment by Sjones352** [comment]
@leikkisa and @rutvigupta-design 
When I add the claimant, the red text still shows below. Basically this red text shows user that there is no claimant in the database prior to adding a claimant
<img width="1490" alt="Screen Shot 2020-09-16 at 4 48 42 PM" src="https://user-images.githubusercontent.com/23080951/93391035-9634f280-f83c-11ea-9610-ca1a5fca4229.png">

If we were to add a claimant, can we get rid of the red text so that user is still not confused as to weather this functionality is working right.
<img width="1430" alt="Screen Shot 2020-09-16 at 4 47 34 PM" src="https://user-images.githubusercontent.com/23080951/93391329-fc217a00-f83c-11ea-998a-4a5d6f418e78.png">

**Comment by rutvigupta-design** [comment]
From a design perspective, I think yes absolutely, we shouldn't show them that alert (red text). Is the user still able to proceed when they get that red text alert?

**Comment by Sjones352** [comment]
Yes user is able to proceed. Thanks Rutvi

**Comment by leikkisa** [comment]
@Sjones352 If you are interested, we just moved this bonus ticket to Ready for Dev, it's a ticket to update the copy.

https://github.com/department-of-veterans-affairs/caseflow/issues/15001
