### ISSUE TITLE
Cancellation of an AttorneyRewriteTask should reactivate JudgeDecisionReviewTask, not JudgeAssignTask

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15218]
## Description
AttorneyRewriteTasks inherit their behavior from AttorneyTasks. Upon cancelling an AttorneyTask we cancel the associated JudgeDecisionReviewTask and open a new JudgeAssignTask. This is correct behavior for a normal AttorneyTask. However when we have an AttorneyRewriteTask the JudgeDecisionReviewTask is properly working, and we should not cancelled it.

Override the cancel flow behavior in AttorneyRewriteTasks

## Acceptance criteria
- [ ] AttorneyRewriteTasks return control to the JudgeDecisionReviewTasks, instead of cancelling them and creating a JudgeAssignTask
- [ ] Bulk Reassign handles this case properly
- [ ] Update any Bat Team docs

## Background/context/resources
[Example case](https://dsva.slack.com/archives/CHX8FMP28/p1599769654200500)

**Comment by hschallhorn** [comment]
Original offending line: https://github.com/department-of-veterans-affairs/caseflow/pull/12295/files#diff-9a9376e40c278cc9cd0d09a8ffc60f1dR67
(all other attorney subclasses would be caught by this callback)
The og fix: https://github.com/department-of-veterans-affairs/caseflow/commit/bab4a7f9865374965d07ec0db3b5eece2b4b30c9#diff-9a9376e40c278cc9cd0d09a8ffc60f1dR67
(Explicitly check for the type)
Ticket to help catch some of these errors https://github.com/department-of-veterans-affairs/caseflow/issues/14133
PR that reintroduced this: https://github.com/department-of-veterans-affairs/caseflow/pull/14448

**Comment by ajspotts** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | |
2 | ||||||
3 | ||||
5 | ||||
8 | 
```

Check that task is an AttorneyTask rather than a child class of AttorneyTask.

[Task trees during Decision phase](https://github.com/department-of-veterans-affairs/appeals-team/blob/master/Project%20Folders/Tasks/tasktrees/descr/tasks-overview.md#decision-phase)

Offending line that sends any attorney task class back to judge assign: https://github.com/department-of-veterans-affairs/caseflow/pull/14448/files#diff-9a9376e40c278cc9cd0d09a8ffc60f1dR66


#### Why 1?
* simple `type == AttorneyTask.name` before sending back to judge assign

#### Why 2?
* Testing :smile:
