### ISSUE TITLE
Create job to check that `on_hold` tasks should have an `active` descendant task

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15267]
Resulting from #14307 investigation for stuck appeals.

## Description

Create data integrity job to check that `on_hold` tasks should have an `active` descendant task. We want a more general version of `OpenHearingTasksWithoutActiveDescendantsChecker` like this (but with better performance):
```ruby
Task.on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name])
 .find_in_batches(batch_size: 5000).map {|group| group.select { |task|
   descendants_excluding_self = task.descendants - [task]
   descendants_excluding_self.map(&:active?).exclude?(true)
} }
=> nil
```

## Acceptance criteria
- [ ] regularly running job that reports on `on_hold` tasks that do not have an `active` descendant task

## Background/context/resources
[#14307 comment A](https://github.com/department-of-veterans-affairs/caseflow/issues/14307#issuecomment-690773618)

## Technical notes

Can add to job `StuckAppealsChecker`.

**Comment by yoomlam** [comment]
Could be implemented in Metabase instead of a job.

**Comment by lomky** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | |
5 | 
8 | 
```

Ensure error message is actionable for Bat Team.

Query might be optimized more

#### Why 1?
* 

#### Why 2?
* we know the query, and have somewhere to put it

#### Why 3?
* room for optimization

**Comment by lomky** [comment]
Optimized Query:
```ruby
Task.joins(:children).on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name])
  .group("tasks.id")
  .having("count(case when children_tasks.status in (?) then 1 end) = 0", Task.open_statuses)
```

<details><summary>Working that out</sumary>

# starting clear but slow query (4.4s in Dev; selects once for all on hold task, then once per descendent, redundantly) 
  Task.on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name]).find_in_batches(batch_size: 5000).map {|group| group.select { |task|
     descendants_excluding_self = task.descendants - [task]                                                             
     descendants_excluding_self.map(&:active?).exclude?(true)                                                           
  } }                                                                                                                   
                                                                                                                        
#<Benchmark::Tms:0x000055dcd17df470 @cstime=0.0, @cutime=0.0, @label="", @real=4.490401327002473, @stime=0.136714, @total=3.967230000000003, @utime=3.830516000000003>
                                                                                                                        
# ref: Finds 41 tasks in Dev that are in this bad state (40 from faulty seed data; one I mucked up)                     
                                                                                                                        
## Working through!                                                                                                     
# we don't think we need the group by, drop it                                                                          
                                                                                                                        
  Task.on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name])                                                  
   .select { |task|                                                                                                     
     descendants_excluding_self = task.descendants - [task]                                                             
     descendants_excluding_self.map(&:active?).exclude?(true)                                                           
  } }                                                                                                                   
                                                                                                                        
# two big issues·                                                                                                       
# iterating over large set of tasks                                                                                     
# running method on each - task.descendants is query intensive - call one one task can end up with a call per child     
                                                                                                                        
# make that three big issues·                                                                                           
# will call this redundantly down a subtree - we only want to run on the leaf-most on hold task per subtree             
                                                                                                                        
                                                                                                                        
# we are looking for: all on_hold tasks where the childen are completed, or no child task exists                        
                                                                                                                        
# note: exclude Evidence Window Task, Timed Hold Tasks                                                                  
                                                                                                                        
# on hold tasks with no active children                                                                                 
                                                                                                                        
  Task.on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name]).reject do |task|
    task.children.open.any?                                                                                             
  end                                                                                                                   
                                                                                                                        
#<Benchmark::Tms:0x000055dcd19cd688 @cstime=0.0, @cutime=0.0, @label="", @real=2.1938136109965853, @stime=0.022581000000000184, @total=1.8670200000000015, @utime=1.8444390000000013>
# cut the time in half! still calling a select per on_hold task to find each children (1 + N) - how can we do one big select to find all children of all the parent tasks?
​
# can we use includes and just use another where not filter?                                                            
                                                                                                                        
  Task.includes(:children).on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name]).where.not(children_tasks: {status: Task.open_statuses})
                                                                                                                        
#no dice - this finds any on hold task with a closed child task, even if it has another child that is active            
                                                                                                                        
# lets try where count of open child tasks is zero - based on existing `stuck_appeals` logic - s/o to Peter·            
# https://github.com/department-of-veterans-affairs/caseflow/blob/74701d9d6809f7360f26f99f9eb608759bae2ca5/app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb#L61-L70
Task.includes(:children).on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name])
  .group("tasks.id")                                                                                                    
  .having("count(case when children_tasks.status in (?) then 1 end) = 0", Task.open_statuses)                           
                   
# rails is being too smart and not pulling in children since we don't reference it
# joins instead?
 Task.joins(:children).on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name])
  .group("tasks.id")
  .having(
    "count(case when children_tasks.status in (?) then 1 end) = 0",
	Task.open_statuses
  )
​
# yaaaaaaaaaaaaaaaaaaaaaaaaaaa it works                                                                                 
                                                                                                                        
                                                                                                                        
Benchmark.measure {                                                                                                     
Task.joins(:children).on_hold.where.not(type: [RootTask.name, TrackVeteranTask.name, EvidenceSubmissionWindowTask.name, TimedHoldTask.name]).group("tasks.id").having("count(case when children_tasks.status in (?) then 1 end) = 0", Task.open_statuses).pluck(:type)
}··                                                                                                                     
[2020-11-09 16:40:12 -0500]    (4.8ms)  SELECT "tasks"."type" FROM "tasks" INNER JOIN "tasks" "children_tasks" ON "children_tasks"."parent_id" = "tasks"."id" WHERE "tasks"."status" = $1 AND "tasks"."type" NOT IN ($2, $3, $4, $5) GROUP BY tasks.id HAVING (count(case when children_tasks.status in ('assigned','in_progress','on_hold') then 1 end) = 0)  [["status", "on_hold"], ["type", "RootTask"], ["type", "TrackVeteranTask"], ["type", "EvidenceSubmissionWindowTask"], ["type", "TimedHoldTask"]]
                                                                                                                        
=> #<Benchmark::Tms:0x000055dccfe1f9b8 @cstime=0.0, @cutime=0.0, @label="", @real=0.006596735998755321, @stime=0.0, @total=0.0020749999999978286, @utime=0.0020749999999978286>
                                                                                                                        
                                                                                                                        
# AND ITS FAST - success       
           
</details>
