### ISSUE TITLE
Add Hover Information to Attorney & Judge Queue Days Waiting Column 

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15405]
## Description
User Story: As a VLJ and or Attorney, I want to see added context or an identifier on the days waiting column of my queue page, so that I can identify when an IHP task has been completed.

## Acceptance criteria
- [ ] Atty Assigned queue shows the IHP timing details on hover
- [ ] Judge Assign queue shows the IHP timing details on hover
- [ ] Attorney On Hold queue shows the IHP timing details on hover

## Engineering Tasks
- [x] Backend (HUNTER)
- [x] Frontend (HUNTER)

## OUT OF SCOPE
Hover information on
1. days waiting for drafted decision
1. assigned to you

## Background/context/resources
~~User Story: #13800~~ User story was split and closed
Sibling User Story: #15404

We want to show a bit more context for Attorneys and Judges who have requested an IHP when that task has completed, so they can understand this case has recently come back into their queues. See the User Story for more context #13800

This tickets focus is to tweak the Days Waiting column to give more context of an IHP task that has recently been finished (Atty&Judge) or is out for an IHP (Atty only)

### IHP Epic Designs
[Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1595518321333/a3929ce45595dca9177fe2adfd3cb3d6e3203fbd) of research and flows 
[Link to designs](https://www.figma.com/file/awxxww4bQNzgr4wP4vdh8Y/IHP-Attorney-and-Support?node-id=0%3A1) in Figma

Active Tab Display | On Hold Tab Display
-- | --
![image](https://user-images.githubusercontent.com/6129479/95504160-5f08bb80-097a-11eb-9e89-a70a0f4bb3fa.png) | ![image](https://user-images.githubusercontent.com/6129479/95503401-55328880-0979-11eb-98c5-97eff6f71201.png)

**Comment by hschallhorn** [comment]
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | 
3 | 
5 | |||||||||
8 | 
```

IHP Requested: Creation date of ihp task assigned to a vso
IHP received: Completion date of ihp task assigned to a vso
On hold for IHP: How many days have passed since creation date of ihp task assigned to a vso

Not currently passed in QueueConfig. Avoid N+1 queries when adding to/populating QueueConfig.

Use existing hover/tooltip component (see queue hearing badge)

#### Why 5?
* Back end calculation of
  * Is there an ihp task on this appeal?
  * When was the ihp task created
  * When was the ihp task completed
  * How many days have passed
* Serialization of IHP information that does not blow up the request for tasks
* Creating a new component in the ui
* Queue components may not be too receptive to addition of new data and new component

**Comment by hschallhorn** [comment]
For whoever picks up the front end portion of this!

The back end will return `latest_informal_hearing_presentation_task` along with our tasks! It has the attributes `requested_at` and `received_at` (possibly null). This should be enough to calculate and display ihp information in a tooltip!

`latest_informal_hearing_presentation_task` will need to be added to the attrs we pull out of the tasks here: https://github.com/department-of-veterans-affairs/caseflow/blob/0324c07738bcfc62ca997e8850965bc27243f498/client/app/queue/utils.js#L64

**Comment by hschallhorn** [comment]
Closed in #15560
