### ISSUE TITLE
Update Documentation!

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1543]
https://github.com/department-of-veterans-affairs/caseflow/blob/master/README.md

Is super out of date:
- we're not using PhantomJS that much, we need to add Chromedriver
- add Yarn setup documentation once that goes through
- rake DB setups?

**Comment by kierachell** [comment]
assigned @shanear because he added Chromedriver
assigned @joofsh because of all the nodejs updates
assigned @NickHeiner cause yarn and he recently had to go through the pains of using outdated documentation - so he is most likely to remember all the workarounds

**Comment by NickHeiner** [comment]
No need to mention `yarn` yet until we actually do #1531.

If chromedriver is only being used from Node, we don't even need to `brew install` it, because we can use [`chromedriver`](https://www.npmjs.com/package/chromedriver). But I think we are using it from Ruby, right?

The docs actually worked fine for me. There were no workarounds other than #1483, but that's resolved now.

**Comment by kierachell** [comment]
And/or you already added the changes (like nvm version fix)

**Comment by joofsh** [comment]
Closing this. Documentation changes related to node & chromedriver are done. We haven't started using yarn yet

**Comment by kierachell** [comment]
+ seems like @aroltsch and @slj contributed too 👍
