### ISSUE TITLE
Investigate: Data race when rescheduling a virtual hearing with outstanding cancelled virtual hearing

### ISSUE THREAD

**Issue by ferristseng** [department-of-veterans-affairs/caseflow#15449]
## Description

We suspect that a data race is preventing the user from creating a new virtual hearing if the delete conference job hasn't fully run for a cancelled hearing (i.e. `job_completed` field hasn't been set to true).

To reproduce in dev:
  - Cancel an existing virtual hearing
  - Ensure the job completed field returns false
  - If false, try rescheduling the hearing

**Note: #15448 might resolve this. This might only be an issue because some hearing tasks point to the same hearing.**

## Acceptance criteria
- [ ] Investigate to see if this could be an issue

## Background/context/resources

See: `LegacyAppeal.find(1019872)`

https://github.com/department-of-veterans-affairs/caseflow/blob/3fedcf6c4f7bf792d94bfb91e3161c51917cbecf/app/models/hearings/forms/base_hearing_update_form.rb#L92-L95

**Comment by rubaiyat22** [comment]
This issue was resolved by [#15448](https://github.com/department-of-veterans-affairs/caseflow/issues/15448) as you can reschedule a hearing as virtual even if the job for cancelled virtual hearing has not finished. This is because when it hits this [logic](https://github.com/department-of-veterans-affairs/caseflow/blob/5d0bf14c9747fc9440f70afcdcebe8a38c3f9a8e/app/models/hearings/forms/base_hearing_update_form.rb#L92), this is a new hearing and it does not have a virtual hearing yet.  

Steps I took to confirm that a hearing can be rescheduled as virtual even if the `job_completed` on cancelled virtual hearing returns `false`
- cancel a virtual hearing by switching the type back to original type
- ensure `job_completed` returns `false`
- go to case details page and reschedule the veteran for a virtual hearing
