### ISSUE TITLE
Cancel ChangeHearingRequestTypeTasks

### ISSUE THREAD

**Issue by lund5000** [department-of-veterans-affairs/caseflow#15507]
# User story
As a hearing coordinator, I want to cancel "Change hearing request type" tasks that show up on appeals when they shouldn't so I can unblock them and reduce confusion.

# Background
`ChangeHearingRequestTypeTask`s should only be added to Travel Board hearings, but something is causing them to get added to other appeals as well (roughly a few each day). Neither the engineering team nor the Branch can identify a common thread for the affected appeals. To alleviate the issue we ought to give coordinators the ability to cancel the task.

# Acceptance criteria
- Users with the "Admin Intake", "Build HearSched", or "Edit HearSched" tasks are given the to option to cancel a `ChangeHearingRequestTypeTask`
- When a Case Details page is loaded for an appeal that has a cancelled `ChangeHearingRequestTypeTask` in its task tree, a new `ChangeHearingRequestTypeTask` *is not* created

**Comment by nicholer** [comment]
Copy suggestion: since the `ChangeHearingRequestTypeTask` reads as "Convert hearing to virtual" in the Actions menu, should the cancel action read as "Cancel convert hearing to virtual"? 

(I'm assuming adding "Convert hearing to video" isn't a near-term priority, so there's no need to make it more general like "Cancel convert hearing")

**Comment by tomas-nava** [comment]
Normally when we cancel a HearingTask, we'd change the appeal's VACOLS location; I'm going to assume that, because we're not changing the location when this task is created, we will also not be changing it when it's canceled.
