### ISSUE TITLE
Enable Caseflow test suite to run on Microsoft Edge

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#15527]
## Description
The VA will soon be setting Microsoft Edge as the default browser on VA computers. In preparation to support Caseflow on Microsoft Edge, we need to enable our automated tests to run on the Edge browser instead of Chrome to see if there are any gaps.

Here are some initial instructions: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium?tabs=c-sharp

## Acceptance criteria
- [ ] Updated local test suite to run on Microsoft Edge
- [ ] Update Circle CI tests to run on Microsoft Edge (if possible)
- [ ] If there are any test failures, [record them in this Google doc](https://docs.google.com/document/d/1jjVdbRnBsXwZXrUbOFxZrOIgt0UBXvhcAcVmOzqCJIY/edit#heading=h.4v5339q3b9lz) and hold off on merging the PR

## Background/context/resources
- [Caseflow - Microsoft Edge Testing Plan](https://docs.google.com/document/d/1jjVdbRnBsXwZXrUbOFxZrOIgt0UBXvhcAcVmOzqCJIY/edit)

## Technical Notes

- It appears that this would just require updating the [Capybara Selenium Driver](https://github.com/department-of-veterans-affairs/caseflow/blob/5d0bf14c9747fc9440f70afcdcebe8a38c3f9a8e/spec/support/capybara.rb#L22) to use Edge instead of using Chrome (See [this thread](https://stackoverflow.com/questions/60940488/how-do-i-set-options-for-the-selenium-ms-edge-driver-in-ruby#answer-60958149))

**Comment by ferristseng** [comment]
I got this running in my local environment. I had to edit one source code file since the `webdrivers` gem we are using doesn't know where to find Edge on Linux (which would mean it's not currently compatible with the environment we have in CircleCI).

![Screen Recording 2020-11-10 at 4 10 48 PM mov](https://user-images.githubusercontent.com/1298274/98734346-d2ce2780-236f-11eb-8c0c-3c05f75b9d6f.gif)
 
Someone (maybe me) can submit a patch to that repo with some default locations to look for the driver, but until then, I would consider this blocked.
