### ISSUE TITLE
Certification | URL from VACOLS opens in IE11

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#15554]
## Description
The URL to get to Certification from VACOLS has started opening in IE11 for some users, and causing the page to not load.  This may be due to the deprecation of Chrome on VA computers.

## Acceptance criteria
- [ ] The Certification page loads in IE11

## Background/context/resources
Here is an example URL of a page that will not load:
https://certification.cf.ds.va.gov/certifications/new/3846036

Here is an example of a Sentry alert:
https://sentry.prod.appeals.va.gov/department-of-veterans-affairs/caseflow/issues/11902/?referrer=webhooks_plugin

This is not impacting MS Edge, just IE11.

## Technical notes
See "Browser Support" section of the react-hook-form FAQ
https://react-hook-form.com/faqs/

**Comment by alisan16** [comment]
@leikkisa We've followed up with VA ITOPS about this and the problem was that the browser routing settings for Caseflow had been removed from recent GFE updates. They will be adding back the setting so that all Caseflow URLs will always open in Chrome. As a team, we are still not supporting IE. ITOPS has also stated that Chrome will likely still be an approved software and might not get removed from GFEs after all. I recommend holding off on this ticket to not add unnecessary bulk to the app just to support IE11. cc @jcq

**Comment by leikkisa** [comment]
@alisan16 Thank you!

**Comment by jcq** [comment]
And for the record, if they possibly deprecate Chrome in favor of the Chromium-based Edge, that's fine — no need to add polyfills for the JS code. The problem is solely with IE.

**Comment by leikkisa** [comment]
Closing this PR - it seems like the VA IT fix resolved things because we haven't heard any new reports of the problem.
