### ISSUE TITLE
Allow values to be pasted into DateSelector

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15676]
## User or job story
As a caseflow user, I need to be able to paste values into date pickers, so that I can more quickly enter information into forms. 

## Acceptance criteria
- [ ] Users can populate `DateSelector` by pasting in a valid MM/DD/YYYY string

---

### Open Questions
- [ ] What other date formats should be supported? (Our date selector is mm/dd/yyyy)

### Background/context

Out date picker can be accessed at [on caseflowdemo](https://www.caseflowdemo.com/storybook/?path=/docs/commons-components-dateselector--default) or [locally](http://localhost:6006/?path=/story/commons-components-dateselector--default) after running `make storybook`

![Screen Shot 2020-12-07 at 10 24 50 AM](https://user-images.githubusercontent.com/45575454/101370091-0caf2280-3877-11eb-8e72-52d5176ee26a.png)

### Other notes
This was spun out of the AC for #14795 as it was a non trivial implementation.

**Comment by lomky** [comment]
[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)
```bash
1 | 
2 | ||||
3 | ||||||||
5 | 
8 | 
```

We don't have a good initial idea how to tackle this.
We would consider the other format implementations, if any, to be follow on.

This is a custom Caseflow component:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/components/DateSelector.jsx

This is a medium priority as it would help ensure data integrity (allowing c/p of data rather than retyping)

`MM/DD/YYYY` is the format from the CAVC website, where date is being copied.

#### Why 2?
* This isn't a novel problem, hopefully there's guidance on the interweb

#### Why 3?
* Unfamiliarity with this front-end code.
