### ISSUE TITLE
Associate CAVC remands with court remand appeal

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#15719]
## Description
Currently, the appeal id stored on a `CavcRemand` object is the appeal id of the appeal that was sent to CAVC (original appeal), not the appeal that was created to handle the court's decision (cavc appeal). This causes a handful of issues.
1. It is hard to find the cavc `Appeal` associated with a `CavcRemand` object.
2. [When displaying the information about the remand](https://github.com/department-of-veterans-affairs/caseflow/blob/f6c37b6587eb6bd083ff03c380cd20c8e6a69ec2/app%2Fmodels%2Fappeal.rb#L358) on a cavc appeal, we try to track down a remand associated with the original appeal (will break if there is more than on remand for a single appeal)
3. [When we return the newly created cavc appeal after processing a remand](https://github.com/department-of-veterans-affairs/caseflow/blob/7b4d8e0f8c8b0524c4ca2592cb0121ecec1644ff/app%2Fcontrollers%2Fcavc_remands_controller.rb#L10), we look for any cavc appeal with that docket number (will break if there is more than on remand for a single appeal)

Instead, when processing a remand, we should use the appeal id of the cavc appeal (either by creating the cavc appeal first or removing the required validation on appeal id and updating the remand after the appeal is created).

## Out of Scope
Whether or not more than one cavc remand and appeal can exist for an original appeal.

## Impact
1. If multiple remands exist on an appeal, users are still directed to the appeal they just created after intaking a remand
2. If multiple remands exist on an appeal, users are shown the correct remand information for the appeal they are viewing
3. Engineers can easily track down which cavc appeal is associated with a cavc remand

## Acceptance criteria
- [ ]  The `source_appeal_id` on a `CavcRemand` is the appeal id of the originating appeal
- [ ] The `remand_appeal_id` on a `CavcRemand` is the appeal id of the created CAVC appeal
- [ ] Relevant tests, factories, and seeds are updated
- [ ] Code in issues 2 and 3 are updated to reflect new association (see Technical notes for suggestions)

## Background/context/resources
[Slack thread](https://dsva.slack.com/archives/CJL810329/p1608564273168800)

## Technical notes
https://github.com/department-of-veterans-affairs/caseflow/blob/7b4d8e0f8c8b0524c4ca2592cb0121ecec1644ff/app%2Fcontrollers%2Fcavc_remands_controller.rb#L10

```ruby
cavc_appeal = Appeal.find(cavc_remand.remand_appeal_id)
```

https://github.com/department-of-veterans-affairs/caseflow/blob/f6c37b6587eb6bd083ff03c380cd20c8e6a69ec2/app%2Fmodels%2Fappeal.rb#L358

```ruby
CavcRemand.find_by(remand_appeal_id: id)
```

**Comment by lomky** [comment]
[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)
```bash
1 | 
2 | ||||||
3 | ||||||
5 | 
8 | 
```

Let's add the cavc appeal id, rather than replace the existing!

Maybe as two PRs? Engineer discretion

1. Migration to rename `appeal_id` to `source_appeal_id`
2. Add a new relation to the created remand appeal `remand_appeal_id` 
3. Should we rename `cavc_remand` to `cavc_decision`? NO, the board calls all cavc decisions "remand" - Remand can _either_ mean "all decisions coming back from CAVC" _or_ "Decisions of type remand from CAVC"

#### Why 1?
* 

#### Why 2?
* Fairly small number of changes in the actual code
* No prod data to update

#### Why 3?
* Refactors always make me a little ancy
* Two migrations in a ticket?!?! :horrified:
