### ISSUE TITLE
[Flaky Test] Expects "veteran_not_modifiable" but gets `nil` when BGS shows a station conflict

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#15865]
## Description

Expects "veteran_not_modifiable" but gets `nil` when BGS shows a station conflict

## Background/context/resources

[Asked Ed in Slack](https://dsva.slack.com/archives/C01CQA12FL7/p1611784320007100)

 - Circle CI Error:  [IntakeStartValidator#validate sets error_code "veteran_not_modifiable" when BGS shows a station conflict - spec.models.validators.intake_start_validator_spec](https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/38714/workflows/32108fb9-76cf-4eca-8af7-9a6452049c9b/jobs/146586)

 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by n1zyy** [comment]
Seen again here: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39059/workflows/6ea03027-ec5e-4271-a8c4-0477a9e1838d/jobs/148301

**Comment by charleyf** [comment]
Seen again here: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39244/workflows/f03d6802-d233-4b4e-92cc-03b25d1f9072/jobs/149227

**Comment by charleyf** [comment]
I started examining this flake as part of IP sprint.

This flaky test was recently rewritten as part of [this PR](https://github.com/department-of-veterans-affairs/caseflow/pull/15909/files).

Those rewrites seem very likely to have fixed this issue, so I'm closing this issue.

**Comment by charleyf** [comment]
Saw just now: https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39955/workflows/3095ca8c-6857-48ab-9f58-b840416d70eb/jobs/152690

**Comment by charleyf** [comment]
I think this flake is happening because the following condition is not being met and none of the other conditions in that if/elsif statement are being met so we're never setting `intake.error_code` and it defaults to `nil`.
https://github.com/department-of-veterans-affairs/caseflow/blob/9575ab994bdb028fede11c48731750bc1c5a1b1a/app/models/validators/intake_start_validator.rb#L28-L29
<br>
If that's correct, then there are only three places where `user_may_modify_veteran_file` could return `true` and cause this flake.
https://github.com/department-of-veterans-affairs/caseflow/blob/9575ab994bdb028fede11c48731750bc1c5a1b1a/app/models/validators/intake_start_validator.rb#L87
https://github.com/department-of-veterans-affairs/caseflow/blob/9575ab994bdb028fede11c48731750bc1c5a1b1a/app/models/validators/intake_start_validator.rb#L92
https://github.com/department-of-veterans-affairs/caseflow/blob/9575ab994bdb028fede11c48731750bc1c5a1b1a/app/models/validators/intake_start_validator.rb#L94

**Comment by charleyf** [comment]
We've merged that PR and if this test flakes again, we should get some useful information on what's happening.
