### ISSUE TITLE
[Flaky Test]  PushPriorityAppealsToJudgesJob - expected <= 1 for distribution count but got 2

### ISSUE THREAD

**Issue by rubaiyat22** [department-of-veterans-affairs/caseflow#15984]
## Description
```
PushPriorityAppealsToJudgesJob.eligible_judge_target_distributions_with_leftovers tracking distributions over time evens out over multiple calls - spec.jobs.push_priority_appeals_to_judges_job_spec
spec/jobs/push_priority_appeals_to_judges_job_spec.rb
Failure/Error: expect(final_counts.max - final_counts.min).to be <= 1

  expected: <= 1
       got:    2
./spec/jobs/push_priority_appeals_to_judges_job_spec.rb:479:in `block (4 levels) in <top (required)>'
```

## Background/context/resources

 - Circle CI Error:  https://app.circleci.com/pipelines/github/department-of-veterans-affairs/caseflow/39862/workflows/23628a81-ff5c-426c-b795-f8f718d46f7b/jobs/152220
 - Has the test already been skipped in the code?
   - [ ] Skipped
   - [x] Not Skipped
 - Related Flakes
    + 

## Approach

Time box this investigation and fix.

Remember that if a test has been skipped for a decent amount of time, it may no longer map to the exact code.

If you reach the end of your time box and don't feel like the solution is in sight:
  - [ ] document the work you've done, including dead ends and research
  - [ ] skip the test in the code
  - [ ] file a follow on ticket
  - [ ] close this issue

**Comment by charleyf** [comment]
This is related to the distribution algorithm work that Alisa [did here](https://github.com/department-of-veterans-affairs/caseflow/pull/15953). By extension it's related to the [flake fix here](https://github.com/department-of-veterans-affairs/caseflow/pull/15975).

**Comment by charleyf** [comment]
This is the flaky test, asking Alisa to consult.
- Is this test still valid? I'm not sure we still do expect these to 'evens out over multiple calls'
- Is there a way to change the two expectations to a) not flake b) reflect our distribution reality
https://github.com/department-of-veterans-affairs/caseflow/blob/533ddec0b6f14bdf06dd7c2b39e370718173404b/spec/jobs/push_priority_appeals_to_judges_job_spec.rb#L471-L481

**Comment by alisan16** [comment]
> Is this test still valid? I'm not sure we still do expect these to 'evens out over multiple calls'
Yes, this test is still valid. This is testing that the priority push distribution job that runs every Monday evens out the number of priority cases distributed to judges. You can read more about this and the way Caseflow distributes appeal cases to judges here - https://docs.google.com/presentation/d/10S5k-5oU1hPordx-zmrR_rKNYNbyC7KjyBNMhDbZ9Sk/edit#slide=id.gc0a548ea3c_0_4

> Is there a way to change the two expectations to a) not flake b) reflect our distribution reality

**Comment by charleyf** [comment]
Thanks for the clarification Alisa! I will keep investigating this today.
- I can reproduce this flake by using the code below.
- This flake existed before [#15953](https://github.com/department-of-veterans-affairs/caseflow/pull/15953)
- I've read through that presentation.



#### Confirmation this was not introduced by #15953
```
git checkout 7b537d989  # A commit from January, well before 15953.
# Change the test to the 'Code to Reproduce' section below
make one-test spec/jobs/push_priority_appeals_to_judges_job_spec.rb
```

#### Examples of the failure
```
    tracking distributions over time
number_judges: 10
priority_count: 10
9
10
11
      evens out over multiple calls (FAILED - 1)
    tracking distributions over time
number_judges: 10
priority_count: 10
8
10
11
9
      evens out over multiple calls (FAILED - 2)
```

#### Code to Reproduce
```
    (1..10).each do |i|
      (1..10).each do |j|
        context "tracking distributions over time" do
          let(:number_judges) { 10 }
          let(:priority_count) { 10 }

          before do
            # Mock cases already distributed this month
            @distribution_counts = to_judge_hash(Array.new(number_judges).map { rand(12) })
            allow_any_instance_of(PushPriorityAppealsToJudgesJob)
              .to receive(:priority_distributions_this_month_for_eligible_judges).and_return(@distribution_counts)
            allow_any_instance_of(PushPriorityAppealsToJudgesJob)
              .to receive(:ready_genpop_priority_appeals_count).and_return(priority_count)
          end

          it "evens out over multiple calls" do
            4.times do
              # Mock distributing cases each week
              target_distributions = PushPriorityAppealsToJudgesJob.new.eligible_judge_target_distributions_with_leftovers
              @distribution_counts.merge!(target_distributions) { |_, prev_dists, target_dist| prev_dists + target_dist }
            end
            final_counts = @distribution_counts.values.uniq
            # Expect no more than two distinct counts, no more than 1 apart
            puts 'number_judges: ' + number_judges.to_s
            puts 'priority_count: ' + priority_count.to_s
            puts final_counts
            expect(final_counts.max - final_counts.min).to be <= 1
            expect(final_counts.count).to be <= 2
          end
        end
      end
    end
```

**Comment by alisan16** [comment]
Interesting, thanks for doing that investigation!

I'm thinking through whether this test failure indicates an actual bug in the code. If it isn't actually distributing it sort of evenly, we may need to revisit the logic. One way to check that is to look in the actual data from all priority push distributions since it launched in 09/2020. You would want to check the `distributions` table where `priority_push = true` and join against the `distributed_cases` table on `distributions.id = distributed_cases.distribution_id` and then group by `distributions.judge_id` and `count(distributed_cases.id)`. Here's a rough histogram I pulled together - https://query.prod.appeals.va.gov/question/229. Average (mean) is 103.65 cases per judge, but there's a pretty wide range.

Would be good to keep an eye on this, but for now, I would recommend just fixing this flake. Caseflow doesn't promise that cases will be distributed *exactly* evenly, so one approach we could take is to increase the margin to `<=2` instead of `<=1`.

**Comment by charleyf** [comment]
I spent a bit longer puzzling away at this and found something interesting that I want come back to an understand
https://github.com/department-of-veterans-affairs/caseflow/blob/533ddec0b6f14bdf06dd7c2b39e370718173404b/spec/jobs/push_priority_appeals_to_judges_job_spec.rb#L464

If I increase that `rand(12)` to `rand(20)` this test fails most of the time, but still succeeds occasionally. If I increase it to `rand(100)` this test always fails. I think that this `rand()` represents a judges target, but I'm out of time today to investigate. I'd like to:
- Figure out what that represents.
- Go look at metabase to figure out what this should be to mimic real data.

**Comment by charleyf** [comment]
I figured this problem out and [have a PR](https://github.com/department-of-veterans-affairs/caseflow/pull/16002) that I think solves it neatly.

The problem is that with the existing code we can accidentally create a test case where it's impossible to even out the assigned cases. Here's an example:
```
# Initial distribution (these represent cases/judge). This is the first reference to @distribution_counts
[0, 0, 0, 0, 10]
# Priority cases to distribute (:priority_count):
30
# Result (final_counts)
[7, 7, 8, 8, 10]
# Expectation: That all of these are within '1', there's no way for this to happen, even though
# our algorithm is working correctly so the test fails.
```

Because this was a difficult flake for me to figure out and this tests a critical algorithm my solution is slightly more complex, but solves the flake for all cases. (I'm not just setting the numbers low enough this will never happen). The solution is based on the relationship between these three values:

```
let(:number_judges) { rand(5..10) }
let(:priority_count) { rand(10..30) }
@distribution_counts = to_judge_hash(Array.new(number_judges).map { rand(12) }) # I'm calling the '12' here 'max_preexisting_cases'
```

We can constrain our values so that they will always work with this formula:
`(number_judges - 1) * max_preexisting_cases = priority_count`
Because we want to set number_judges and priority_count first, this changes to:
`max_preexisting_cases = priority_count / (number_judges - 1)`
