### ISSUE TITLE
Add an error page for when a veteran can't be located in VBMS

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#16]
Somewhat of an edge case. When a user enters the wrong SSN in VACOLS but go through the proecss of adding all the other relevant detials. When the open Caseflow ... the veteran's SSN is not the same.

**Comment by paultag** [comment]
@alex do we have a test ID for this case?

**Comment by alex** [comment]
Probably not. @KHarshawat originally filed this issue IIRC?

**Comment by paultag** [comment]
(removed my assignment on this; hit it back over to me if needed!)

**Comment by plusjeff** [comment]
A way to setup for this is to create an appeal in VACOLS for an SSN that is not in VBMS.

**Comment by plusjeff** [comment]
Unfortunately, we cannot implement this due to limitations in VBMS. 

When we request documents from VBMS for an SSN that does not exist, VBMS sends back a 200 (OK) response with an empty list of documents. However, this is the same response for a veteran that has an empty eFolder. We cannot distinguish reliably.
