### ISSUE TITLE
Manager View | Allow manager to set custom goals

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1690]
As a manager, when needed, I would like to manually adjust the number of cases assigned to each employee. 

## **AC**
1. Verify that at the start of the day, an 'unlocked' icon and an "Edit" link displays next to the Claims Assigned number for each employee.

2. Verify when a manager clicks on "Edit" (for a locked or unlocked quota), the Claims Assigned number becomes an editable number field, and the "Edit" link changes to a "Save" link.

3. Verify that if a user enters a number that causes the total number of locked assignments to be greater than the total number of cases for that day, Caseflow forces the number back down to the maximum allowable number (see example below).

4. Verify that when the "Save" link is clicked, that users' quota is set to the number in the Claims Assigned box. The grey "unlocked" icon changes to a darker grey "locked" icon. The "Save" link is converted back to a "Edit" link. The editable box is converted to a plain text number.

5. Verify that if the dark grey "locked" icon is clicked, the icon turns into a light grey "unlocked" icon, and the Claims Assigned number goes back to being automatically set by Caseflow based on an even distribution of the the total claims among all unlocked case workers.

## SVG file
[Lock svg file](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/lock.svg)
[Unlock svg file](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/unlock.svg)

## **Mocks** (a little out of date, use for visual reference)
_ARC Work Assignments at the beginning of the day:_
<img width="552" alt="screen shot 2017-04-23 at 5 45 00 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317745/a8633c32-284c-11e7-87d4-a50d1bc349bb.png">
_Editing an employee's Claims Assigned_
<img width="156" alt="screen shot 2017-04-23 at 5 47 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/25317751/fc234754-284c-11e7-95d5-c02ae30d7ec7.png">
_Edited Claims Assigned number_
<img width="592" alt="screen shot 2017-04-23 at 6 40 23 pm" src="https://cloud.githubusercontent.com/assets/4975959/25318057/56b97d08-2854-11e7-967d-d98c91d44c5a.png">

## Examples
If there are 10 cases for the day and 3 employees (A, B, and C) the initial assignments should be
A: 4 Unlocked
B: 3 Unlocked
C: 3 Unlocked

If B is edited and manually set to 6 and saved, then the assignments should be changed to:
A: 2 Unlocked
B: 6 Locked
C: 2 Unlocked

If B is manually edited to 7 and saved, the assignments should be changed to:
A: 2 Unlocked
B: 7 Locked
C: 1 Unlocked

If A is unlocked and manually set to 4, then Caseflow should force it back to 3 since 7 + 4 = 11, which is more than the total number of cases that day. The assignments should then be:
A: 3 Locked
B: 7 Locked
C: 0 Unlocked

If the Lock icon beside B is clicked, then B should be unlocked and the assignments are changed to:
A: 3 Locked
B: 4 Unlocked
C: 3 Unlocked

If the number of employees is changed to 4, the assignments would be changed to:
A: 3 Locked
B: 3 Unlocked
C: 2 Unlocked
D: 2 Unlocked

**Comment by shanear** [comment]
It makes more sense to me for them to all start out as "locked" (which means they are automatically set) @gnakm @lakohl, can we chat about this?

**Comment by shanear** [comment]
We should also not allow users to assign more cases than there are for that day.

**Comment by gnakm** [comment]
@shanear added the link to svg under AC.

**Comment by astewarttistatech** [comment]
@shanear Could you take another look at the AC? Based off the mocks there is no mention of an edit /save button next to the lock in the manager view. Is this in scope? Because this changes how the functionality works (there are different button clicks).

 Current view:
<img width="1347" alt="screen shot 2017-05-15 at 11 05 01 am" src="https://cloud.githubusercontent.com/assets/23038505/26064331/a2b38846-395e-11e7-9502-ed06808160ae.png">
<img width="1321" alt="screen shot 2017-05-15 at 11 05 24 am" src="https://cloud.githubusercontent.com/assets/23038505/26064330/a2b0deb6-395e-11e7-8898-339e669b43eb.png">

**Comment by kierachell** [comment]
## The flow between the lock and Edit/Save is mildly confusing. It is unclear if the lock means `uneditable` or `save` or `non-recomputable`

## Also, the table shifts all weird, as shown above

**Comment by shanear** [comment]
@gnakm @lakohl thoughts on the first bullet?

The second bullet is my bad.

**Comment by gnakm** [comment]
@shanear I revisited the flow of this and I think this might make more sense. It is also Lara-approved. I'm going to break it down so I the logic written out. Let me know if this makes sense to you. 

Everything will be defaulted to unlocked and user will have the option to lock it or edit the case assigned number. 
![image](https://cloud.githubusercontent.com/assets/13420618/26118383/b454b2b2-3a37-11e7-939e-5ca2f279b3d2.png)

In order to edit anything, the user has to unlock the lock first. Once the lock is unlocked, user can click edit, the case assigned number will be focused and the user will have the option to save. 
![image](https://cloud.githubusercontent.com/assets/13420618/26118174/e67e3de0-3a36-11e7-849e-09eb5262f6b3.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26118199/f8a838f4-3a36-11e7-8d8f-b1455b318ddb.png)

**Comment by shanear** [comment]
@kierachell e, pi and tao are numbers 😄

**Comment by kierachell** [comment]
Yes, but it only allows me to put `e`...not `pi` and `tao`..that's why I was sad

**Comment by kierachell** [comment]
### Boxes are still exploding:
<img width="477" alt="screen shot 2017-05-17 at 1 02 10 pm" src="https://cloud.githubusercontent.com/assets/18075411/26166297/111ae25e-3b01-11e7-91d1-4db7dcbb1f5e.png">

### The `Edit` button and the `lock` placement does not match the mocks...
<img width="107" alt="screen shot 2017-05-17 at 1 15 31 pm" src="https://cloud.githubusercontent.com/assets/18075411/26166837/eb9c1c76-3b02-11e7-9c82-46c2bdb9189c.png">

### In order to edit anything, the user has to unlock the lock first. ->currently is editable even when locked



### I can type text and negative numbers:
<img width="516" alt="screen shot 2017-05-17 at 1 02 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/26166332/26e07ad6-3b01-11e7-960f-245f5db9a6a4.png">


### I can... delete tasks!?!?!? by save 0s:
<img width="443" alt="screen shot 2017-05-17 at 1 11 03 pm" src="https://cloud.githubusercontent.com/assets/18075411/26166704/577e3b46-3b02-11e7-8ff7-c6228fc10cea.png">


<img width="475" alt="screen shot 2017-05-17 at 1 03 39 pm" src="https://cloud.githubusercontent.com/assets/18075411/26166372/4961a864-3b01-11e7-97d0-49a4aa9201d8.png">

**Comment by shanear** [comment]
@kierachell fixed the issues you mentioned

**Comment by gnakm** [comment]
@kierachell This what @shanear and I discussed. 

- We are going to stick to just showing the lock button
- In order to unlock, you can click the lock and it will disappear
- In order to lock, you can click the edit, you can change the case assignment by changing the number in inform box and clicking the save the link button will save the new number and lock it
- There may be cases where there are 0 assignments so we should allow that option

![image](https://cloud.githubusercontent.com/assets/13420618/26204769/bf9e13ee-3bad-11e7-8348-b1a566b641f0.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26204781/cb9818ac-3bad-11e7-939e-ded7b3d6714f.png)

![image](https://cloud.githubusercontent.com/assets/13420618/26204796/dafa7f4c-3bad-11e7-8de4-3fe193009a94.png)

**Comment by kierachell** [comment]
**PASSED**
Made a bunch of issues from this to avoid scope creep
