### ISSUE TITLE
Get POA information from BGS [5]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1710]
We should fetch POA information using BGS.

This is a complex issue that will likely take awhile to get right. The dev should feel free to adjust requirements, second-guess this ticket description, etc.

`VetRecordService` will give us a POA code for a single Veteran, which we need cross reference with a list of POA names and types cached to get the human-readable name and type of the organization.

`findPOAs` on `StandardDataWebService` returns a list of all organizations that represent Veterans. We should cache this in Redis with a TTL of 24 hours, and use the cached POA list to cross-reference with the code.

We should start by using `ruby-bgs` to make manual requests to verify the endpoints we need and the information that comes from them.

We should only make the BGS requests for the POA list on UAT for now.

Get BGS documentation from Alex and Shane.

![image](https://cloud.githubusercontent.com/assets/3781835/25349654/98596038-28f0-11e7-9161-559e2411691c.png)

Acceptance Criteria:
BGS POA info should populate Certification fields on the Confirm Case Details page.

Steps to reproduce:
 - Update a Veteran's power of attorney info in BGS.
 - Start a new certification.
 - Observe that POA info from BGS is present.

**Comment by amprokop** [comment]
This is blocked on validating until alexis and artem have BGS accounts, but we can start development.

**Comment by amprokop** [comment]
Anya will do the ruby bgs issue, another dev might do the Caseflow integration.

**Comment by amprokop** [comment]
This issue needs to be updated with new info.

**Comment by amprokop** [comment]
Work closely with @amprokop on this. Blocked until @shellicious adds updated mocks and details.

**Comment by shellicious** [comment]
From a conversation with @shanear, @nicholasholtz, @amprokop, and @laurjpeterson, we've determined that BGS is not an accurate source of information about the representative. 

**Assumptions resulting from conversations:**
- If VACOLS and VBMS (which is essentially the same thing as BGS) have matching representative information, we'll assume that the representative information is correct. We'll display a confirmation message or skip to the next step.
- If VACOLS and VBMS do not match, we will inform the RO user. We will ask them to review rep info from VACOLS and VBMS and select the correct one. If neither are correct, we ask them to enter in info about the representative type and select their name (if a Service Org) from a searchable, scrollable dropdown. 
- If neither are correct and the representative type is "Other", we'll ask the user to enter in name and contact info in VACOLS manually. @cmgiven sez this happens in about .6 (or was it .06%?) of cases.
- We will not display the representative's address/contact info to the user, since we do not want them to edit it from Caseflow. We think this information can be retrieved from the OGC database behind the scenes and updated in VACOLS. @amprokop is exploring this.
- We assume that if an appeal has multiple representatives (different reps for different issues), that is has already been split into different appeals by the time certification happens. If an appeal with multiple reps makes it this far, we think that users should cancel the certification and split up the appeal, then certify the appeals separately.

cc @cmgiven, who had thoughts in the VA design meeting today.

**Open questions:**
- If VBMS/VACOLS info is incorrect, do we want users to select the name of an Agent or Attorney from a dropdown, similar to the flow for Service Organizations?
- What is an ideal UX pattern/component for selecting an Attorney name, if the current list of attorneys is in the 10s of 1000s? Is a searchable dropdown still feasible? 
- Which layout do users prefer -- VBMS and VACOLS info in 2 columns, or the info displayed as a table?
- @nicholasholtz, a thorough list of representative situations to evaluate these mocks and our assumptions against would be very helpful! Could you ask one of your contacts to provide a list?

Mocks:

Mismatching info, 2 column layout of VBMS/VACOLS info:

![new poa flow mismatching 1](https://cloud.githubusercontent.com/assets/1178390/25911691/d2c384c6-3582-11e7-9564-d472464b9394.png)

User selects "None of the above" bc both VBMS/VACOLS info is wrong.

![new poa flow mismatching 2](https://cloud.githubusercontent.com/assets/1178390/25911715/dddcd074-3582-11e7-983c-7ef6d27e50aa.png)

User selects "Service organization" and sees a searchable/scrollable dropdown of service orgs. They are able to select "Unlisted service org" as one of the dropdown choices.

![new poa flow mismatching 3](https://cloud.githubusercontent.com/assets/1178390/25911756/00c85a86-3583-11e7-8660-20b946f08af1.png)

User selects "Other" and is reminded to update name/contact info manually  in VACOLS.

![new poa flow mismatching 4](https://cloud.githubusercontent.com/assets/1178390/25911782/18dd5748-3583-11e7-918a-4cd03ab20c0a.png)

User selects "Attorney". How should this, and "Agent", behave?

![new poa flow mismatching 5](https://cloud.githubusercontent.com/assets/1178390/25911801/2d34a570-3583-11e7-823b-30bccad4359b.png)

Variation of mismatching flow, with VBMS/VACOLS info displayed as a table. I personally slightly prefer this one because it's cleaner.

![new poa flow table](https://cloud.githubusercontent.com/assets/1178390/25911826/3c402fa8-3583-11e7-9549-d50f2b33de97.png)

Possible confirmation page if VBMS/VACOLS info matches. It feels strange to make the user click through a page that only has a success message on it. I'm very open to skipping the "Confirm Case Details" step if VBMS/VACOLS info matches, and take the user straight to "Confirm Hearing".

![new poa flow happy path](https://cloud.githubusercontent.com/assets/1178390/25911855/5165c244-3583-11e7-8e51-aee3868c3ee5.png)

**Comment by cmgiven** [comment]
"Other" is the POA 0.6% of the time.

My note was that at some point, Caseflow will have to become the authoritative source of truth for POA, because it will be the only system that can associate POA on a per-issue basis. Rather than asking users to select a single POA, when in fact there could be multiple POAs, perhaps this will push us to assume responsibility for authoritative POA information.

**Comment by shanear** [comment]
@cmgiven What do you think about this statement for now:

> We assume that if an appeal has multiple representatives (different reps for different issues), that is has already been split into different appeals by the time certification happens. If an appeal with multiple reps makes it this far, we think that users should cancel the certification and split up the appeal, then certify the appeals separately.

**Comment by cmgiven** [comment]
That's news to me. VBA is splitting appeals with multiple reps? Has that been common practice? It seems counterproductive, as they'll just be merged back on the Board side.

**Comment by shanear** [comment]
According to @nicholasholtz and another attorney who I can't remember her name, yes. They also won't be merged back, this is the practice that the Board uses as well.

**Comment by shanear** [comment]
@shellicious A couple other assumptions we picked up that weren't listed:

1) The main problem is the VACOLS PoA being incorrect. VBMS can be assumed to be correct, since they are diligent to update VBMS with a new 21-22.

2) It's much less risky and difficult to update VACOLS than it is to update BGS/VBMS/CorpDB. If we accidentally update BGS with the wrong PoA it can cause lots of problems. I don't think we should touch it.

3) If the VACOLS and BGS PoA's are not the same, they will have to look at the most recent 21-22 or 21-22a to figure out whether a) the VACOLS PoA is wrong, it wasn't updated correctly, or b) the appeal truly has a different PoA from their normal PoA.

Because of the above assumptions, I think we should provide the following scenarios:
- If BGS and VACOLS match, great!
- If they differ, then we show the most recent 21-22 or 21-22a, and ask whether the VACOLS PoA should be updated to match the VBMS PoA, or to keep the VACOLS PoA as is. If they need to do anything more special, we should tell them to do it in VBMS/VACOLS for now.

**Comment by amprokop** [comment]
@cmgiven @shanear — the other attorney was Brianne Ogilvie. And yes, from our discussions, those appeals do not get merged back together, the only way to support multiple POAs is with multiple VACOLS appeals.

**Comment by amprokop** [comment]
@shellicious — Agree that the page as written looks strange, but maybe that's because we're not showing details on the page. Didn't we specifically add a documents check success page? Is this different in some other way?

**Comment by nicholasholtz** [comment]
Sent these questions to Christa Schriber, the attorney who runs the OGC Accreditation database:

•	Is there a requirement that attorneys, agents, and VSOs keep their address updated to maintain accreditation? We are looking for a source of truth for representative contact information. 
•	Who maintains control of database on the IT side? 
•	Do you know if it is possible to obtain access to the underlying data? Am I correct in my assumption that there would be no PII concerns, since the database search is public. 
•	Looking at the Excel file extract, I saw 18,000+ names; is that an accurate count of accredited attorneys and agents? How often is it updated? And generally, how often are new submissions received?

**Comment by nicholasholtz** [comment]
Christa responded: 

•	Is there a requirement that attorneys, agents, and VSOs keep their address updated to maintain accreditation? 

> We are looking for a source of truth for representative contact information. Attorneys and Claims Agents are required to send in statements of good standing (every year) and proof of their Continuing Legal Education requirements (every other year) so our addresses for active attorneys and claims agents are pretty accurate.  We are working on revising our regulations to expressly state that they must update their addresses with our office within 30 days of a change.  Also, the Data Governance Council (Susan Sullivan) is heading a VA-wide project that would identify OGC as the primary source for all contact information for representatives.     

•	Who maintains control of database on the IT side? 

> Randy Trexler and Charlotte Price

•	Do you know if it is possible to obtain access to the underlying data? 

>Yes, I believe that we can give other offices access if there is a business reason that would require the access.  Other IT systems also query our staging server so that they can stream our information into their system (e.g., EBenefits allows you to select a representative based off of information that has been streamed from OGC’s database).  

•	Am I correct in my assumption that there would be no PII concerns, since the database search is public.  

> It depends. If you are directly accessing our GCLAWS database, there are privacy concerns because all of the information that is included in our database is not public.  If you are querying our staging server, which preps the info to go public, I doubt there are privacy concerns. 
     
•	Looking at the Excel file extract, I saw 18,000+ names; is that an accurate count of accredited attorneys and agents? How often is it updated? And generally, how often are new submissions received? 

> Our list for claims agents is accurate and updated nightly.  Our list of accredited attorney includes everyone that is accredited but the list hasn’t been purged in a while. We are in the process of suspending all the attorneys that are delinquent on their CLE requirements so by the end of the year that list should be accurate too. Also, not sure if it would be helpful but we are also hooked up with gov.delivery which is a emailing services that allows us to send mass emails to all representative to update them on initiatives (e.g., we could send out an email telling everyone to make sure that their address on OGC’s public facing webpage is correct.)

She also provided an IT proposal requesting a new database for the accreditation program, but not including it here right now until I can be sure about contracting issues. 

@amprokop - figure you are going to like this stuff!

**Comment by shellicious** [comment]
Design changes I'm gonna make:
- Flesh out the "matching" situation so there is more content. We could display the representative name and type underneath the green success message so there is a point to showing this page.
- I'm gonna move forward with the table layout for showing representative info if VACOLS/VBMS doesn't match, unless someone has a strong opinion against it. 

Remaining open questions (@amprokop, @cmgiven, @nicholasholtz, @shanear, your thoughts welcome here! I will also ask this of designers in tmrw's design sync):
- If VBMS/VACOLS info is incorrect, do we want users to select the name of an Agent or Attorney from a dropdown, similar to the flow for Service Organizations?
- What is an ideal UX pattern/component for selecting an Attorney name, if the current list of attorneys is in the 10s of 1000s? Is a searchable dropdown still feasible?

Changes to explore for a future release:
- In slack, @shanear and I discussed linking to the Form 21-22 and Form 21-22A if there is a mismatch between VBMS and VACOLS in the future. For now, we suggest to users to check for the documents manually.

**Comment by shanear** [comment]
We should break this down into iterations. Updating either system will be technically challenging and fraught with edge cases. I propose:

# Iteration 1
- Get POA from BGS & VACOLS, compare them, and tell the user if they are the same or different. If they are different, warn them, and tell them to update in VACOLS if they need to and reload the page.
- Default the "Attorney, Agent, Organization, Other" radio field from VBMS.

# Iteration 2
If they are different, give the user the option to update VACOLS with the information from VBMS. There are some issues with this however.
- There isn't always a 1 to 1 mapping of VBMS PoAs to VACOLS PoAs. It seems like a lot of the time we will be setting vacols to "Other: POA Name"
- There is no easy way to get the PoA address. It looks like we may need to build a custom API for this. So for a little while, we won't be able to copy over the address, which means they will still have to copy over some PoA info manually, which sort of defeats the purpose.
- As you noted @shellicious, there isn't a good way for them to know whether to update VACOLS or not without looking through the recently uploaded documents for a 21-22 or a 21-22A.
