### ISSUE TITLE
Chromedriver 58 breaks builds

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1744]
As soon as Chromedriver 58 was published, our rspec tests started failing with the following error:

```
  1) Admin Establish Claim page
     Failure/Error: visit "/admin/establish-claim"
     
     Selenium::WebDriver::Error::WebDriverError:
       unable to connect to chromedriver 127.0.0.1:51675
     # ./spec/feature/admin_spec.rb:18:in `block (2 levels) in <top (required)>'
```

We fixed this by using the previous version of Chromedriver we were on, which is 53.
Versions here: https://launchpad.net/ubuntu/trusty/amd64/chromium-chromedriver
It would be better if we were not locked to an old version of Chromedriver. Possible solutions:

1. Wait to see if a later version just magically fixes the problem we have with 58. It's only a few hours old at this point, so as @kierachell points out, they may roll this back or patch it.
1. Dig in more to see why 58 causes a problem for us. This could involve setting up docker locally to run the Travis docker image we use and get more info.

**Comment by NickHeiner** [comment]
Lol, I did mean to fix this with #1743.

**Comment by mogrenAtWork** [comment]
This was not fixed with the latest version of Chromedriver. I suspect it will take some additional shell commands in .travis.yml to start chromedriver before the test runs. 

I'm going to wait until we have a discussion on Docker/CircleCI before sinking any time into this.

Will set up meeting with @NickHeiner and @askldjd

**Comment by mogrenAtWork** [comment]
@kierachell this is super low priority but take a look at this and see if you can figure out what's wrong. I imagine we'll have to start the chromedriver and possibly xvfb a little differently in our travis.yml with the updated version.

**Comment by kierachell** [comment]
So it's running in a docker composer now with latest chromedriver. I think this might be a Travis-specific failure:
<img width="652" alt="screen shot 2017-07-07 at 12 18 14 pm" src="https://user-images.githubusercontent.com/18075411/27981384-3c989bf8-6359-11e7-8876-fa71ee2d4a4f.png">
<img width="499" alt="screen shot 2017-07-07 at 12 20 36 pm" src="https://user-images.githubusercontent.com/18075411/27981385-3c99666e-6359-11e7-91b6-c2c617d124d3.png">

**Comment by mogrenAtWork** [comment]
Let's keep the scope of this issue focused on Travis since there is another ticket to tackle Docker. 

This is most likely due to the latest version of chromium-browser and not chromedriver itself.

Have you tried running the tests in Travis with the latest chromedriver and using the `no-sandbox` option that Alan figured out?

For reference, if you try to execute `chromium-browser` with the latest version in similar environments, you'll receive the error:
```
No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

Even though `no-sandbox` shouldn't be used for normal browsing since it is a security risk, I think it will be fine to execute our tests in until the issue is fixed with chromium. I've also tried updating to the latest version of Ubuntu to see if that would resolve it and had no luck.

**Comment by mogrenAtWork** [comment]
Welp, adding the `no-sandbox` flags didn't seem to work on Travis. I'm removing myself as an assignee and just letting Artem take over

**Comment by NickHeiner** [comment]
If we are using the latest Chromedriver on a new CI setup, then this ticket can be considered successfully resolved.

**Comment by kierachell** [comment]
Need to fix PR builder before closing
