### ISSUE TITLE
Create New EP | Regional Office to Station of Jurisidiction mapping

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#1833]
# Description
We have this RO to Station table that is used to determine the Station of Jurisdiction:
https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Dispatch/Routing%20EPs/Station%20Codes.csv

There are several ROs with missing Stations, which results in `null` value for Station when Creating New EP

- What do we do with that?
- Does this happen in prod?

## Reproduction Steps

**Scenario 1 -**

1. Go to Dispatch
1. Get a case with REGOFF = RO99
1. Process it to make a new EP
1. See `null` value under Station of Jurisdiction

**Validated in the following Envrionment(s)**
- [ ] Dev
- [ ] UAT
- [X] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Null Station]_**
![](https://cloud.githubusercontent.com/assets/18075411/25644357/71322286-2f73-11e7-9859-9186b6fa99b8.png)

# Related Issues
**_Support_**

**_Engineering_**

**Comment by cmgiven** [comment]
Has this been observed in the wild? NHA cases are special issues, so they shouldn't reach this screen.

**Comment by joofsh** [comment]
@cmgiven @kierachell I'm not aware of this occurring in production yet. Do we know of any real cases that are RO99? 

Chris, are you saying anything that is assigned RO99 is automatically an NHA case? If so, do we want to automatically flag that special issue based on the appeal's RO value? Otherwise we are depending on the user to notice and assign it the NHA special issue.

**Comment by cmgiven** [comment]
Maybe @abbyraskin can confirm?

**Comment by abbyraskin** [comment]
yeah, anything without an existing VBMS station doesn't get an EP (tier 3 special issue -- even the VBMS station listed for the PMCs is misleading because it's shared w/ the entire RO), so I don't think this would ever happen (NCA is piloting VBMS and may have a station by now, but we are not creating EPs for them).
