### ISSUE TITLE
[1] Apply style guide changes to app canvas to V2

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#1895]
Review this style guide ticket https://github.com/department-of-veterans-affairs/caseflow/issues/1677. There should be 40px padding on all sides of the app canvas. I *think* this can be accomplished just by adding the id "app-canvas". 

Acceptance criteria:
Reference the style guide ticket. We should have 40px padding on all sides of the app canvas.

**Comment by nemodjuric** [comment]
@shellicious Should/does Header.jsx with officer's name and appeal ID(see pic below) belong to app canvas? The css id used in referenced ticket is cf-app-segment--alt which makes background white. Neither our Header nor our Progress Bar components have white background.
![caseflow certification 2](https://cloud.githubusercontent.com/assets/4960030/26119009/c43468ba-3a39-11e7-91d8-8a6273943321.png)

@mmlumba @Sjones352

**Comment by mmlumba** [comment]
Ok...I'm gonna take a stab at this based on previous style guide work. Please correct me @gnakm if I'm wrong.

The term "App Canvas" contains most of the information that the user interacts with in order to go through a workflow. See this ticket for details: https://github.com/department-of-veterans-affairs/caseflow/issues/1088

The Header (containing progress bar and officer name) is _not_ a part of the app canvas. Instead, it is in the "Main Content" area of the page, which include both app canvas and outside actions: https://github.com/department-of-veterans-affairs/caseflow/issues/1087

Side note: the "Cancel Certification" and "Continue" buttons are _not_ a part of the app canvas because they are also actions. See this ticket for an explanation on actions: https://github.com/department-of-veterans-affairs/caseflow/issues/1089

**Comment by nemodjuric** [comment]
If that stands, this issue is already fixed. @shellicious 
<img width="1248" alt="screen shot 2017-05-16 at 2 27 02 pm" src="https://cloud.githubusercontent.com/assets/4960030/26122399/57e3f4c6-3a45-11e7-941f-4c9ee8c57348.png">

**Comment by shellicious** [comment]
Ah yes, @nemodjuric, looks like there is 40px of padding within the app canvas. Great! Should we go ahead and close the issue @amprokop?

**Comment by amprokop** [comment]
sounds good!
