### ISSUE TITLE
Determine frontend analytics approach (discussion on 6/28)

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1896]
What kind of analytics should we capture across our apps, and what tools should we use? We currently have Google Analytics running, but it's seldomly used at the moment and not set up with our React SPAs.

**Comment by amprokop** [comment]
The approach isn't quite clear here. Research options and start a discussion in this thread before implementation.

**Comment by NickHeiner** [comment]
Reader is having similar discussions about this as well. @abbyraskin, would you like to merge our discussion with this one? Or maybe we need to figure out what we want on our own first?

We should at least have Google Analytics. It's trivial to implement. We'll get information like page views for free. We can also track specific events, although I think a tool like Mixpanel is better suited to in-depth user tracking. I'm guessing that getting Mixpanel approved would be a huge lift, though.

Then there are things like [Snowplow](https://snowplowanalytics.com/), which are open source, and we could implement entirely on our own. That can be a *lot* of work, though, and probably is not worth the effort, given that we have direct personal access to many users.

**Comment by abbyraskin** [comment]
I'm fine with turning the conversation into a broader team meeting if we think it'll be useful. The design team is also discussing the topic this week. Is this Wisdom Wednesday Worthy? 

I think it'll depend a bit on the individual projects, but it would be great to align on Caseflow-wide goals, tools, things to avoid (e.g., storing PII in GA), and maybe some general guidelines around implementation.

**Comment by joofsh** [comment]
I think we can safely capture the product info we need within GA alone (avoiding PII). I don't see enough value in switching to something like Snowplow.

Things that I believe should apply to all Caseflow products:
- all url changes as the user navigates within mini-SPAs (dispatch is lacking this for sure)
- any sort of core submit success/failure events

Beyond that, I think what events we'll want to track will vary between products. Reader may have very specific things they want to track like how often a user selects more than 1 category filter. That's useful product information and doesn't contain any PII. For products like Certification & Dispatch that have a flow, it might be valuable to track how often users click to go back a page.

**Comment by NickHeiner** [comment]
Also, what about [Hotjar](https://www.hotjar.com)? I have no idea if it's good; I just found it from the ads on the lodash docs.

**Comment by avrildavid** [comment]
@amprokop - what google analytics do we already have in place for the Certification V2 NYRO pilot? Is there anything else that should be added?

cc @wturne @laurjpeterson

**Comment by Chingujo** [comment]
Designers have also been documenting some product questions in the following design issue, so far @abbyraskin for Reader and @shellicious for Certification. 

[#205 Product Questions for Analytics](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/205)

**Comment by NickHeiner** [comment]
Other things that may be useful, if we can use them:

* https://heapanalytics.com/
* https://www.kissmetrics.com

**Comment by Chingujo** [comment]
My two cents in case its helpful. 

[ Kissmetrics](https://www.kissmetrics.com) offers more refined digital marketing side (conversions, marketing funnels and etc). Also good for tracking paths across multiple devices (I think all of our users are desktop). When I used both it was usually google analytics to store session data and Kissmetrics to do more detailed DM analysis. 

Where most of the questions were basic user, session (URL and paths to error messages that JD mentioned), and UI data, mostly did Google Analytics into a reporting tool - thinking more downstream on how we use data - like [Analytics Canvas](http://analyticscanvas.com), [Tableau](https://www.tableau.com). Or an even more simpler heat map tool like [CrazyEgg](https://www.crazyegg.com) for UI related insights. 

[Heap](https://heapanalytics.com/) is more of an end to end solution that bypasses the above need by offering event visualization and built in reporting. Only used this for a few months but looked promising because you don't have to jump through hoops for more advanced tracking and lets you push existing dataLayers.  [Implementation](https://docs.heapanalytics.com/docs/implementation-guide) wise they give a pre built script that can be modified as necessary. 

## Free Solutions 
Not sure if pricing is a concern so the "Free" softwares so far listed would be: 

[Google Analytics/GTM](https://www.google.com/analytics/tag-manager/) - Free 
[Heap Analytics](https://heapanalytics.com/) - free for 5,000 session and 50k sessions for badge

**Comment by NickHeiner** [comment]
@Chingujo have you worked with Mixpanel?

**Comment by Chingujo** [comment]
@NickHeiner 

I have but not an expert. Sat through a demo and created tracking plans for it.  Not an expert. 

Some things to consider

Pros: 

- [ ] You can run it with Google Analytics (JS doesn't interfere or shouldn't when I did both) 
- [ ] Event tracking emphasis over page views. The nice thing is that it is pretty hands off 
- [ ] Works with Ruby (thought haven't done technical implementation)
- [ ] "Codeless tracking feature" literally just install the JS library and enabling auto track - features everything. 

Cons:

- [ ] Steeper learning curve (not the most friendly UI)
- [ ] There is a [property limit](https://mixpanel.com/help/questions/articles/are-there-any-limits-on-how-many-properties-i-can-send-to-mixpanel) for UI interactions 
- [ ] Sometimes slow 
- [ ] Not that great at tracking percentage behavioral changes

**Comment by NickHeiner** [comment]
Ok, thanks for those insights.

**Comment by NickHeiner** [comment]
The in-person discussion for this will happen directly after standup on Friday, June 9th.

**Comment by amprokop** [comment]
@NickHeiner @Chingujo — did this happen?

**Comment by NickHeiner** [comment]
Not yet. We were waiting for @cmgiven to get back. I'm going to reschedule it now that he's here.

**Comment by nickheiner-usds** [comment]
## Discussion Notes
