### ISSUE TITLE
Speed | Investigate: Almost all in-page interactions are slow when there are many documents

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1983]
All in-page interactions that use redux are delayed when viewing a case with many documents. 

Investigate ways to increase the speed -- e.g., using a new library, such as immutable-js.

**Comment by NickHeiner** [comment]
To reproduce this locally, use `reader_id2`, which has many documents: http://localhost:3000/reader/appeal/reader_id2/documents.

The problem, as @tejans24 first discovered, is that when we have many documents, the redux reducer is slow, because copying all that data takes a long time. 

Here's a [JSPerf test](https://jsperf.com/immutability-helper-v-immutablejs) for various ways we can implement the reducer:

![image](https://cloud.githubusercontent.com/assets/829827/26017234/8c51d366-3736-11e7-854e-19884e5b3fe3.png)

As you can see, by switching to ImmutableJS, we could expect a nearly 2x speed gain. I think this is a good idea. I've used ImmutableJS before and enjoyed it, and it would provide other benefits like protecting against accidental mutation errors. This will be another big PR, so we should do it with care.

**Comment by NickHeiner** [comment]
Based on the advice on [redux.js.org](http://redux.js.org/docs/faq/Performance.html#do-i-have-to-deep-clone-my-state-in-a-reducer-isnt-copying-my-state-going-to-be-slow), we may wish to investigate making our state shallower, so fewer copies are necessary.

![image](https://cloud.githubusercontent.com/assets/829827/26018326/30605c02-373c-11e7-820f-8e91013b8d5f.png)

In this example, we can see that our current approach (nested `immutability-helper`) is `96%` slower than shallow ImmutableJS.

**Comment by kierachell** [comment]
Probably related to:
https://github.com/department-of-veterans-affairs/caseflow/issues/1958

**Comment by NickHeiner** [comment]
Update on the value of flattening the data:

With #1994 applied, I've anecdotally tested the reducer update time for:

```js
      return update(state,
        {
          ui: {
            pdfList: {
              dropdowns: {
                [action.payload.filterName]: {
                  $set: !originalValue
                }
              }
            }
          }
        }
      );
```

Anecdotally, this takes around `~20-30ms`. 

If I flatten it to:

```js
      return update(state,
        {
          [action.payload.filterName]: {
            $set: !originalValue
          }
        }
      );
```

then it takes around `~2-5ms`. So speaking very roughly, we may see a `4x-10x` speedup in reducer time by flattening our data structure.

Note that if reducer time is not the hotspot, then this is not the best place to start working on perf.

**Comment by NickHeiner** [comment]
We've done a bunch of PRs for this. It is now time to re-evaluate with users to see if we need further perf improvements. If so, let's open a new ticket.
