### ISSUE TITLE
Discussion: ImmutableJS

### ISSUE THREAD

**Issue by NickHeiner** [department-of-veterans-affairs/caseflow#1992]
Reader would like to add [ImmutableJS](https://facebook.github.io/immutable-js/) as our way of storing Redux state, and anything else that makes sense. We are doing this because we are experiencing performance problems for cases that have large numbers of documents, annotations, and tags, which make the Redux state very large, which makes updating it slow. 

I did a [performance test](https://jsperf.com/immutability-helper-v-immutablejs), which showed that ImmutableJS has a nearly 10x speed gain over our current approach, immutability-helper:

![jsperf results](https://cloud.githubusercontent.com/assets/829827/26017234/8c51d366-3736-11e7-854e-19884e5b3fe3.png)

I have used ImmutableJS on prior projects and was happy with the result. ImmutableJS is widely used; it has 18k stars on GitHub. (For reference, Lodash has 23k, and it has been around much longer.)

## Pros
* Improves performance
* Removes a class of errors from accidental mutation of objects that are supposed to be immutable
* Provides a built-in data manipulation API

## Cons
* Works best with an "all-in" approach
* More conceptual overhead than native JS objects
* Data manipulation API is nice but not as powerful as Lodash

## Further Reading
* [Using ImmutableJS with Redux](http://redux.js.org/docs/recipes/UsingImmutableJS.html)
* [Pros and Cons of using Immutability with ReactJS](http://reactkungfu.com/2015/08/pros-and-cons-of-using-immutability-with-react-js/)

**Comment by askldjd** [comment]
My thoughts:

ImmutableJS comes with a lot of tradeoff. It works great for optimizing very specific scenarios, but often backfire when it leaks to other simple components. It makes code harder to read, unit test harder to write, and interoperability issue with other library (have to use `toJS()`, which is sloowww).

I think Redux covers the Cons of this library a lot better. http://redux.js.org/docs/recipes/UsingImmutableJS.html#what-are-the-issues-with-using-immutablejs

Do we have performance data to confirm that the reducer is the hotspot (usually it is the renderer)? And if the reducer is really the hotspot, is it limited to a specific action that can be optimized without Immutable?

My thought is that if only specific action and update is leading to this, optimize just that action. That usually resolves my issue 90% of the time. But if the update complexity is spread out all over state tree, then ImmutableJS is likely the right choice.

Another thought: 
Maybe just do less?

**Comment by NickHeiner** [comment]
I agree that it's important to have perf data indicating that the reducer is the hotspot. We thought we had initial data showing this, but as we've dug in more, it appears that `render` is indeed the bottleneck. I'm going to close this for now, but we may revisit later.

**Comment by joofsh** [comment]
Looks like I'm late to the party, but +1 what @askldjd said. I've generally found the performance gains from ImmutableJS to not be worth it. It adds yet another layer of abstraction to our frontend, making the barrier of entry for new engineers to the team even higher. I think we should be really careful with adding new tools like this. 

We can get larger performance gains by flattening or redux state structure, and by preventing unnecessary React renders, all without making drastic changes to our frontend architecture.

**Comment by NickHeiner** [comment]
For what it's worth, my perf tests suggest that moving from immutability-helper to ImmutableJS will give approximately a 7x improvement, whereas flattening the redux structure and staying on immutability-helper will give close to a 2x improvement. So I don't agree that we can get larger gains by flattening the redux shape as opposed to switching to ImmutableJS, but I agree that focusing on wasted renders is the place to start.

![image](https://cloud.githubusercontent.com/assets/829827/26128965/527c19d4-3a5c-11e7-9618-df200bde2543.png)

**Comment by askldjd** [comment]
The issue is already closed, but the topic of performance always interest me. Just throwing out my thoughts on this.

The benchmark above highlights the strength of ImmutableJS. It is really really good at doing immutable updates. But whenever there is a data structure change, there is usually a trade-off. For immutable, in addition to programming complexity, you pay for it at access time.

Here's my highly bias example.
![image](https://cloud.githubusercontent.com/assets/3258724/26158108/dc646750-3ae8-11e7-84d6-c92d820f6783.png)

Native object wins hands down since naive property access is close to free. Of course, the benchmark above is unrealistic since the application uses a mixture of read and writes. However, just highlighting updates alone is also unrealistic. 

I have been bitten by [Amdahl's Law](https://en.wikipedia.org/wiki/Amdahl%27s_law) many times. The lesson I have learned is that narrow benchmark is not very useful in practice. 

Just like we have agreed, hotspot should be the _only_ area of focus.
