### ISSUE TITLE
Reader | Welcome gate

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#1999]
## Description
This is operation, **"Let's get rid of URL hack!"** Currently users have to type in the Veteran ID number in the URL in order to access Reader. Let's give them a better experience!

### Welcome message
- [ ] Welcome message `h1` from [styleguide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography)
- [ ] Body message in lead paragraph
[Text styling in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography)
- [ ] Width of "new" button should match "continue" button
- [ ] Add link to Reader "Help" page
- [ ] URL for welcome gate should be at /reader/appeal
- [ ] All text must have [character width](https://github.com/department-of-veterans-affairs/caseflow/issues/2116) of 70 rem 

### Table
- [ ] [Use table from style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#tables)
- [ ] Work assignments should be in `h2` from [style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography) and sentence cased
- [ ] Provide the columns with the following headers: 
  - **Veteran** - Veteran name
  - **Veteran ID** - Veterans ID number
  - **View claims folder** - Button to open case file _[NOTE: copy differs from mock]_
- [ ] If case has already been viewed by that user, show [secondary button](https://standards.usa.gov/components/buttons/) styling with word "Continue". If case in brand new, show `primary` button with word "New"

## Mockup
![image](https://user-images.githubusercontent.com/13420618/27557976-9ee0e654-5a89-11e7-9203-326ddf5c07cf.png)

Note: Work assignments 

## Copy 

_NOTE - copy below is more accurate than copy in the mock!_

Title: Welcome to Reader!

Body: Reader allows attorneys and judges to review and annotate Veteran claims folders. Learn more about Reader on our Help page.

## Related Story
https://github.com/department-of-veterans-affairs/caseflow/issues/2342

**Comment by gnakm** [comment]
Can we get the FAQ in for Milestone 2?
What will be the requirement for entering ID?

**Comment by gnakm** [comment]
Previous AC:

## Description
Currently (for the pilot) users have to type in the Veteran ID number in the URL in order to access Reader. This is prone to error and quite frankly, annoying. Let's give them a better experience!

Operation let's get rid of URL hack!

## AC
- [ ] Verify that entering the Veterans ID in the search box will enter into Reader.

## Mockup

![image](https://cloud.githubusercontent.com/assets/13420618/26074270/1d0801f6-397f-11e7-9548-3eb2df06a794.png)

**Comment by gnakm** [comment]
@mdbenjam Could we show users what cases they've already opened vs. new ones that came in? Trying to understand the level of complexity this may entail. 

![image](https://cloud.githubusercontent.com/assets/13420618/26422720/fe8f1dba-4098-11e7-9f35-daf7dbba2616.png)

**Comment by mdbenjam** [comment]
@gnakm I think that's doable. We'd have to create new DB entries, but that could lead to some interesting data so I think it's worth doing.

**Comment by mdbenjam** [comment]
Two notes.
1. To the dev who works on this: I'll have a DasRepository merged today that you can use to get the current cases assigned to a user.
1. @gnakm I think it's best to remove the issue/number of documents columns for now. The issues should be easy to add. I can work on that when I get back from the offsite. The number of documents should probably wait until we've integrated with eFolder Express.

**Comment by gnakm** [comment]
@mdbenjam Sounds good. 

Dropping this here for future: 
![image](https://cloud.githubusercontent.com/assets/13420618/26698207/0c19f6a8-46e3-11e7-850b-e740c7393586.png)

**Comment by abbyraskin** [comment]
@gnakm i can't capitalize Attorney/Judge. it hurts my soul too much.

**Comment by abbyraskin** [comment]
also, I can take point on updating FAQs with @wturne. 😄

**Comment by abbyraskin** [comment]
@mdbenjam to what extent does including the search functionality here increase the scope of this ticket (is it something we can reuse from another application?)? i'm wondering if we should break it out as its own ticket or if you think it makes sense to develop all of this at once.

**Comment by gnakm** [comment]
@abbyraskin I vote that we make a separate issue for the top as well. I beefed up the AC for the search part at the top. 

@mdbenjam Also, could you tell me some use cases of errors for searching ID number? The :tumbler_glass: Check list told me to check in with you about this 😛 
![image](https://user-images.githubusercontent.com/13420618/26887738-d0e553a0-4b76-11e7-8861-56314b8077ad.png)

**Comment by nicholasholtz** [comment]
For the copy, you might be better off going with "claims folder" rather than "case file". That is the language people use, anyway. But I defer to all of you wise folks.

**Comment by abbyraskin** [comment]
Thanks, let's go with that if @gnakm is okay with it! (I think I've had "c-file" engrained in me since my very formative eFolder Express days.)

It looks like the AC could use a little updating in general, as we removed some of the columns. I will tidy it up and post the old AC here. (note there will be small copy changes that differ from mocks @mdbenjam)

**Comment by abbyraskin** [comment]
(Old AC for reference)

## Description
This is operation, **"Let's get rid of URL hack!"** Currently users have to type in the Veteran ID number in the URL in order to access Reader. Let's give them a better experience!

## AC
### Welcome message
- [ ] Welcome message `h1` from styleguide
- [ ] Body message in lead paragraph
[Text styling in style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#typography)
- [ ] Add link to FAQ page https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/reader/help#faq

### Search
- [ ] The [style guide search component](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#search) is currently being added to the style guide. Incase it's not ready on time, here is the [search issue](https://github.com/department-of-veterans-affairs/caseflow/issues/1423) for it. 
- [ ] When a user enters the 9 digit Veteran ID, it should go straight to the Veteran's case, Documents List page.

### Table
- [ ] [Use table from style guide](https://dsva-appeals-certification-dev-1895622301.us-gov-west-1.elb.amazonaws.com/styleguide#tables)
- [ ] Provide the columns with the following headers: 
  - **Veteran** - Veteran name
  - **Veteran ID** - Veterans ID number
  - **Issues** - Number of issues in the case
  - **Documents** - Number of documents in the case
  - **View case file** - Button to open case file
- [ ] Show cases in the order of when it was assigned to user (newest on top, oldest on bottom)
- [ ] If case has already been viewed, show [secondary button](https://standards.usa.gov/components/buttons/) styling with word "Continue". If case in brand new, show `primary` button with word "New"


## Mockup
![image](https://user-images.githubusercontent.com/13420618/26882444-69f1d712-4b68-11e7-8271-edf9f105a600.png)


## Copy 

NOTE - copy below is more accurate than copy in the mock!

Title: Welcome to Reader!

Body: Reader allows attorneys and judges to review and annotate Veteran case files.
Search for a Veteran ID below to get started.

Learn more about Reader on our FAQ page.

**Comment by abbyraskin** [comment]
Search story tracked in https://github.com/department-of-veterans-affairs/caseflow/issues/2342

**Comment by gnakm** [comment]
@mdbenjam Sorry for getting back to you late on the comment width. I added this to the AC above - Width of "new" button should match "continue" button. Basically the padding on the button is correct according to style guide but I'm going to add when buttons are STACKED, they should all be same width. It's an exception we're going to have to add.

**Comment by kierachell** [comment]
### AC is missing the URL for the welcome page: `reader/appeal`

### Going back from other pages can result in a beautiful JSON:
![jsonhistory](https://user-images.githubusercontent.com/18075411/27483538-ca4cb4f0-57f3-11e7-9c55-3abe42fee3ef.gif)

**Comment by mdbenjam** [comment]
JSON is interesting, let me look into that.

**Comment by kierachell** [comment]
## Bad time with the header
![whatsupwithheader](https://user-images.githubusercontent.com/18075411/27489404-706c47e2-5808-11e7-80ce-5cecde9cfc60.gif)

## It's not exactly loading new documents for a different case if the previous one failed

**Comment by mdbenjam** [comment]
Header is a known limitation of doing the page layout in Rails not React. Here is the ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/2422. I'll look into two and three.

**Comment by mdbenjam** [comment]
Additional error. Tried in Prod and Jane Nicholas couldn't access her cases. There were two reasons for this:

1. We are not saving VACOLS user ids in our database, but assumed we were. Therefore we were querying with a null user which turned up nothing.
1. We were looking for when the decision signed date was null, instead we should be looking for when the received date is null.

**Comment by kierachell** [comment]
### Show cases in the order of when it was assigned to user (newest on top, oldest on bottom)
How can one tell? Does this even matter?

### If case has already been viewed by that user, show secondary button styling with word "Continue". If case in brand new, show primary button with word "New"

Does not work when using browser's back button:

Only works by clicking the logo.
![backtoappeals](https://user-images.githubusercontent.com/18075411/27648592-0f8b9d1c-5bfd-11e7-89d7-71db27194670.gif)

**Comment by abbyraskin** [comment]
@mdbenjam @kierachell I will take out the AC about ordering -- we can explore this in a future enhancement ticket after we test this with users. re: your second point, ideally this would work with the browser's back button as well.

**Comment by kierachell** [comment]
**PASSED**
I guess

**Comment by nicholasholtz** [comment]
@abbyraskin I know this is closed, but wouldn't the correct order be based on currently-assigned due dates? (which are subject to revision, of course)

**Comment by abbyraskin** [comment]
technically it's random for now, but I think that's a good approach.
