### ISSUE TITLE
Investigate eFolder Express integration

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2091]
- Begin investigating eFolder Express integration (with Alex/Shane?)
- Write and share tech spec with team
- Break into smaller tasks for next sprint(s)

**Comment by shanear** [comment]
A couple other advantages of using efolder express is that we get all the permissions logic & sensitivity checking which is nice.

**Comment by shanear** [comment]
I think the TLDR here is (correct me if I'm wrong, @mdbenjam):

**We need to support downloading all the documents in a folder before-hand asynchronously for a variety of reasons. How should we do this?**

Options:
1) Use eFolder Express
2) Do it in Caseflow

We should separate this decision from the decision on how to integrate with DAS. The integration with DAS just complicates the decision.

**Comment by shanear** [comment]
I'm very partial to option 1 for the following reasons:

a) We don't need to duplicate logic. There is a ton of permissions logic and integration logic that we can avoid.
b) This allows us to possibly move eFolder Express front end into Caseflow (or into its own repo?). Which can be the first step in potentially splitting our front-end and back-end over an API. It also allows us to consolidate our React styleguide stuff?

Notes on your tech spec from option 1:
1) We should follow the JSON API spec. We should also stick to RESTful routes too  (ie: `POST /documents` instead of `POST /documents/start_and_create`)

2) We should stream the document content directly from eFolder Express to the Reader front end, instead of forming an awkward (and potentially error prone) 3 way integration with eFolder Express, Caseflow, and S3.

**Comment by mdbenjam** [comment]
Tech spec has been merged: https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md. Thanks for everyone's feedback!
