### ISSUE TITLE
Document List | Make Search Great Again

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2171]
## Searching by date
![datesearch](https://cloud.githubusercontent.com/assets/18075411/26508329/5e878b5a-4222-11e7-973d-0d56bb629177.gif)

## Tokenization between spaces is awkward; why not `,` or `;` or `/`?
![searchspace](https://cloud.githubusercontent.com/assets/18075411/26508342/65f46480-4222-11e7-87c3-9c260b1aa311.gif)

## Search empty state has `.` in the `"` marks.
<img width="60" alt="screen shot 2017-05-26 at 2 48 57 pm" src="https://cloud.githubusercontent.com/assets/18075411/26508376/7830ba68-4222-11e7-852a-3a406f67f1ef.png">

## Expand all disabled on empty space?
<img width="1115" alt="screen shot 2017-05-26 at 2 49 51 pm" src="https://cloud.githubusercontent.com/assets/18075411/26508418/a6a126f8-4222-11e7-8065-d9a056f0f4b4.png">
<img width="1137" alt="screen shot 2017-05-26 at 2 50 01 pm" src="https://cloud.githubusercontent.com/assets/18075411/26508417/a69eb170-4222-11e7-93a1-4494aea2e9c3.png">

**Comment by gnakm** [comment]
@mdbenjam So, Artem has a lot of concerns. 

- We already have an issue for searching by date: #1789
- `,` , `;`, `/` - I think this sorta goes hand in hand with the form 9 giphy above. 
  Currently, our search is "or" but it's throwing users off. Heard about 2 other times a user typed in "form" and when they typed "9," more information showed up because it picked up on receipt dates. I don't know if we explicitly said this but I think we should change our search to and string.
- Empty state " ." now in #2174
- We should disable expand/ collapse all when there aren't any comments in all situations.

**Comment by gnakm** [comment]
@abbyraskin I think we should close this issue because all of the 4 concerns above are now being resolved or talked about in other tickets. If you agree, please close!

**Comment by gnakm** [comment]
Actually, reopening it again because we should make sure that the "and" search issue is neatly written out.

**Comment by abbyraskin** [comment]
"and" is documented in #2231 fyi
