### ISSUE TITLE
Rename all instances of “UnconnectedComponent” to just “Component”, and `export default` those classes

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2208]
This is an example of our currently preferred style.
```
export class Dockets extends React.Component {
…
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Dockets);
```

**Comment by astewarttistatech** [comment]
**PASSED**

Env: Local
Browser: Terminal/Sublime

Steps to Validate: 
1. Open the Caseflow app on your local machine
2. In Sublime search the whole Caseflow folder for "unconnected" 
3. When no results show, search "export default" 
4. For each of the results see that there is just the component instead of unconnected (component)
