### ISSUE TITLE
Documents List | Comments filter

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#2229]
When viewing the documents list, I want to quickly filter to show/expand only those documents with comments, so I can read through all my comments at once.

## AC
- Add new toggle feature that allows users to toggle between all documents and all comments
   - Documents: Should show everything within filtered view. 
   - Comments: Should show all comments expanded and filtered only. 
- The `ToggleButton` component should be used, as listed in the Style Guide
- The length of each toggle button should be the same 
- There should be 20px of space between Show all: and toggle
- Toggling between documents and comments works as a filter. It works as an AND with the categories and issue tags filters.
  - Filters should apply to both views
  - Search should apply to both views
  - When toggling back to all documents after have been on comments view, we should collapse the comments. 
- When comments = empty state, filtering by message should mention comments. Related: https://github.com/department-of-veterans-affairs/caseflow/issues/2496
Example:
![image](https://user-images.githubusercontent.com/13420618/27871962-4d01f24a-6175-11e7-9058-728b3bd341a9.png)

## Mockups
![image](https://user-images.githubusercontent.com/13420618/27708139-dcb6f848-5ce5-11e7-9218-2faa36d81f6a.png)

![image](https://user-images.githubusercontent.com/13420618/27708143-e55ff404-5ce5-11e7-9065-792e3dcbc534.png)

## Related
- Style guide ticket for new toggle button #2478
- #2496

**Comment by abbyraskin** [comment]
@gnakm it seems like we should combine the expand all with comment filtering, rather than having them disjointed; I don't see a use case for using one but not the other (and i think the expand all will be more useful if it's limiting the view) - thoughts?

**Comment by abbyraskin** [comment]
this also gives us an opportunity to clarify the label of the button, since i think there's some confusion

**Comment by gnakm** [comment]
@abbyraskin I totally agree with this. The button is too detached and missing a function. I think we should decide on design end of this week as we synthesize findings and define our product more this week.

**Comment by gnakm** [comment]
@abbyraskin For our discussion later

1. View all comments tab

![image](https://user-images.githubusercontent.com/13420618/27226165-a8ffac2c-526b-11e7-8c62-13c2b0bf8f09.png)

![image](https://user-images.githubusercontent.com/13420618/27226173-b246bee2-526b-11e7-8954-bca1af62d386.png)

![image](https://user-images.githubusercontent.com/13420618/27226255-1562ae00-526c-11e7-8e0b-19b83b51a695.png)

I added a header (no ticket for it yet but if things start getting very gnarly at the top, how about we use the accordion as header? I'm going to discuss this with Lara right before our meeting because I know she wants to add a global Veteran name and ID button at the top.

We also need to talk about how search will work for both filters. I'm inclined to say might be different for each section after this pilot. Would love to know your thoughts. 

2. Expand all button turns into a filter-esque button 

![image](https://user-images.githubusercontent.com/13420618/27226282-35554b1e-526c-11e7-876f-018f98060e88.png)

![image](https://user-images.githubusercontent.com/13420618/27226270-25ff42f0-526c-11e7-9477-6182432a552c.png)

Note for both:
We talked about maybe calling comments notes instead. I added it in the mocks but we can talk about this. Also, added back # of comments and the word notes to bring a little more visibility to the feature to expand individual comments.

**Comment by gnakm** [comment]
@abbyraskin This is combo of what we played with a little before and your suggestions: 
- Moved search to top right corner
- Put process # of documents where search used to be
- Put show all buttons on top

Question for us -- do we want to give users the option to expand all AND filter in any order? The invision link has it so that you can only expand all when you filter comments only. 

[Invision Link](https://va-gov.invisionapp.com/share/BNC8AEDZT#/screens/239709874) to help visualize this interaction

## Mockups
No filter
![image](https://user-images.githubusercontent.com/13420618/27410421-79e95336-56b5-11e7-9df9-08d547c4ab87.png)

With notes filter on
![image](https://user-images.githubusercontent.com/13420618/27410426-83a20c6a-56b5-11e7-8780-b119454a1d72.png)

With note filters on and expanded
![image](https://user-images.githubusercontent.com/13420618/27410434-8fae7034-56b5-11e7-87ba-a94923b8dc24.png)

**Comment by gnakm** [comment]
In Nick's Voice, "meEeegaa filter."

Abby/ Gina convo:

With the filter alert coming up each time, we thought it was jarring and redundant. It gave us a space to explore what a mega filter would look like. 

- allows the combination of seeing all filter-able options including 
- It might be a better alternative to the filter + expand all situation
- It helps separate from the search box yet easily show users the relationship between what's being searched and what was filtered. 

![image](https://user-images.githubusercontent.com/13420618/27485672-a896e508-57fb-11e7-9c2d-2373f665ccd7.png)

**Comment by abbyraskin** [comment]
We also probably need an empty state if there are no documents with notes.

**Comment by gnakm** [comment]
@abbyraskin Agreed on explicitly calling it out. 

Toggling between documents and notes works as a filter. It works as an AND with the categories and issue tags filters.  

- Filters should apply to both toggle views
    - ex. The common super user use case we saw was those who filtered categories first and then clicked the expand all buttons. 
- If you search, it should be applicable to both toggle views
- Empty state issue here: #2490

**Comment by gnakm** [comment]
^ For anybody reading this thread, we've decided to stick to comment because it's a bigger scrub to change everything and wasn't hi-priority or urgent enough to change on UX side.

**Comment by abbyraskin** [comment]
@gnakm I'm confused about last AC: "When comments = empty state, show all documents and make sure that filtering by text mentions comments."

**Comment by gnakm** [comment]
@abbyraskin I updated the AC. Basically even if there aren't any comments, we should still have in the filtered text message that it is being filtered by comments.

**Comment by NickHeiner** [comment]
![image](https://user-images.githubusercontent.com/829827/28547594-97cc6012-709d-11e7-8b54-0a968a74850d.png)

@gnakm when you're in the Comments view, should the user still be able to click on the comments indicator (the `4 v` in this screenshot) to expand / collapse comments for an individual document?

**Comment by NickHeiner** [comment]
If a user has comments expanded for a doc when in the Documents view, and then they switch to the Comments view, then back to the Documents view, do we want the comments for that doc to still be expanded?

**Comment by NickHeiner** [comment]
If #2496 is not done by the time I'm ready to merge this, then that ticket can include updating the filtered-by message based on whether the user is on Documents or Comments.

**Comment by NickHeiner** [comment]
> There should be 20px of space between Show all: and toggle

For some reason, `18px` is very easy to make look good, but `20px` will require more effort. Can I just make it 18? :smile:

**Comment by NickHeiner** [comment]
> When comments = empty state

I am not sure what this means.

**Comment by gnakm** [comment]
@NickHeiner 
1. 18px is fine. 
2. When there are 0 comments but the toggle is on comments, the little filter message below the search bar should still list comments.

**Comment by NickHeiner** [comment]
I don't see the "{count} documents" message in the mocks. Is that going away?

![image](https://user-images.githubusercontent.com/829827/28575357-afbd20f4-711e-11e7-9e9f-97a88bba5c76.png)

**Comment by gnakm** [comment]
1. The count message is being moved to the top on the right side of `h1`
The format has also changed so that it shows x out of y documents viewed. 
![image](https://user-images.githubusercontent.com/13420618/27708143-e55ff404-5ce5-11e7-9065-792e3dcbc534.png)


2. > If a user has comments expanded for a doc when in the Documents view, and then they switch to the Comments view, then back to the Documents view, do we want the comments for that doc to still be expanded? 

I think when toggling back to all documents after have been on comments view, we should collapse the comments.

**Comment by astewarttistatech** [comment]
**PASSED**  I don't know if this has made it passed @gnakm 's eyes for the UI but tagging her in here as reference

Env: UAT
Browsers: FF and Chrome 

Steps to Validate: 
1. Access Reader for a test veteran 
2. Toggle the "Documents | Comments" button
3. Verify that the results filter out based on comments or shows all documents if "Documents" is toggled on. 

Screenshots: 
![readerheading](https://user-images.githubusercontent.com/23038505/28781181-392e48ec-75d7-11e7-890f-a9b992785b88.gif)

**Comment by gnakm** [comment]
@astewarttistatech yup! I've been checking and looks good!
