### ISSUE TITLE
eFolder Express Integration | Document Download Job

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2338]
Read the full eFolder Express integration tech spec [here](https://github.com/department-of-veterans-affairs/appeals-pm/blob/master/caseflow/tech_specs/prefetching_files_for_reader.md).

We need a job to download all the relevant documents for a given case at night, so they are ready to be worked in the morning.

# AC
1. Verify 1500 documents assigned to Reader users are loaded into the S3 bucket for Reader at 9PM
    - The job will finish fetching all of the docs for the appeal it's currently processing and then check to see if it's above the limit of 1500 docs. The final total of docs downloaded may be over 1500
1. Job outputs the results (i.e. number of documents successfully retrieved, failed and number of appeals that failed) to the value from the environment variable `SLACK_DISPATCH_ALERT_URL` (this is the same location in Slack that Dispatch uses)

**Comment by mogrenAtWork** [comment]
Waiting until #2511 is complete to be able to test load of query and make sure we don't bring down VACOLS the first time this is run

**Comment by mogrenAtWork** [comment]
We have 25 users currently with a rough average of 5 assignments per user. Worst case scenario could be that each assignment contains 200+ documents, so 25 * 5 * 200 = 25,000 documents to upload. We're about to open this up to 50 more users, which would then result in an initial load of 50k docs the first night the app is available to them. Then when we release to everyone at BVA this puts us at 500+ users, creating an initial batch of 500k docs for the first run after it's available to these users.

We could change this to pre-fetch 5 users documents concurrently. 

We'll need to execute this to see how long execution time is before creating a scheduled job. If the first job takes over a day to complete, the next job will begin execution and lead to a race condition.

**Comment by mogrenAtWork** [comment]
Artem ran some rough load tests for downloading documents in UAT and each document averaged 1.26 seconds to download. 4432606 documents were download.

From this, it makes more comfortable attempting to download 1500 each night and having it finish before midnight (when the other jobs will run)

**Comment by kierachell** [comment]
@mogrenAtWork 
Can you verify that https://github.com/department-of-veterans-affairs/caseflow/blob/0bd8960c2109fe69ef45801008c3f54fc8daf87c/config/sidekiq_cron.yml#L36 passes `lmit=1500` and not a hash.
Seems to have cause some Sentry alerts because it's comparing Fixnum to Hash in `perform`

**Comment by kierachell** [comment]
@mdbenjam 
### This is a lot of documents to download, how to handle failures?

- It seems like the job assumes that `vbms_id` aka `BFCORLID` is a valid way to look up the files. Do I understand that correctly?
```
<ns4:EFolderFault xmlns:ns4="http://service.efolder.vbms.vba.va.gov/common"><ns4:code>EFSERR1017</ns4:code><ns4:message>File number or SSN does not exist within the system.</ns4:message><ns4:type>Business</ns4:type><ns4:uuid>0461b4cc-6631-4451-8cb8-fc5d1aafaf7a</ns4:uuid>
</ns4:EFolderFault></detail>
</env:Fault></env:Body>
</env:Envelope> --uuid:f1b0a1a9-58ba-42fd-8d7e-17278939dde3--, request=#<VBMS::Requests::FindDocumentSeriesReference:0x0055e18a101e88 @file_number="224889050">
```
- What happens if it is not a filenumber/ssn and it might need to be checked with BGS? (look up filenumber by SSN?)
- Should the job "fail fast" or swallow some errors? the Above error halts the whole job and sends it into a retry loop

**Comment by mogrenAtWork** [comment]
@kierachell this job will change now that we have the eFolder API to pull from. 

Does eFolder have the same problems as 1 + 2 mentioned above?

To your remaining points:
- The job should fail fast. Since we'll be using eFolder, what we can do is keep track of failed requests. If 5 or so consecutively, we can stop the job
- The previous point applies if VBMS is down. If we get errors from eFolder because VBMS is down, we'll stop

I'll make the updates, thanks for the thorough testing!

**Comment by kierachell** [comment]
### BFCORLID != SSN
```
    BFKEY    SNAMEF SNAMEL       SSN SNOTES        SADDRST1 SADDRST2 SADDRCTY SADDRSTT SADDRCNTY SADDRZIP  BFCORLID BFCORKEY
1 1998666 FREDERICK  CASEY 046366366   <NA> 25 Knorr Avenue     <NA>  Seymour       CT      <NA>    06483 24344498C CK816338
  BFATTID REPKEY REPTYPE REPSO STAFKEY SATTYID SLOGID SUSRPW
1    1191   <NA>    <NA>  <NA>  MCELLI    1191 MCELLI   <NA>
```
- So what I am seeing is that you're looking up Documents by sanitized BFCORLID and not SSN?

**Comment by kierachell** [comment]
So what I am seeing is that `FindDocumentSeriesReference` fails fast, but `GetDocumentContent` keeps going
```
[ActiveJob] [RetrieveDocumentsForReaderJob] [0c151aa4-2c18-4dcc-9507-15469e1ad41c] [2017-07-26 10:45:28 -0400] Performed RetrieveDocumentsForReaderJob from Sidekiq(default) in 97902.29ms
=> true
```
It _does_ run tho...

**Comment by mdbenjam** [comment]
Probably just need to strip the ending character from BFCORLID. @mogrenAtWork look at the appeal.sanitized_vbms_id function

**Comment by mogrenAtWork** [comment]
Blocked by https://github.com/department-of-veterans-affairs/appeals-deployment/issues/732

**Comment by mogrenAtWork** [comment]
This will need to be refactored once efolder is enabled. I'll need to provide the user on the query to efolder now as well and disable document fetching since efolder will handle that automatically.

**Comment by mogrenAtWork** [comment]
It also is failing because it's picking up Appeals without VBMS IDs set. I don't know if that's a problem with this job or a problem with our prod data.

**Comment by kierachell** [comment]
So I double checked and the job is definitely generating Appeals without VBMS IDs when it looks up case assignments.

- I updated all Appeals to have VBMS ID in our database about 1 min before the job ran for 2 days in a row
- The job still exploded with missing VBMS ID.
- Check how you are creating the Appeals models. @joofsh made it so that calling `vbms_id` method will pull the BFCORLID from VACOLS now.
- It is possible that you're calling `sanitized` method from the start which might not use the new `vbms_id` getter.
- Also check how you are creating `case assignment` Appeals - `find_or_create_by_vacols_id` is the _only_ method that creates them correctly
- One problem with it is that it might try to insert non-unique Appeals, so double check that (I had UniqueViolation errors pop up once or twice on the welcome page)

**Comment by mogrenAtWork** [comment]
Thanks @kierachell!

**Comment by kierachell** [comment]
yeah,sorry I was looking at the older code. :(

**Comment by mogrenAtWork** [comment]
Blocked by #2804

**Comment by kierachell** [comment]
**PASSED**

<img width="526" alt="screen shot 2017-08-14 at 11 56 33 am" src="https://user-images.githubusercontent.com/18075411/29280008-a4303626-80e7-11e7-8b3b-3a08bce67110.png">
