### ISSUE TITLE
Rspec doesn't pick up the latest build

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2467]
Popular belief has it that rspec often doesn’t pick up the latest local build unless you manually run `npm run build`.

NTH 2017 commented, "Yes."

He continued on:
```
NTH 2017 [4:22 PM] 
The Capybara tests are supposed to rebuild everything if necessary, but that does not always seem to work.
```

**Comment by joofsh** [comment]
I believe this is due to running hot module reloading. In HMR mode, the compiled assets are served from memory. Before that, running `npm run dev` was watching for file saves and recompiling constantly. That way when running tests, you always got the freshest assets. 

Compiling the assets before every test run is slow, so in order to avoid slowness we added a caching mechanism here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/spec/rails_helper.rb#L157 . This assumed that if assets existed at all in that location, then we were running `npm run dev`. 

The quickest fix is simply removing this conditional, but this will slow does test runs locally & dev iteration.

**Comment by alisan16** [comment]
Closing this issue as it is now obsolete. Will re-open if the issue comes out again.
