### ISSUE TITLE
SPIKE | Investigate a strategy for logging/saving writes to VACOLS and other integrations to maintain data integrity

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#2580]
## Connects:
- https://github.com/department-of-veterans-affairs/appeals-deployment/issues/691
- https://github.com/department-of-veterans-affairs/caseflow/issues/2268
- https://github.com/department-of-veterans-affairs/caseflow/issues/2292

## Problem

There is a possibility of data corruption when we deploy something buggy. This data corruption can propagate quickly down the Appeal stream and affect real lives.

1. We don't know what was in VACOLS before we wrote to it
1. We don't keep a permanent-enough track of exactly what we wrote
1. We don't keep track of _when_ we start writing new data. We have this manual entry but that's kinda lame: https://github.com/department-of-veterans-affairs/caseflow/blob/master/docs/data-changelog.md

We need a strategy to monitor what we write that is better than what we currently have (`Rails.logger`).

## Considerations

- Time series DB?
- Speed? Adding a read for every write is expensive, yes.
- @cmgiven any thoughts?

**Comment by NickHeiner** [comment]
Proposed solution from our discussion in #2621: create a table that provides a complete audit log of all writes to VACOLS. Columns could include:

* Timestamp
* App doing the write (eg Reader, Certification, Dispatch, Hearings Prep)
* Optionally another string label for the app to document why the write is happening, if it's otherwise ambiguous.
* Previous value
* Next value

**Comment by NickHeiner** [comment]
Closing in favor of #2681.
