### ISSUE TITLE
Change VACOLS login form to have example text

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#260]
to suggest what to enter (`RO99` or something)

**Comment by paultag** [comment]
@maryannbrody mentioned ghost text wasn't great; so, use an `e.g.`, I think?

**Comment by plusjeff** [comment]
Overlaps with #259 and #275 .

**Comment by maryannbrody** [comment]
@paultag @plusjeff I don't think we need this -- changing label to "VACOLS Login ID" should do the trick.  What we do need is for the field to be selected on default when a user opens the page.

**Comment by plusjeff** [comment]
Placeholder text won't work since the username field is autofocused at load. Placeholder text does not display when a field has focus, so this will not show up when the user arrives on the page.

**Comment by plusjeff** [comment]
![image](https://cloud.githubusercontent.com/assets/950486/11566983/d8421d94-99b2-11e5-8208-0dcbaf0877ab.png)

**Comment by plusjeff** [comment]
Packged into PR #275

**Comment by webinista** [comment]
I know you already fixed this @plusjeff, but we can use `placeholder` attribute for each `input`. Guides both sighted and assistive tech users. Clears when the user begins typing, rather than on focus. (And we can change the opacity of the placeholder text to hide it on focus for sighted users.

(Can make this a lower priority fix to do later, since we have a solution in place though.)

**Comment by paultag** [comment]
Lower priority on this SGTM;, want to be the PR reviewer for #275, @webinista ?

**Comment by webinista** [comment]
Sure.

**Comment by plusjeff** [comment]
@webinista Good suggestion! Wasn't thinking from that angle. Will do.

**Comment by plusjeff** [comment]
Added #280 for the password placeholder.
