### ISSUE TITLE
Talk with Jed about fixing the Caseflow seam 

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#261]
I think adding `caseflow_start` and `caseflow_finished` to VACOLS is what we need as a common ground with VACOLS

**Comment by paultag** [comment]
cc @plusjeff

**Comment by paultag** [comment]
We had over 50% fall into this, since VACOLS sets the cert date and friends before passing to Caseflow, and users who don't want to actually upload after looking at the form 8 (or close out of Caseflow unintentionally, or have their machine crash) put the case into the wrong state

**Comment by paultag** [comment]
(I've manually fixed those records)

**Comment by plusjeff** [comment]
After discussing with the team, the best solution is that VACOLS will not set the certification date for cases that **are paperless** and **belong to a Caseflow enabled RO**. This will prevent things from getting certified prematurely, but also allow them to remain in the workflow report that triggered someone to try to certify it. Additionally, it means that users can always return to Caseflow since the Complete Form 8 button will never be unintentionally disabled.

@JedWagner is heroically making the change in RO VACOLS Dev and will e-mail the DS team once complete. @paultag or I can test the change in conjunction with Caseflow after that.

**Comment by paultag** [comment]
Jed sent me an email saying it's all set, this is great!

**Comment by plusjeff** [comment]
Testing this out now

**Comment by plusjeff** [comment]
@paultag Tested it out and it works! Thanks @JedWagner !

Closing this issue.

**Comment by paultag** [comment]
:us:
