### ISSUE TITLE
[Friday 7/21] How to get more realistic VACOLS data in UAT

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2619]
When working on the welcome gate ticket for Reader we had some problems with getting accurate data to test with. We had assumptions based on what we thought the data should look like, I asked Artem to create data based on these assumptions and the tickets passed. However, they failed in prod, because the data was not what we expected. I would like to explore how to migrate scrubbed data from Prod to UAT. It would reduce churn, and make sure we can trust our testing environment.

In particular we _thought_ we needed users with cases assigned to them in DAS. But we're not sure which user to query etc. If we had things more in sync we could look up a known user id and compare the results of our calls with what we expect for that user.

**Discussion points**
- Have other people experienced problems like this?
- Is this worth pursuing?
- I don't have a good sense of how difficult this will be and wanted to know if people have experience with things like it.

**Comment by kierachell** [comment]
## VACOLS data
  - Our VACOLS data is fine it is pretty darn realistic compared to many other situations you might find yourself.
- Currently I am working on https://github.com/department-of-veterans-affairs/appeals-deployment/issues/635 which will help resolve the issue - we will be able to have people go in with read-only access into prod - safe and sound
- Furthermore, I did reach out to you with description of the table(s). If you want me to give you a prod data dump of what you think might be data needed for a feature - just ask. I am more than happy to test your joins/selects/order-by-s/whatever; give you data dumps; whatever. @tejans24 @aroltsch @slj @shanear have all asked and received Prod and Prod-like data from me.
- Having said that: you can have all the data in the world, but what you do with it is on you. 


## The real problem is:
- What is off is the VBMS/BGS/CSUM data. Which I *almost* have full control over in UAT; this has been a painful and slow process
- **However**, I have no visibility into VBMS/BGS/CSUM prod.
- I have loaded a good amount of realistic documents into VBMS, but then they dumped their UAT DB cause I made mess there too. So I just need to reload that
- However, as far as what BGS produces in UAT/Preprod - it's total shit; nothing realistic and nothing is editable.
- This is what lead to the issue you mentioned above. This is not the first time these dependencies messed us up:
  - https://github.com/department-of-veterans-affairs/connect_vbms/issues/154
  - https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/450
  - https://github.com/department-of-veterans-affairs/caseflow/issues/2363

I wish I could be of more help with the latter, it's "in progress"

**Comment by mdbenjam** [comment]
@kierachell thanks for the detailed response. I didn't have a good handle on what you are capable of doing wtih VACOLS UAT. I'm too isolated in my nice little fake data island :). I wasn't aware of https://github.com/department-of-veterans-affairs/appeals-deployment/issues/635 but that is super exciting. Thanks for highlighting how I can work better next time.

**Comment by kierachell** [comment]
I like to have these discussions in person, so maybe this Thursday (heads-down day) would not be ideal.
Maybe schedule the discussion for a day when most can be at BVA so I can be on the VA network and show the data live? I do want to hear more about how to make VACOLS and other dependencies more accessible so that you can know what your code will be hitting. 

Additionally: @aroltsch can show her setup for running your code against UAT (in case not everyone is familiar with configurations?)

**Comment by mdbenjam** [comment]
Gah I always forget about heads-down-thursday. Let's move to Friday.

**Comment by mdbenjam** [comment]
# Action Items
1. Get Read-Only VACOLS access (https://github.com/department-of-veterans-affairs/appeals-deployment/issues/635)
1. Use this to validate against real data when needed with *precautions* 
  - Precautions mean to pair with someone who can validate the queries we're running to avoid harming VACOLS.
1. Investigate creating a weekly/daily snapshot of VACOLS in RDS (https://github.com/department-of-veterans-affairs/caseflow/issues/2680)
