### ISSUE TITLE
[MONDAY 07/24] Strategy to deal with Dispatch cron job failure

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#2625]
Recently, we had sidekiq job failures that lead to Dispatch errors. https://github.com/department-of-veterans-affairs/caseflow/issues/2512 https://github.com/department-of-veterans-affairs/caseflow/issues/1814

I would like to come up with a list of action item that we can do to mitigate disruptions to the user.

Here are some thoughts:
 - Cron job failure should be reported to Sentry (then therefore in Slack)
 - Move cron job closer to business hours to give us time to address the issues.
 - Integrate failed job with PagerDuty (is this too much?)

@shanear @kierachell @cmgiven @lakohl @sharonwarner

**Comment by askldjd** [comment]
Verified that Raven does capture exceptions in Sidekiq. At minimum, we should be able to wrap up all cron jobs in the Raven scope.

Here's an experiment using the Heartbeat Task.

## Sauce
```ruby
class HeartbeatTasksJob < ActiveJob::Base
  queue_as :default

  def perform
    begin
      1 / 0
    rescue ZeroDivisionError => exception
      Raven.capture_exception(exception)
    end 
    Rails.logger.info Sidekiq::Stats.new.inspect
  end
end
```

## Sentry integration
![image](https://user-images.githubusercontent.com/3258724/28240499-28b7479e-6951-11e7-89f9-b90c831d2dc2.png)

## Sentry -> Slack integration
![image](https://user-images.githubusercontent.com/3258724/28240503-374235c6-6951-11e7-82da-e37eff26f0b0.png)

**Comment by kierachell** [comment]
Please see #1814 for proper suggestions. It's an old issue and has not been prioritized, so I updated it cause it needs to be resolved for our sanity.

**Comment by cmgiven** [comment]
Yeah, I would suggest maybe run reassign and create at 4:30, and then prepare at 5:30?

Side note: we are recording the number of appeals prepared on the dispatch stats page. As it turns out, I don't have sufficient permissions to access them, but they should be there.

**Comment by amprokop** [comment]
https://deadmanssnitch.com/ a tool to evaluate — basically do something like `curl deadmansnitch.com/4898332c` at the end of each job and it will tell you when those jobs don’t run
Dead Man’s Snitch
Dead Man's Snitch — A dead simple cron job monitoring tool.
Dead Man’s Snitch is a cron job monitoring tool that keeps an eye on your periodic processes and notifies you when something doesn’t happen. Daily backups, monthly emails, or cron jobs you need to monitor? Dead Man’s Snitch has you covered.
 
i haven't played with it though :(

**Comment by aroltsch** [comment]
There are two different issues here:
1. Cron job doesn't run at all. We need to figure out why this might be happening. Add more monitoring if the job doesn't run. 
2. Cron job fails in the middle due to some error.

Each job should be handled differently:

PrepareEstablishClaimTasksJob:
1. If "preparation" of the task fails, we will catch VBMS error and continue with the next task.
2. We will keep track of the tasks that failed and log them to the log file.
3. We will have Slack integration to log to the devops-alerts channel “PrepareEstablishClaimTasksJob successfully ran. 10 tasks prepared. 3 tasks failed”
4. The PrepareEstablishClaimTasksJob will run at 5pm
5. This ticket focuses on the PrepareEstablishClaimTasksJob: https://github.com/department-of-veterans-affairs/caseflow/issues/1814

CreateEstablishClaimTasksJob:
1. Task creation is very important. If we miss the task due to an error, it might get lost forever. We need to figure out what to do here?
2. We will have Slack integration to log to the devops-alerts channel “CreateEstablishClaimTasksJob  ran. 10 tasks created. 3 tasks failed”
3. CreateEstablishClaimTasksJob will run at 4:30.

ReassignOldTasksJob
1. Does it ever fail?
2. The job will run at midnight.

**Comment by kierachell** [comment]
- I think we could benefit from a blanked job monitor - success or not.

- ReassignOldTasksJob does not completely fail, but it has a bug where `assigned` tasks will not `expire` so it just gets stuck in a loop trying to `expire!` it. This can be resolved by adding `start!`

**Comment by kierachell** [comment]
I think we're mostly covering this with webhooks and @sharonwarner has a couple more issues to catch job failures and manage retries. So this can probably be closed.
