### ISSUE TITLE
Form 8: Question17b:  Change to a Radio button options

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#272]
As a Caseworker, I would like to have question 17B - Title of Certification changed to  a set of radio buttons containing the most commonly used job titles and a the field "Specify other title" added so that a custom title can be provided, quick title selection performed, and form completion is faster. 

### Acceptance Criteria 
1. Verify that question 17B is a set of radio buttons.
1. Verify that there is a new text field "Specify other title" that only appears when "Other" is selected.
1. Verify that question 17B contains the following valid options:  (Select a Title), Decision Review Officer, Rating Specialist, Veterans Service Representative, Claims Assistant, Other
1. Verify that there is no default value for 17B.
1. Verify that the "Specify other title" field is only enabled and visible when the option "Other" is selected for the "Title of Certification".

### Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/21206824/5b300916-c232-11e6-9459-49f47570d042.png)

**Comment by joduinn** [comment]
From: Kavi Harshawat [mailto:notifications@github.com]
[snip]

Feedback we received from a user:

Suggestion - It would be useful if under block 17B you created a dropdown box with job titles most commonly used instead of having to type out the user's current job title (i.e. dropdown box containing - Decision Review Officer, Rating Specialist, Veterans Service Representative, Claims Assistant, etc.). This feature would allow us to complete the form a little faster.

We should do this.

[snip]

I like this!



I don’t know the scenario, so maybe silly question, but does it make sense to add an “Other” on the list, in case we omit a title, and un-expectedly require users to choose an incorrect value…





John.

**Comment by KHarshawat** [comment]
Yep, that was the hitherto unspoken and never mentioned plan @joduinn ;)

**Comment by KHarshawat** [comment]
Include the following options in the drop down:

Decision Review Officer
Rating Specialist
Veterans Service Representative
Claims Assistant
Other 

Other would allow users to enter a custom title.

**Comment by KHarshawat** [comment]
Confirming that 17b should be a drop down menu with the following options:

- Decision Review Officer
- Rating Specialist
- Veterans Service Representative
- Claims Assistant
- Other

When "Other" is selected we should show a short text input box that lets the user enter a custom title. This question should still be required. 

![image](https://cloud.githubusercontent.com/assets/6335546/20689046/85843eb0-b591-11e6-8e9b-03b5e9917b34.png)

![image](https://cloud.githubusercontent.com/assets/6335546/20689051/89209b18-b591-11e6-8543-a4c5b4eb7c14.png)

![image](https://cloud.githubusercontent.com/assets/6335546/20689102/ad420d24-b591-11e6-92f6-1ba7b48ca4a3.png)

**Comment by amprokop** [comment]
@KHarshawat @shanear  — I'm pretty far into implementing this but it looks inconsistent to me. We use radio buttons elsewhere in the certification form instead of dropdowns, and for other similar-looking cases, the label for the custom field says "Specify other {xxxx}:" Attached is a screenshot of another part of the form that looks analagous to me. Do we really want to use a dropdown & this different label text? Mind clarifying?

![image](https://cloud.githubusercontent.com/assets/3781835/21014772/a851ef0e-bd35-11e6-9366-a6612e72f26c.png)

**Comment by KHarshawat** [comment]
@amprokop good catch! I can't think of a good reason we should no make this radio buttons besides saving space. Apologies for not seeing this earlier and for the work you've already put in to make this a dropdown!

**Comment by amprokop** [comment]
no review necessary yet

**Comment by amprokop** [comment]
@KHarshawat — I updated the requirements for this based on our discussion. Would you confirm that the updated issue body description reflects what we want? Thanks!

**Comment by nikitarockz** [comment]
I have updated the mockup to contain radio buttons.
