### ISSUE TITLE
Make the asynchronous certification loader a reusable component

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#2794]
Make the https://github.com/department-of-veterans-affairs/caseflow/pull/2772 loader reusable across applications.

## Dev AC
A reusable component called `AsynchronousDataLoader` can:
- Poll an endpoint provided via prop at an interval provided via prop
- Show a spinner with color and a message provided via prop
- Change the message to a different one if the spinner has been up for >X seconds if optional `extendedWaitMessage` & `timeToShowExtendedWaitMessage` properties are passed in
- Show an error message provided via prop if the server returns an error or after an optional `timeout` has elapsed
- Call `onSuccess` and `onError` functions passed in via prop

Example:

```
<AsynchronousDataLoader
  condition=someFunctionThatReturnsAPromise
  pollingIntervalSeconds=1
  spinnerColor="#459fd7"
  message="Now loading your data..."
  extendedWaitMessage="Your data is loading slowly.."
  showExtendedWaitMessageInSeconds=10
  onSuccess={someOnSuccessFunc}
  onError={someOptionalOnErrorFunc}
  errorMessage="Sorry, we couldn't load your data"
  showErrorMessageInSeconds=20
/>
```

**Comment by NickHeiner** [comment]
This looks like it could be useful to me. The two suggestions I'd have for changes to the above spec are:

First off, instead of an endpoint to poll, allow the parent to pass a promise. I think that this will make it easier to share this component across apps, because then each app can define for itself what it's waiting for. For instance, Reader does not poll an endpoint; it simply makes a single request and waits for it to return.

The logic could look something like this:

```
if the promise is resolved:
  enter success state
  call onSuccess()

if the timeToShowExtendedWaitMessage timeout is reached 
    and the promise has not yet been resolved:
  enter long wait state
  
if the promise is rejected or the timeToShowErrorMessage timeout is reached:
  enter failure state
  call onError()
```

The second thing to change is passing times as numbers instead of strings, and making the name include the unit. (So that would be `pollingIntervalMS` instead of `pollingInterval`.)

**Comment by amprokop** [comment]
@NickHeiner — good points to note.

**Comment by mdbenjam** [comment]
This definitely seems useful. We might be moving to polling in Reader so the extended wait time message is great.

**Comment by amprokop** [comment]
Sync up with Sharon and Mark — would they be able to integrate this into Hearings Prep and Reader? Can they approve the spec for it to make sure it'd be usable across apps?

**Comment by amprokop** [comment]
Also, we can edit the AC to incorporate Nick's comments.

**Comment by mdbenjam** [comment]
I don't think there are any polled endpoints in reader right now. So I'm not sure if it'd be useful at the moment.
