### ISSUE TITLE
Use input type date for all form 8 fields

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#292]
Right now, all input fields that have dates use `<input type="text"...>` because IE11 does not support the date type. However, IE11 will switch them to text fields as a default, so this should still work even though the user will not benefit from its use.

Low priority enhancement.

**Comment by webinista** [comment]
In order for this to work, the format of the dates pulled from the model needs to be output using _yyyy-mm-dd_ format instead of a _mm/dd/yyyy_ format. 

Once we make this change, browsers that support the date input type will show in _mm/dd/yyyy_ format. So far, only Chrome and Microsoft Edge (the successor to IE) support this.

## Chrome
<img width="486" alt="Chrome date type" src="https://cloud.githubusercontent.com/assets/354277/11694819/1b8d9b3e-9e7a-11e5-8dd7-b00847c5741f.png">

<img width="509" alt="Chrome date type expanded" src="https://cloud.githubusercontent.com/assets/354277/11694980/e2297556-9e7a-11e5-9dc9-1b1ba93b4744.png">

## Microsoft Edge

<img width="515" alt="MS Edge date type" src="https://cloud.githubusercontent.com/assets/354277/11695081/552050a2-9e7b-11e5-87a5-1e5c1edb5c94.png">

<img width="646" alt="MS Edge date type expanded" src="https://cloud.githubusercontent.com/assets/354277/11695067/4b50ee60-9e7b-11e5-9e13-e0e6a93d96ac.png">

## Other browsers

Other browsers -- hi, Internet Explorer 11 -- will instead pretend that `input type="date"` is `input type="text"` and display the date as printed: `yyyy-mm-dd` (shown below).

<img width="500" alt="Date input type in non-supporting browsers" src="https://cloud.githubusercontent.com/assets/354277/11694818/1b6a0200-9e7a-11e5-94c8-33b7cdee9a6a.png">

**Comment by KHarshawat** [comment]
Argh.. IE. So the ideal state should be that the user always sees and enters the date as *mm/dd/yyy* regardless of what browser they're using. We actually got feedback about this in our NYRO usability session.

It looks like there isn't a ton of support for `input-type=date` across the board yet: http://caniuse.com/#search=input-date

@webinista is there anyway we could do this with Javascript for browsers that don't support it?
