### ISSUE TITLE
Reader Broken in Prod 8-9-17 Post-Mortem 

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2925]
# Cause
- The content_url method in document.rb which gets the url the frontend needs to hit to retrieve document content was wrong.
  - In https://github.com/department-of-veterans-affairs/caseflow/pull/2866/files#diff-da766db961b1ebe7e7e8de051dac4096R182 it was changed to stop looking for the feature toggle
- The feature toggle, :efolder_docs_api, was enabled in UAT for testing. Therefore this worked properly in UAT.
- The feature toggle, :efolder_docs_api, was disabled in Prod. Therefore we picked the wrong content_url, and could not retrieve the document content.

# Solution
- We added the check for the feature toggle back into the code: https://github.com/department-of-veterans-affairs/caseflow/pull/2922

# Events
- 2017/08/09 8:37AM: First feedback from a user that Reader was broken
- 2017/08/09 9:23AM: Mark and Artem start debugging
- 2017/08/09 9:23AM: Second feedback from a user that Reader was broken
- 2017/08/09 10:02AM: Abby sends email to all users that Reader is down and that we are working on a fix.
- 2017/08/09 9:23AM: Second feedback from a user that Reader was broken
- 2017/08/09 ~10:00AM: PR for fix was sent out: https://github.com/department-of-veterans-affairs/caseflow/pull/2922
- 2017/08/09 10:22AM: Change was approved by JD and merged
- 2017/08/09 10:24AM: Change was deployed to Prod
- 2017/08/09 10:49AM: Change finished deploying
- 2017/08/09 10:50AM: Jane tested the change and it worked
- 2017/08/09 10:52AM: Abby notified users that Reader was back in service

# Action Items
- After testing a feature flag in UAT, ensure we revert it so that QA can properly test changes.
- Refactor Reader feature flag forks to reduce the chance of a similar error in the future. https://github.com/department-of-veterans-affairs/caseflow/issues/2926

**Comment by kierachell** [comment]
- Sounds like another vote for a more UI-friendly FeatureToggle. At this point having to SSH into Rails console 3 times for every validation ticket is becoming a pain.
- I need an outline of what Features are to be toggled in Production for which use cases so I know what is `bleeding-edge` code and what is `production-ready` code.
- My next task is to setup Preproduction for Prod parity.

**Comment by joofsh** [comment]
CC @evankroske since he had some ideas around this & storing our feature toggles in source control. Piggybacking off that idea:
- Store feature toggles in source control
- Production reads from the source control file for its feature toggles
- In UAT, we could have the ability to override these and temporarily enable bleeding edge features. However, we'd also have a function to `FeatureToggles.reset!` which would reset them all to the source control file. This would effectively give us a lever to pull to make UAT mirror production

**Comment by evankroske** [comment]
Could you add more context on the issue? "Summary" and "Impact" sections would be helpful

**Comment by kierachell** [comment]
> In UAT, add the ability to override these and temporarily enable bleeding edge features. Create a function for FeatureToggles.reset! which would reset all features to the source control file. This would effectively give us a lever to pull to make UAT mirror production

- I added a `feature toggler` to the `/test/setup` page a while back but it has evolved so much since then that I did not keep up. I will make an issue to bring it up to date.
- I would need more than a reset, but a list of "production-ready" features since we have very specific combinations of how we use it.

**Comment by mdbenjam** [comment]
Closing this post-mortem. We now have feature-toggles in code!
