### ISSUE TITLE
Reader job incorrectly logs documents that we've already cached in S3 as failures

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3010]
For each document we fetch in the RetrieveDocumentsForReader job, we call `record_doc_outcome` with the output of `fetch_document_content`:

```
  def fetch_docs_for_appeal(appeal)
    appeal.fetch_documents!(save: true).try(:each) do |doc|
      @counts[:docs_attempted] += 1
      record_doc_outcome(fetch_document_content(doc))
    end
  rescue HTTPClient::KeepAliveDisconnected, VBMS::ClientError => e
    # VBMS connection may die when attempting to retrieve list of docs for appeal
    @counts[:appeals_failed] += 1
    @counts[:consecutive_failures] += 1
    Rails.logger.error "Failed to retrieve appeal id #{appeal.id}:\n#{e.message}"
  end
```

```
  def record_doc_outcome(doc)
    if doc
      @counts[:docs_successful] += 1
      @counts[:consecutive_failures] = 0
    else
      @counts[:docs_failed] += 1
      @counts[:consecutive_failures] += 1
    end
  end
```

^ If `doc` is not present, we record it as a failure.

`fetch_document_content` returns `doc.fetch_content_unless_cached` if the eFolder API isn't enabled.

Unfortunately, `fetch_content_unless_cached` will return nil if we find the file cached in S3. 

```
  def fetch_content_unless_cached
    fetch_content unless S3Service.exists?(file_name)
  end
```

So it looks like the job will fail if we've already cached some number of the documents.

The easiest fix might be to make a one line addition:

```
  def fetch_content_unless_cached
    return true if S3Service.exists?(file_name)
    fetch_content 
  end
```
This code path might also warrant a refactor later on.

**Comment by mogrenAtWork** [comment]
Returning a value for `fetch_content_unless_cached` in every case would cause the batch job to loop over the same 1500 documents each time it's executed. 

I've moved the functionality of this method into the batch job. 

There's still a problem of not being able to tell how many documents were pulled from VBMS when we start using eFolder.

**Comment by mogrenAtWork** [comment]
I tested this in UAT. The fix correctly accounts for documents cached in S3. 

We have two remaining bugs in this:
1. There's still a problem of not being able to tell how many documents were pulled from VBMS when we start using eFolder.
1. The job checks for the `limit` provided after fetching the documents for all appeals for a user, not after each appeal, which causes more load on VBMS than it can handle.

Here are a couple of things we might want to consider:
1. This job is complex, for a seemingly simple task. The data structures and external dependencies leaves Caseflow in the dark about what appeals are _actually_ assigned to the users, since it's not the system of record for this information.
     - This causes a majority of the complexity in the job and the application. I wonder if there are easier assumptions we can make about the data and how often it changes in VBMS, instead of fetching **everything** each time this is run. This does not scale well when we ramp up to 700 users.
        - This piece may be added to eFolder instead of having to worry about changing the data structures in Caseflow, since we're going to go that route soon.
        - Or we may be able to break apart some of these queries into more manageable chunks
1. We could just leave this just running 24/7 to continuously poll VBMS instead of having all of these work-arounds.
    - It can already catch the exceptions if VBMS is down. We can add waits if so many consecutive exceptions happen in a row
1. We could limit the # of appeals that are fetched instead of relying on # of documents. We could fetch the average # of docs associated with appeals and use this as guidance for this job. This might be the easiest solution so we don't have to worry about this not working when we enable eFolder and also makes the job a little less confusing.

3. might be the best option in the short term. We can run some stats to see what would be the right number of appeals to fetch each night

**Comment by mdbenjam** [comment]
The job has been substantially changed. I don't think this is relevant anymore.
