### ISSUE TITLE
Post to #appeals-devops if Dispatch Jobs do not start or complete

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3023]
We currently post if jobs do not start or complete. However, for business critical jobs, we should ensure that they finish, and send an alert if they do not.

**Comment by joofsh** [comment]
To QA: 

Can run `MonitorBusinessCriticalJobsJob.perform_now` from the rails console. It should provide output to slack

**Comment by amprokop** [comment]
Did we determine that the distinction between jobs not starting and jobs not finishing was not important, or that it was not something that needed to be addressed? Just wondering since the title of this task was changed

**Comment by amprokop** [comment]
Or, after looking at the PR, it seems like we actually post if they don't start and if they don't finish? Not sure

**Comment by kierachell** [comment]
- If the job is triggered from the console, then the new middleware does not write it to Reidis: expected?
- Does it have to be 5 hours? Is that configurable by job? 
- What's up with double `@here`s?

<img width="458" alt="screen shot 2017-08-23 at 12 25 19 pm" src="https://user-images.githubusercontent.com/18075411/29627008-9a99002a-87fe-11e7-91bd-f85b6efae4fe.png">

**Comment by joofsh** [comment]
@kierachell  
- For some reason it looks like the sidekiq middleware is not loaded by the rails console. To test it with middleware we'll have to run it through sidekiq directly `MonitorBusinessCriticalJobsJob.perform_later`
- It doesn't have to be 5 hours, it is somewhat arbitrarily coded to that number. I can change it to take an ENV var if you'd like? but I don't think it's necessary since I've set the task in jenkins to run at 6pm EST
- The double `@here` is just to denote that there are 2 problems to look at. Not the prettiest output but it's functional (and was the simplest way to code it). Let me know if you see this as a problem and I can remove the extra `here`

**Comment by joofsh** [comment]
@amprokop yes sorry, updated the title & AC accordingly. This job will verify that it has started & completed

**Comment by kierachell** [comment]
**PASSED**
<img width="532" alt="screen shot 2017-08-29 at 9 13 57 am" src="https://user-images.githubusercontent.com/18075411/29822717-6aab758c-8c9a-11e7-8d6e-4ba1949c7336.png">

<img width="501" alt="screen shot 2017-08-29 at 9 14 20 am" src="https://user-images.githubusercontent.com/18075411/29822726-74cf55f6-8c9a-11e7-8e11-c0dbdc5ea2a8.png">
