### ISSUE TITLE
Document Viewer | Creating/deleting issue tags while having multiple tabs open

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3028]
# Description
Some users requested ability to view documents in new tabs, but this poses a bunch of issues relating to race conditions when creating tags and whatnot:

- Deleting the last instance of an issue- does it get removed from suggestions list?
- Editing the same document in two tabs?
- Categorizing documents?

Basically, we need a good UX and technical investigation in to how to make this work, if at all. Prolly too much work for little gain, but feedback requests are there...

## Reproduction Steps

**Scenario 1 -**

1. Go to Reader
1. Open a case file
1. Open one document in one tab
1. Open another document in another tab
1. Note that you're able to move between documents
1. Create an issue tag for one document
1. Not see it on the other document suggestion list?

<continued with multiple tabs open...>
1. Create the same issue on two documents
1. Move between documents in one tab
1. Create the same issue for the same document in another tab
1. Try to delete issue in the first tab

<continued with multiple tabs open...>
1. Categorize one document in one tab
1. Move to that document in the other tab

<continued with multiple tabs open...>
1. Create the same issue on two different documents in two different tabs
1. Delete it in one tab
1. Click the down arrow for suggestions and see that issue twice

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Screenshots
**_Scenario 1 - [Two same issues?]_**
<img width="1273" alt="screen shot 2017-08-20 at 11 35 24 am" src="https://user-images.githubusercontent.com/18075411/29496186-aafb0aea-859b-11e7-8f1a-82a6de2913ef.png">
**_Scenario 2 - [Console error on delete]_**
<img width="1346" alt="screen shot 2017-08-20 at 11 38 35 am" src="https://user-images.githubusercontent.com/18075411/29496209-1b8626be-859c-11e7-8f13-35e898daaedc.png">

# Related Issues
**_Engineering_**
#2712

**Comment by gnakm** [comment]
@mdbenjam @abbyraskinUSDS 
Revisiting these issues that Artem put together last year. 

- Deleting the last instance of an issue- does it get removed from suggestions list? 
We have it now where it's removed from the list of suggestions, correct? Don't think this is an issue anymore. 

- Editing the same document in two tabs?
In terms of issues, I don't think it's a huge deal because users can refresh the page and have those issues come up on the list. Seeing issues twice situation above that Artem mentioned is not happening anymore (just tried it).  

- Categorizing documents?
This is another one where when tabs are refreshed, it is up to date with categories.

**Comment by mdbenjam** [comment]
I agree the amount of effort here is REALLY high. Unless users are asking for it a lot, I vote to close.
