### ISSUE TITLE
Rephrase messaging on the error page

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#303]
At the point users use Caseflow, they've looked at the case a number of times -- it's *very* rare it's outright missing, and much more often the case the document isn't labeled right. Test users even reacted to that page by saying "Oh! The document must be labeled wrong"

We should change our assumption to align with the common case (and avoid blaming the user!) by saying the document is mis-mismatched (and not outright missing)

**Comment by webinista** [comment]
So instead of:

> Caseflow could not find the documents with an `x` below, in the appellant’s eFolder. Try looking for the missing document in VBMS and changing its date to the date in the VACOLS column.

Maybe:

> Caseflow could not find the documents with an `x` below, in the appellant’s eFolder. This can occur when:
>     1. the document is mislabeled (most likely). 
>     2. the document date in VBMS and VACOLS do not match.
> Once corrected, refresh this page.

@KHarshawat @maryannbrody can you two weigh in here?

**Comment by maryannbrody** [comment]
(CC @KHarshawat and @webinista ) 

How about, 

Caseflow could not find the documents marked with an x  in the appellant's eFolder. This usually happens when something doesn't match up. Try checking:
- The **document type** in VBMS to make sure it's labeled correctly
- The **document date**—the date in VBMS must match the date in VACOLS

Once you've made corrections, refresh this page.
