### ISSUE TITLE
Refactor | Design better table for DocumentsTable

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3102]
We currently use the Table component for our DocumentsTable. The Table component works well for static data, but struggles to handle dynamic data. Let's design a new advanced table component that works for our use case. The best solution might just be wrappers around the html table tags (table, tr, tc, etc...). Ideally this advanced table component can be used to implement the current table component so that it's easy to unify styles.

# AC
- [ ] Design but do not implement a new table component that suits our needs.
- [ ] Present the component to the team for their opinions.
- [ ] Create a new ticket to implement the table.

**Comment by joofsh** [comment]
Ensure:
- Can render dynamic row content
- Is 508 accessible

**Comment by joofsh** [comment]
Example using react-virtualized
```
 return <div>
   <Table
     rowCount={rowObjects.length}
     rowGetter={({ index }) => rowObjects[index]}
     width={1200}
     rowHeight={50}
     headerHeight={30}
     height={300}
   >
     <Column
       width={300}
       label='Receipt Date'
       cellRenderer={({ rowData }) => {
       return <span className="document-list-receipt-date">
         <Highlight>
           {formatDateStr(rowData.receivedAt)}
         </Highlight>
       </span>
       }}
     />
     <Column
       width={500}
       height={50}
       label='Document Type'
       cellRenderer={({ rowData }) => {
         return <ConnectedDocTypeColumn doc={rowData}
           documentPathBase={this.props.documentPathBase}/>
       }}
     />
   </Table>
```

**Comment by joofsh** [comment]
# Research Results

Solutions that are windowed, expandable content, and accessible: 

## [React Virtualized](https://github.com/bvaughn/react-virtualized)
I was able to get a working version of a windowed, accessible table with expandable content using react-virtualized. This is the only library I could find that could potentially support what we need here. A gif of that solution is below:

![windowed_and_expanding](https://user-images.githubusercontent.com/2256237/30667425-7a35f6ca-9e25-11e7-852e-076db4b6bc1b.gif)

Audio of it being accessible with JAWS:
https://drive.google.com/open?id=0BxS1c0ZghPGvaC03VGktZ0dXMlE

#### Pros:
- The `rowObjects` array includes purely documents. So only one "row" is rendered per document. The comments are considered expandable content within that row
- The content is windowed, so will not have performance issues even in very large efolders
- The content is still accessible, I've verified using JAWS and manual keyboard navigation
- Re-renders (such as when searching) on the 150 document efolder (reader_id2)  finish ~40ms faster than without windowing. This difference would be even more pronounced on larger defolders.

#### Cons:
- Windowing add complexity and can come with scrolling bugs. The added complexity is definitely worth it on very large datasets (1 million rows). In efolders that seem to max out around 1000 it is more debatable whether its worth it
- We have to manually set the width/height of all rows/columns/cells. This is less elegant than a purely CSS-based solution.
- Because we manually set the height, we must also manually update the height when a row is expanded to show its comments

**Note:** In order to get proper screenreading to work with JAWS, I had to change the top-level table `<div>` to a `<table>`. I've opened an [issue in react-virt](https://github.com/bvaughn/react-virtualized/issues/819) so that the library itself can be updated with this change. However, if it is not accepted we can easily insert this into our implementation (albeit slightly hacky).

---------------------

If we don't care about windowing, we should then focus on expandable content & accessibility:

### [RC-Table](https://github.com/react-component/table)
Support: 210 stars directly, 17.5k stars indirectly, last commit 2 days ago
Documentation: Good [API documentation](https://github.com/react-component/table#api) & [demo examples](http://react-component.github.io/table/) 

#### Pros
- Has native support for expandable sub-content and even nested sub-tables. 
- Is heavily supported. While this library itself does not have that many stars, it is the library used internally (and supported by) the very popular [Ant Design system](https://github.com/ant-design/ant-design). Pulling in rc-table directly gives us all the benefits of that table component without adding all the bloat of the full Ant Design suite & its styling.
- Accessible. It is rendered with real `<table>`, `<tr>`, `<td>` elements.


#### Cons
- Not windowed

### [React-Table](https://github.com/react-tools/react-table)
Support: 1.6k stars, last commit 2 weeks ago
Documentation: Good [API documentation and demo examples](https://react-table.js.org/#/story/readme)

#### Pros
- Has native support for expandable content and nested sub-tables.
- Very full-featured as it supports pagination, server-side fetched data, default & custom sorting, editable fields, etc. 
- The API for the component is very callback-centric and therefore provides high customization. 

#### Cons
- Not windowed
- The component is not very accessible. It is rendered with `<div>`s and does not add aria-labels, roles, or tab indexes.

**Comment by nickheiner-usds** [comment]
To test accessibility, there is more we should check. (I couldn't tell if that testing was done from the audio clip you posted.) Re-posting from Slack:

![image](https://user-images.githubusercontent.com/25331532/30670421-3e7191ac-9e30-11e7-80df-0757776065e1.png)

> Windowing add complexity and can come with scrolling bugs.

What are the scrolling bugs you have in mind? I was hoping that `react-virtualized` would take care of a lot of this for us.

> We have to manually set the width/height of all rows/columns/cells.

And by "manually set the width/height", do you mean set them all to be a uniform height? This was problematic the last time I discussed it with @gnakm and @abbyraskinUSDS, although it's worth re-visiting. However, the [`react-virtualized` demo](https://bvaughn.github.io/react-virtualized/#/components/Table) looks like it accepts variable height rows.

## Woe With Uniform Heights
`react-list` requires rows to have uniform heights.

If I recall correctly, the problem preventing us from having each row height be uniform was the tags:

![image](https://user-images.githubusercontent.com/25331532/30670569-cf8d6bf2-9e30-11e7-900a-eee70c0a53fd.png)

The tags can be of arbitrary height. @gnakm and @abbyraskinUSDS didn't think it was worth it to come up with an alternate design that constrains the tags to some height. 

If a row is expanded, then it also contains an arbitrary amount of comments, which adds a corresponding amount of height.

Virtualization is easy when heights are uniform, because you can determine what window to show with simple arithmetic. When heights are variable, and we can't know the height until we render the component, then things get far more complicated.

**Comment by joofsh** [comment]
@NickHeiner It does support dynamic height rows (that's how the command comments work in my prototype GIF above). 

To your question about all the table screenreader support, I'm not sure. I would have to test deeper whether each table screenreader action worked properly with this implementation. I would say though that even if they don't work I still feel this is sufficiently accessible. For me the prototype was extremely understandable and navigate-able with my eyes closed

**Comment by mdbenjam** [comment]
Note that this discussion shows how we can make it accessible: https://github.com/bvaughn/react-virtualized/issues/819#issuecomment-342548476
