### ISSUE TITLE
eFolder Integration | Roll Out

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3128]
We want to turn the feature toggle on and connect Caseflow to eFolder in production. We also want to do this cautiously so that if anything breaks we don't effect many users.

# AC
1) Verify with Artem that there are no known issues with the eFolder integration.
1) Abby has reached out to two pilot members: Jane Nichols, and Nate Kroes about turning on the integration for them. Verify we've turned the `efolder_docs_api` feature toggle on for both of them: BVANKROES and BVAJNICHOLS.
1) Work with Abby to sync with them after turning it on. Verify there are no issues.
1) If the rollout to two users is successful, scale eFolder up and roll out to 25% of users.
1) If the rollout to 25% of users is successful, scale eFolder up and roll out to the remaining users.
1) When all traffic is going through eFolder, scale down certification.

**Comment by amprokop** [comment]
We tested this morning, and after opening 20-30 claim folders in a 30 minute period, UAT instances started dying. This may be related to our longer-tem problem with eFolder memory, rather than anything Reader-specific. We basically keep using more and more memory until a deploy is done.

![image](https://user-images.githubusercontent.com/3781835/29936764-5de026b4-8e51-11e7-8722-bda1307a0952.png)

The prod instances have much more memory than the UAT ones (30.5 GiB vs 4 GiB), so it doesn't

**Comment by mdbenjam** [comment]
This is turned on for everyone.
