### ISSUE TITLE
Check out the way fields in this form are approached on gov.uk application. 

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#322]
Hey @KHarshawat, 

I just stumbled across this and thought it was an interesting approach when you have a lot of form fields and some are complete and some are not. The intent of this design is to show progress to the user, but I could see something like this being interesting to draw attention away from pre-filled fields in a form like Form 8 on Caseflow. Probably too much for Form 8, but interesting either way. Here's the link where I found it: https://designpatterns.hackpad.com/Progress-indicators-3AOrLoia9Us

![image](https://cloud.githubusercontent.com/assets/12674895/11630365/2a1f3c08-9ccb-11e5-860d-2ecdfd017441.png)

p.s. - would you use github like this? Or is this better as a chat... just curious -- want to make sure i'm using communications in best way. :)

**Comment by KHarshawat** [comment]
@maryannbrody This is an interesting approach for very long forms (rather than a turbotax style wizard). I imagine it would be frustrating to use this to fill out the form fro the first time because it involved clicking into each sub-section. I really like the `Complete`, `Incomplete`, and `Not started` indicators.

You can use Github for this but given that it's just an idea for conversation the issue would get closed right away. Also might want to add a label like `Idea` so these things are easy to get back to. I'll change the label and close it now :)
