### ISSUE TITLE
Should "If you can’t find the document, click the This case cannot be certified link below." be removed from "Find missing documents" screen?

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#328]
We've adjusted some of the copy and the button on this page. I assume this means that the "If you can’t find the document, click the This case cannot be certified link below." text should also be replaced. The question I have is "with what?"

![forms-not-found](https://cloud.githubusercontent.com/assets/354277/11631931/7c99d158-9cd2-11e5-9e60-cc51fb6432c2.png)

**Comment by paultag** [comment]
Also cc'ing @maryannbrody

**Comment by maryannbrody** [comment]
@webinista @paultag @KHarshawat 

How about, 
---
**Tried everything?** If Caseflow still can't identify this document, it can't be certified right now. Click < can't certify > below—the certification date will not be set in VOCALS.

**Comment by KHarshawat** [comment]
@maryannbrody so the whole thing would be the following? If so, LGTM ...

----

Caseflow could not find the documents marked with an `x` in the appellant's eFolder. This usually happens when something doesn't match up. Try checking: 

- The **document type** in VBMS to make sure it's labeled correctly
- The **document date** – the date in VBMS must match the date in VACOLS

Once  you've made corrections, [refresh this page]().

**Tried everything?** If Caseflow still can't identify this document, it can't be certified right now. Click ` Can't certify` below—the certification date will not be set in VACOLS.

**Comment by maryannbrody** [comment]
@webinista this is ready for you... Full copy for this page should be what @KHarshawat posted last night.

**Comment by webinista** [comment]
More confusion on my part: in this copy it says click _Can't certify_, but that link says _Cancel certification_, instead of "Can't certify." Should they both read _Cancel certification_?

![start-screen](https://cloud.githubusercontent.com/assets/354277/11752323/fda51b26-a00c-11e5-8af5-dd08e15a1800.png)

**Comment by KHarshawat** [comment]
@webinista Yes it should say "Cancel certification" or whatever the link in the bottom left becomes should we decide to change it again :)

**Comment by webinista** [comment]
This was fixed. 

![start-page](https://cloud.githubusercontent.com/assets/354277/12020304/dd771752-ad48-11e5-9811-e2dab9b6879f.png)
