### ISSUE TITLE
Update 'Case Not Certified' screen. 

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#335]
Blocks #307 

![cannotcertify_03_confirmation](https://cloud.githubusercontent.com/assets/6335546/11602174/41452c70-9aa6-11e5-80cc-0a5be46df1f0.png)

**Comment by webinista** [comment]
@KHarshawat Just want to confirm that these are updates to the error page, and not a new screen.

**Comment by webinista** [comment]
@paultag @alex @plusjeff What's the best way to hide the "3-across" box component using ERB?

**Comment by alex** [comment]
Make it use the basic layout, instead of the new application layout.

On Tue, Dec 8, 2015 at 4:04 PM, Tiffany Brown <notifications@github.com>
wrote:

> @paultag <https://github.com/paultag> @alex <https://github.com/alex>
> @plusjeff <https://github.com/plusjeff> What's the best way to hide the
> "3-across" box component using ERB?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/caseflow/issues/335#issuecomment-163017197>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
