### ISSUE TITLE
Create data principles documents 

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3404]
## AC
- For Work Queue and general appeals data, we should have data principles documents as part of the discovery phase for work queue data (& appeals data)

**Comment by amprokop** [comment]
@cmgiven — ping on this! did you have time to get any thoughts down? raw or unfinished thoughts are great, happy to smooth out/synthesize.

**Comment by cmgiven** [comment]
A few general ideas:

1. Don't overwrite history. We would ideally be able to understand the state of a given appeal at a given moment in history without resorting to snapshots. We would be able to know what had happened to the appeal, what issues were attached to it, how those issues were classified, etc. Most attributes should probably be immutable.

2. Issues as a unit of analysis. A lot of reporting will look at issues, as opposed to appeals (although appeal-level remains important). An NOD contains a set of issues; we should be able to identify which NOD originated a given issue, and track events that happened to that issue over the course of its lifespan.

3. Plan for required events/tasks to change. We're in the midst of the appeals process going through a pretty major set of changes, but we shouldn't assume the legislation will be the last of it. We should plan for the process to continue to change over time, and create a data model that anticipates a transient process with steps being added or removed, both over time and conditionally by appeal. Instead of SOC date being an attribute of an appeal table, as it is today in VACOLS, we would prefer that an SOC be a type of task or event tracked in a generic task/event table (optionally with a polymorphic association to an SOC table for SOC-specific attributes). One step further would be tracking the process requirements as data, instead of code; i.e. an SOC is required for these appeals but not these appeals, it requires these antecedent steps to be completed, etc. but this may be architecture astronaut-y.

Other thoughts:

* There are a lot of things we want to cache for performance reasons but for which we are not the source of truth. This is currently happening with a lot of one-off decisions, like for example the discussion on #3414 (I think, GitHub not loading right now). Currently this is mostly happening with VACOLS, which will cease to be an issue, but we're going to have similar issues with BGS and VBMS as we try to integrate with claims and other information (eFolder document metadata is a good example). We need to have a strategy around what we are the source of truth for, what we're not, and how we mark/invalidate/otherwise deal with those things for which we are not the source of truth but are hanging onto that information in our DB.

* There's often a question of wanting to know who entered a specific piece of information. This is potentially a rabbit hole that leads to overcomplicating the design, but something worth keeping in mind, particularly for any information that we know or speculate to be error prone. I also note that we don't currently have a description of the role of a given user (e.g. user BVAXXX is a judge, VBAXXX is a DRO); this would be useful, but I'm not sure how best to collect that information.

* Cancellations, changing your mind, etc. are important data. If a judge reassigns a case from one attorney to another, we still care about both assignments, and would ideally like to know when/why that happened. All tasks must end, even if the task is not complete, but we'd ideally like to know why the task was closed, particularly when this is not expected. In VACOLS, open or closed is often just a single-character column indicating status. It would be better to have a close date, and reason, always.

**Comment by evankroske** [comment]
A fascinating approach to storing data for analysis: [Turning the database inside-out with Apache Samza](https://www.confluent.io/blog/turning-the-database-inside-out-with-apache-samza/).

**Comment by amprokop** [comment]
Awesome, scanned it a bit. Yeah, the idea of immutability might be potent
here. Will take a more in depth later. Thanks, Evan and Chris!

**Comment by amprokop** [comment]
closing for now, will re-open later
