### ISSUE TITLE
Record form 8 inputs in postgres for data analysis

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#350]

**Comment by amprokop** [comment]
I'm going to knock this and #321 (which involves recording edits in caseflow certification to form 8 values) out in the same PR.

There are a couple of options for how we want to do this. Will discuss with @cmgiven

**Comment by cmgiven** [comment]
Also be aware of #342.

**Comment by amprokop** [comment]
This issue became a lot more complex than first anticipated. 

Converting the model to a persisted record is a touch-and-go affair due to all the Rails magic, there were a number of errors. Also guessing at the correct schema took awhile, and figuring out what the `SERIALIZATION` stuff is in the form8 took some investigation.

There were also data model discussions. The best data model is here is actually fairly unclear and will probably shift. Had an extended discussion with @mdbenjam and @joofsh about the future data model, and we considered a number of options. Our presumption is that the future path forward includes elimination of the Form 8. At some later point in time, Certifications and Form 8s will not exist as separate concepts. At that point, we'll probably want to merge Certifications and Form 8s into one table, possibly drop many of the columns, and have that table linked to Appeals. However, it seems that the best present way forward is to link Form 8 records to Certifications, we don't see any problem with changing that in the future. I recommend that we try to think a few steps ahead in the future, it seems like there's a lot of decisions we could make here that we'll regret.

Discussion with @shanear also uncovered a few additional concerns. Currently, the form8 data is cached to ensure that users who navigate backwards will have their data saved. We'd like to move away from that model and always fetch data from the db. However, we want to take an incremental approach to doing that. The PR that fixes this issue will save all Form 8s to the db, but if the Form 8 data is available for the VBMS id in the cache, it will use that data to populate the form at `certifications/xxx/new`. The next PR will then eliminate the caching behavior. This is so users who navigate backwards sometime after a deploy will not have the app crash.

One additional detail— @shanear mentioned that the form 646 data in the Form 8 is the only known piece of data in the Form 8 that affects the life of an appeal after certification. Leaving this tidbit here so I and maybe others keep it in mind later on.

**Comment by amprokop** [comment]
I'm in the final stages of implementation. Hoping to have this in review today.

**Comment by shanear** [comment]
@amprokop agree on wanting to eventually kill the concept of the form8 (and the form8 table). Starting to record this data programmatically will help us figure out exactly how to do that. We can always migrate the data when that happens.

We shouldn't be afraid of quick wins, and incremental improvement, even when it's not perfect.

**Comment by amprokop** [comment]
brought up an edge case on this today: there was previously no way to update the data from vacols once the certification has been started. so, for example, if i visit /certifications/new/123C, then close my browser, then come back in six months and visit /certifications/new/123C, even if the underlying data in vacols has changed, the data displayed in certification will be the data we fetched from vacols six months ago. 

@shanear and i discussed options, including adding a "Refresh from Vacols" button, and concluded that we'll write some expiration logic to cover this. if the form 8 has been updated more than 48 hours ago, visiting /certifications/new/123C will cause a refresh of the form8 data from the vacols appeal.
