### ISSUE TITLE
[Frontend] Hearing Worksheet | Page load error doesn't work

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3548]
AC:
- When the worksheets.json request to the backend fails, we display an error

**Comment by kierachell** [comment]
**PASSED**
- broke the code
- reloaded the server
- reloaded page
- won the ELB roulette:
- because AC is 100% non-descript gonna pass it
<img width="952" alt="screen shot 2017-10-23 at 9 55 57 pm" src="https://user-images.githubusercontent.com/18075411/31921383-2ab0fb68-b83d-11e7-9a9c-dba7f6853d47.png">
<img width="820" alt="screen shot 2017-10-23 at 9 56 26 pm" src="https://user-images.githubusercontent.com/18075411/31921384-2ac56120-b83d-11e7-9eb6-7c0b11a8ce0c.png">
