### ISSUE TITLE
Search | Index document test using redux search

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3644]
See the tech spec here: https://github.com/department-of-veterans-affairs/appeals-pm/tree/master/caseflow/tech_specs/reader

In order to enable efficient searching we want to add redux-search to Reader. Since we don't have a search UI designed yet, and since this will take several changes to get working, we're going to hide a preliminary UI behind a feature flag for testing.

# AC
1) Verify when the `search` feature toggle is on for a user:
   1) they can see a search box on the pdf page.
   1) when they search for terms they see a list of page numbers that contain that term.

**Comment by kierachell** [comment]
### Looks fugly, yo...
<img width="593" alt="screen shot 2017-10-20 at 8 40 44 am" src="https://user-images.githubusercontent.com/18075411/31821304-b097142e-b572-11e7-9ea4-17231aa1359a.png">
<img width="571" alt="screen shot 2017-10-20 at 8 40 55 am" src="https://user-images.githubusercontent.com/18075411/31821305-b0b7898e-b572-11e7-9244-deb99f165ff2.png">

### What pages is it displaying? Not where the text is:
<img width="554" alt="screen shot 2017-10-20 at 8 41 02 am" src="https://user-images.githubusercontent.com/18075411/31821306-b0d605bc-b572-11e7-8c2c-018b10d64e8c.png">
<img width="448" alt="screen shot 2017-10-20 at 8 41 36 am" src="https://user-images.githubusercontent.com/18075411/31821309-b10e92ec-b572-11e7-9cac-ae23e355245b.png">

![looksugly](https://user-images.githubusercontent.com/18075411/31821344-d423b0b4-b572-11e7-8941-633f2299f6b1.gif)

**Comment by mdbenjam** [comment]
Agreed the ui looks bad. It's just for testing now as we roll out the rest. Sorry the pages are not page number right now but page indices. Does it still fail with that context? @kierachell

**Comment by kierachell** [comment]
Uh... What is a page index? you mean it counts from 0?

**Comment by mdbenjam** [comment]
Yeah 0-indexed pages.

**Comment by kierachell** [comment]
### It is hard to tell because it is searching by first term + subsequent terms:

- Fine if both terms are together all the time:
<img width="1361" alt="screen shot 2017-10-23 at 8 57 30 am" src="https://user-images.githubusercontent.com/18075411/31890329-bcf204f8-b7d0-11e7-9936-93cf1a287006.png">

- matching `about` on the first page, but the whole phrase is on the last page
<img width="886" alt="screen shot 2017-10-23 at 8 58 28 am" src="https://user-images.githubusercontent.com/18075411/31890330-bcfb8582-b7d0-11e7-898f-59f44ae79768.png">

- again, there is no `product management` but there is `product` everywhere. So... should it match?
<img width="955" alt="screen shot 2017-10-23 at 8 59 13 am" src="https://user-images.githubusercontent.com/18075411/31890331-bd0525a6-b7d0-11e7-9825-133f7a99e7cf.png">



### Searching for empty string:
![hard_to_tell](https://user-images.githubusercontent.com/18075411/31890282-8c727ea2-b7d0-11e7-93f1-5a32359af078.gif)

**Comment by mdbenjam** [comment]
This is really an intermediate step. We will consider these problems in the final PRs.
