### ISSUE TITLE
How have this year's Certification changes affected business metrics we track on the stats page?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3676]
We did Certification v2 pilots in June and July, and our regional rollout happened starting on July 31st with the Southeast. Certification v2  been fully rolled out since September 1st. 

## How has v2 affected our users?
Our main goals with v2 were to reduce POA/hearing data errors, and to remove the overhead of the Form 8. We verified that POA/hearing data errors were reduced by v2 using a manual sample of cases. However, our stats page surfaces a few more insights.

## Cases certified
![image](https://user-images.githubusercontent.com/3781835/31784489-d8cba3a4-b4cf-11e7-98a4-242400efd437.png)
![image](https://user-images.githubusercontent.com/3781835/31784474-c9975694-b4cf-11e7-81e1-4cd1e81fcf1b.png)
- Well over 10,000 appeals have been certified with v2, including over 9000 certifications since v2 has been fully rolled out.

## Time to certify
Time to certify before regional rollout started
![image](https://user-images.githubusercontent.com/3781835/31784637-7cba30d4-b4d0-11e7-8c64-abb59a9966bb.png)
Time to certify after v2 was fully rolled out
![image](https://user-images.githubusercontent.com/3781835/31784743-d2c17dac-b4d0-11e7-872a-a340685d795d.png)
- The median time to certify a case dropped significantly. Looks like it was roughly halved. The median time it took users to certify a case in Caseflow went from approximately 3 minutes to 1.5 minutes. 
  - This was not a goal of ours, but it is a welcome development!
  - This is likely because we removed the Form 8, which had 20-30 fields to fill out. 
- The median time to certify a case with missing documents also dropped significantly.

## Fuzzy date matching 
Before PR was merged
![image](https://user-images.githubusercontent.com/3781835/31785033-d595d608-b4d1-11e7-9439-6141a4f81043.png)
Most recent week of data
![image](https://user-images.githubusercontent.com/3781835/31785047-e5a65036-b4d1-11e7-99a8-9fbccab0d571.png)

- The fuzzy date matching PR was merged on May 17 (https://github.com/department-of-veterans-affairs/caseflow/pull/2025), so it was likely in production in the next few days (not sure of exact date). It was not gradually rolled out, so we don't expect a gradual effect.
- Fuzzy date matching is applied to only SOCs and SSOCs, so we hoped to see a drop in the missing document % for those two types of documents. Looking at the general trend, it does appear that a small drop has occurred over time. We don't have any baseline as to how much of a drop we expected, so it's hard to draw any conclusions here.
- It would be better to view these metrics by month, but there appears to be a bug in the monthly view, and it doesn't load.
- If we wanted to dig into this further, we could have a dev filter these results by ROs. We expect that predominantly ROs on the West Coast and points further west were affected by fuzzy date matching.

**Comment by laurjpeterson** [comment]
Thanks for compiling all of this!

> Time to certify before regional rollout started
Could we also check time before the pilots started? end of May/early June? 

> This was not a goal of ours, but it is a welcome development!
Nice!

This could be a good time to remind us of the success criteria for v2 laid out in priorities.md:
- [ ] reduce misreported hearing preferences
- [ ] more accurate/up-to-date POA information in VACOLS 
  - When we have more Certification v2 data, we want to track routing errors for those v2 cases. This will help us address the first two success criteria above - reduce user-facing form 8 questions
- [x] reduce user-facing form 8 questions
  - We've clearly reduced user-facing form 8 questions! I think it's worth showing how the time it took to certify decreased over this time period and how we think it is likely due to reducing these questions when discussing this point.
- [x] (add fuzzy date match - not listed in priorities.md but presented during trainings)
  - One of the metrics we capture in the product impact statements is "Percentage of cases with mismatched documents". Perhaps we can update this metric in relation to fuzzy date match. 
  - Or, could we check into how Hawaii's utilization of Certification might have increased? It looks like their utilization of Certification increased drastically recently. 

I agree overall that seeing these metrics month by month would be useful, when we can figure out the bug.

**Comment by amprokop** [comment]
> Could we also check time before the pilots started? end of May/early June?

If you look to the left of the highlighted bar in the screenshot I posted, you can see the bars that correspond to those weeks,. Unfortunately, it's hard to take screenshots with more than one #. This is on the stats page in prod if you wanna look there.

**Comment by amprokop** [comment]
Completed! Closing
