### ISSUE TITLE
RAMP Intake | Auto CEST the EP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#3749]
There is a big desire to auto CEST the EP that we are asking them to create manually now.

## Acceptance Criteria
- The Finish intake page should no longer have steps for creating the EP and the contention
- When the intake is completed, there should be an EP of the appropriate type created in VBMS.
- The Complete page should have another checkbox saying "Established EP: 682HLRRRAMP - RAMP - Higher Level Review Rating for Station 397 - ARC" (or "683SCRRRAMP - RAMP - Supplemental Claim Review Rating" depending on the selected option)

**Comment by abbyraskinUSDS** [comment]
I will add updated mocks. Moving this into triage in the meantime.

**Comment by abbyraskinUSDS** [comment]
I will add updated mocks. Moving this into triage in the meantime. In addition to removing the EP steps, we should update the checkbox language and clarify that we are showing active _eligible_  appeals.

**Comment by abbyraskinUSDS** [comment]
We're still waiting on more info from AMO - they expect to send this to us today.

**Comment by abbyraskinUSDS** [comment]
683: RAMP-Supplemental Claim Review Rating
682: RAMP-Higher-Level Review Rating

**Comment by shanear** [comment]
![screen shot 2017-11-07 at 2 14 16 pm](https://user-images.githubusercontent.com/1596259/32512904-86dd249a-c3c6-11e7-8b80-9455c99a9217.png)

<img width="873" alt="screen shot 2017-11-07 at 2 15 00 pm" src="https://user-images.githubusercontent.com/1596259/32512916-8b000308-c3c6-11e7-8d12-53c5b42ae66f.png">

<img width="956" alt="screen shot 2017-11-07 at 2 15 54 pm" src="https://user-images.githubusercontent.com/1596259/32512923-8e83fcfa-c3c6-11e7-908c-5ee586036a6f.png">

<img width="1258" alt="screen shot 2017-11-07 at 2 17 37 pm" src="https://user-images.githubusercontent.com/1596259/32512932-909afce6-c3c6-11e7-9e49-58691c3e87e9.png">

**Comment by shanear** [comment]
:gorilla: :gorilla: BOOYAH :gorilla: :gorilla:

**Comment by kierachell** [comment]
### YOU KNEW I WAS GONNA DO THIS:

- What happens when there's already an EP in VBMS?
- What is the exit scenario for the user?

https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/527/

<img width="418" alt="screen shot 2017-11-08 at 8 37 26 pm" src="https://user-images.githubusercontent.com/18075411/32584297-932fb0be-c4c5-11e7-80ef-ccaf9be533bf.png">
<img width="867" alt="screen shot 2017-11-08 at 8 42 00 pm" src="https://user-images.githubusercontent.com/18075411/32584298-933e9804-c4c5-11e7-84ba-0a64828af1c6.png">
<img width="890" alt="screen shot 2017-11-08 at 8 42 13 pm" src="https://user-images.githubusercontent.com/18075411/32584299-934b6c00-c4c5-11e7-8187-7f4758aa3999.png">

- You even made an error for it but you don't log it in the Intake model.
<img width="624" alt="screen shot 2017-11-08 at 8 43 11 pm" src="https://user-images.githubusercontent.com/18075411/32584301-93603b58-c4c5-11e7-8bcf-e175bd43655c.png">

**Comment by shanear** [comment]
> What happens when there's already an EP in VBMS?
> Can we make duplicate 683s? 682s?
No, it should error on the duplicate. There shouldn't ever really be a duplicate since Intake should be the only thing creating 682s and 683s and it will catch duplicates earlier. Either way, there might want to be an error message for it:
https://github.com/department-of-veterans-affairs/caseflow/issues/3912

> Can someone have 683 and 682?
We don't check this at an EP level, but we do check it at the RAMP intake level, so it's not really worth checking again at the EP level because it shouldn't happen in theory.

**Comment by kierachell** [comment]
**PASSED**

As discussed with @shanear : we'll fix it as it goes.
