### ISSUE TITLE
Daily Docket | Add # of Issues on Daily Docket page

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#3848]
As a judge I would like to know how many issues are involved in each case that I am hearing. This is most useful for hearing prep. I can see the number of issues, then decide which hearings to prep. This also helps give me an awareness of long it is to prep as well as how long the hearing might take.

**AC:**
Below the veteran ID display:  [x] Issues
If there is only 1 issue display: 1 Issue

**Mock below:** 
(When there is only 1 issue, make sure 'issue' is not plural.)

<img width="565" alt="screen shot 2017-11-03 at 1 13 52 pm" src="https://user-images.githubusercontent.com/22620270/32386989-6ffc10e0-c099-11e7-8e01-3df92aff82e5.png">

**Comment by sharonwarner** [comment]
**Context**

Judges often use the number of issues to decide the order in which they prepare their cases. For example, one judge begins preparing cases with the fewest number of issues and then works her way up to the more complicated cases. It would be easier for the judges if they could see the number of issues for a case on the daily docket page instead of having to click through to every hearing worksheet.

Even just pulling issues from VACOLS for one appeal takes several seconds. Pulling the issues for every appeal in the daily docket on pageload would take way too long. 

**Goal**

We need to preload issues for judge's upcoming hearings so that we don't need to hit VACOLS on the Daily Docket pageload.

**Implementation Details**

1) Cache appeals_ready_for_hearing
1) Create a job that, given a judge's css_id, will pull in appeals_ready_for_hearing for all upcoming hearings
1) Trigger the job to run when the judge loads the upcoming hearings page
1) Create new backend request for Daily Docket page that includes the issue count
Update Daily Docket UI to include the issue count

**Concerns**

We only pull issues from VACOLS once. The earlier we pull them in, the higher the chance that they'll be out of sync. If we pull in issues for all of the judge's upcoming docket days, we'll be pulling issues about a month in advance.

**Comment by sharonwarner** [comment]
@annienguyenUSDS 

Do you think it's ok to pull issues from VACOLS about a month in advance of the hearing?

**Comment by annienguyenUSDS** [comment]
@sharonwarner, yes a month works.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated in: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Navigate to the Daily Docket page
3. Verify that the Issue text is correct. 

Screenshots: 

<img width="1331" alt="screen shot 2017-12-22 at 3 32 26 pm" src="https://user-images.githubusercontent.com/23038505/34311759-7a1a6288-e72d-11e7-9702-c88ebdbf67ad.png">
