### ISSUE TITLE
Log out doesn't work on local dev and possibly all envs

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#3920]
When clicking "Log out" locally, nothing happens. According to @kierachell, log out doesn't work across all envs since we don't clear the session cookie. We should look into this. 

![logout](https://user-images.githubusercontent.com/3781835/32793990-8cb94aaa-c935-11e7-9ee8-b8c05fb2ddf2.gif)

## AC
- After clicking "Log Out", user should be prompted to log back in before accessing Caseflow applications on local dev/demo
- After clicking "Log Out", user should be prompted to log back in before accessing Caseflow applications on UAT/preprod/prod

**Comment by amprokop** [comment]
From @kierachell 

Artem Vovk [2 minutes ago] 
afaik logging out doesn’t work in prod either because we don’t delete the session cookie


Artem Vovk [2 minutes ago] 
So… it’s a buggy feature?? ¯\_(ツ)_/¯


Alex Prokop [< 1 minute ago] 
ah yeah, i’m remembering that now. we should probably fix log in. if someone needs to use another person’s computer, they probably can’t now.

**Comment by amprokop** [comment]
Maybe we should have a quick sync with @shanear on the best path forward here. Log out not working on local dev/demo was an intentional choice, to make testing and dev easier. I do think it would be a drag to have to log in every time on local dev. Is there a way we can have users logged in by default on local dev/demo, but also if someone intentionally logs out, they'll be able to see the login screen?

**Comment by amprokop** [comment]
Or maybe on local dev/demo we can introduce a FeatureToggle so we can turn off default login on local dev/demo? 

@nemodjuric, what do you think?

**Comment by nemodjuric** [comment]
When I click on Logout in Certification UAT, it removes the user name, so it seems like it works. We have a login_spec.rb test that is supposed to test these scenarios, I'll look into it more. @shanear is welcome to shed some light. sh

**Comment by kierachell** [comment]
- It redirects to `help` or `generic` page but does not clear the SAML cookie
![fake_news](https://user-images.githubusercontent.com/18075411/33318716-9ff2cb58-d409-11e7-93c5-b3db54968f1e.gif)

**Comment by lisac-usds** [comment]
Updating with some notes from a Jan 2019 [slack discussion](https://dsva.slack.com/archives/C2ZAMLK88/p1547760961343200?thread_ts=1547745589.332900&cid=C2ZAMLK88):
- on user login, the identity provider (not a Caseflow subdomain) sets a cookie 
- because this is not a Caseflow app cookie (and it's not stored in our cookie store), our app has no direct access to it
- because we don't have access to it, we can't delete it (would be part of the Caseflow logout)
- however: if there exists a logout page/service associated with that cookie, the Caseflow app could redirect the user to that page


It's possible there is indeed a logout service offered by the identity provider. From what I understand, the general idea is that the Caseflow logout action would make this request to the identity provider, which would then redirect to Caseflow:

general idea (not the actual url): `https://<identity_provider_url> /[...]/logout?redirect=https://<caseflow_url>/[...]/postLogout`

**Comment by pkarman** [comment]
This is typically known as SLO (single log out) the corresponding feature to SSO (single sign on) and is part of the SAML standard.

To implement I think we would need to add the correct config to caseflow efolder's omniauth config.

I'm inclined to close this as a won't fix since IMO the effort outweighs the benefit, esp since we've not heard from any actual users about this.

**Comment by pkarman** [comment]
Reopening because we have now seen this in action for Judges in production. It affects users who share computers.

**Comment by pkarman** [comment]
Sent email to OIT requesting documentation on SLO.

**Comment by pkarman** [comment]
Re-sent email to wider audience

**Comment by pkarman** [comment]
We are switching to new SSOi system in Q1 2020 so will reapproach then.

**Comment by pkarman** [comment]
https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1178

**Comment by pkarman** [comment]
seems to be fixed now in SSOi IAM version of efolder.
