### ISSUE TITLE
VACOLS | Add configuration to use forward proxy

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3999]
### Problem:

- We want to use Envoy to proxy VACOLS traffic
- Envoy is now deployed alongside the app
- We need to seamlessly switch between direct and proxied requests
- note that this might require restarting connections/pools as well.

### Solution:
- add a feature toggle of some sort to be able to shift traffic from querying VACOLS directly to localhost:10002
  - https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/utility-roles/forward-proxy/templates/envoy.json.j2#L76

**Comment by amprokop** [comment]
I looked into this. Making the VACOLS-forward proxy path toggleable with a standard FeatureToggle is a lot more more tricky and risky than BGS/VACOLS/VVA, since BGS/VACOLS/VVA requests happen over HTTP and VACOLS queries happen using a shared TCP connection pool, and we warm up half of our VACOLS connection pool when the app starts. 

The easiest way to achieve a toggle might be to use a FeatureToggle & also require app restart (something like `sudo service pumactl restart`, need to find the command) to have the toggle take effect. This comes with the downside that we'll cause a bunch of requests to get cut off if we do need to toggle this on and off in production.

What do folks think?

@lisac-usds @askldjd @kierachell

**Comment by kierachell** [comment]
### Can't you just recreate the connection pool object with a toggle? 
- http://www.rubydoc.info/gems/ruby-oci8/OCI8/ConnectionPool

- Or is it possible to add 2nd pool in database.yml to use localhost settings and the feature toggle will just switch which pool is used by a new request/transaction

The greater benefit of making this work now is making this possible: https://github.com/department-of-veterans-affairs/caseflow/issues/3549

**Comment by kierachell** [comment]
As per: https://dsva.slack.com/archives/C2ZAMLK88/p1511892979000463

We don't need it; just delegate all the VACOLS env vars to `appeals-deployment` where we will set the host/ip/port and etc to use the proxy

**Comment by kierachell** [comment]
This will be covered in appeals-deployment

**Comment by amprokop** [comment]
Sounds good!
