### ISSUE TITLE
Decide amount of spacing between questions in same group

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#400]
Related to #241

**Comment by KHarshawat** [comment]
@webinista I think I was getting too fancy with spacing the groups and questions differently. Since there's no consistent groupings the flow of the page gets thrown off too irregularly. WDYT of keeping the spacing exactly the same (top and bottom) for all questions regardless of groups. I think 20px should do it. Would you be able to send a screenshot of what this looks like?

**Comment by webinista** [comment]
It's easier to just make the change since I'll have to make the markup and CSS consistent anyway.

**Comment by webinista** [comment]
This is what it looks like when there are 20px between questions, regardless of grouping. I think it needs more space between each question, and possibly additional space between each group. What do you think @KHarshawat?

![issue400 2](https://cloud.githubusercontent.com/assets/354277/12123929/a30a2054-b3b1-11e5-96e7-4cb98475bde6.png)
