### ISSUE TITLE
eX Pager Duty alerts

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#4048]
Alerts:

# eX
### 2. DB connection count is greater than 200
* 16 Nov 2017 12:40 PM EST
* DB connection count spike - 11:05 AM EST
* No ALB Connection graph data for that time period

### 3. Could not obtain a database connection within 5 sec 
* 29 Nov 2017 11:01 AM EST 
* DB connections spike - 284 DB connections

![image](https://user-images.githubusercontent.com/3811786/33559226-1a4b707e-d8da-11e7-9730-a8773c379e86.png)

* ALB New Connection Count spike

![image](https://user-images.githubusercontent.com/3811786/33559188-fd5959f4-d8d9-11e7-9637-3b33938cdef5.png)

-----

We have two theories about why we see an increase in latency and the 500's about not being able to get an active DB connection.
1) There was a surge in HTTP traffic to eFolder Express.
1) Increasing the DB connection pool locked up the system and caused us to respond slowly to requests, and reject some.

We believe that number 2 is the more plausible explanation. In the graph below, we see the following. The number of requests decrease over the period of the incident, while the number of active HTTP connections and the latency increases. This correlates directly with an expansion in the DB connection pool. It seems that an increase in the DB connection pool locked up the system for some period of time. While the expansion was happening, the latency of each request spikes, and even though the number of requests drop, since they take longer to resolve, we hold on to more DB connections at any given moment. This causes a cascading effect. When one box runs out of connections the subsequent lockup forces it to not accept any new connections, these new requests get sent to different boxes, and those boxes then run out of DB connections. These then expand the pool, and the lock up themselves. Once all instances are in this lock up state, new requests cannot get a new DB connection because they've run out. 

![image](https://user-images.githubusercontent.com/3885236/33565145-5000bb88-d8ea-11e7-8022-9c87b97a95c7.png)

-----

### Puma thread count vs connection pool count
Currently, in eX 
* Each web server has a DB connection pool of 32
* Each Sidekiq has 64 DB connections max
* puma_min_threads: 40
* puma_max_threads: 80
* puma_num_workers: 1
1. We think puma thread count is too high
2. Each thread needs a database connection, so the database pool needs to be set to (the number of puma threads + 2)

# Caseflow
### 1. Caseflow instances dropped to zero
* 30 Nov 2017 14:15 PM EST
* This correlates to a ton of eX API errors

![image](https://user-images.githubusercontent.com/3811786/33558813-dfa4d9fc-d8d8-11e7-8748-bcfcfa76fab2.png)

* DB connection spike

![image](https://user-images.githubusercontent.com/3811786/33559295-500859f2-d8da-11e7-81dc-4e467efb4741.png)

**Comment by evankroske** [comment]
Why does it take so long to expand the DB connection pool? I would expect it to take the pool less than one second to create a new connection and add it to the pool. How do you know that the pools were expanded?

**Comment by aroltsch** [comment]
I agree with @evankroske that an increase in the DB connection pool would not lock up the system because creating a new connection should be very fast. @mdbenjam

**Comment by mdbenjam** [comment]
Going to write the new post-mortem here and then copy to the PR since it's hard to include images in PRs....

# (WIP) Post-Mortem: 20% Efolder db connection attempts failed for ~15 seconds

269 requests to efolder backend (API and web app) returned 500 errors due to database connection attempt failures over a period of ~15 seconds beginning at 11:01:47 EST and ending at 11:02:01 EST (as indicated by [sentry](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/666/)).

## Status
No longer experiencing elevated database connection error rate. Resolved naturally without external intervention.

## User impact
API and web app HTTP requests' time to response spiked dramatically for one minute (median response time was nearly 10 seconds). We did not communicate this issue to the users of caseflow because the event was over by the time we were investigating it. ![image](https://user-images.githubusercontent.com/32683958/33403687-5afe2fac-d52f-11e7-9d7f-739f71abcd33.png)

## Timeline
* **11:01:47 AM** First of 269 ActiveRecord::ConnectionTimeoutError errors occurs
* **11:01 AM** Sentry posted to Whiskey team slack channel - "ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds..."
* **11:02:01 AM** Last of 269 ActiveRecord::ConnectionTimeoutError errors occurs
* **11:02 AM** Sentry posted to Whiskey team slack channel - "ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds..."
* **11:06 AM** Artem noted in a thread that the database had run out of connections
* **11:08 AM** PagerDuty posted to App Alerts slack channel triggered by "Sum HTTPCode_Backend_5XX GreaterThanOrEqualToThreshold 30.0 for LoadBalancerName dsva-appeals-efolder-prod" cloudwatch alert
* **11:11 AM** Lowell acknowledged this alert in PagerDuty, debugging began with Nick, Sunil, Mark, Anya, and Lowell in Hoth conference room
* **11:45 AM** Debugging stopped for lunch
* **12:00 PM** Lunch was delicious

## Root causes
### Why did we throw an error?
To understand the error, we should first dig into the callstack posted on Sentry. While the callstack within the application code is limited, looking at the full stack trace is informative. Below is the trailing end of the callstack:

```
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.085 seconds)
  from active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
  from active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
  from active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
  from active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
  from monitor.rb:214:in `mon_synchronize'
  from active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
  from active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
  from active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  from monitor.rb:214:in `mon_synchronize'
  from active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  from active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  from monitor.rb:214:in `mon_synchronize'
  from active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  from active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
```

It's illustrative to look into how ActiveRecord connection pools work in our version of Rails (4.2.7.1). Our app is initialized with a set of connections in the connection pool. Every time a thread requests a DB connection, ActiveRecord tries to grab one from the pool. If it cannot, then it tries to allocate another connection. However, if ActiveRecord has reached the hard-cap on number of DB connections then it waits for a connection to become available. If a connection is not freed within 5 seconds, then the `ActiveRecord::ConnectionTimeoutError` is thrown. This suggests we ran out of DB connections.

### Why did we run out of connections?
We began by looking into this graph of our response rate, latency, active connection count, and active DB connections.
![33565145-5000bb88-d8ea-11e7-8022-9c87b97a95c7](https://user-images.githubusercontent.com/3885236/33734099-eef30c5c-db59-11e7-86a1-33773dc35756.png)

Notice how the latency spikes. While our response count doesn't substantively change, the fact that each request takes longer, means that we have more active connections. To get more clarity we look at the number of idle DB connections over this same time period:
![screen shot 2017-12-07 at 2 26 55 pm](https://user-images.githubusercontent.com/3885236/33734536-b4d5548e-db5a-11e7-8252-4b71be951133.png)

Together these graphs tell the following story. A surge in latency caused us to hold on to more requests at one time. Each request acquired a DB connection. During the incident, we ran out of DB connections in the pool and had to expand the pool size. However, during this expansion we either couldn't allocate new connections fast enough, or hit the hard-cap of DB connections and started failing to grab new connections.

### Why did we see a surge in latency?
Digging into the eFolder server logs over the incident we notice some curious things. There are an large number of requests from a single user. They are all GET requests to the `/api/v1/documents/:id` endpoint, and they are only requesting one of two document ids: 12117871 and 12117872. The former is 74.7 KiB, the latter is 7.8 MiB. From 11:01:15 to 11:01:43 we requested the 7.8 MiB doc 334 times. Our requests to retrieve this large doc from S3 slowly took longer and longer to resolve. S3 started out serving our requests within .1-.5 seconds (real time), but eventually took upwards of 20 seconds (real time) to resolve. And many more requests failed to return within the time window of these logs. We believe these requests took so long because our calls to S3 are currently (erroneously) being routed through our NAT. We think this overloaded the NAT and caused a slowdown:

![image](https://user-images.githubusercontent.com/3885236/33735386-1f9442ec-db5d-11e7-9dbb-b70e69b6de66.png)

### Why did we see requests for the same documents over and over?
The final piece to this puzzle is understanding why we are receiving so many requests for just a couple of documents. We can get a hint here by looking at eFolder responses. We see that we periodically have a surge in 304 responses. In the graph below the rightmost blip is the incident in question. But there are other occasions when we received a much larger flood of requests that resulted in 304 responses:
![screen shot 2017-12-07 at 2 46 34 pm](https://user-images.githubusercontent.com/3885236/33735493-75e1a5d6-db5d-11e7-9ff3-976f85809ec0.png)

Digging into logs for these other surges we saw a similar pattern. 2-3 of the same documents were being requested over and over again. In fact, several of these surges were being caused by the same user. Previous surges just didn't request a large enough document to cause a latency spike and therefore went undetected by our DB connection alert. These surges seem to happen with semi-regular frequency.

A quick code inspection didn't reveal any reason we'd be making repeated requests for the same docs. The fact that we only responded with 304 statuses also seemed strange. Circling back to the Sentry error we can see one more crucial piece:

![screen shot 2017-12-07 at 2 51 39 pm](https://user-images.githubusercontent.com/3885236/33735732-2a1a4bc0-db5e-11e7-8a96-4a7664c60eab.png)

A vast majority of users were calling the App from IE. Reader users are the only ones that hit this endpoint, so it appears that the user that triggered these 304 response was using IE. We have known bugs in IE, including a stack overflow exception. This suggests that on IE our frontend can get stuck in an infinitely loop, hitting our server relentlessly.

## What went well?
* Readiness for multiple developers to engage with the alert when it happened
* Coordination between devops and application engineers to bring different knowledge to the table to debug the issue.

## What can be improved?
* Lowell did not realize he could not access AWS until the incident response was underway. Developers should ensure they have access to all vital applications and tools at all times.
* We could have noticed and addressed the surges in 304 errors sooner.

**Comment by mdbenjam** [comment]
Closing this out, PRs were written for both issues:
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/post-mortems/2017-11-29_efolder-db-connection-timeouts.md
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/post-mortems/2017-11-30_caseflow-zero-healthy-instances.md
