### ISSUE TITLE
Daily Docket: Time zones differ

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4054]
in Demo, seeing both EDT/EST. We are using EDT.

<img width="957" alt="screen shot 2017-12-04 at 2 27 16 pm" src="https://user-images.githubusercontent.com/22620270/33572943-738fa362-d902-11e7-9194-1ea8c3da2bab.png">

**Comment by nolawi** [comment]
Its not that it differs - EST and EDT are the same thing. 
 `jun.tz('America/New_York').format('ha z');     // 8am EDT`
`dec.tz('America/New_York').format('ha z');     // 7am EST`

We are by default just showing EST/EDT but our label shows EDT no matter what. 
Now for the timezones - since we are picking the time for each RO we have to use the regular labels. 

@annienguyenUSDS lets discuss

**Comment by astewarttistatech** [comment]
@annienguyenUSDS So what are you looking for to be validated in this ticket since @nolawi mentioned that EDT and EST are the same? Is this ticket perhaps obsolete?

**Comment by annienguyenUSDS** [comment]
@astewarttistatech, we made a decision to update to always show EST/CST/PST from EDT/CDT/PDT so we don't see both versions in #4110 so we can close this.

**Comment by astewarttistatech** [comment]
Sounds good. **Obsolete/No Validation Needed**
