### ISSUE TITLE
Hearing Prep | Update p.m. & a.m. times without periods (am & pm)

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4085]
Story: 
Update all of Hearing Prep pages that show morning and afternoon (a.m. & p.m.) without the periods to be consistent with Reader, and helps removes extra characters on the Upcoming Hearings, Daily Docket and Hearing Prep pages.

AC:
On Upcoming Days, change start times with "a.m." and "p.m." to "am" and "pm".
On Daily Docket, change "a.m." and "p.m." to "am" and "pm" after the time. 

Current: 
Upcoming hearings: 10:52 a.m. EDT
Daily Docket: 1:45 p.m. EDT /12:45 p.m. CST
Hearing Worksheet: Last saved at 4:03 p.m.

Desired: 
Upcoming hearings: 10:52 am EST
Daily Docket: 1:45 pm EST / 12:45 pm CST
Hearing Worksheet: Last saved at 4:03 pm

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Hearing Prep
2. Verify that the Daily Docket page has times with "am" and "pm" instead of characters separated by a "."

Screenshots: 
<img width="1247" alt="screen shot 2017-12-12 at 9 52 57 am" src="https://user-images.githubusercontent.com/23038505/33891007-bc666442-df22-11e7-8ceb-86d98154d8f6.png">
