### ISSUE TITLE
Reader | Bug in jumping between search results within a page

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4098]
#4056 introduced a bug in navigating between search results: when scrolling between results within a page, the document would not scroll to the next mark's position until the user jumped to the result after that.

In PR #4056, in the `PdfFile.scrollToSearchTerm` function, logic to only scroll if the `currentMatchIndex` changed was moved to the top of the function. As a result, the call to scroll the document was only reached the next time the user iterated through search results, scrolling the document to the previously-set `scrollTop`.

## AC
* Load document, run search for term present multiple times on a page.
* Jump between results on that page forwards and backwards. With each jump, the document should scroll to place the mark below the search bar.

**Comment by astewarttistatech** [comment]
**PASSED**

Validated: 
1. Access Reader
2. Access a multipage document
3. Initiate search on one page and scroll away to verify if the search resumes on another page instead of bringing the user back to the next result in the search. 

Screenshots: 
![readersearch](https://user-images.githubusercontent.com/23038505/34048616-6198d2ae-e182-11e7-9617-d4a6b010aaea.gif)
