### ISSUE TITLE
Create a rate Caseflow screen on the congratulations page

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow#417]
We want a way to collect simple feedback on the user experience of the application for every user like lyft, uber, or Airbnb. We'd put this on the congratulations screen. 

We should offer simple 5 star rating on the congratulations screen once every X days and require the user to give a rating before moving onto the next appeal. We if they give anything less than a 4 we should let them provide additional feedback about what can be approved. 

@maryannbrody WDYT?

**Comment by webinista** [comment]
Is this something we can build using the same feedback tool linked in the footer? Otherwise, we need to investigate a service for this. There's currently no database in place to collect this data (which also prevents us from executing #341 and #340).

**Comment by KHarshawat** [comment]
@webinista yeah, this isn't something we'll be able to do anytime soon w/out a DB and I'd rather not hack it w/ our silly sharepoint site but I figure I'd do the mocks now. Creating a new label called "Needs databass" and applying it to those issues and this one :)

**Comment by maryannbrody** [comment]
Hello!

So, I think we should think about the goals and what we're trying to accomplish with this type of feedback. For services like AirBnB and Lyft, ratings are really important because you're actually interacting with a human. But with Caseflow, that's not as much the case - it's a much simpler interaction. I also think it could be kind of annoying for staff who use it all the time (just an assumption).

If we find that it would be valuable, maybe we could ask for more lightweight/concrete feedback -- something along the lines of this: http://www.usability.gov/what-and-why/project-management.html ("was this page helpful?"... but a different prompt along the lines of "Did Caseflow work okay for you/as you expected?")

Thoughts, @KHarshawat ?

**Comment by KHarshawat** [comment]
@maryannbrody A few things ... 

- I like the idea of a more concrete ask such as "How well did Caseflow work with you"
- What I like about Lyft/Airbnb is that the feedback collection is interruptive and required. I was looking at the feedback form we have on the site and in the week that our users piloted it not a single person sent us anything.
- We should not do this to the point at which it's annoying. Here's some ways to avoid that:
     - We should do this at the end of a workflow rather than the middle of it.
     - We should make the feedback mechanism as lightweight as possible (e.g. clicking an option rather than typing free text)
     - We shouldn't ask them every time the use Caseflow but maybe each user once a week or once a month.
     - Any free text should be optional

**Comment by maryannbrody** [comment]
@KHarshawat circling back on this.. 

I think with the addition of your suggestions this sounds good. How about:

- we ask users once a week
- we add this feature in every time we do user testing so we can get feedback on it 
- We ask, "How well did caseflow work for you today?" 
 - Great — everything worked like I expected. 
 - Pretty good — but 1 or 2 things did not work like I expected.  
 - Not great — most things did not work the way I expected. 
 - Terrible — I was not able to do my job at all.

**Comment by KHarshawat** [comment]
@maryannbrody I like all of these suggestions!

We won't be able to do this for user testing right away until we have a database but then we should be good to go! Marking this as unassigned until we get a databass :)
