### ISSUE TITLE
Styleguide | Move styles to Caseflow Commons (part 1)

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#4183]
This is a multi ticket effort to move our common app styles to [Caseflow Commons](https://github.com/department-of-veterans-affairs/caseflow-commons).

For this ticket, the following styles are moved to commons and/or updated to reflect new standards:
* class name `cf-red-text`
* class name `cf-font-light`
* the modal close button using the color `$color-gray-dark`
* table margins in modals are 20px left and right
* removing redundant class name `usa-alert-heading` in `_main.scss` of [caseflow repo](https://github.com/department-of-veterans-affairs/caseflow)

## AC:
- [x] Verify that in Reader, any cases with the distinction "AOD, CAVC" are still in red
- [ ] Verify that in Style guide (under Typography/Font Family), the heading "Source Sans Pro Light" is in a lighter font weight
- [ ] Verify that in Style guide (under Alerts), the alert title is in Source Sans Pro
- [x] Verify that in any modal, the [x] is `$color-gray-dark`

**Comment by astewarttistatech** [comment]
**PASSED**

Since more detailed areas of design are reviewed during PRs. Reader and modals were verified. 

Validated: Preprod | Chrome 

Steps to Validate: 
1. Access Reader
2. Navigate to veterans that have the distinctions "AOD" and "CAVC" respectively 
3. Verify that those distinctions are still `red`.
4. Use the search feature at the welcome gate to open a modal for a veteran (any working veteran ID in BGS/VACOLS will do)
5. Verify that in the modal the [X] is `$color-gray-dark`

Screenshots: 
<img width="1288" alt="screen shot 2017-12-19 at 7 16 55 pm" src="https://user-images.githubusercontent.com/23038505/34185599-436a5a26-e4f4-11e7-97d5-aa8f789d3bd9.png">
<img width="1200" alt="screen shot 2017-12-19 at 7 24 03 pm" src="https://user-images.githubusercontent.com/23038505/34185600-4377bfcc-e4f4-11e7-81bf-fd76b24a8913.png">
