### ISSUE TITLE
BLOCKING BUG: Certification fails on veterans with large eFolders

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#455]
> I am unable to certify the appeal to BVA for the above Veteran.
> It should be noted the Veteran’s VBMS file contains almost 2,600 documents and seems to be timed out while spooling to find the necessary documents to complete the Form 8.  Other appeals for other Veterans (with significantly less documents in VBMS) can be certified using Caseflow before and after attempts for the above Veteran.

Let me know if you need the vet ID.

**Comment by shanear** [comment]
I've committed to having this issue fixed by Nov. 28th, since it's a showstopper for her.

We need to recontact her after the issue is fixed.

**Comment by orischwartz** [comment]
Relevant log entry shows 45 second request to VBMS: 

```
I, [2016-11-15T10:45:37.033745 #3168] INFO -- : sent VBMS request VBMS::Requests::ListDocuments for XXXX: 0.720000 0.040000 0.940000 ( 45.340449)
```

I don't see any errors in the log for this user though. Maybe the timeout is happening somewhere else in the chain. ELB and HAProxy timeouts are both 60 seconds.

**Comment by shanear** [comment]
@orischwartz have you tried loading the form 8 page for this case in prod? does it work?

**Comment by orischwartz** [comment]
Definitely something odd with the data in this case. Case loads in ~50 seconds but none of the fields are pre-populating correctly. 

![image](https://cloud.githubusercontent.com/assets/16327036/20402160/9dcf61c8-acc9-11e6-8f75-ddeac2f31197.png)

**Comment by orischwartz** [comment]
I'll bump the timeouts up to 90 seconds on both ELB and HAProxy (https://github.com/department-of-veterans-affairs/appeals-deployment/issues/215) but the form was coming up blank due to a different bug, now tracking in #464.

After deleting the existing certification record, I am able to bring up the user's case # without a problem. 

@shanear now so safe ask user to attempt again. Closing this issue, cause tracked in #464
