### ISSUE TITLE
Attorney check out | Submit OMO

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4600]
As an attorney, I need to select the type of OMO when OMO reviews are needed. When an attorney assigns an OMO work product to a judge for review, they need to enter in the document ID, mark the case overtime, and input any notes, so the judge can easily find the work product and get context on the case they are signing.

#### User selected "OMO Ready for Review" as the action in the table or appeals detail view and was directed to OMO Review page
- [ ] Verify title of page is "Submit OMO for Review"
- [ ] Verify the instructional text is: 
        "Complete the details below to submit this OMO request for judge review."
- [ ] Verify that there is a section called "OMO Type" with the selections as radio buttons: 
    - OMO - VHA 
     - OMO - IME 
    - OMO work product in VACOLS is updated based on this logic -  https://github.com/department-of-veterans-affairs/caseflow/issues/4525
- [ ]  Verify that there is a checkbox underneath the Work Product with the following copy "This work product is overtime" 
 - The overtime designation is updated in VACOLS per work product logic above
- [ ]  Verify that there is a section called "Check out to" with the name of the Judge who assigned the task
- [ ] Verify that there is a link that shows "Select another judge" next to the Judge name in "Check out to" 
- [ ] Verify that there is a section called 'Document ID" and attorney can type in the document ID number with a required label in secondary color and italicized. 
- [ ] Verify that there is a text field called "Notes" that save back to the VACOLS field 'factors affecting timeliness'
- Notes save back to VACOLS field - 'factors affecting timeliness'
- [ ] Verify that there is a link at the bottom left of the app canvas with the following copy "Go back to draft decision (Appeal ID)" 
- [ ] Verify that the button on this page says "Submit" 
- [ ] Verify that clicking submit takes the user to the OMO confirmation page (#4479)

### Style Guide Components Used (top to bottom)

- Header
- App canvas
- Dropdown 
- Text field 
- Text input label
- Link
- Primary button
- Text area
- Footer

### Mocks and specs
Page title: Heading 1 (34)
All body text: Body (17)
Row labels should be bold 
Spacing should follow existing dimensions from the Queue MVP and Ticket views 

#### OMO Work Product screen 
![select w p - dropdown omo](https://user-images.githubusercontent.com/23316107/36439941-5f4a7fae-163c-11e8-887d-b903788e18f2.png)

### Related Issues
#4255 Queue Table
#4466 Queue Task Details
#4465 Submit draft decision
#4479 Confirmation Screens

**Comment by dannysellers** [comment]
Is there a reason for us to use a different style/location for the breadcrumbs than in other Caseflow apps? Alternatively:

![screen shot 2018-02-13 at 2 12 37 pm](https://user-images.githubusercontent.com/8533004/36168706-fa5b2db0-10c7-11e8-9e0c-a379fa7dc7be.png)

This might also make the "< Back to your queue" link redundant—with a second step in the breadcrumbs at that point, I'd argue it's more obvious that the user can click there to go back, rather than it just being a generic top-level product logo link.

![screen shot 2018-02-13 at 2 15 03 pm](https://user-images.githubusercontent.com/8533004/36168839-64451074-10c8-11e8-8315-503bccd889aa.png)
![screen shot 2018-02-13 at 2 15 23 pm](https://user-images.githubusercontent.com/8533004/36168840-6453a95e-10c8-11e8-93e2-1dce6ef03ad6.png)

**Comment by laurjpeterson** [comment]
hey @dannysellers, a few reasons:
- we're thinking the higher level breadcrumbs helps users distinguish between products - like queue and reader - and since this check out flow is within queue it's ok that the user can follow links to get through it
- we've seen users are more inclined to interact with links versus the higher level breadcrumbs, which look somewhat static
