### ISSUE TITLE
Investigate how Remands work in VACOLS and VBMS

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#476]
It's unclear what needs to happen in VACOLS for a remand to be "re-certified"

Also, do we need to re-upload a new form 8 to VBMS?

We need to figure out exactly whats going on.

See: https://github.com/department-of-veterans-affairs/appeals-pm/issues/165
for more details.

**Comment by shanear** [comment]
@cmgiven do you have any insight here?

**Comment by cmgiven** [comment]
I do, working on this for an unrelated inquiry. Will post some notes here within the next couple days.

**Comment by cmgiven** [comment]
This is the starting point. There's more digging that needs to happen here.

The updated form 8 is something that Abby is hearing about from the ROs (and we heard about in Oakland), but it does not appear that AMC bothers with this. Its absence does not prevent activation of a post-remand case.

There are two items in VACOLS that must be updated:

1. The location needs to be set to 96.
2. The mailing status (BRIEFF.BFMS) needs to be set to "R" (returned, a holdover from paper days).

It obviously must continue to be marked as a VBMS case (FOLDER.TIVBMS).

One open question is whether a case with a pending hearing will be updated in this way prior to the hearing. Will get clarity.

**Comment by shellicious** [comment]
If there's more info that we need on RO workflows, I or a designer can hop on a call with an engineer and dig into this.

**Comment by abbyraskin** [comment]
FYI - according to The Manual, the person recertifying the case is supposed to add annotations to the Remarks section of the Form 8. The DROs and VSRs we interviewed last week mentioned submitting a new Form 8 entirely when recertifying remands (since they can't use Caseflow on remands). 
Re: AMC, it's possible the Claims Assistant we observed simply isn't the one responsible for annotating or uploading the Form 8 (responsibility of DRO/VSR).

@cmgiven how does a user set the mailing status to "returned"? I assume this is different than dispatching to BVA (since you mentioned a case can get activated regardless of whether this happens?).

**Comment by cmgiven** [comment]
This is overloaded terms again. This "dispatch" is different than the "dispatch" on an original certification, which is of course different than the "dispatch" that our team is currently working.

The "dispatch" that doesn't affect activation is for original certifications.

In order to return a remand to the board, AMC/RO will "dispatch" it in VACOLS with the following dialog box:

![remand dispatch](https://cloud.githubusercontent.com/assets/5375557/20526384/d1ae5d5c-b091-11e6-94f3-bcf9fd10c441.png)

If "Remand returned to BVA" is selected, it will be moved to location 96. If "VBMS e-folder scanning complete" is selected, the mailing status will be set to "returned." (Otherwise, that will be set when BVA receives the paper case.)

**Comment by abbyraskin** [comment]
@cmgiven is it possible to figure out the breakdown of re-certifications conducted at AMC vs. ROs? I want to make sure our research is covering both groups appropriately, as well as think more about whether we want to eventually include AMC in (re)certification if they work on the majority of remands. (cc: @shellicious)

**Comment by shanear** [comment]
@abbyraskin @shellicious @cmgiven  Also, do they start a re-certification in the same way in VACOLS (clicking "Certify Appeal")? because it should be opening up Caseflow if that's the case.

Or are they just reuploading a new form 8 and changing the location to 96?

**Comment by cmgiven** [comment]
No, it's a different dialog, the one screenshotted above. Can't speak to the new form 8 process, but there is no "checkout to 96" option, as they do when they move cases between AMC and ROs. They have to use the dialog.

**Comment by cmgiven** [comment]
@abbyraskin 

In order to answer this question, let's look at each time a case (of cases decided in FY16) was moved into location 96. Each of these moves is grouped by the previous location of the case. Primarily, we're interested in cases that moved to 96 from 50 (RO) and 98 (AMC). Based on these numbers, we can say that AMC handles roughly 75% of all recertifications.

50 | 51 | 54 | 70 | 96 | 98 | 99
--- | --- | --- | --- | --- | --- | ---
2,712 | 6 | 5 | 473 | 2 | 8,259 | 4

**Comment by cmgiven** [comment]
BTW, loc 70 is court remands.

**Comment by cmgiven** [comment]
R code for this answer:

```r
test <- event_getPriorLocs(con, "BFDDEC >= date '2015-10-01' and BFDDEC < date '2016-10-01' and BFDC in ('1', '3')") %>%
  group_by(BFKEY) %>%
  mutate(prev = lag(LOC)) %>%
  ungroup() %>%
  filter(LOC == '96')

table(test$prev)
```

**Comment by shanear** [comment]
Another question here is:

If users won't be opening Caseflow Certification by overriding the "Certify Appeal" button in VACOLS (like we currently do it), what will trigger opening caseflow certifications for remands? Will there just be another work queue?

**Comment by cmgiven** [comment]
We could do pretty much exactly what we did before and override the dispatch dialog. They would just have to know to start there in VACOLS, rather than first uploading an updated Form 8 to VBMS.

**Comment by shanear** [comment]
@shellicious scheduled a meeting to ask some questions of AMC and an RO on 12/1.

It's my understanding that we aren't going to try and tackle the whole Remand Order process with the certification update quite yet. Assuming that. We have some open questions about just the "re-certification" process back to the board:

Open questions:
- Are they re-uploading a Form 8. If yes, how are they doing this? What are they modifying?
- There is an EP associated with resolving and recertifying the remanded case. How does this work?

add any more questions here if you have them @shellicious @abbyraskin @cmgiven

**Comment by abbyraskin** [comment]
**Workflow**
- In general it would be great to develop a better high-level view of all the different people at VBA working on a remand at any given time. What are their individual responsibilities? Where do handoffs occur and how are they tracked? 
- (Similar to above...) What are all the steps involved in recertification from beginning to end? Who is responsible for each part?
- How do they know when a case is ready to be recertified to BVA? 
- Which document(s) do they look for? Which document(s) do they fill out and/or upload? Who does this?

**Partial Grants**
- What if the appeal also includes a granted issue? Do they wait for the grant to be authorized/paid before recertifying to BVA? How does this work? Who is involved?
- Are cases ever prematurely recertified to the board? What happens if a case is remanded to the board while some issues are still in development or grants are still being adjusted?

**Clearing the EP**
- If a veteran's profile has multiple EPs, how do they know which one(s) to clear? How does this work for partial grants?

**Comment by shanear** [comment]
Scheduled RO interviews on Thursday afternoon

**Comment by shellicious** [comment]
Draft of interview questions for RO interviews:

Introduction (5 min)

- Talk through goals of the interview
- Warm-up question: how are you doing? What are you working on today? Walk me through your day.
- How many cases are you currently responsible for? How many of those are remands? How many are ready to be certified?
- How many other people on your team work on remands? Where do you hand off cases to each other, and how do you do it?

Caseflow Certification usage (10 min)
-  In the last week, how many cases did you certify via Caseflow? 
- Tell me about cases that you are not able to use Caseflow for, and about how often they occur. Date discrepancies? Missing documents? Form 8 confusion? Pending FOIA requests? Trouble logging into Caseflow remotely?
- Any other reason you aren't able to use Caseflow?

Remand process (15 min) -- screensharing
- Walk me through your process for recertifying a remand.
 - What documents/tools do you use, like checklists or worksheets?
 - What do you do with the old Form 8? Do you make a new Form 8?
 - There is an EP associated with resolving and recertifying the remanded case. How does this work?

Additional remand questions (5 min)
**Partial Grants**
- What if the appeal also includes a granted issue? Do they wait for the grant to be authorized/paid before recertifying to BVA? How does this work? Who is involved?
- Are cases ever prematurely recertified to the board? What happens if a case is remanded to the board while some issues are still in development or grants are still being adjusted?

**Clearing the EP**
- If a veteran's profile has multiple EPs, how do they know which one(s) to clear? How does this work for partial grants?

**Comment by shanear** [comment]
@shellicious do you want to put your notes here?

**Comment by shanear** [comment]
Alrighty, big take aways:

**Re-certifying remands is a completely new feature** Recertification does not involve recreating a Form 8. They just add a small bit of text explaining new evidence to the "Remarks" question on the Form 8. Most of the time, a new SSOC was also added as part of the remand. They also add a Form 21-0960 as a receipt that new evidence was added (I may not have the wording right). It's also initiated by clicking the "Dispatch Appeal" button, which simply changes the location.

After discussing, it looks like this would be a completely new feature that doesn't benefit off of almost any functionality Caseflow Certification already has. Additionally, there is no obvious impact that incorporating Caseflow Certification would have on this process.

**Investigate VACOLS "Dispatch Appeal" Button** If you click Dispatch Appeal in VACOLS it apparently also loads Caseflow Certification. But regardless of what happens in certification, it still moves the location to BVA, which is problematic.

**EPs are actually a lot of busy work during certification** When DRO's are certifying an appeal, they use EPs (Claims) to track what needs to happen on each appeal. VBMS doesn't have the UI to allow them to change or "close out" existing EPs, so they have to use yet another program called "SHARE" (which looks like it was made in Power Builder) to do this.

 We also have a document of all EP codes that Daravann uses when certifying an appeal. We need to follow up with other ROs to see if they use EPs in the same way.

We need to ask Nicholas whether adding an 070 EP is useful/required when certifying to the BVA.

**Comment by shellicious** [comment]
Messy notes are here: https://github.com/department-of-veterans-affairs/caseflow/issues/476#issuecomment-264491246

@shanear let's not close this yet, since we have 2 more remand-related interviews next week with ROs, and pending remand related interviews with AMC folks as well. I'm re-opening.

**Comment by shellicious** [comment]
@shanear has an excellent summary of the notes. It's too early for me to say that recertifying remands is a completely new feature. We might learn more from AMC staff about remands. 

I think there is space in Certification for incorporating remands, and it's worth a whiteboarding session to figure out future Certification flows that can accommodate recertification. I don't think this is a priority for Certification in this or next sprint, since recertifying remands does not appear to be time-intensive or error prone.

**Comment by cmgiven** [comment]
One note here is that we're currently looking into a seam here, cases where VBA says they've returned them to the board but BVA has not picked them up. Addressing that and ensuring that everything is owned by someone at all times is the potential reason to add recertification.

**Comment by shellicious** [comment]
very interesting, @cmgiven! Is there an issue tracking that discovery work?

**Comment by cmgiven** [comment]
Not at the moment. Using "we" broadly. The initial impetus for this one was a list created by VBA, and while I have provided some input to help the Board with triaging that list, it's currently being handled outside the appeals modernization team.

**Comment by abbyraskin** [comment]
@shellicious I pinged Matt at AMC again about connecting us with a DRO/VSR/RVSR at AMC. 

Also, to overlap with some of the ongoing Dispatch discovery...I was thinking we could also ask RO folks today whether the signed decision documented is ever missing from VBMS as they work on a remand, and what they do in this scenario.

**Comment by shellicious** [comment]
@abbyraskin What do you think about closing this issue since we've completed interviews with ROs, and then opening another to track AMC interviews about remands?
