### ISSUE TITLE
Judge queue | Case details | Show document ID and attorney name

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4762]
When a judge is viewing details about a case they have to sign, they want easy access to the document ID, so they can open up the decision document in Microsoft Word for review.

## Acceptance Criteria
- [ ] Verify that the Document ID: ######## and abbreviated attorney name is listed underneath the Veteran name on the queue appeal details page
- [ ] Attorney name is abbreviated [first initial] [.] [last name]

## Mocks
![review case details dispositions](https://user-images.githubusercontent.com/23316107/37788609-3bca51c2-2dd8-11e8-810d-389561305588.png)

**Comment by amprokop** [comment]
Some questions on this for @laurjpeterson and @Chingujo 

1. Previous versions had a dropdown here. Is it no longer in the mocks? If so, how does the judge checkout flow continue from here?
2. Is it confusing that this just says "Document ID" instead of "Attorney Case Review Document ID" or something?
3. Is Document ID really judge-specific? 

Thanks!

**Comment by laurjpeterson** [comment]
@amprokop 

1. no dropdown because this is included in the first release to judges, the judge MVP where judges can view their tasks. the dropdown to complete an action is only needed when judges have the ability to assign to attorneys, the second release to judges

2. i don't think it's confusing necessarily. i don't know of other documents that have an ID like BVA decisions and OMO requests. it's possible for decisions we could say "Decision Document ID" and for OMO "OMO Request ID".

3. good point. i think dispatch staff later on will need to see this.
