### ISSUE TITLE
Investigate if Caseflow checks the boolean behind the "VBMS/VVA" box in Caseflow

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#479]
DRO's currently need to check the "VBMS/VVA" box in VACOLS when they're certifying an appeal.

We think we might already be doing this, need to investigate.

**Comment by shanear** [comment]
@cmgiven do you know the table/column behind this field in VACOLS?

**Comment by cmgiven** [comment]
There are two.

VBMS: FOLDER.TIVBMS
VVA: FOLDER.TISUBJ2

And I knew that off the top of my head, as an indication of how VACOLS is warping my mind.

**Comment by cmgiven** [comment]
Reading this, I would adjust the issue, as these are two separate checkboxes. We need to confirm that the VBMS checkbox is checked. We can leave the VVA one as is.

**Comment by shanear** [comment]
@cmgiven we currently don't do anything with either of these two fields. So you're saying we should make sure the VBMS checkbox is checked before the Form 8 screen is displayed. If it is not, we should a) automatically check it and continue to show them the Form 8 screen, or b) show them an error message telling them to correct it in VACOLS?

And also that the VVA field doesn't matter.

**Comment by cmgiven** [comment]
I would suggest that when we certify, we should set FOLDER.TIVBMS to 'Y'. I wouldn't do that before, like when the Form 8 is previewed, because maybe some reason that would cause someone to not proceed with the Form 8 would also be a reason to not indicate that the case is being worked in VBMS. But at the point at which Caseflow has successfully certified a thing, it should definitely be marked as a VBMS case, so I don't see value in making the user check the box.

**Comment by shanear** [comment]
@shellicious how does Chris's suggestion above sound?

**Comment by shellicious** [comment]
Sounds good to me @shanear and @cmgiven!

**Comment by shanear** [comment]
Created https://github.com/department-of-veterans-affairs/caseflow/issues/483 for the development. Closing this guy. Thanks all!
