### ISSUE TITLE
[Backend] | Update UAT for Hearings Prep demos

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#4987]
Update UAT to use during Rollout Trainings and 4/19 and 5/3.

**Comment by tejans24** [comment]
It might be beneficial to hold off until FACOLS is fully setup? @sharonwarner thoughts?

**Comment by annienguyenUSDS** [comment]
Including updating Case Summary doc types

**Comment by annienguyenUSDS** [comment]
Update Daily Docket to show more Veterans in bold (no appellant).

**Comment by lakohl** [comment]
There are still a number of items that were not accurate in UAT during the training demo on 4/19. If the plan is still to use UAT instead on the Demo environment fro the training on 5/3, we'd like to have these items fixed before 5/3.

Things to fix:

**Your Hearing Days**
- Show RO City for all Video Hearings
- Erase first two calendar dates with inactive links

**Daily Docket**
- Show the earliest hearing time at the top and the rest of the Veterans in defending time order
- Bold the Veteran name when they are the appellant

**Hearing Worksheet**
- Make sure that Periods and Circumstance of Service is auto populated
- Show Prior Issues
- Show multiple appeal streams
- Docs since Certification should be < Docs in Claims Folder

**Case Summary** 
- Display all the Doc Types in the case Summary
- When the Claims folder is ‘unfiltered’ display additional docs that are not part of the ‘Case Summary’
