### ISSUE TITLE
Ensure we can monitor attorney chekout launch

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5055]
Let's ensure we can effectively monitor the health of the attorney phase 2 launch! We'll be deprecating Grafana, so let's not add any more monitoring there.

## AC 

- A Queue Business Metrics dashboard should be created with the following:
  - Attorney Case reviews completed (segment by OMO Request / Draft Decision) 
  - Judge case assignments to attorneys completed
- Ensure that we can monitor response time/response codes(error, success, etc) for the following routes in either New Relic or Datadog: 
  - GET /queue 
  - GET /queue/:user_id
  - GET /queue/tasks/:task_id
  - POST /tasks/:task_id/complete (we're interested in this because we think it might be very slow)

**Comment by laurjpeterson** [comment]
@amprokop @aroltsch - if possible, i'd love to use datadog for this because we have some caseflow dispatch business metrics set up for it!

why are we tracking judge case assignments to attorneys for this release, since judges are still assigning to attorneys in DAS?

Additional thoughts, realizing these might be better serviced tracking elsewhere/in google analytics:
- # times assigned to someone other than the pre-filled judge - to get a sense for how often this happens/how useful the pre-fill is
- # times added issues - to get a sense for how "wrong" VACOLS issues really are
- # times deleted issues - same as above

**Comment by aroltsch** [comment]
@amprokop as far as the endpoints metrics we already have all this info in NewRelic. Sunil and I talked and he said that Nick did a lot of work to ensure we striped PII when sending data to NewRelic. 

Regarding Queue Business Metrics - I can set it up in Datadog. 

* Attorney Case reviews completed (segment by OMO Request / Draft Decision)
* Judge case assignments to attorneys completed
* Number of times attorneys added issues - to get a sense for how "wrong" VACOLS issues really are
* Number of times attorneys edit issues
* Number of times times deleted issues

**Comment by amprokop** [comment]
> @amprokop as far as the endpoints metrics we already have all this info in NewRelic. Sunil and I talked and he said that Nick did a lot of work to ensure we striped PII when sending data to NewRelic.

@aroltsch — cool, can we make sure all that info is easily findable (like with one link), and can we circulate how to get to it to all the foxtrot engs? New Relic also has some sort of custom dashboard feature I've used years ago. It's worth looking into that I think — thoughts?
