### ISSUE TITLE
AMA Intake | Establish HLR End Product

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5239]
This story covers the technical step of creating a Higher Level Review End Product for rated issues in the National Work Queue.

## Acceptance Criteria
- When a user selects the **Establish claim** button on the "Finish" page, we create the End Product associated with that type of review (in this case, HLR).
  - EP code 030 for Higher Level Reviews (rated)
- Establish the EP in the National Work Queue (station 499)
- For now, we're only establishing rated EPs (non-rated will be covered in a later story)

**Comment by leikkisa** [comment]
For both this and SC, we're using the old station code because more work needs to be done before using National Work Queue, station 499.  There's a regional offices place where they're all defined (in which case we would just need the data for National Work Queue), but Abby was saying National Work Queue might be different altogether from a RO.

**Comment by shanear** [comment]
turns out the reason Leah can't do this in UAT is because the ep code is wrong. Need to fix that

**Comment by leahbannon** [comment]
this works - there was also already an 030 and an 031, so it correctly made an 032
