### ISSUE TITLE
[discussion] - foxtrot retro + sprint activities

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5378]
Please provide your thoughts on each discussion topic and their questions by end of day 5/3. Don't hold back! 

## 1. Retro
1. Should we have a **retro** at the end of each sprint? 
2. These are some goals for a session like this. Are there any other goals you would add?
   - continuous improvement
   - pulse check on how the team is feeling
   - opportunity for positive feedback and shoutouts (though we should really be doing these alldatime)
3. What is your opinion on the format should this retro take?
   - e.g. 1 hour, using retrium

## 2. End of sprint activities
1. Should we have a **short, end of sprint activity** where we review tickets slated for the previous sprint?
2. These are some goals for a session like this. Are there any other goals you'd add?
   - preparation for sprint planning meeting on Monday
   - ensure alignment around the end of the sprint and what was accomplished

**Comment by evankroske** [comment]
## Retro
1. Yes.
1. No.
1. 1 hour with Retrium.

## End of Sprint Activities
1. No, I'm not sure what problem this meeting would solve. If someone wants to know what was accomplished last sprint, I think that I could write a GitHub issue query to provide an answer.

**Comment by aroltsch** [comment]
### Retro

1. Yes, good idea. However, every two weeks is often, I would do it once a month
2. No
3. If we do it once a month, 1 hour using Retrium sounds good

### End of sprint activities

I agree with Evan on this.

**Comment by Chingujo** [comment]
## Retro

1. Yes for all the goals stated. +1 to every two weeks - to keep us honest about action items. If there aren't that many topics then it will naturally (hopefully) be shorter. 

2. A minor addition related to continuous improvement:
    - What are our principles (for those joining) and success metrics? Do we need or want to define any?
      
3. One hour sounds good 

## End of Sprint
- Can see why having a deliberate space to review what we accomplished might be helpful to check velocity, alignment, broader goals, and surface any gotchas or dependencies for the next sprint.  
 - Would this be better as a higher level meeting with tech leads, pm, design?
 - If we decide to go with this, what if we made this meeting optional?

**Comment by mdbenjam** [comment]
# Retro
I agree with Anya 1/monthly (ideally alternate big team retro/foxtrot retro).

# End of Sprint
Don't see this being super useful if we already have a standup meeting every day.

**Comment by mkhandekar** [comment]
## Retro
1. Yes
2. Nothing else to add
3. 1 hour block with flexible end time, per sprint

## End of Sprint

I've experienced 2 valuable things during effective sprint reviews:
1. Super quick demos of what was done during that sprint. As a team, we've gone through the tickets in the done column at a very high level and the person responsible for that ticket shares the outcome of their time and efforts. This allows for_all sorts_ of tangible and invisible work to be transparent to the rest of the team.
2. On the other hand, we also go through the tickets (at a very high level) that are still in the "doing" or "to do" column — this time discussing (without blame) why that work wasn't completed, what challenges came up during the sprint that might have blocked work. This is super useful because it helps the team over time improve the way we scope work for upcoming sprints, and helps us prepare for any concerning patterns early and often.

**Comment by oscarAtNava** [comment]
### Retro
1. Yes
2. Nothing to add
3. One hour at most

### End of Sprint
Demo the implementation of each user story. At the conclusion of demo a summary of successes, challenges, and what is left to do. 

I am not keen to review tickets in an all-team meeting. I think we all are curious to know what our colleagues are working on, and what the team objectives are, but at a higher level than individual tickets. These details only pertain to the folks doing the feature implementation.

**Comment by laurjpeterson** [comment]
Looks like most everyone has had a chance to respond and agrees with having sprint retros. Plus, the wider Caseflow team agreed to having sprint team retros during the time of our existing team-wide retro. 

As for end of sprint ticket review, I don't think there is enough appetite for it. Lets monitor going forward, and see if implementation of a better task tracking/kanban board + retro gets us closer to those goals.
