### ISSUE TITLE
Fix hearing worksheet link 

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5390]
When an attorney clicks the Hearing Worksheet link in Case Details, a new tab opens up and the print functionality immediately shows up. I think the expected result is to show the .pdf view of the hearing worksheet, rather than prompt the user to print.

Something like this shows up:
<img width="348" alt="screen shot 2018-05-03 at 4 26 50 pm" src="https://user-images.githubusercontent.com/27704093/39601078-d33e2e48-4eee-11e8-8636-3f65d1598816.png">

## AC
- When the user clicks Hearing Worksheet, the Hearing Worksheet pdf opens in a new tab.

**Comment by lakohl** [comment]
@laurjpeterson there may be room for improvement here. The idea is to supply the attorneys with a non-editable version of the judge's Hearing Worksheet. 

When we were conceiving of the judge view of Hearing Prep we added a 'Save as .pdf' button to the Worksheet because we learned some judges wanted to print their worksheets. We therefore made the font size smaller and squished the items together on the page as much as possible so that the information would print on a single sheet, or if absolutely necessary on a couple pages. The result is that the .pdf works fine when printed, or if it is saved and enlarged, but it's not very readable in the browser. So, when the user clicks 'Save .pdf', we automatically launch the .pdf view in a new tab and open the browser print/save function on top of it (Chrome defaults to whichever you did last, Print or Save). We require the user to take an action (print or save) because we didn't want to end up with a situation where the judge had two different versions of a Veteran's hearing worksheet open at the same time. 

We knew that we wanted the attorney view of the Hearing Worksheet to be 'flattened' - e.g. non-editable. Do to limited resources, we re-used the judge's.pdf function. However, if you decide you want to show a non-editable, non-pdf view of the Hearing Worksheet in the browser, I think that might be better. For the moment the attorney will need to save the .pdf and view it in Acrobat or another .pdf viewer.
