### ISSUE TITLE
How should we manage access control for Caseflow going forward?

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5549]
Access control is a hard problem. Folks debate on whether there is a clear winner on role-based (e.g. "Police Officer") or activity-based (e.g. "Arrest People", "Zoom Through Red Lights") permissions checks. The activity-based approach is generally seen as more modern.

https://lostechies.com/derickbailey/2011/05/24/dont-do-role-based-authorization-checks-do-activity-based-checks/
https://csrc.nist.gov/projects/abac/
https://csrc.nist.gov/Projects/Role-Based-Access-Control

- Currently, Caseflow uses CSEM functions which are meant to be activity-based
    - The way we do so doesn’t neatly match either the activity-based or role-based approach  
    - Some Caseflow CSEM functions are phrased as activities e.g. “Certify Appeal”, “Establish Claim” 
    - Some are phrased as roles e.g. “Reader”, “Hearing Prep”
- Currently, Queue is using feature toggles to manage all access, and complexity in recent weeks has started to become an issue
  - Conceptually, feature toggles are meant to be less permanent than roles/functions
  - Need to establish patterns for when to use each
- The VACOLS staff table is the canonical board list of folks in many roles (Attorney, Judge, Co-located), and it currently is role-based
    - Jed updates this list
    - Seems like a headache to try to move that to CSEM and keep it updated — what’s the real lift there?
    - On first glance, our designs don’t seem like they fully lend themselves to purely activity-based access control. Judges and Attorneys have different Queue list views, for instance— but what is the difference in the activity they are performing by looking at their queue? 
- However, it does seem like introducing more activity-based permissions could reduce some complexity
    - We could introduce CSEM function called View Appeal, give it to everyone at BVA
    - As we roll out throughout the board View Appeal & case_search feature toggle will allow users to see Case Search as their home page
    - We’ll have another function Edit Appeal, editing UI will be hidden if not
    - Who will have this? IDK but there will probably be some users who can view but not edit
    - View Appeal could be given to non BVA users as well if we like
- We don’t have to use CSEM/CSUM for anything new if we don’t want to
    - We have our own list of Functions overrides, we have our own layer where we can manage them along with CSEM
    - However, need to weigh the advantages of having an outside party do the authz management
- Hypothesis: case details-related things lend themselves more to activity-based management, but we'll still need roles

**Comment by laurjpeterson** [comment]
We're at a point where Caseflow products are converging more obviously. We have users using more than one application at a time, and are building ways for them to flow seamlessly from one product to another (e.g. from Queue to Reader). We also have quite a few feature toggles in Queue that might be able to be consolidated (already started with #5474). 

Last summer, we explored relying on CSEM for access permissions, but that is not necessarily the only option. Here's some info about CSEM. 

- CSEM includes "roles" and "functions". In our code, we use the term "role" to refer to what CSEM defines as a "function". For instance, HearingPrep is a role in our code, but a function to CSEM.
- Currently, most applications use the "user" role, but we have different functions related to our applications. As Caseflow adds more products, we want our CSEM roles and functions to accurately reflect our users and products. 
- Post-Standup discussion, August 2017, recognizes merits of using CSEM/CSUM while having control over System Admin role - department-of-veterans-affairs/appeals-pm#1540
- Follow-up, desire to use existing BVA and VBA roles and functions, though they may not be specific enough - department-of-veterans-affairs/appeals-pm#1339
   - Idea was to use a template for CSEM to see, by Role, what Functions a user should automatically have access to. The CSEM initiator would not be able to edit the Functions (e.g. Reader, Hearing Prep) because of the template.
   - For example:

Role | Functions
---|---
Attorney | Reader (inclusive of Queue)
Judge | Reader, Hearing Prep

**Comment by amprokop** [comment]
```
Use a template for CSEM to see, by Role, what Functions a user should automatically have access to. The CSEM initiator would not be able to edit the Functions because of the template.
```

This is an interesting idea — would we be able to edit the Functions then?

**Comment by laurjpeterson** [comment]
What do you mean by editing the functions? Editing which functions each role gets? Or editing what constitutes a function? I believe that yes, we could edit any code related to the Reader function. We can also request new functions from CSEM. Nikita has a better relationship with CSEM folks so this shouldn't take as long to establish as it had originally.

**Comment by laurjpeterson** [comment]
Permissions we have right now:
- VACOLS roles
- System admin protections in our code (Caseflow Commons Functions)
- CSEM functions
- Feature toggles
- BGS access controls - Sensitivity levels + VSO restrictions

**Comment by laurjpeterson** [comment]
Closing, because documentation and discussion about user authorization and access permissions will continue with this PR https://github.com/department-of-veterans-affairs/caseflow/pull/12043
