### ISSUE TITLE
BVA dispatch - October 2018 scope

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5590]
## Background

Broadly, dispatching a case includes the handoff from the judge (who signs the decision) to the BVA Dispatch team responsible for mailing out the decision to both the Veteran, their representative, and congress member (if applicable). The appeal is then routed to the next Area of Jurisdiction (AOJ) the appeal should travel to for adjudication, based on the type of decision. 

The Board built an Interactive Decision Template (IDT) that populates Veteran data from VACOLS, text from the CFR, and other "snippets" of language for decisions from an Access Database into one of the various decision templates in MS Word. All attorneys and judges are now using the IDT for legacy appeals. BVA Dispatch employees use the IDT to review and mail decision letter and have integrated it in to their workflow, too. 

### Business goals
- Reduce processing time from judge signing decisions to outcoding
- Facilitate upload of decisions to VBMS more quickly
- Support AMA legislation and the ability for Dispatchers to outcode AMA appeals

### Internal goals
- Reuse existing Caseflow functionality - like how cases are divided among co-located team members, add/edit functionality
- Seamless transfer from Caseflow Queue to Caseflow Dispatch (if still applicable)
- Increase accuracy of addresses (veteran and attorney) to decrease the amount of returned mail
- Redesign the attorney-judge-BVA Dispatch-Dispatch process by front-loading tasks that attorneys are better equipped to handle and automating manual parts of the process. 

### Stretch goals
- Allow judges to upload decisions into VBMS
- Eliminate BVA dispatch step entirely. When case uploaded and judge signs the case out, issues are final and the appeal is routed correctly via Caseflow Dispatch.

## Top pain points from research
- Lack of updated, trustworthy veteran and attorney data in VACOLS forces Dispatchers to reconcile systems to verify accuracy. This increases the time they spend dispatching a decision and, if the data is incorrect in both systems, delays the vets decision letter.
- Strict regulations make VBMS uploads inflexible for dispatchers, causing them to perform workarounds to get their work done and increasing the likelihood for missed uploads.
- BVA Dispatch employees work in a fragmented, ever changing process that's riddled with edge cases and rules to remember, forcing them to spend time remedying data problems and remember lists of rules and exceptions.
- BVA Dispatch systems and tools (and the process/hacks they must use to navigate them) are prone to human error, increasing the likelihood of errors in decision letters or internal processes, and perpetuating problematic data at the VA.
- A Dispatcher's ability to complete a blocked tasks relies on a feedback loop that's not always reliable or timely for Dispatchers or Judges, causing delays in dispatching decisions or the extreme, which is assigning a case back to 4E.
- Sometimes, Dispatchers are checking data that's already been checked because it's the way they've been instructed to do their job or there is a lack of awareness of how the IDT works.
- Errors addressed by the Dispatch team could often be remedied earlier in the process, creating more work for Dispatchers and reinforcing poor processes.

## User stories
Since this epic touches on several parts of the appeals process, it's broken up into phases (below)

### BVA dispatch distributes cases to team members
- As a BVA dispatch supervisor, I need to distribute work evenly among my team. 
  - Should try to automate, like for co-located admin support. Currently done using a VACOLS batch assignment program that Jed built

#### Open questions
- Who is responsible for batch assignment among BVA dispatch teams?

### BVA dispatch checks and mails decision
- As a BVA dispatch user, I want to view the cases I need to work on all in one place.
- As a BVA dispatch user, I need to see if the case I'm working on has any open mail, so that I can be sure the decision can be sent out. (Case details)
- As a BVA dispatch user, I need to review the decision for errors, so that the veteran and representative do not get incorrect information. (currently done in MS Word for legacy decision letters or Interactive Decision Template)
- As a BVA dispatch user, I need easy access to documentation in VBMS so that I can verify that the veteran's address is correct. 
- As a BVA dispatch user, I need to know when an address was last updated (especially if it's coming from Vet360) so that I can determine if that address is accurate or if I need to go by another source of truth. 
- As a BVA dispatch user, I need to know if a member of congress is still in office so that I know whether or not I should mail a decision letter to that person.
- As a BVA dispatch user, I need to contact judges to correct errors in decision letters, if applicable. 
- As a BVA dispatch user, I need to edit incorrect appeal data, so that BVA has the correct system of record.
- As a BVA dispatch user, I need to print the BVA decision so it can be mailed to the Veteran and representative.

#### Open Questions 
- For the ideal state of the BVA Dispatch process (post October), we need to assess whether or not we rebuild some of the IDT functionality in Caseflow so that we can deprecate the IDT. 

### Upload to VBMS
- As a BVA dispatch user [or as a judge], I need to upload the final, errorless BVA decision to VBMS, so that BVA has the correct system of record.
- As a BVA dispatch user, I need to ensure the that the date on the letter matches the date the decision is uploaded to VBMS because it is required by law for the decision to be mailed and uploaded to VBMS on the same day.

### "Outcoding"
- As a BVA Dispatch user, I need to outcode (or route) decisions to their correct destination so that they can be adjudicated and veterans can receive what they've been granted. 
- As a BVA dispatch user, I need to mail and outcode the BVA decision on the same day. (Current requirement)

#### Other outcoding notes:
- For AMA appeals: 
   - If an issue has a duty to assist error, Caseflow Intake must create a Supplemental Claim EP in VBMS.
- For legacy appeals: 
   - If an issue has a remand, the case is automatically put into the correct VACOLS location (97) so it can be tracked by ROs. 
- At the time of outcoding, the BVA decision date and time is stored in Caseflow DB. Case details for this appeal is updated. 

#### Related Issues
[Issue #5591: Streamline/replace Caseflow Dispatch](https://github.com/department-of-veterans-affairs/caseflow/issues/5591) 

### Resources
- [BVA Org Chart](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Appeals%20background/20180417%20BVA%20Org%20Chart.pdf) for the list of BVA dispatch employees
- [BVA Dispatch workflow](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505351876598/8b1f55b00b530967abaa598a7e6f52829168bb22), Queue discovery, Fall 2017 
- Product Ideas/Key Findings from [BVA Dispatch Research](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/BVA%20Dispatch/Product%20Ideas.md), Spring 2017
- BVA Dispatch functionality within the Interactive Decision Template (IDT) [training deck](https://docs.google.com/document/d/1E5__8Kf0ict8GyRoicrIxvfRO7cC6FdhUD89CtQjR7k/edit)
- Queue discovery [interview guides](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Interview%20Guides.md#colocatedsupport)
- Queue discovery [research plan](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Caseflow%20Queue/Research/Discovery%20project%20outline.md)
- [08 Dispatch Process for the Interactive Decision Template.pdf](https://github.com/department-of-veterans-affairs/caseflow/files/2112988/08.Dispatch.Process.for.the.Interactive.Decision.Template.pdf)
- [Interactive Decision Template training decks](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/BVA%20Interactive%20Decision%20Template)
- [Screenshot of dispatch tab in VACOLS](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Wiki/bva%20vacols%20dispatch%20tab.png)
- BVA Dispatch [discovery/research folder](https://github.com/department-of-veterans-affairs/appeals-design-research/tree/master/Projects/Caseflow%20Queue/Research/BVA-Dispatch)

### BVA dispatch error study
- Most error types were with the POA name, document ID, or other
- Within other, 12 had mail pending and could not be dispatched
- Within other or blank, 3 also had POA issues, bringing POA error totals up
- 8 missing digital signatures

BVA Dispatch team member | Dates participated | Total errors recorded | Cases outcoded | Error rate
---|---|---|---|---|
Randall Davis| 3/5 - 3/9 | 12 | 235 | 5.11%
Tina Hunter | 3/13 - 3/29 | 44 | 516 | 8.53%
Thomas Williams | 3/7 - 3/16 | 9 | 233 | 3.86%
Elizabeth James | 3/7 - 3/19 | 13 | 339 | 3.83%

#### Errors tracked
- Veteran name
- Veteran address
- Docket number
- POA name
- POA address
- Issue dispositions on decision don't match VACOLS
- Missing issues
- Claim number/file number
- Document ID
- Missing digital signature
- Other

### Resources about DTA errors and BEAAM
- Rachel talked to AMO Jennifer about BEAAM remands and post-decision actions. She said they have procedures in place to process DTA errors identified on HLR. They already have issued 433 of these and have readjudicated 24. Jennifer said the higher-level adjudicator drafts a deferred rating using form 21-6789 and creates a 683 EP with a claim label that says something like "HLR DTA Error". She said she would look into getting the Board a special claim label for the 683 EP. If any of our BEAAM decisions identify a DTA error, we would issue the decision and email the AMO-Ops email box separately to alert them of the remand.
- For BEAAM grants/denials, Jennifer agreed that VBA would need to process any supplemental claims through RAMP (using the RAMP Selection Form) prior to the effective date. She initially suggested that we ask the claimants to wait until February and file the AMA supplemental claim form, but then acknowledged that this would be a bad call. They have a full year to file a supplemental claim, so we will need to instruct them that if they want to file prior to February, they do so through RAMP; after February, they'll need to use the real form.

### Email from Marissa Caylor with IDT requests
  1.  An application programming interface (API) to allow the IDT to pull information related to VAIMA appeals from the Caseflow Queue database. **prioritized - Alex will be spiking this week of 7/2**
     *   We have discussed developing APIs for the IDT with Lauren and Alex, but we don’t believe it’s on anyone’s list of things to do.  We wanted to raise the need as something that could cause issues going into implementation.  A testing period would be necessary.
  1.  A technical POC assigned to the IDT. **complete - this is Alex**
     *   If there were someone Paul could contact to ask technical questions before we pursue technical solutions that touch on VADS products, that would greatly assist us in our planning and implementation strategy and process.
  1.  An API for IDT to automate upload of dispatched decisions to VBMS (eFolder). 
     *   Lower priority than the other two, but as part of our changes to the dispatch process, we have been in touch with many people at VBMS to discuss possible ways to automate the upload of Board decisions in dispatch.  They indicated that we should explore whether we could use the API USDS has set up for eFolder.  We have other options, but if this option would work, it would be preferable.

### Decision template types
- Generic Decision and Remand template, which handles the bulk of the types of issues that the Board sees. 
- There are other templates that use a different format or have different appellate rights and notice letters attached to them, like loan guaranty, life insurance, and attorney fees decisions, death dismissals, responses to motions alleging that the Board made a clear and unmistakable error in a prior decision, and decisions vacating Board decisions. 
- VHA opinion and independent medical expert opinions templates. These are actually letters, and look nothing like the Board’s decisions and remands, and they go through the Board using a different process (through the Outside Medical Opinion Office), but are also tracked using VACOLS.

### Pre-IDT dispatch process
Pre-Interactive Decision template dispatch process (see [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505351876598/8b1f55b00b530967abaa598a7e6f52829168bb22) from Queue discovery, fall 2017):
- Judge signs decision with electronic signature in their decision document in Word
- Judge assigns case to locations 31 or 32 in DAS (soon to be Caseflow)
  - As of 4/9, some cases are assigned to location 4E as part of the Interactive Decision Template pilot
- Co-located reviews MS Word decision for errors
- Co-located assigns case to location 30, BVA dispatch, in VACOLS
- BVA dispatch reviews MS Word for checking errors
  - As of 4/9, there is a pilot for BVA dispatch to check for errors using the Interactive Decision Template
- BVA dispatch "outcodes" the appeal in VACOLS
- BVA dispatch uploads the decision to VBMS
- Caseflow Dispatch picks up the decision when it is both outcoded in VACOLS and uploaded in VBMS

**Comment by laurjpeterson** [comment]
Noting that we discussed the desire to build BVA dispatch/outcoding functionality for AMA appeals first. What would be the desirable process to finalize an appeal at the Board and ensure it's ready for transfer to VBA, without the constraints of the legacy process? (There will be legislative constraints, of course.)

We can take a similar approach to co-located admin support - where we built with an eye toward the future state.

**Comment by laurjpeterson** [comment]
@allyceh @amprokop and @laurjpeterson connected on 7/27/2018 to discuss scope. We reviewed the ideal state, october scope, and extra ideal flows in this [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1532611240488/4b7f2aa967e925a9dd9086ca1b8b4f001d74cb47). 

### Next steps 
- Alex to ask BGS about POA address updated dates
- Consider relying on BGS for legacy cases
- Allyce to confirm Vet360 diagram with Steve Kovacs. How often does VBMS fetch updates from Vet360?
- Surface congressional interest mail item for legacy cases in Case details
- Allyce to sit with Rachel to understand legislation around decision and mail date
- Alex to ask Paul about uploading decision to VBMS from IDT
- Allyce to get screenshots from BVA dispatch team for outcoding flow
- Alex to ask Jed for outcoding logic - e.g. change status of appeal, change VACOLS location based on issue dispositions


### Ideas about Scope

Build for BVA dispatch:
- queue
- show document ID
- put on hold (maybe not for RAMP appeals)
- outcoding logic
- feeding into Caseflow Dispatch (?)

Build for IDT:
- give IDT a way to look up an appeal by ID
- Caseflow exposes Veteran address, appellant address, and representative address, and possibly contested claimant (maybe, cached from BGS for x day(s))

**Comment by allyceh** [comment]
On August 14, @laurjpeterson , @nicholasholtz , and I briefly discussed giving board members the ability to edit POA. Here is where we landed: Give people (specific board members TBD, but def Dispatchers) the ability to update the POA name. This does not include editing the POA address. Hopefully, we can tie address to POA name so that when the POA name is edited, their address is reflected. If Dispatchers see any issue with the address, they'll have to reach out to someone else to update it (TBD who this is). As a starting point, we'll see how dispatchers feel about this during testing and make sure it meets their needs.

**Comment by allyceh** [comment]
**High-Level Results from Usability Testing**

*Dispatcher Requests from Usability Testing, likely to be addressed post-Oct*
- Indicate if the veteran is deceased or not (present when there is an About the Appellant section)
- A way to edit veteran name (change the spelling if it’s wrong) or address. A way to change POA or edit address (that's not emailing an admin with SHARE access).
- Other name that the veteran is known by (AKA’s)
- Wants the IDT prompts revised and thinks they’re repetitive. 
- Would be nice if “days waiting” in case details could pertain to the dispatch team members. For example, “days waiting” would represent the number of days a case has been assigned to Dispatch.
- Needs to know if a case has open mail when it’s sent down to Dispatch or when it’s in Dispatch for a couple of days. 
- See if there are contesting claimants (so that he can send both parties copies of the letter)
- Wants to see congressional inquiry 
- Way to upload “tomorrow’s letter” to VBMS the same day. Or, automatic upload. 

*Gaps/Open Questions*
- Need a place to pull VSO address from. Currently, it’s a “database” of addresses maintained in VACOLS by dispatchers (we found out during testing0. Do we pull this address data into the IDT still? Is it wonky to pull VACOLS addresses into the IDT, and everything else is coming from Caseflow? @laurjpeterson @amprokop My take is to pull in the addresses if we can, but want to see what you thought. 
- I think we need a way to “un-do” outdoing, or the decision date that’s logged in Caseflow. Is there a way that Dispatcher could undo this? @amprokop @aroltsch If we need a way to "undo" this, is outcoding like a toggle they switch on when they are done with a case, or switch off if they need to un-outcode?
- Does the IDT prevent judges from sending cases to Dispatch if they have open mail, or just give them a warning that they can override? @aroltsch @amprokop (also maybe a question for Paul). 
- A Dispatcher needs to know if there is open mail when the case is in Dispatch. One solution could be having the Dispatcher look for the "new docs in e-folder" icon that pops up when something has been added. Any flaws in this? @laurjpeterson @amprokop

**Comment by allyceh** [comment]
Met with @mdbenjam @amprokop @aroltsch @lowellrex @laurjpeterson  to chat about Oct Scope, edge cases, and temporary workarounds, based on recent changes + outcomes from usability testing one user. 

Open questions are captured in this mural and below: https://app.mural.co/t/workqueue2001/m/workqueue2001/1535565721180/6fc33e4466b959672928b346bbf07e97a7af9c0a

- Confirm that dispatchers have access to Case Details (@aroltsch is looking into this)
- During next round of testing, ask Libby how she would view if a veteran has new mail in VBMS to vet as a potential solution 
- Ask Jed (?) if we can get an export of VSO addresses from VACOLS since we won't be pulling these in to the IDT
- Dispatcher can view congressional inquiry in VBMS for now. What is the form number that they have to search to find this? Is there also a congressional form in VBMS if there is congressional inquiry?
- Can attorneys tell Dispatchers if a claim is contested since we won't have this data point for Oct? Figure out a way to bake this into their process. 
- Rather than having Dispatchers email finished cases to ARC, we can run a weekly query to find completed Dispatch tasks that we can send to ARC. This will prevent back and fourth emails if a dispatcher needs to re-work a decision and put less burden on the dispatcher to track this via email. Note from @mdbenjam : We could also include a list of special issues (marked by the attorney) in the spreadsheet.

**Comment by allyceh** [comment]
@nicholasholtz cc: @laurjpeterson and @marvokdolor-gov , I am (intentionally) getting in the weeds after usability testing with the BVA Dispatch team and trying to identify any edge cases they might have to handle when using Caseflow on Oct 1 (so that we have a proposed solution). 

Edge case 1: POA is incorrect in Caseflow and needs to be changed.

If POA is incorrect in Caseflow, Lauren and I were talking about two options we have for our pilot users to change it: 
1) We get one of our pilot users access to SHARE so he can be a point person for updating POA during the pilot and for the long-term. He is currently is responsible for making other permissions-based updates in VACOLS and is used to having blockers or problem cases escalated to him. This would help the Dispatch team get cases out more quickly and fix any inconsistencies. 
2) We learned that the co-located team has access to SHARE and uses it. We could have dispatch rely on co-located to update POA. Dispatch could send an email to co-located to request an update to POA. Once Dispatch users have queues later down the line, they could assign a task to co-located to update POA for them, and email goes away. 

I'm a bigger fan of option one because we're letting the Dispatch team solve problems without needing a feedback loop. As we're revisit this again, @laurjpeterson and I wanted your take and to see if there's anything I am overlooking here.

**Comment by nicholasholtz** [comment]
@allyceh Did Rolandus have thoughts on one of them getting access to SHARE? That seems like it could be a relatively small lift if he was good with it.

**Comment by laurjpeterson** [comment]
Notes from convo with Rolandus 9/20:
- Request that Will, Libbie, and Corey have access to SHARE so we don't need to wait for a specific person to dispatch the case
   - @nicholasholtz - do you know who we should talk to to initiate their access?
- Think about asking attorneys/judges to help identify contesting claimants and congressional inquiries because they are required to review the eFolder
- Longer term question - where should VSO addresses truly live? follow up with BGS after the pilot begins?

**Comment by nicholasholtz** [comment]
I believe that Dhonyale should be able to get them set up - standard CSEM stuff. @laurjpeterson

**Comment by laurjpeterson** [comment]
Sent Dhonyale, Rolandus, @nikitarockz, @nicholasholtz, and @allyceh an email to initiate CSEM access for Will, Libby, and Corey. Dhonyale's out of office reply said she would be back in the office on Monday, September 24th.

**Comment by laurjpeterson** [comment]
Closing because we've delivered a solution for BVA dispatchers for October 1, 2018 RAMP appeals pilot. We'll continue BVA dispatch work with #5591
