### ISSUE TITLE
Show overtime cases

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5597]
When judges are assigning cases to their attorneys, they want to see if cases currently part of their attorney's caseload are overtime, so they know they can continue to assign more cases to them.

We can use the work product field to identify that a case is overtime from the backend: 
- OT DEC
- OT VHA
- OT IME

Designs
![judge-table-overtime](https://user-images.githubusercontent.com/31224257/55510865-38ebb800-562d-11e9-8e79-ed05c588f3b5.png) @annekainicUSDS here is the final look of the badge for Overtime (black badge with OT label)

## AC
- If the work product field in VACOLS is either - OT DEC,  OT VHA,  OT IME - show the OT badge on the judge queue 'Review' page and the individual attorney queues on the 'Assign' pages

**Comment by mkhandekar** [comment]
@laurjpeterson can you describe what "overtime" means?  My first assumption was it means "overdue" or that a case has been with the attorney for longer than allocated, but I don't think that quite adds up with "judge can continue to assign more cases to them".

**Comment by laurjpeterson** [comment]
Sure thing! Attorneys can work "overtime" - outside of their normal 40 hour work week. (The Board pays attorneys an overtime rate for these cases, so they definitely want to keep track of them.) Senior Counsel, not judges, typically assign overtime cases to attorneys. They try to assign smaller, less complex cases that could be completed in a single overtime shift. 

If a judge sees that the attorney has some overtime cases on their plate, they know that the attorney will work on them during the overtime shift and not during the work week. This will help the judge knows if they can assign the attorney more cases to work during the work week.

**Comment by mkhandekar** [comment]
Thank you for the context! 

Which would you say is true?
- _this case is overtime_ 
  - then, I'd think this indicator would be part of case details
- _this attorney is working overtime, and so I can assign a few more cases to them_ 
  - then, I'd think this indicator would be part of the judge table (where they're able to see and assign to their attorneys)

Is it also helpful to know _which cases_ an attorney is working on while overtime? I'm not sure this is helpful or true because (I'm assuming!) an atty might start on a particular case while working overtime, and may finish it dring normal business hours?

**Comment by laurjpeterson** [comment]
Both of those statements are true. The second, "this attorney is working overtime, so I can assign a few more cases to them", is the primary motivator for judges requesting this feature. 

Attorneys should not work overtime cases during working hours. Senior counsel/chiefs, not judges, assign overtime cases. This is because Chiefs are management while judges are not, and only management can assign overtime cases.

**Comment by mkhandekar** [comment]
@laurjpeterson should we include this in the "labels" work this sprint, or should it be deprioritized? cc: @sneha-pai

**Comment by tomas-nava** [comment]
Needs design, and detail on source of these parameters: `OT DEC`, `OT VHA`, `OT IME`. Maybe SMALL?

**Comment by laurjpeterson** [comment]
@tomas-nava - luckily, we'e already designed this!

@sneha-pai - reminder to add your designs to this ticket

**Comment by hschallhorn** [comment]
Release notes! Ensure users know only legacy cases will have the overtime badge until followup work is done on marking ama cases as overtime. Do we want to put this behind a feature flag until that's done?
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |
3 | |||||||
5 | |||||
8 | |
```
Can add a field to the serializer for legacy appeals. Can also replicate design for hearing badge.  Hearing badge column may not be generic enough to accept other badges. Could be a 5 because of translating backend information to the front end and further discrepancies between legacy and ama appeals.

**Comment by araposo-tistatech** [comment]
Closing, updated requirements on #13417
