### ISSUE TITLE
Discussion (6/1/2018) - how should we format retro?

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5614]
Please provide feedback on the goals and your ideas for retro.

## Goals of retro
- Provide a safe space to reflect about the team's accomplishments, performance, processes
- Provide enough time to discuss the important issues

> Regardless of what we discover, we must understand and truly believe that everyone did the best job he or she could, given what was known at the time, his or her skills and abilities, the resources available, and the situation at hand.
> - Norm Kerth

## Ideas
- Each person bring their top 1-2 items to retro

## Questions
- How much time should we leave for shoutouts?

## Resources
- For reference: [our last retro](https://funretro.github.io/distributed/#669e969b-f545-481f-bda6-7f7afbc32928)

**Comment by mkhandekar** [comment]
I agree to moving shoutouts to full-team retro -- and, it could be nice to have the _option_ of writing down shoutouts in our retro as they might be fresh on people's minds for that sprint. We can read through the shoutouts on our own time, but not spend any meeting time on them. This way they are also available to us to re-iterate during the full-team retro. I don't feel strongly about this, but agree that we need to make more time for the meaty conversation topics.

I don't see much value in voting within our sprint team retro. We write each comment because it means something to us and every comment is worthy be talked about regardless of how many people agree with the sentiment or felt it's effect. If we move shoutouts to full-team retro, then we also have time to talk through everyone's comments.

**Comment by lowellrex** [comment]
Do we consider team building to be an explicit goal of sprint team retro or is it more of a happy side effect?

**Comment by aroltsch** [comment]
I agree with @mkhandekar that we should read through every comment. Everyone should bring top 1-2 items to retro. I think moving shoutouts to the team wide retro is a good idea.

**Comment by laurjpeterson** [comment]
I also agree with moving shoutouts to full team retro, and also in slack whenever they come up!

@lowellrex - Good question. Are there activities that we'd do in retro that are specifically team building? In general, I think it's prob more of a happy side effect.

**Comment by laurjpeterson** [comment]
discussion 6/1:
- today, we'll try using Retrium again
- we agreed to move shoutouts to team retro, and through slack or in person throughout sprints
- we agreed to read through what went well tickets, but start discussion with what didn't go well to focus conversation there
- we'll try a retro without voting today, and read through all tickets. folks can limit to 1-3 topics they want to discuss. after today, we can better assess what an optimal number of topics to bring to retro are.
- the next time we are all in person at BVA, we'd like to try an analog retro, using post-its instead of computers.
