### ISSUE TITLE
Discussion (5/23/2018) - team format

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5615]
How should we format our team?

## Questions
- How does our team format cultivate teamwork?
- How does our team format cultivate velocity?

## Ideas
- Each engineer owns an epic/project
- Form squads/partnerships around features/topics, etc.
- Others?

**Comment by evankroske** [comment]
I think that a splitting into cross functional teams that own features would help to improve our velocity and the quality of our work. Feedback could be faster because the team would be able to make decisions independently. Because the team would own the features it builds, members could be more incentivized to write maintainable code. Fewer code reviews would have to go to Alex.

**Comment by mkhandekar** [comment]
What might those teams be? Some umbrellas I see that might / might not be grouped together:

- Viewing and prioritizing work (data in tables, filtering, etc)
- Viewing details about a particular case (case details, history & timeline of data, ability to take action)
- Handoffs between teams (assigning to others, viewing what's been assigned to you)
- Overall optimization, accessibility and tightening up of patterns
