### ISSUE TITLE
RAMP election | Close any pending eligible appeals at time of intake

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5681]
Because we are now allowing multiple RAMP Opt-in elections, we are changing the logic here to have a RAMP election close everything out, instead of appeals received before the RAMP Election

## Acceptance Criteria
- When a RAMP Election is processed, appeals should be eligible regardless of their nod date.

## Notes
This story reverses https://github.com/department-of-veterans-affairs/caseflow/issues/5115

**Comment by abbyraskinUSDS** [comment]
@shanear this came up again today - the NOD and Opt-in were received on the same date.

**Comment by abbyraskinUSDS** [comment]
There are a lot of NODs coming in on the same date as RAMP elections. We should minimally close appeals appeals with the same (or earlier) receipt date - not just those dated a day earlier or more.

**Comment by leikkisa** [comment]
@shanear Per the comments are we making it so that the same day are okay, or so that any date is okay?

**Comment by leikkisa** [comment]
Leah to send Sally file numbers, and Sally to check if they have any pending appeals open?

**Comment by leikkisa** [comment]
@shanear I am looking into this, and am wondering in this case if pending means "active"

**Comment by shanear** [comment]
yeah it does 👍

**Comment by leikkisa** [comment]
@leahbannon @suzchap 
All of the currently established ramp elections have no eligible appeals still open, and the closed appeals all have pretty old nod_dates, before 2004.

561349914 isn't established yet, and has an nod_date of January 20, 2018.  Right now we can't take in AMA with a receipt_date before 4/17/2018, but that is arbitrarily set.  I'm asking Shane if I can change it to be before January 20th so that we can validate this ticket.  So don't process that veteran_file_number for now and maybe we can use it later to validate this ticket.

**Comment by shanear** [comment]
This has been deployed for months. We can assume it's working correctly
