### ISSUE TITLE
Inconsistency between development.rb and demo.rb is breaking deployment build

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#569]
This is how RAILS_ENV map to AWS env today.
RAILS demo -> AWS demo
RAILS production -> AWS UAT and Prod

Recently, a new [change](https://github.com/department-of-veterans-affairs/caseflow/commit/cb68525db1bdc4c4c666df81342648eeef3812f5) was introduced to the rails `development` environment. The changes were only applied to `development.rb` and not `demo.rb`. In the AWS deployment `demo` environment, we are using `RAILS_ENV=demo`. This is breaking all deployment to AWS `demo` env. Mirroring the two files would resolve this issue for now.

For long term, ideally, `demo.rb` should always equal `development.rb`. Is there any reason to keep demo separate from development?

**Comment by joofsh** [comment]
development.rb  = local development. It's with non-compiled assets.

demo.rb represents a hosted environment with compiled assets. I added demo specifically so that we could verify things in the asset compilation step worked properly before elevating them to UAT. 

Coupling our local dev configuration to the same as a hosted environment will cause issues long term. I think we just need to be more careful with changes to our configuration file and get more eyes on it before merging to master.

**Comment by shanear** [comment]
We can also put config changes related to all environments in `config/application.rb`
