### ISSUE TITLE
Remove date-picker from editable date fields in Form 8.

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#574]
This one is for you, @webinista 

From usability:
- 2 participants clicked on date picker and quickly used manual entry instead (they were entering dates 3 to 5 years in the past). 

Can you please just remove the date picker?? Let's use the USWDS unless @KHarshawat objects. https://playbook.cio.gov/designstandards/form-controls/#date-input

**Comment by orischwartz** [comment]
@paultag was going to change all of our date fields from HTML 5 date inputs to jQuery datepicker as described in #558.

Using the USWDS standards is actually easier but their code relies on `<input pattern=...` attribute which is only supported on IE10+.

**Comment by paultag** [comment]
I started in https://github.com/paultag/caseflow/tree/paultag/form8-date but context switched away for a minute. What's consensus, replacing with jQuery or removing it entirely?

**Comment by paultag** [comment]
(https://github.com/paultag/caseflow/commit/fb7fc6269a8ecb81d6f8c86b44e8f86fa1195e7c) is a trivial change, it needs to at least change the dates that get sent over to `_date` flavors

**Comment by orischwartz** [comment]
#588 addresses this using the [jQuery masked input plugin](https://github.com/digitalBush/jquery.maskedinput). It's a `text` input that accepts only digits and formats the contents while you type. You can see a demo [here](http://digitalbush.com/projects/masked-input-plugin/). @KHarshawat @maryannbrody any feedback on this approach? 

The USWDS [date](https://playbook.cio.gov/designstandards/form-controls/#date-input) has some drawbacks:
* Needs additional vaildation to ensure inputs are digits
* Needs additional javascript to jump from one field to the next as user types.
* Requires more significant changes to caseflow codebase because it splits what had been one date input field into 3.

**Comment by maryannbrody** [comment]
@orischwartz The approach you posted above seems fine with me from a usability perspective.. Thanks for pointing out the drawbacks and making some recommendations!

cc @KHarshawat
