### ISSUE TITLE
Case details | Case snapshot | About the case

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5744]
With the new Case details design, we've introduced a case snapshot that gives the user a quick view of information about the case, user-specific task information (e.g. admin action type and instructions for co-located, and allows the user to start certain actions. 

This Case snapshot section will look different depending on the user and task associated with it. 

### All users and scenarios
- Verify that there is an 'About the case' section left aligned in the Case snapshot section.
- 'About the case' section includes:
   - Type: e.g. AOD, CAVC, original, post remand - moved from the former location in former case details
   - Docket number
- Currently assigned to: information - @mkhandekar to confirm location of this in mocks

### If a user navigates to case details and the case is assigned to them
- 'About the case' section also includes:
   - Calendar days waiting = calendar days the case has been assigned to them / in their queue

## Out of scope for this issue
- Actions
  - e.g. Judges assigning to attorneys in Case details - https://github.com/department-of-veterans-affairs/caseflow/issues/5303

## Mocks
![image](https://user-images.githubusercontent.com/1598889/40918784-5ad1fb6a-67d5-11e8-8bd7-68332104bdc0.png)

## Resources
- [Case details Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1525112874684/5765d285f568b5f631990e2c8e514a39d9b6b570)

**Comment by lowellrex** [comment]
@mkhandekar I'm curious to get your thoughts on this first pass I made at the case snapshot element:

| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/32683958/40866721-55917e00-65cd-11e8-9243-69647a6bd75d.png) | ![image](https://user-images.githubusercontent.com/32683958/40866680-0dba32a2-65cd-11e8-84ce-03bc36cc0f7c.png) |

A few notes:
* I did not include the "task instructions" item because I don't know where we draw that from. I think that might be a new AMA task field, but am happy to add it back if it should apply to legacy VACOLS tasks as well.
* From what I could tell from the mocks the proportional width of the various sections were 1/4, 1/2, 1/4. The "medical request ready for review" action in the actions dropdown wrapped onto a second line when the container was limited to 1/4 width so I changed the proportions to 1/4, 1/4, 1/2. If we are going to leave the "task instructions" item out of the middle section I think this works fine, but I am definitely open to ideas about how this should look.
* I have not yet added the "view diary" link.
* I have not yet added the "on hold until" item, but will add that as we get deeper into co-located work.

Let me know what you think when you get a minute!
