### ISSUE TITLE
Create script to close appeals that should be closed

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5786]
Appeals that we closed with RAMP are being reopened in the field. We need to automatically reclose these. It would also be nice to know the stats on how often it happens.

- Nightly, we should check all appeals closed with RAMP. If any of them have been reopened, or closed with a different disposition, reclose them with a "P"

## Technical concerns
For post-remands, we will need to check the status of the follow up appeal, not the appeal linked via` RampClosedAppeal`. This will require a little bit of extra logic.

Checking in on all appeals closed with RAMP takes quite a long time (several hours), is the load going to be too heavy for a nightly job?

**Comment by shanear** [comment]
@cmgiven thoughts on this story?

**Comment by cmgiven** [comment]
For post-remands, we could also look at the `RampClosedAppeal`. But the key is not its disposition, but rather whether it remains in HIS status as it should. I assume that would be the one more likely to be reopened, if any, rather than the P record.

I assume several hours is based on iterating through each appeal. Should we instead just run a query to find all of the ones that have been re-opened? That would take only seconds.

**Comment by shanear** [comment]
This has been running successfully for the past couple days and appears to be working well.
