### ISSUE TITLE
Flow 1 | Build Schedule | Upload Errors

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow#5820]
## User Stories 

When Scott and Justin upload a file, they want to know if there are any errors, so they can correct the spreadsheet and re-upload.  

## AC
- [ ] Verify that upload errors are in secondary body and have the following text. 
 - The headers much match the template exactly
    - Error message: We have found column names that vary from the template. Please check your excel file for any additional or different columns and upload the corrected file again.  
  - All dates should all be in this format: mm/dd/yyyy.
    - Error message: All dates must be in the following format : mm/dd/yyyy. Please check your excel file to make sure all dates match this file. 
  - All dates should be within the date range specified by the hearing coordinator
    - Error message: You have already uploaded a file for these dates. Please check your file to make sure you have entered the correct dates. 
- [ ] Verify that when there is an error, the continue button is in disabled styling
- [ ] Verify that the date range becomes editable 

## Mocks
![upload schedule error](https://user-images.githubusercontent.com/23316107/41598617-b11c497e-739e-11e8-91ad-e2d52bc6f274.png)

**Comment by sharonwarner** [comment]
@Chingujo 

Could you send me wording for these errors: 

1) User doesn't select a filetype
1) User doesn't fill out start date, end date, or upload a file
1) User selects an end date that is before the start date

Also, because we have different form inputs inside the radio buttons, the styleguide error formatting looks weird. 

<img width="705" alt="screen shot 2018-07-24 at 5 46 01 pm" src="https://user-images.githubusercontent.com/4306128/43167974-8736f9ce-8f69-11e8-858d-a56a7bd9dd6e.png">

Would something like this work instead?

<img width="691" alt="screen shot 2018-07-24 at 5 47 09 pm" src="https://user-images.githubusercontent.com/4306128/43167997-9d57a3f2-8f69-11e8-986c-c8bc4072d548.png">

**Comment by Chingujo** [comment]
@sharonwarner Sorry this took so long my laptop was bricked most of yesterday

### Rendering error messages
- O no! The first would be ideal. Is it possible to put space between the "to" to make the red boxes render correctly? The main thing I'm worried about is that the red text alone may not give enough of a visual indicator and straying from style guide.
 - Option 1 (most ideal): We remove the to in between the date fields and label the left box with "Start date" and the right with "End date"
- Option 2:  If the above is too difficult, would it be possible to at least include the red line? 

### Copy
- _User doesn't select a filetype_ (does this mean that when the file is not a spreedsheet)
  - To: Please make sure that you are uploading a .xls file and try again.
- _Please enter a start date and an end date, and upload a file_
  - To: Please enter a start and end date and then upload your file again.
- _User selects an end date that is before the start date_
   - To: Please enter an end date that is before the start date and upload your file again.
