### ISSUE TITLE
Block substitute appeals from being eligible for RAMP

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5829]
We are being asked by AMO to block appeals where claimant isn't the veteran. May not be too difficult and will prevent me from having to reinstate a bunch of VACOLS appeals later on down the road.

**Comment by cmgiven** [comment]
We look for whether VACOLS has a non-Veteran appellant listed in the CORRES table. `where CORRES.SSPARE1 is null` will select only those appeals where the appellant is the Veteran.

**Comment by suzchap** [comment]
@leikkisa can you help me get a test ID for this one?

**Comment by leikkisa** [comment]
I think this is a file number where the claimant isn't the veteran:
141102030

**Comment by leikkisa** [comment]
@cmgiven Hey Chris, sorry all of the file numbers I post are for UAT, and we are using UAT for validation.  Understood that Prod data is sensitive.  I've been trying to say so when I do so in emails, but I was taking for granted that Suzanne knew that, and I will be more clear going forward to say the file numbers are UAT file numbers.

@shanear I am wondering where the PR is for this ticket?  I want to see how we approached this.  I found a file number that should be eligible, but it has a SSPARE1 that is different from the Veteran's last name, and in the UI it comes up as ineligible. However, the relationship to the Veteran is listed as "Veteran" (as opposed to child or spouse or something).  I don't think having a different last name from the Veteran is a good way to check if the appellant is someone else, because both a child and spouse could have the same last name as the Veteran.

**Comment by leikkisa** [comment]
All data below is fake test data.
I validated this ticket using Veteran 141102030

When I create a LegacyAppeal for them with their vacols_id, and get the ramp_ineligibility_reason, it is :claimant_not_veteran

The SSPARE1 is different from the Veteran's last name (please see note above that I don't think this is the correct way to check for a claimant different than the veteran, but it seems to be what was implemented).  Otherwise, the data indicates that they would be eligible for RAMP.

![Screen Shot 2018-08-15 at 10.46.31 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9b7c9e7d70200133c2088/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6455f66b7191a379ef0c2f57415c4fbc30254d58eeb9cb74fce36f34985619e8d96f0e76903818aeb18249bb01eb278b4fd7b4b98a4f92fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e54e50a2173465e37f3f6e0a.png)

**Comment by leikkisa** [comment]
Here is the error if we try to intake them:

![substitute_appeal_5829.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9b7c9e7d70200133c2088/125516c66e82c728ace21e0d46fb819830968abd9afdba7ca54de091284a18267156fa693cc7f33ab0487e021b4d44be44505d15feaf8c22a4bf3c268e5c5aead16d0d76c33d12feaa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4c3a1d001e8ffe593da2985985.PNG)
