### ISSUE TITLE
Hearings Queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#5873]
## Background

The high-level tasks we learned the Hearing Branch is responsible for are (See [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505349548084/3eb3bf056f6b342f810f06b2c146c230ea7c2b5a) from research 2017):
- Create hearing schedule (and related tasks)
- Schedule hearing (and related tasks)
- Mark hearing disposition and route (and related tasks)
- Transcribe hearing (and related tasks)
- Process hearing related mail
   - i.e. today, a case is routed to Sal's location. Let's say it's missing a hearing transcript. Sal would process that mail by routing the case to Transcription.

It seems like the main tasks of Schedule hearing and Create hearing schedule should be confined to Caseflow Hearing Schedule, but processing mail when assigned to a Hearing Branch user should be in Queue. Transcribe hearing should also be covered through a connection between Hearing Prep and Queue. When a hearing disposition is marked in Hearing Prep, I think the case should automatically go into a "transcription queue".

## Goals
- Surface actionable mail to the Hearing Branch
- Assign transcribe hearing tasks to the correct user immediately after a hearing

## Non-goals
- Include scheduling tasks in their queue; those should be in Hearing Schedule

### No Show, Cancelled Disposition
- After a Hearing Branch coordinator marks the hearing disposition `No Show` or `Cancelled` in Hearing Schedule, a `Decision` task (?) is created and the case is held in active inventory until it can be assigned to the judge.

### Postponed Disposition
- After a Hearing Branch coordinator marks the hearing disposition `Postponed` in Hearing Schedule, a `Schedule hearing` task (?) is created and the case is held in active inventory until it can be assigned to the judge.

### Held Hearing Disposition and Transcription
- After a judge marks the hearing disposition `Held` in Hearing Prep, a `Transcribe hearing` task is created and assigned to a Transcription user.

- After a Hearing Branch coordinator marks the hearing disposition `Held` in Hearing Schedule, a `Transcribe hearing` task is created and assigned to a Transcription user.

- If the case is an AMA Hearing case, after a judge or Hearing Branch coordinator marks the hearing disposition `Held`, a 90 day counter starts for the Veteran and representative to submit evidence. The case cannot be distributed to a judge before 90 days, unless the Veteran waived the 90 days. 

### Mail and admin action tasks
- When hearing related mail is added to a Veteran's eFolder, a member of the hearing branch needs to be notified, so they can act on that mail if needed. 

- When hearing related mail is added to a Veteran's eFolder and the case is currently assigned to a judge or an attorney, we need to prevent that judge or attorney from continuing work on the case until it's proven that they can do so, so we are sure the Veteran gets due process. 

- If the hearing related mail is transcript related, a Hearing Branch user needs to create a `Transcribe hearing` task and the case needs to be assigned to a transcription user. 

- If the hearing related mail or admin action tasks are `Missing hearing transcript`, `Transcript request`, and `Motion to correct hearing transcript`, then it should be assigned to transcription users.   

Related - [Surfacing actionable mail](https://github.com/department-of-veterans-affairs/caseflow/issues/5950)

### Caseflow Navigation
- As a Hearing Branch user, I want to be able to easily navigate from Hearing Schedule to my queue to view my cases if I need to. 

## Open Questions
- Should the transcription queue be separate from the hearings queue?

## Resources
- https://github.com/department-of-veterans-affairs/appeals-design-research/issues/912
- [Surfacing actionable mail](https://github.com/department-of-veterans-affairs/caseflow/issues/5950)
- [Transcription Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505172017951/a1cb171138fd2172c7c8fcdd45ace1d4c9c0edba)
- [Hearings Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1505349548084/3eb3bf056f6b342f810f06b2c146c230ea7c2b5a)

**Comment by MeredithStewart** [comment]
I'll have to think more on this, but two things that come to mind is having connections to VBMS where appropriate, because like co-located staff, they are often checking. Also, like co-located staff, they are sending out mail. It would be a huge improvement if they could be tracking this as it needs to be done.

**Comment by MeredithStewart** [comment]
I'd also like to explore more if it also makes sense to develop the hearing scheduling to model queue-like structure. I know @Chingujo has also been thinking about this. But there's benefit to thinking of the hearing scheduling in terms of tasks that someone has to do, and serving it in that way to the user. Lots of ideas here that I'd love to explore further.

**Comment by laurjpeterson** [comment]
+1 +1 +1 to thinking about scheduling in terms of tasks! We should leverage the task model wherever we can!

Could you tell me a little more about what the Hearing Branch is checking in VBMS (if you know it)? We are trying to show VBMS data wherever possible - e.g. showing POA from BGS in Case details

**Comment by Chingujo** [comment]
### VBMS
They are looking through the file for the specific hearing clarification letter. Since the labels are not correct in VBMS, they have to check everything since the date of the letter. This task takes about 2 to three hours a day collectively since the entire team is responsible for mail.  They did not find the information we had in Case details too helpful. Mostly, hearings information, RO, POA sometimes, and Veteran information alluding to the hearings screen. The _daily docket_ was the most useful and that is currently in VACOLS.

### Scheduling and Queue model
Yes, was thinking of a queue structure to lighten the admin roles and the UI. The benefit here is that there is less searching and filtering a user has to do to schedule if we can somehow render scheduling tasks. 

 There are complications to this model. For mail, approvals, it makes sense as there are very simple and straightforward. However, for schedules, we would have to write the logic and define what a scheduling task may be. For example, 

- Is it when we know something should be geographically re-scheduled?
- Do we automatically detect when a hearing re-schedule comes in and render the user something to show. How?
- Who are our users? 

I like LP's reasoning where we tackle the definitive tasks firsts such as mail until we uncover what scheduling actually is and what it means. More should be revealed closer to July.

**Comment by laurjpeterson** [comment]
### Re: Mail

> collectively since the entire team is responsible for mail
- I thought Sal was the only team member responsible for mail? Does he assign cases with mail to individuals on the team? Re: document types in VBMS, @nicholasholtz is looking through the available VBMS document types to see which ones are relevant for appeals, and perhaps we can get more specific about hearing related mail. there will likely always be some human error, but we're hoping to rely on them to better route mail. 

> The daily docket was the most useful and that is currently in VACOLS.
- We should totally reuse Hearing Prep's daily docket page! Have you all thought about that as part of Hearing Schedule?

### Re: Scheduling and queue model
I think you're right on. We will need to define the logic for scheduling tasks. Some thoughts I've had, that would need to be approved and vetted by Tango team:
- When we intake an AMA appeal in the Hearing docket, we automatically add a Schedule hearing task
- Anything with a hearing disposition of `Postponed` creates a Schedule hearing task. Assuming reschedules have the disposition of postponed.
- Schedule hearing users I think would be the Board Hearing Branch
- I'm thinking that come February, the Board would own all of the Schedule hearing tasks. I wonder if VBA should have capability to mark dispositions - like no shows. 

There's definitely a lot here to unpack, and I think we can postpone until after your August deadline - I know you need focus on Building the Schedule and thank you both for your thoughts on this already. Let's keep this issue as a place to store all of our thoughts, and when Tango is ready, we can come together and sync define these features.

**Comment by Chingujo** [comment]
@laurjpeterson 

Yup! He does assign the mail across the team. So he is the point of triage for hearings. It looks something like this


Mail team ---> 57 ----> Sal ---> Relevant coordinator*

* = the person responsible for that hearing and/or at least by the type of hearing

So multiple people are doing mail across the team. This may have changed due to the vast amount of mail the hearings team were receiving when we last talked with them at the beginning of queue reearch.

**Comment by laurjpeterson** [comment]
got it - thank you for clarifying!

**Comment by laurjpeterson** [comment]
Closing this github issue in favor of those created by the Hearing Schedule team:
- https://github.com/department-of-veterans-affairs/caseflow/issues/8617
- https://github.com/department-of-veterans-affairs/caseflow/issues/8618

cc: @MeredithStewart
