### ISSUE TITLE
Save EndProductEstablishment to the DB

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6093]
Now that we moved a lot of the end product creation logic to the `EndProductEstablishment` model, we can begin saving.

`EndProductEstablishment` should represent both a point in time where we established an end product, as well as a continual synchronization with the current values of that End Product in VBMS/BGS.

This will allow us to create and track multiple end products for the same AMA review, which is something we will eventually need to do

blocks  #6148 

## Plan of attack
1) Create table with established_at, end_product_status, id (primary id), polymorphic source_id and source_type, :veteran_file_number, :reference_id, :claim_date, :code, :valid_modifiers, :station
Add index to retrieve the end_product_establishments in each RAMP and AMA model with source_id, source_type and veteran_file_number

2) Before creating a new end_product_establishment, check to see if there's an existing established end product in the db with veteran file number and reference id, if so, don't create a new one. Update perform to set established_at and save.

3) Add migration to backfill RAMP end product establishments.

4) Remove double writing to AMA models (what usually happens after `perform!` is called)

5) Update sync job -> app/jobs/ramp_election_sync_job.rb (app/jobs/sync_reviews_job.rb) needs to now sync end_product_establishment instead and still needs to do `RampElection.recreate_issues_from_contentions!`. `RampReview.sync_ep_status!` can likely be moved to EndProductEstablishment. If we use source.sync from EndProductEstablishment, then we can do any model specific sync stuff.

6) Remove double writing to the RAMP models.

**Comment by leahbannon** [comment]
all of the existing models need to be refactored to use this 
main thing: need many:one relationship with AMA review (HLR or SC only)

open questions:
- RAMP?

**Comment by leikkisa** [comment]
Regarding validation, I noticed while looking at UAT data earlier today that the EndProductEstablishments table was not saving the modifier to the DB, although the EndProducts were correctly being created, and other data was being saved to the database.

I checked prod data, and there was a record with a modifier on 7/27, which should have been after this was merged, everything since then is missing it though.  So more investigation is required (like when the PR got deployed, whether it was due to other VBMS issues).  

It's possible we will have to backfill prod data, which should hopefully not be too bad because RampElection is just one end product modifier code.

**Comment by leikkisa** [comment]
For validation:
Kara or Sally to look at UAT intakes that have happened after this, and check the EndProductEstablishments table data for correctness
If there isn't a UAT intake for each type of flow, have Suzanne make a new intake for that type of flow so that we can check the data in the database
