### ISSUE TITLE
Improve judge case assignment screen when there are no cases to assign

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6146]
PR #6143 fixed an issue where judges may have been jarringly presented with a big "TASKS NOT FOUND" message after assigning the last case in their queue by replacing that message with an empty table. In the [slack conversation](https://dsva.slack.com/archives/C6E41RE92/p1531148770000233) related to that PR, we discussed what the ideal empty state of a table should be and how we could unify that approach to those empty states across queue/caseflow. 

In order for this screen (judge case assignment when there are no cases to assign) to match the desired end state for empty tables the following changes need to be made:
* [x] Add text, centered, to table content area: "You currently don't have any cases to assign. When you do, they will appear here."
* [ ] Remove the "assign to" set of UI elements (including dropdown and button) when there are no cases to assign.

**Comment by lowellrex** [comment]
cc @mkhandekar @evankroske @sneha-pai

**Comment by mkhandekar** [comment]
@allyceh @sneha-pai -- We could do something like this, but waiting for content strategy guidance:

![image](https://user-images.githubusercontent.com/1598889/46759305-ef28a300-cc83-11e8-8f95-86c1b3a95b24.png)

**Comment by lowellrex** [comment]
First objective of this ticket was completed by https://github.com/department-of-veterans-affairs/caseflow/pull/7389

**Comment by carodew** [comment]
This is what I see when I impersonate a judge and assign all my cases to my team – 

![image](https://user-images.githubusercontent.com/10144074/69185600-0f609d80-0ae5-11ea-9499-0075221302ed.png)

Since there's a request new cases button right there on the screen, I think the current version is perfectly cromulent. There are some relatively minor usability errors on the screen (assign 0 cases button, for example) but I think these are of lower priority than what we currently have cooking. 

@lowellrex – can you confirm that I'm looking at the right place in Caseflow Demo for the current version of the screen referenced in this issue?

**Comment by lowellrex** [comment]
Agreed @carodew ! Definitely cromulent. I'll close this ticket out.
