### ISSUE TITLE
AMA Intake | 21-22a Intake - Limited POA

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6206]
We need to support issue-based POAs for all AMA review types. The "21-22a" form is the mechanism veterans will use for designating a POA for a specific issue(s).

For appeals, we will need to process this form and store the issue based POA however the queue team decides we should do it.

For HLRs and SCs, we need to be able to process this form because they will need to split an EP into two EPs if a veteran requests a POA for only some of the issues on their review. We will need to maintain the links between these EPs and the review in Caseflow, and there is not a good way to do this in VBMS alone.

Lets begin investigating what it would take for Intake to be responsible for intaking the 21-22a too.

Mural for how it should work in Queue:
https://app.mural.co/t/workqueue2001/m/workqueue2001/1524163475348/3f583e97fd628f81eb05d516c829d3aced02fd57

## Notes
- It is possible to change the "Limited POA" for EPs in VBMS. However, this requires changing each EP individually.
- @laurjpeterson is it possible to change the "Limited" (appeal based) POA on appeals in Caseflow?

## Open Questions
- We need to ask AMO who should be responsible for processing this form and if there is an SOP for it.

requires https://github.com/department-of-veterans-affairs/ruby-bgs/issues/58

**Comment by shanear** [comment]
Had a meeting with @amprokop and @laurjpeterson yesterday where we aligned on the plan in the mural.

**Comment by suzchap** [comment]
Starting to wrap my head around this and have some basic questions... maybe @laurjpeterson knows?

1. Are we incorporating 21-22 and 21-22a or just 21-22a?

2. If a Veteran wants to apply a POA to just one issue out of multiple, how do we know which issue? I don't see a way to specify this on either the 21-22a or on the AMA forms.

**Comment by amprokop** [comment]
2. will require a manual step. Intaking the 21-22a probably will require a
staff member to look at issues on open appeals and decide what to apply it
to.

**Comment by laurjpeterson** [comment]
1. Just the [21-22a](https://www.vba.va.gov/pubs/forms/VBA-21-22A-ARE.pdf). 
2. I agree with Alex's response, based on what we know now. Honestly, it seems hard to do! Since BVA folks process form 21-22a's today, perhaps this is something we could do some research on / ask how they currently know which issues have another POA based on the form.

**Comment by suzchap** [comment]
Thanks to you both for quick responses!

2. Ah so it sounds like there's nowhere that we know of where the Veteran would specify X issue should be connected to Y POA. Yes, we should do some research on that. Who should I ask about that -- or are you going to ask @laurjpeterson?

**Comment by amprokop** [comment]
One more suggestion: I'd love to pursue a solution here that works for both
AMA and legacy appeals, if possible. In my fuzzy imagined scenario where
Caseflow Intake handles 21-22a forms, there are a few possibilities:

1. Save the 21-22a information in the Caseflow DB and then display it on
the Case Details page for every AMA/legacy appeal with that appellant
2. Allow the staff member to immediately associate 21-22a rep choice with
specific issues on AMA/legacy appeals (which then may trigger an appeal
split)

I could also envision something like 1. is the first pass at 22-21a
handling, and 2. is the second pass.

Just some unvetted thoughts here :)

**Comment by amprokop** [comment]
Oh, super sorry to just spew words here— just one more thought that I've
verbalized a few times but never written down on GitHub — one scenario that
I *think* is crucial to correctly handle:

1. Veteran starts an appeal for PTSD with American Legion as the
representative
2. Veteran submits a 21-22a stating "Attorney B will represent me for all
mental health-related issues"
3. Veteran starts an appeal for another mental health issue

How do we ensure that Attorney B, rather than American Legion, is
representing the Veteran for both appeals?

**Comment by nicholasholtz** [comment]
@amprokop The sitaution you described here https://github.com/department-of-veterans-affairs/caseflow/issues/6206#issuecomment-413944714 shouldn't happen. 

First, the [21-22a](https://www.vba.va.gov/pubs/forms/VBA-21-22A-ARE.pdf) is limited to a particular claim (or appeal):

![image](https://user-images.githubusercontent.com/16781398/44286753-3bcda000-a238-11e8-81ef-917e8b43b0a3.png)

Per 38 CFR s 14.630, it is not permissible to make an individual a rep for a category of current and future disabilities:

> §14.630   Authorization for a particular claim.
> (a) Any person may be authorized to prepare, present, and prosecute one claim. 

This ^ is not changed in the proposed draft regs.

**Comment by nicholasholtz** [comment]
Also, you will never see a situation where an entire VSO is appointed pursuant to a 21-22a. This is also due to 38 CFR s 14.630, and what is on the form. The form 21-22a is solely for the appointment of an *individual*:
![image](https://user-images.githubusercontent.com/16781398/44286906-b7c7e800-a238-11e8-81d9-1656002213ac.png)

And, as s 14.630 says, it limits it to a "person" to represent on a single claim. 

Now, you may see a situation where a single person from a different VSO is appointed for a particular claim. Imagine this scenario:

I have an appeal for issues A and B. I am represented by DAV. However, I decide that I want my good buddy @amprokop, who works for, say, VFW, to represent me for issue B. I could file a 21-22a and identify @amprokop as the individual in box 7a and note in box 7b that he is a VSO rep from VFW:

![image](https://user-images.githubusercontent.com/16781398/44286986-168d6180-a239-11e8-9aec-bdb2d2796c30.png)

@laurjpeterson FYI

**Comment by amprokop** [comment]
Aha! Thanks for the correction, Nicholas.

**Comment by amprokop** [comment]
In that case, we *can* just apply the 21-22a representative directly to an
issue.

**Comment by shanear** [comment]
Confirmed with AMO that the 21-22a is the only way to set a "Limited POA" (claim based POA)
