### ISSUE TITLE
Automatically mark cases AOD due to age

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6274]
Veterans who are 75 years or older are automatically Advanced on the Docket (AOD). 

Caseflow should:
- mark cases cases AOD due to age when they are established
- mark cases AOD if they turn 75 at any point in the appeals process 

For reference, today, Jed runs a report each week to identify Veterans who are 75 years or older by their birthdate and adds an AOD diary to their case. 

## AC
- Verify that Veterans who are 75 years or older at the time of case establishment at the Board
- Verify that a Veteran who turns 75 years old at any point in the appeals process is marked AOD

**Comment by mdbenjam** [comment]
I propose two main approaches to this. Both approaches require a change in Intake to save the veteran's birthdate in Caseflow. This can be added to https://github.com/department-of-veterans-affairs/caseflow/issues/6351

# Daily job
Our first option is to setup an active job that runs once a day looking at every appeal (or possibly every active appeal, i.e. each appeal with at least one task), and set the `advanced_on_docket` boolean to `true` if the birthdate is over 75 years ago.

That would look like:
```
class MarkCasesAsAdvancedOnDocket < ApplicationJob
  def perform
    Appeal.where("birthdate < ?", 75.years.ago).update_all(advanced_on_docket: true)
  end
end
```

# Lazily
Our second option is to do it lazily. We can change the Appeal table column from `advanced_on_docket` to `granted_motion_to_advance_on_docket` and create a new `advanced_on_docket` method in the Appeal model that returns:

```
def advanced_on_docket
  granted_motion_to_advance_on_docket || birthdate < 75.years.ago
end
```

Now if a judge asks for new cases using auto case distribution they we will need to know which cases are AOD. This can be done with the query:

```
Appeal.where("granted_motion_to_advance_on_docket='true' OR birthdate < ?", 75.years.ago)
```

# Pros and Cons
The first option has the advantage of code and semantic simplicity. There is one field `advanced_on_docket`, when it is `true` the case is marked as AOD, when it is `false` it is not AOD. It's clear which cases are which. However, the first option involves a job. What happens if the job fails to run? We end up with missing AOD cases.

The second option has the advantage of always being up to date. As soon as someone turns 75 their case will be treated as AOD. We also don't need a job to set this value. However, we lose semantic simplicity. Whenever a user needs to query for advanced on docket cases they'll need to know to run the more complex query
```
Appeal.where("granted_motion_to_advance_on_docket='true' OR birthdate < ?", 75.years.ago)
```
Instead of the first option's simpler and more intuitive query `Appeal.where(advanced_on_docket: true)`

# Which is better?
I'm pretty on the fence, but am leaning to option 2. I think the added complexity of a job probably isn't worth it.

**Comment by cmgiven** [comment]
I'm pretty strongly inclined toward 2. What's stored in the database is immutable and true, and the determination of whether the claimant is AOD or not is stored in application logic. Avoiding the need for a potentially fragile job is a bonus. The need for devs to need to know the more complex query could be avoided by create an aod scope.

One note is I think it makes the most sense to determine AOD at the claimant level, not the appeal level.

**Comment by mdbenjam** [comment]
Ah yeah the AOD scope makes a lot of sense 👍 

When a claimant asks for a motion to get advanced on the docket, does that apply to all their appeals for ever?

**Comment by mdbenjam** [comment]
So maybe we just need to instruct people to change AOD for every open appeal for the veteran?

**Comment by cmgiven** [comment]
Yes. Or we do it ourselves?

**Comment by mdbenjam** [comment]
Yeah editing aod on the case details page could automatically updated aod on all open appeals.

**Comment by cmgiven** [comment]
Side note: it would be great if this was more than a checkbox. Ideally we’d know for what reason the motion was granted (age, illness, financial distress, other). That’s on top of knowing who flipped the box (including if they removed AOD status) and when they did that.

**Comment by mdbenjam** [comment]
Will there always be a document in VBMS if it's not-age-related? Maybe we could either say due to age, or link to the document?

**Comment by cmgiven** [comment]
I think a judge can grant AOD without a formal motion in a hearing. @annienguyenUSDS would know.

**Comment by laurjpeterson** [comment]
- Option 2 seems great to me, too.
- I agree with editing AOD on the Case details page could automatically update AOD on all open appeals (if this is allowed - [slack thread](https://dsva.slack.com/archives/CA1QBDLEL/p1535478824000100) for more info from LRP). cc: @allyce because she will design this functionality. we may need to incorporate some copy to explain this
- @mdbenjam - I believe there should always be a document in VBMS for this - the judge has to sign the granted AOD motion
- Yes, a judge can grant an AOD without a formal motion in a hearing. See Hearing Prep.

<img width="1122" alt="screen shot 2018-08-30 at 11 29 20 am" src="https://user-images.githubusercontent.com/27704093/44862083-f6519f80-ac47-11e8-8d78-b0e1d9bd0d37.png">

**Comment by amprokop** [comment]
Given Chris's comments, would it make sense to have an AODGrants table with 

`reason`
`created_by`
`created_at`
`veteran_id`
`active` (<- to enable a toggle back and forth)

Then if we want to know if an appeal is AOD, we could just:

- determine if the Veteran is over 75, or
- query this table to see if a row exists that was created after the appeal was established

**Comment by mdbenjam** [comment]
I like this idea. Allows us to separate out the AOD information. At some point I think it'd be cool to add a document_id field to let us link to the document in VBMS.

**Comment by mdbenjam** [comment]
@amprokop I think this thread confirms it: https://dsva.slack.com/archives/CA1QBDLEL/p1535478824000100

**Comment by mdbenjam** [comment]
Also I think AOD applies to a claimant not a veteran, right?
