### ISSUE TITLE
IDT API epic

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6358]
This covers the IDT integration work for attorneys/judges and BVA dispatch to support RAMP.

## Background
The Board built an Interactive Decision Template (IDT), which populates Veteran data from VACOLS, text from the CFR and other "snippets" of language for decisions from an Access Database into one of the various decision templates in MS Word. All attorneys and judges are now using the IDT for legacy appeals. BVA dispatch users will be integrating this into their workflow, too.

The Board would like to continue using the IDT for AMA appeals come February 2019, as well as for the RAMP appeals pilot in October 2018. Since Veteran and appeal data for AMA appeals will not be in VACOLS, Caseflow will need to surface Veteran and appeal data to the IDT.

By October 1st, we will have transitioned the attorney/judge IDT off of VACOLS entirely for both legacy and AMA appeals. For the BVA Dispatch IDT, by October 1st we will support AMA appeals but not legacy ones. 

### Done
- [Associate CSS ID with token](https://github.com/department-of-veterans-affairs/caseflow/issues/6361)
- [Return VACOLS appeal list (by user and by file number) from /idt/api/v1/appeals](https://github.com/department-of-veterans-affairs/caseflow/issues/6360)
- [Return more detailed info about VACOLS appeals from /idt/api/v1/appeals/:appeal_id](https://github.com/department-of-veterans-affairs/caseflow/issues/6467)
- [Return user information from /idt/api/v1/user](https://github.com/department-of-veterans-affairs/caseflow/issues/6395)
- [Return list of judges from /idt/api/v1/judges](https://github.com/department-of-veterans-affairs/caseflow/issues/6395)
- [Add additional attributes to /idt/api/v1/appeals/:appeal_id](https://github.com/department-of-veterans-affairs/caseflow/issues/6645)

### Ready for dev

- [Return AMA appeals from /idt/api/v1/appeals](https://github.com/department-of-veterans-affairs/caseflow/issues/6699)
- [Return AMA appeal details from /idt/api/v1/appeals/:appeal_id](https://github.com/department-of-veterans-affairs/caseflow/issues/6700)
- [Ensure BVA Dispatch users can view their AMA appeals when making a call to /idt/api/v1/appeals](https://github.com/department-of-veterans-affairs/caseflow/issues/6890)
- [Allow BVA Dispatch users to receive all claimant and POA addresses from BGS for AMA appeals](https://github.com/department-of-veterans-affairs/caseflow/issues/6701)
- [Allow BVA Dispatch users to complete their tasks using the IDT API](https://github.com/department-of-veterans-affairs/caseflow/issues/6888)

# Under investigation

For @amprokop to investigate

- [Parse and return contesting claimant info and addresses from Power of Attorney wrapper](https://github.com/department-of-veterans-affairs/caseflow/issues/6492)
- Fix skipped IDT appeals controller test
- Figure out citation numbers for AMA appeals and return them to the API
- Determine what to do with the IDTDISPATCH table still in VACOLS - should we continue to use it for AMA?

**Comment by shanear** [comment]
##Proposal: Build a Caseflow Decision Uploader in favor of an IDT Outcode API
Instead of having the appeal be outcoded when it's signed, it should be outcoded when it's uploaded to VBMS. We can do this by building a simple Caseflow widget that dispatchers use to upload the document to VBMS and outcode the appeal at the same time. This would automatically link the VBMS document with the Caseflow appeal. Removing the need to search for the decision document from VBMS after the fact in the Dispatch job.

###Why?
1) It would align incentives for BVA dispatch and processing decisions faster. Right now, BVA dispatch employees are measured on how many appeals are outcoded, not including uploading the Decision document to VBMS, even though it is a necessary step in having the decision processed, and can delay processing for weeks.

2) It would be similar, maybe less than the complexity of modifying current Dispatch processes to support AMA appeals: 
- It would completely remove the need for the Dispatch job to try and match up decision documents. This job is both error prone, and has edge cases that are required by the Dispatch UI to resolve.
- It completely remove the need for the Missing Decision Documents page in Caseflow. This is a win from both the engineering perspective (as most of the fields would have to be switched to come from either VACOLS or Caseflow), and the process perspective (we would no longer have to pester the BVA dispatch team to stay on top of the missing decisions page)
- Since in October, we aren't recording special issues and all dispatch EPs will be routed to AMO, we can automatically generate the dispatch EP in response to the decision being uploaded. 

3) It would be closer to our desired end state. We want to get away from the IDT and have more stuff handled in Caseflow anyways, so this gets us closer to that state with little to no extra work.

**Comment by amprokop** [comment]
Super nice. Will think / talk this through with some folks tomorrow, @shanear. Thanks!

**Comment by amprokop** [comment]
@laurjpeterson, mind taking a look at Shane's proposal and offering thoughts?

**Comment by amprokop** [comment]
I remember there being some rules associated with decision uploads to VBMS — like for example, if it's after 3pm the document doesn't get uploaded until the next day? Is that right?

**Comment by amprokop** [comment]
Yeah — we discussed this with Paul. The interesting bit here is that it might actually be the lowest-effort way to hook up Caseflow Dispatch.

**Comment by allyceh** [comment]
Good stuff here!

@laurjpeterson @amprokop The date on the letter must match the day a letter is mailed. This date must also match the date it's uploaded to VBMS. 

Mail is picked up daily at 3:30 pm. If it's after this time, Dispatchers can still prepare decision letters, but they must date the letter for the following day. They mail and upload the decision letter on the following day because VBMS does not offer date selection for the future; so, they must always upload to VBMS on the day the letter goes out. 

If someone is working from home, the date they choose for the decision letter is the date they'll be in the office next. Example: If someone works from home every Monday and Tuesday, they would date their letters for Wednesday when they're back in the office. On Wednesday morning, they take an hour or so to print out several letters, stuff envelopes, and upload all of these to VBMS before they can start on any new cases. Kind of playing catch up.

**Comment by allyceh** [comment]
@amprokop I like your tweak because it reduces the burden on the Dispatcher. Before we go that route, I am wondering if we might need some sort of date selection for this or way to "back out" of an automatic outcode/upload? See below.

1. Most common use case: It's business as usual, and a Dispatcher prepares a decision letter that will be mailed today. It's outcoded and uploaded to VBMS automatically. Everything is golden.
2. Edge case 1: It's after 3:30 pm, so a Dispatcher dates a decision letter for the following day. The decision is automatically outcoded and uploaded to VBMS and it's routed to it's next destination. Therefore, the Dispatch tool will route the case to ARC prior to the letter actually going out in the mail. **Q:** @sunil-sadasivan @shanear are there any risks in doing this? 
Edge case 3: Someone is working from home and dating their decision letters for the next day they are in the office. They get sick, and don't end up coming into the office for a few days. They must change the date on their decision letters when they get back in. **Q:** Similarly, is there a risk in having decisions outcoded + in VBMS when they'll actually be mailed a couple days later? Do Dispatchers need a way to "un-do" an outcode/upload? Or to select a date that it should be uploaded?

When we were accounting for automatic outcoding (but not automatically uploading to VBMS) earlier, I wasn't concerned about the decision getting to ARC before a letter was mailed because I knew that for decisions to get routed, the decision had to be both 1) outcoded, 2) uploaded to VBMS for the job to pick it up. And since decisions are mailed the same day they are uploaded to VBMS, we would not run into this issue. 

Would love for you all to weigh in on this!

**Comment by shanear** [comment]
> the IDT could upload the decision document through the Caseflow API, which would accept the document upload itself and upload to VBMS.

I pitched this when chatting with Sunil, but he seemed to think that it wasn't possible, but I'm all for it.

**Comment by sunil-sadasivan** [comment]
> I pitched this when chatting with Sunil, but he seemed to think that it wasn't possible, but I'm all for it.

Wasn't sure of what was possible via word macros 🤷‍♀️. Changed my view on this after chatting with Alex and realized Paul (S) was already asking about that possibility.

**Comment by amprokop** [comment]
I’ll talk to Paul about this. Fallback is probably manual processing due to
the number of appeals, but Anya and I can see if we can get this done for
Oct

**Comment by sunil-sadasivan** [comment]
@amprokop yeah I was thinking about that too.  Though in building a widget within Caseflow, we would then have to onboard the BVA staff who outcode on to the Caseflow UI since they wouldn't have access to Caseflow for the October pilots?  Is that correct?

If there's a way around that snag (can we help onboard them on to Caseflow?) I think a widget within Caseflow would make sense esp as it may be what happens for a long-term solution.

**Comment by allyceh** [comment]
@sunil-sadasivan the BVA Staff who are our pilot users will have access to Caseflow! Specifically, the Case Details page to view veteran/appeal information. Unless we think there's a better place for the widget, we could put it on the Case Details page. It seems like we would need to ensure that only BVA Dispatchers can click and/or see this widget. We wouldn't want anyone accidentally uploading-- unless that wouldn't be possible, technically (i.e., there's a rule where a decision would need to be outcoded before the widget becomes active).

**Comment by amprokop** [comment]
Update: @sunil-sadasivan, @laurjpeterson, and i had a long discussion about this. We are considering setting a definite date to start dispatching of RAMP appeals, and considering proposing that it be November 1st. This would give us a bit more certainty and room to plan a solution.

**Comment by pkarman** [comment]
@laurjpeterson I think this Epic is complete?

**Comment by laurjpeterson** [comment]
Yep!
