### ISSUE TITLE
Can we use the VSO organization code for board admin teams?

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#6443]
In order to launch to admin teams at the board we'll need a streamlined way to make new queues. To do this effectively I believe we should move towards very generic queue code where we can store queue parameters in our database to make it simple to spin up new queues. The way we built the VSO queue is the first step in this direction. The VSO queue is built on the idea of organizations within the board. Each organization acts as a user. We can assign cases directly to an organization instead of a user. Then anyone who is part of that organization can view the cases assigned to the organization.

Organizations are defined in our database. We can identify who is part of an organization by looking at their staff record in VACOLS. We can distribute cases by either round robin-ing them to users within the organization, or by providing an assignment flow on the page that lists all the cases assigned to the organization.

Extrapolating this model enables us to build out new queues by just adding rows to the organization table in our database. I propose that in order to keep things constant we always assign tasks to an organization before then assigning them to an individual user. i.e. assign a case to co-located, and then assign a child task to a user. This gives us an automatic admin page, with the ability to override the round robin by going to the admin page and changing who a task is assigned to.

**Comment by laurjpeterson** [comment]
To help this discussion, here is a list of appeals processing tasks associated with organizations at the Board:

Organization | Example tasks | Notes
---|---|---
VLJ Support Management Branch / Co-located Admin Support |- Hearing clarification<br>- POA clarification<br>- Edit case data<br>- Arneson letter<br>- other Admin actions, etc.
FOIA/Privacy Act | - Process FOIA request<br>- Process privacy act request
Hearing branch | - Schedule hearing<br> - Reschedule hearing<br>- Transcribe hearing (includes sending to contractor)<br>- Provide hearing transcript<br>- Motion to correct transcripts | TBD how Hearing Schedule and queue interact; Transcription could be it's own organization
Transcription | - Transcribe hearing (includes sending to contractor)<br>- Provide hearing transcript<br>- Motion to correct transcripts | BVA might prefer this to be included in Hearing Branch organization
Dispatch Branch | - Finalize decisions/outcode decisions |
Case management/case storage |- Mail tasks | TBD, pending more research
AOD | - Process AOD motion |
VSOs |- Write IHP<br>- Prepare for hearing |
Translation | - Translate documents (includes send to contractor |
Lit Support | - Respond to inquiries<br>- Mail tasks | Lit support folks are also attorneys; likely more tasks here
Outside Medical Opinion (OMO) (legacy cases only) |- Acquire outside medical opinion |
Case Review and Evaluation Branch (legacy cases only) | - Activate appeal |

Notes:
- Mail management branch has been excluded, under the assumption that they will only work in the mail portal. Research with mail team may disprove this.
- Did not include reporting tasks
- Did not include intake team here either, because for AMA appeals

**Comment by laurjpeterson** [comment]
- I like the approach of having organizational queues because of the flexibility it provides - we can choose to show org queues or default to round robin
- The only risk I see is mimicking the BVA org chart too much, and keeping up to date with organizational changes. This could be mitigated by building a configuration UI, where admin users map employees to organizations

**Comment by laurjpeterson** [comment]
## Discussion notes
- db or code? assigning tasks to organizations, so db
- add free text tasks if we don't know what all the tasks are yet? store tasks in another table, add and remove tasks easily
- for other admins, we should mimic what we've done for co-located
- judge assignment to attorneys could be the organization queue concept we're looking for
- can we make "completion" generic for everyone? what does it mean for a task to be completed for each type? define this in code?
   - we could add features to "mark tasks as done"
   - so far, we've been taking an integrative approach to completing tasks - e.g. complete = assign back to attorney
- assignment could be different across organizations, too
   - co-located = round robin. try to incorporate with other queues
- creating tasks outside of tree model vs. tasks inside of tree model

## Action items
- @mdbenjam - to write a more detailed spec, e.g. with models, some psuedo code, rollout plan
- @mdbenjam and @laurjpeterson to connect on FOIA, QR, mail, AOD

**Comment by laurjpeterson** [comment]
re: action items:
- tech spec here - https://github.com/department-of-veterans-affairs/caseflow/issues/6573
- mark, lowell, and lp connected on teams 8/8

**Comment by laurjpeterson** [comment]
This work is tracked here: https://github.com/department-of-veterans-affairs/caseflow/issues/6573
