### ISSUE TITLE
Intake | Investigate how to retrieve data for which contentions are connected to rating issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6545]
VBMS said that their is a way to retrieve which rating issues are connected to which contentions. We need to investigate which endpoint we should call to get this data.

Background here:
https://github.com/department-of-veterans-affairs/appeals-design-research/issues/932

## Acceptance Criteria
- We should know the service required to retreive this data. There should be an issue to add the code necessary to call the service needed to retrieve this data.

**Comment by leikkisa** [comment]
It turns out this is most likely in BGS
Ratings sends the contention ID and rated issue ID after finalizing the rating

Nate suggests we look at these:
manageRatingProfile
manageRatingProfileForAwards

I'm noticing these might also have information:
RatingManagementService
RatingInformationService

I think the next step is to look at the WSDL

**Comment by leikkisa** [comment]
We believe this is in the RatingInformationService as the rbaIssueContention.  In order to check this, we need to have test data where new decisions/awards come out after a Claim Review.

We also need to figure out tracking contentions that are denied.

**Comment by leikkisa** [comment]
Test data set up on test file number 123458311, modifier 032

**Comment by leikkisa** [comment]
Looks like it's called cntntnId, and it's in rbaIssueContentions in RatingInformationService.

**Comment by leikkisa** [comment]
Created development ticket  #7278 and am closing this research ticket.
