### ISSUE TITLE
Replace gender pronoun with just gender

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6547]
We currently extrapolate the Veteran's preferred pronoun from the gender field in VACOLS. We'd like to change that to just show gender. 

## AC
- Verify that Case details now displays "Gender:" M or F
- If the gender field is null, display ...

**Comment by lowellrex** [comment]
Yup! Should be a relatively quick tweak (and after I make it we can put this label in `COPY.json`!).

For what it's worth, I think this field is *not* the person's gender but rather their sex. VACOLS has only a field in the database for gender, and not one for sex. I don't know where the information that populates this field comes from (doesn't look like the NOD form has either a gender or a sex field), but in my experience military and government forms generally ask for a person's sex and not their gender.

I mention all of this because I suppose we are making this distinction between sex/gender here to be more accommodating to people whose gender identity differs from their sexual assignment, but I fear the data we are using may actually be their sex and not gender, which gives the appearance that we assume this person's gender is the same as their sex.

**Comment by laurjpeterson** [comment]
What if we changed the name of the field to Sex instead of Gender? @nicholasholtz @sneha-pai @allyceh what do you think?

**Comment by allyceh** [comment]
@lowellrex  you bring up a good point. Is there a way that we can find out how this information gets into VACOLS today? Like, where we get it from and what people are asked to fill in (sex or gender)? I feel like it's important to know in order to accurately label. 

I haven't seen anything about the veterans gender/sex from Intake, unless I missed it. Would Jed be a good person to ask? Or Ivy, since she's on the front lines of many things?

**Comment by lowellrex** [comment]
The field label and values have been moved to `COPY.json` so they can be more easily changed. After we deploy tomorrow the labels will read "Gender: Female" or "Gender: Male" and can be edited here: https://github.com/department-of-veterans-affairs/caseflow/blob/01f9bbcf748c1d3267530503c4034ec90108d9bb/client/COPY.json#L57
