### ISSUE TITLE
Research: How are AMA appeals associated to a RO?

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/caseflow#6585]
**Question**
In order to see the associated RO to a hearing, it will be interesting to find out if AMA appeals are associated to an RO? Since the Legacy Appeals are (https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/legacy_appeal.rb#L32) associated to an RO, it's easier to find that information.

Is this information in BGS?

**Goal**
We want to figure out which RO the Veteran should be associated to when we want to slot them for hearings.

**Comment by MeredithStewart** [comment]
There is some complications with the associated RO for **Legacy** cases that we'll need to talk through and learn more about: 
* From Justin Madigan, we've learned that appeals have been shifted to be worked on by different ROs that they would have been done traditionally. 
* This appears to have also happened for appeals that have hearings. Justin described that some of Colorado's cases were moved to Cheyenne to be worked. One of those was a Veteran that needed a hearing and that Veteran needed to be moved back to Colorado RO so that they could be scheduled for a hearing. 
* The moving of cases is happening so that the RO that works them is getting work credit for working the cases.

**Comment by MeredithStewart** [comment]
For AMA: 
* Do we need to assign an RO at intake? 
* Do we rely on the BGS station of jurisdiction? 
* Meredith: Do we need another data element - location of hearing?

**Comment by MeredithStewart** [comment]
We should talk to Shane about this one. Is intake having some sort of association with an RO? Otherwise, we'll need to decide how we want to associate to an RO.

**Comment by MeredithStewart** [comment]
We talked to Intake about this -- they didn't have a plan for pulling in station of jurisdiction and indicated that we needed to explore that data element further. 

For AMA hearings -- Using our geo-location, we will map the the appellants address to a Regional Office based on home address.
