### ISSUE TITLE
Prevent requests that assume user works at board when loading Queue

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#6622]
Currently, we make a handful of requests from the Queue frontend when loading the personalized task queue. Some of these requests assume the user works at the board and fail when the user is neither an attorney nor a judge (or colocated admin?). In order to support VSO users, we need to be able to load the queue for the various VSO organizations.

We can handle this a number of ways, but the simplest is probably just to avoid making requests that assume the person accessing the page works at the board by default.

**Comment by mdbenjam** [comment]
This line causes a 403: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueLoadingScreen.jsx#L45 because we can't access that endpoint.

This line makes us not make the call to the endpoint we need, because VSO are not attorneys or judges:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueLoadingScreen.jsx#L59

This no longer works since it is for legacy appeals not ama appeals and ama tasks which is what VSO tasks/appeals are: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueLoadingScreen.jsx#L72

We probably should just make an organizational loading screen to avoid all these problems, and replace it here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueApp.jsx#L133
