### ISSUE TITLE
Data Structures | Caseflow parent records and hearing days

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#6741]
Meet with Oscar, Sharon, and Teja to confirm data structures, and then create them in Caseflow.

**Comment by oscarAtNava** [comment]
Meeting took place, Below are the notes, which are also in the tech spec.

August 28, 2018
Merge Central Office and Video Hearing Day into one table and move hearing_type to consolidated table.
appeal_id - how do we associate to both LegacyAppeal and Appeal models.
How is team assigned? Do we need it? In VACOLS UI the team field is populated based on what is on the staff table for the judge.
Remove veteran_id as this information can be fetched from the appeal.
Remove media_type? For hearings since September 2017 there were 25 which used cassette tape.
Rename media_problem to recording_problem.
Rename hold_days_vlj to hold_days. Does it generate an alert after n days?
Separate hearing prep data from hearings data? When appeal is rescheduled do we want to keep the hearings detail data? We would move the hearings row and associate it with another HearingDay row.
