### ISSUE TITLE
Transaction in EndProductEstablishment.sync can time out due to BGS call

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6811]
It looks like we are making a BGS call in the middle of a transaction in `EndProductEstablishment.sync`. This is causing a timeout when BGS is #ultraslow.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2355/

**Comment by shanear** [comment]
This isn't a ticket we really need to communicate with BGS about. Removing the BGS label.

**Comment by pkarman** [comment]
may be addressed by #7111

**Comment by pkarman** [comment]
It looks to me like the call is:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/higher_level_review.rb#L68

which should now run async and not tie up the psql transaction.

It is called from:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/higher_level_review.rb#L51
via
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/claim_review.rb#L71
via
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/end_product_establishment.rb#L300

However, there is also a VBMS read at:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/claim_review.rb#L90

that might slow things down as well, since that is not async.

**Comment by pkarman** [comment]
Should the entire `sync` be run async so we can re-try?

**Comment by shanear** [comment]
> may be addressed by #7111

yeah this is true
