### ISSUE TITLE
Create attorney special issues page

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6854]
For the RAMP appeals pilot, we want to experiment with attorneys entering special issues (that today are entered by ARC staff in Caseflow Dispatch) because (1) this simplifies the amount of work we have to do for dispatching RAMP appeals today and (2) we plan to deprecate Caseflow Dispatch down the line anyway.

## AC
- Create a screen titled `Select special issues`
- `Select special issues` screen comes after selecting remand reasons in the checkout flow
- The following special issues should be listed on this page (TODO)

## Mocks

See [mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1536261263374/a50fb8424a7bff4e04c49d0b4023a6a63e519f09) for flow.

This is how special issues are displayed in Caseflow Dispatch. Let's replicate it.
<img width="670" alt="screen shot 2018-09-06 at 7 12 30 pm" src="https://user-images.githubusercontent.com/27704093/45189842-e833ee00-b208-11e8-85f9-5d7b36a437c3.png">

**Comment by laurjpeterson** [comment]
@mdbenjam - I got the answer from AMO that these special issues do not apply for RAMP appeals, so we should remove them from the Special issues page:

- Vocational  Rehab
- DIC - death, or accrued benefits - United States
- Education - GI Bill, dependents educational assistance
- Foreign pension, DIC - Mexico, Central and South America,   Caribbean
- Foreign pension, DIC - all other foreign countries
- Home Loan Guaranty
- Insurance
- National Cemetery Administration
- Pension - United States
- VAMC
- Waiver of   Overpayment
- Scholarship, transfer of entitlement

**Comment by laurjpeterson** [comment]
@mdbenjam 

Option 1: Remove the below for AMA appeals:
- Hearing
- Manlincon Compliance
Both of these are not relevant for AMA. 

Option 2: If you don't want to fork these two pages based on if an appeal is legacy or AMA in the future, you can append them
- Hearing ... (legacy appeals only)
- Manlincon Compliance (legacy appeals only)

**Comment by allyceh** [comment]
@laurjpeterson Is this the one we should re-open for design + content for the special issues page?

When shadowing an attorney working a RAMP case yesterday, she saw the special issues page for the first time and noticed it was new. She understood it after we explained it to her, but some additional context around 1) what these special issues are, 2) what the attorney needs to do on this page, 3) how we use any special issues they check (routing purposes) could help orient first time users. 

Additionally, she missed the POA/agent special issue checkbox (located at the bottom left of the page) and only realized it when we asked her to return to the page. Should we make this more prominent since the majority of cases have POA? Should it be the first special issue if it's the most common? Can we default the POA checkbox if a veteran has a POA in VBMS?

**Comment by laurjpeterson** [comment]
@allyceh - this is the ticket that includes fixing the copy for this page - https://github.com/department-of-veterans-affairs/caseflow/issues/7036. If we don't use this ticket, I suggest we create a new one to track your copy suggestions.

I agree that we should include the three things you mentioned ( 1) what these special issues are, 2) what the attorney needs to do on this page, 3) how we use any special issues they check (routing purposes) could help orient first time users.)

> Should we make this more prominent since the majority of cases have POA? 
- This is only tracking private attorney or agent. Yes, the majority have cases have a POA, but many more have VSOs as their POA. If you think we should move this checkbox up, that works for me!

> Can we default the POA checkbox if a veteran has a POA in VBMS?
- Yes, we could probably pre-check this checkbox in the future if we can tell that the POA is an attorney or agent in VBMS. I'm not certain if we can distinguish VSO from private attorney/agent. 
- Side note: Shane and I went through the AMA related special issues and we realized that quite a few of the special issues could be pre-checked in the future. I think this will come with the Outcoding, VBMS upload, and EP creation effort.

**Comment by allyceh** [comment]
Moving this convo to #7036!

**Comment by allyceh** [comment]
@laurjpeterson @aroltsch Latest mock is above for copy review. Updated based on @nicholasholtz feedback.

**Comment by allyceh** [comment]
@laurjpeterson @aroltsch An updated mock for the special issues page for AMA appeals is ready as well. I ended up doing both since they were easy to update simultaneously. 

Since attorneys will be seeing the updated verbiage and categorization for legacy appeals, can we also update the AMA special issues screen so that the experience is consistent for them?
