### ISSUE TITLE
Case details | Put deceased date in About the Veteran section

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#6882]
We are capturing the Veteran deceased date from BGS for AMA appeals. BVA dispatchers use this to know context about who is receiving the BVA decision. 

## AC
- Veteran deceased date exists in About the Veteran section of Case details

**Comment by mkhandekar** [comment]
👋 

What do you all think of the placement of the deceased date here, right below date of birth?

Also, what language might be best? "Deceased date" vs "Date of death"?

Also, is there a need to treat this data point more than a data point in this list? Does anyone need to know up front (higher up on case details, or elsewhere) that the Veteran has deceased? 

![image](https://user-images.githubusercontent.com/1598889/45499924-60d80480-b74b-11e8-9cd2-b4f30ee6eea7.png)

**Comment by allyceh** [comment]
The placement makes sense to me, and I prefer the lingo "Date of Death" because it's consistent with "Date of Birth" and makes for easy scanning in this data view. 

Question @laurjpeterson @mkhandekar : if this data point will be going live on 10/1-ish, should we consider the design/placement of Date of Death in the context of what's live today?
<img width="927" alt="screen shot 2018-09-13 at 12 39 29 pm" src="https://user-images.githubusercontent.com/40216950/45502502-26259a80-b752-11e8-81ef-cf059381d6a4.png">

Please correct me if I'm wrong about what's live today and what this section will look like on 10/1.

**Comment by laurjpeterson** [comment]
Here's what the demo site looks like for AMA appeals:

<img width="821" alt="screen shot 2018-09-13 at 5 08 41 pm" src="https://user-images.githubusercontent.com/27704093/45515984-b7f3ce80-b777-11e8-8040-a70f42fb4c63.png">

I think the placement of "Date of Death" underneath Date of Birth makes sense, and I don't think it needs to be higher up on the page at this time. (We could get feedback from our users that it should be, but I haven't gotten that sense from previous research yet.)

As a general note - I find the gray words a bit hard to see because they blend in with the Veteran data text. I wonder if there might be a higher contrast way to display this? We can also wait until we hear user feedback about the visibility here.

**Comment by mkhandekar** [comment]
@laurjpeterson I hear you and I'm good with reverting to bold normal text like in the demo site! We can just keep the gray text in capitals in case snapshot.

**Comment by mdbenjam** [comment]
If the veteran is alive, do we want to omit the `date of death` label? Or show it with a blank space after?

**Comment by mkhandekar** [comment]
@mdbenjam Good q - let's omit.
