### ISSUE TITLE
[IDT AMA] Return whether there is outstanding mail for AMA appeal

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#6883]
Return whether there is outstanding mail for AMA appeal

**Comment by laurjpeterson** [comment]
@aroltsch - I think the way Paul currently identifies whether there is outstanding mail for legacy appeals in the IDT is because it looks for VACOLS mail "tasks". We don't currently have Caseflow mail tasks ready, so we likely won't be able to identify outstanding mail in the same way for AMA appeals. What were your thoughts here? I do think we can keep this issue for post-October, when we do tackle AMA mail.

**Comment by aroltsch** [comment]
Yes, this should be post-october. Apologies.
