### ISSUE TITLE
Ensure BVA Dispatch users can view their AMA appeals when making a call to /idt/api/v1/appeals

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#6890]
# AC
- When making a call to /idt/api/v1/appeals, BVA Dispatchers should get a list of their AMA appeals
- We don't *need* to return legacy appeals in that queue for now (although how easy is it?)

**Comment by aroltsch** [comment]
1. BVA Dispatch user should have access to the case search page - done. We should enable the feature flag for our two BVA Dispatch users when we are ready. 
2. BVA Dispatch user should be able to search for both AMA and Legacy appeals and view details - done. 
3. When BVA user goes to /queue, we will present with the case search page instead of their queue - done. 
4. It will require some more work to enable legacy appeals for IDT for BVA Dispatch because we have to implement  a new query to get assigned appeals. You can read here: https://github.com/department-of-veterans-affairs/dsva-vacols/issues/32#issuecomment-422457879
