### ISSUE TITLE
Make SC/HLR establishment idempotent

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#6940]
In order to be able to retry processing the VBMS calls for a claim review, we need that function to be idempotent.

## Acceptance Criteria
- The `process_end_product_establishments!` should be idempotent, and not make calls that have already succeeded.

**Comment by pkarman** [comment]
Some notes to make sure I am understanding the scope of this ticket. Please correct/challenge my assumptions.

## Current behavior

The `ClaimReview` `process_end_product_establishments!` method encapsulates 4 tasks:

 1. create an EndProduct corresponding to the Claim via `end_product_establishment.perform!`
 1. create contentions for the new EndProduct
 1. create rated issues for any of the new contentions
 1. update the RequestIssues for each contention for `rating_issue_associated_at`

The first 3 tasks all involve one or more `VBMSService` calls, which may fail explicitly with a non-2xx response or may timeout altogether, leaving VBMS in some unknown state.

In the happy path, all 4 tasks succeed, in that order.

In the unhappy path, the first `VBMSService` call to fail will raise an exception and interrupt the flow.

In either case, calling `process_end_product_establishments!` again could create duplicate VBMS records.


## New behavior

We want to be able to call `process_end_product_establishments!` repeatedly and trust that any already-successful tasks are skipped.
This new behavior requires that either:

 * every VBMSService call is self-aware --- it has some way of tracking its completeness and/or recognizing itself in existence already at VBMS, OR
 * some orchestrating class (could be `ClaimReview`, `EndProductEstablishment` or some as-yet-undefined class) tracks the state of each task

## Proposal

As described in #5339 there are two common models for this kind of [distributed transaction pattern](https://blog.couchbase.com/saga-pattern-implement-business-transactions-using-microservices-part/). When considering what direction to take, I think it's helpful to consider the additional requirements mentioned in other tickets.

Tasks should be:

 * idempotent (this ticket)
 * asynchronous (#6941)
 * reversible (#6942)

We could write several more business-specific methods on `ClaimReview` and/or `EndProductEstablishment` to accomplish this, but I think in the long run those classes play more of the orchestrator role and we can abstract the tasks away from the task master.

I propose `EndProductTask` (but of course naming is the Hardest Problem, so we can ~fight about~ discuss that part). It's similar to some of the [pseudo classes I've seen](#6354) in tickets related to this feature. The goal is to have a small db model that represents a discrete, reversible job that is self-conscious about how to revert itself. This would be similar to ActiveJob, but with two main differences:

 * the added intelligence about how to revert itself (undo or cancel or notify a human)
 * db persistence, so that the orchestrator can check state over time

(NOTE I haven't actually written/tested any of this pseudo code -- for logical flow only.)

```ruby

# example schema
create_table :end_product_tasks do |t
  t.belongs_to :end_product_establishment, null: false
  t.string :type, null: false. # STI pattern
  t.datetime :performed_at
  t.datetime :reverted_at
  t.datetime :expired_at
  t.timestamps null: false
end

# base class 
class EndProductTask < ApplicationRecord

  # abstract methods
  def perform_task
    raise "#{self.class} must implement perform_task"
  end

  def revert_task
    raise "#{self.class} must implement revert_task"
  end

  # flow methods
  def perform
    return false if performed?
    if perform_task
      update!(performed_at: Time.now.utc)
    end
    create_next_task
  end

  def revert
    return false if reverted?
    return false unless performed?
    return false unless reversible?
    if revert_task
      update!(reverted_at: Time.now.utc)
    end
    create_next_task
  end

  def reversible?
    true # by default. subclasses may not be.
  end

  def create_next_task
    # create the next task, if dependent on this task
    # default is a no-op
  end

  def performed?
    !!performed_at
  end

  def reverted?
    !!reverted_at
  end

  def expired?
    !!expired_at
  end

  def should_expire?
    # TODO time-based logic here to indicate whether we have tried long enough
  end
end

# example subclasses
class EstablishClaimInVBMSTask < EndProductTask
  def perform_task    
    end_product_establishment.perform!
  end

  def revert_task
    # undo? cancel?
  end

  def create_next_task
    CreateContentionsTask.create!({end_product_establishment: end_product_establishment})
  end
end

class CreateContentionsTask < EndProductTask
  def claim_review
    end_product_establishment.source
  end

  def perform_task
    claim_review.create_contentions_for_end_product_establishment(end_product_establishment)
  end

  def revert_task
    # undo? cancel?
  end

  def create_next_task
    CommitEstablishmentTask.create!({end_product_establishment: end_product_establishment})
  end
end

class CommitEstablishmentTask < EndProductTask
  def perform_task
    end_product_establishment.commit!
  end

  def revert_task
    raise "Cannot revert a committed end_product_establishment"
  end

  def reversible?
    false
  end
end

# since the Task classes are discrete, they can be performed sync or async.
# To run them async, we need something like:
class EndProductTasksJob < CaseflowJob
  queue_as :low_priority
  application_attr :intake

  def perform(end_product_establishment_id)
    RequestStore.store[:current_user] = User.system_user

    EndProductEstablishment.find(end_product_establishment_id).perform_tasks
  end
end

# new methods in EndProductEstablishment like
def perform_tasks
  return if committed?

  # start with the queue of tasks in the db, and then add to it locally.
  tasks = end_product_tasks.to_a
  
  tasks.each do |task|
    next if task.completed?
    next if task.reverted?
    next if task.expired?

    if task.should_expire?
      task.expire!
      next
    end
    
    if next_task = task.perform
      tasks << next_task
    end
  end

  reload # committed_at may be changed by a Task

  # TODO ticket #6942 has requirements about when we give up,
  # so we don't recurse indefinitely.
  if !committed?
    EndProductTasksJob.perform_later
  end
end

def revert_tasks
  return if committed?

  end_product_tasks.each do |task|
    task.revert
  end
end    
```

Then we would change `CaseReview` like this:

```diff
--- a/app/models/claim_review.rb
+++ b/app/models/claim_review.rb
@@ -19,8 +19,8 @@ class ClaimReview < AmaReview
   def process_end_product_establishments!
     end_product_establishments.each do |end_product_establishment|
-      end_product_establishment.perform!
-      create_contentions_for_end_product_establishment(end_product_establishment)
+      EstablishClaimInVBMSTask.create!({end_product_establishment: end_product_establishment})
+      EndProductTasksJob.perform_later
     end
```

Questions:

 * Is this level of task granular enough? Unlike the above example task classes, it seems like each `VBMSService` call should have its own task class, so that we re-try at the appropriate level.
 * Should we attempt to revert tasks automatically? Under what conditions?
 * Should we attempt to run tasks synchronously first, and then create async jobs
   only if they fail? That might give a more pleasant UX.

**Comment by leikkisa** [comment]
I'm still looking over the bigger picture, but just to comment on the first part:

1. create an EndProduct corresponding to the Claim via end_product_establishment.perform!
- In our response, we get a claim_id which indicates a success, and we add it to our database
2. create contentions for the new EndProduct
- In the response, we get a contention_id, indicating a success, and then we add it to our database
3. The new contentions then get mapped to the rated_issues
- Once this succeeds we get "true" as a response, and we update the rating_issue_associated at in the database

**Comment by leikkisa** [comment]
So right now the status of tasks are tracked in three places.  The claim-level successes are being tracked in the end_product_establishmets table, the issue-level successes are being tracked in the request_issues table.  For a claim_review as a whole, the status is tracked in the claim review tables (establishment_processed_at), higher_level_reviews and supplemental_claims).

I am wondering if having another subclass to keep track of the tasks would be useful or if it would make it more convoluted.  I do think we probably want to keep track of more than we currently are planning, to indicate when a re-try happened and if it failed or succeeded, and keeping track of the tasks could be useful for this.

**Comment by pkarman** [comment]
Thanks @leikkisa 

Each of those table-level statuses track, ultimately, Is The Thing Done Or Not. Since we now want to do things async and re-try them, we need some way of tracking Has The Thing Been Tried Or Not, which to my mind is a slightly different question. So I agree with you that it is more convoluted, which async and re-try inevitably is.

**Comment by shanear** [comment]
Couple things:

1. One end product isn't the correct level of granularity, since multiple end products can be created as a result of a single claim review, and we'd want the processing of that entire claim review to be atomic.
2. I think this over complicates things a little bit, right now we are mostly idempotent because we a) skip the ep establishment if `reference_id` is set (here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/end_product_establishment.rb#L53), b) we only attempt to create contentions for contentions that have `contention_reference_id` is nil (here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/claim_review.rb#L63), and c) re associating rated issues is an idempotent operation anyways. This might just be a matter of writing/validating the tests.

**Comment by pkarman** [comment]
@shanear if we assume that all the methods within `process_end_product_establishments!` are idempotent, then does this change make sense?

```diff
--- a/app/models/claim_review.rb
+++ b/app/models/claim_review.rb
@@ -18,12 +18,14 @@ class ClaimReview < AmaReview
   # outstanding end product establishment. If all end products have been created then this
   # method does nothing
   def process_end_product_establishments!
+    return if establishment_processed_at
     end_product_establishments.each do |end_product_establishment|
       end_product_establishment.perform!
       create_contentions_for_end_product_establishment(end_product_establishment)
     end

     end_product_establishments.each(&:commit!)
+    update!(establishment_processed_at: Time.zone.now)
   end
```

**Comment by pkarman** [comment]
adding this to the tests, they all continue to pass:
```diff
--- a/spec/models/claim_review_spec.rb
+++ b/spec/models/claim_review_spec.rb
@@ -90,7 +90,11 @@ describe ClaimReview do
       allow(Fakes::VBMSService).to receive(:associate_rated_issues!).and_call_original
     end

-    subject { claim_review.process_end_product_establishments! }
+    subject do
+      3.times do
+        claim_review.process_end_product_establishments!
+      end
+    end
```

**Comment by shanear** [comment]
Yeah that looks perfect. Great call on the tests! Very easy

**Comment by pkarman** [comment]
@kahlouie and I paired on a solution and wrote a long unit test to simulate VBMS failures at every step. The results are in #7074 

We did find one bug where rated issues would fail to be associated if they did not succeed at VBMS on the first try.

We did some refactoring as well, to make it clearer that `EndProductEstablishment` is the orchestration class for VBMS processes.

**Comment by shanear** [comment]
I'm happy with the automated testing here to say this is good.
