### ISSUE TITLE
Change the call to action to launch Caseflow

### ISSUE THREAD

**Issue by plusjeff** [department-of-veterans-affairs/caseflow#70]
Without explanation, it was unclear that Caseflow was a tool that would help VSRs complete and automatically upload a Form 8. This was partially because normally these VSRs would complete a PDF based Form 8 that was saved on their computer before attempting to change the certification date.

To Dos

- [ ] Before a user can get to the **Update Appeal** screen, they would be asked if the appeal is `eFolder` or `Non-eFolder (Paper, VirtualVA, etc)` (similar to the current Certify Appeal screen, minus certification date).

![image](https://cloud.githubusercontent.com/assets/6335546/10855380/982ed400-7f17-11e5-8548-21589f85a60e.png)

- [x] If the user chose *VBMS paperless appeal*, show (on the *Update Appeal* screen) a *Complete Form 8* button item. This would be in place of the *Cert to BVA* and *Sent to BVA* input fields.

![image](https://cloud.githubusercontent.com/assets/6335546/10855463/12f8bebc-7f18-11e5-8e87-8061e5911070.png)

- [ ] After the user has certified the appeal using Caseflow, the Update Appeal screen should display the *Cert Date* field (non-editable), but not the *Sent to BVA* field.

![image](https://cloud.githubusercontent.com/assets/6335546/10855478/295c6906-7f18-11e5-832b-2b52c1f5f94e.png)

- [ ] If the user chose `Non-eFolder (Paper, VirtualVA, etc)`, show (on the *Update Appeal* screen) the *Cert to BVA* and *Sent to BVA* fields as editable.

![image](https://cloud.githubusercontent.com/assets/6335546/10855490/48ade88e-7f18-11e5-977d-96d41bcfc3e5.png)

- [ ] Remove the *Certify Appeal* dialog button (on the Find Appeal screen) and menu item (from the View Appeal and Update Appeal screens)

![image](https://cloud.githubusercontent.com/assets/6335546/10855498/54ae22b6-7f18-11e5-8a61-0e13b5989ab6.png)

**Comment by plusjeff** [comment]
Assign to @KHarshawat for mocks, then assign back to me for follow-up with Jed.

**Comment by alex** [comment]
@plusjeff these are all changes in VACOLS, not in Caseflow, right?

**Comment by plusjeff** [comment]
Correct

**Comment by KHarshawat** [comment]
@plusjeff added screenshots for what these should look like. Assigning back to you to speak with Jed :)

**Comment by KHarshawat** [comment]
@plusjeff question for you. what does VACOLS currently look like for a post-remand appeal? Should we continue to showing the *Complete Form 8* button after a case has been remanded? Or would we follow the exact same logic as this but the user would just add an SSOC date?

**Comment by plusjeff** [comment]
@KHarshawat Good question. I'll check in with Jed first to see what that flow looks like w/ post remands.

**Comment by plusjeff** [comment]
Meeting w/ Jed on 11/4 at 9:30am. If anyone has any questions they want asked, feel free to add here.

**Comment by plusjeff** [comment]
In the second *Update Appeal* screen above, when clicking the `Complete Form 8` button, data will be updated in the database so that Caseflow has what it needs. However, the same validation rules should apply as the `Update` button.

**Comment by plusjeff** [comment]
@JedWagner and I chatted about this today. Some notes (Jed: Feel free to correct me if I got anything wrong):

- For the second screenshot (at top), the *Complete Form 8* will be greyed out until the Form 9 date has been entered
- Jed thinks we should keep the *Certify Appeal* button and menu option, but relabel to *Complete Form 8*. While users stumbled to use this in user tests, they also didn't have context for what that button did upfront. If we did this, the user flow would mimic the Dispatch flow.
- *Sent to BVA* field should be kept intact as-is. Reason for this is that cases that have a hearing pending will not have been sent over to BVA yet, but will have been certified.
- RE: Remands (from @KHarshawat 's question): The RO will not be involved in post-remands in most cases because they will be handled by the AMC. Even when the RO does have to re-certify something, a form 8 is not filled out (Barbara, @labecker, @Brizzle59 : Can you confirm this?)
- For the Certify Screen (last screenshot at top), the certification date will be greyed out / uneditable when the case is a VBMS/paperless one.

**Comment by plusjeff** [comment]
Turning this ticket over to @JedWagner for implementation on the VACOLS changes.

**Comment by plusjeff** [comment]
![certify_appeal](https://cloud.githubusercontent.com/assets/950486/11094104/d459dafe-885b-11e5-9d9a-93e8bf91e650.png)

![update_appeal](https://cloud.githubusercontent.com/assets/950486/11094105/d45f40c0-885b-11e5-8f50-5181ee02a91c.PNG)

**Comment by plusjeff** [comment]
@KHarshawat and @JedWagner : Some screens attached above. The flow pictured goes:

1. Search
1. Update
1. Certify Complete Form 8
1. Certification pop-up
1. Caseflow

A few things that I see offhand that need updating, but let me know what you think:

- [ ] Wording for *Certify Complete Form 8* button to just *Complete Form 8*
- [ ] Premature certification (see issue #142 )

Some things I still have to test:

- [ ] Does the user get prompted at the Update screen if the case doesn't indicate paper or efolder?
- [ ] Does *Complete Form 8* button get hidden for paper cases

**Comment by KHarshawat** [comment]
@plusjeff @JedWagner 

- The Certification pop-up should not appear when you click the Form 8 button, it should appear when the user first tries to update the appeal, forcing them to declare what type of appeal (efolder or other) it is.
- The text in the Certification pop-up has not been updated according to the mocks
![image](https://cloud.githubusercontent.com/assets/6335546/11094428/c8c6bc6e-885d-11e5-90c9-c4e1e3fb6bdb.png) vs 
![image](https://cloud.githubusercontent.com/assets/6335546/11094442/d9512ccc-885d-11e5-958d-195d484519cf.png)
- The Certify Appeal button is still in the search results.

**Comment by JedWagner** [comment]
I think it would make more sense and be less confusing to the users if we used ‘Certify’ on the buttons and menus, that’s the nomenclature BVA has always used.  Whether it’s an efolder or non-efolder they will always use this process to certify the appeal to BVA,  the Complete Form 8 is just part of the Certification process which will only occur for efolders.  So they will use the process 100% of the time to certify the appeal but the completion of the Form 8 will only occur for those appeals that are VBMS.  I think ‘Certify’ is less confusing since they won’t always be completing the Form 8 via VACOLS.

**Comment by JedWagner** [comment]
Thanks for the feedback Jed! Do you mind if we sync up over the phone later today? Are you free around 3pm?

- Kavi

From: "Wagner, Jed" <jed.wagner@va.gov<mailto:jed.wagner@va.gov>>
Date: Thursday, November 12, 2015 at 8:19 AM
To: 'department-of-veterans-affairs/caseflow' <reply@reply.github.com<mailto:reply@reply.github.com>>, department-of-veterans-affairs/caseflow <caseflow@noreply.github.com<mailto:caseflow@noreply.github.com>>
Cc: "Maher, Jeff" <Jeff.Maher@va.gov<mailto:Jeff.Maher@va.gov>>, Department of Veterans Affairs <kavi.harshawat@va.gov<mailto:kavi.harshawat@va.gov>>
Subject: RE: [EXTERNAL] Re: [caseflow] Change the call to action to launch Caseflow (#70)

I think it would make more sense and be less confusing to the users if we used �Certify� on the buttons and menus, that�s the nomenclature BVA has always used.  Whether it�s an efolder or non-efolder they will always use this process to certify the appeal to BVA,  the Complete Form 8 is just part of the Certification process which will only occur for efolders.  So they will use the process 100% of the time to certify the appeal but the completion of the Form 8 will only occur for those appeals that are VBMS.  I think �Certify� is less confusing since they won�t always be completing the Form 8 via VACOLS.

**Comment by JedWagner** [comment]
Sure 3:00 is fine.

**Comment by KHarshawat** [comment]
Spoke with Jed... going to change the name from Fill out Form 8 to Certify and we will re-assess after next usability test. Goal is to understand if the call to action is clear enough for people to launch Caseflow. 

Other note about the decision: "Certify" is a general enough term that it works for both Paper and Paperless cases vs "Fill Form 8" that only works for Paperless.
