### ISSUE TITLE
Existing EP |  Assign Claim |  Disable all buttons that are not loading

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#712]
As a case worker, when I click a button "Assign to Claim" or "Create New EP", I should not be able to make any other actions on this page.

## Acceptance Criteria
- Verify that when any "Assign to Claim" button is clicked on the Assign Claim page, the other buttons are disabled while the action is loading.

*Note: The disabled state a for secondary button is 25% opacity at this time.*

DEMO:
![assign-disabled](https://cloud.githubusercontent.com/assets/1053255/24714471/a386b91e-19f6-11e7-8fac-cfe8d4696002.gif)

**Comment by lakohl** [comment]
Assigning to myself to provide design

**Comment by lakohl** [comment]
@shanear @nikitarockz this is ready to go

**Comment by lakohl** [comment]
@nikitarockz @shanear I changed the logic on this as the user has the right to change their mind. That being the case, I'm not sure we actually need this issue, but may be useful to clarify the action.

**Comment by shanear** [comment]
@lakohl There are technical limitations to a user changing their mind while the EP is being assigned. Clicking multiple buttons could cause erratic behavior in the app. That's why I created this issue.

**Comment by lakohl** [comment]
@shanear I spoke to @KHarshawat about this ealier and the design above would be the more expected experience. Let's discuss technical limitations and how long it takes for this step to be completed. Ideally there really shouldn't be an interstitial state when you click on a button, but I know VPN etc.can be a factor

**Comment by lakohl** [comment]
@shanear we need to hash this out together.

**Comment by kierachell** [comment]
I think this needs to have a more general issue with browser back button functionality, because at the moment there's only one page that stops the users from going back (has a **Cannot edit end product** flash) and doing some other action.

Related bugs, all happen during the **Loading** animation:
- After clicking **Create new EP** and then **Create End Product** I am able to go back and click **Assign to claim** - not sure what I expect to happen, but I _can_ do that :D 
- After clicking **Create End Product** I am able to check boxes and change modifiers while **Loading**
- After clicking **Assign to claim** I am able to go back and check/uncheck SIC and even switch **Decision documents**

Yeah, I have to be pretty quick about it, but we _do_ have 55 second waits on some of the transactions

**Comment by shanear** [comment]
@lakohl what do we want to do here?

**Comment by lakohl** [comment]
In my view the button that was clicked should show a loading indicator. If you think that the other buttons should not be clickable (cause it will disrupt our system) then we should freeze the rest of the page while the button loading indicator shows. But I would refrain from changing all the other buttons to a passive state. It makes the page look broken.

**Comment by slj** [comment]
Per my discussion with @lakohl the assign claim button will be faded in a way that bring attention back to the button in its loading state, as the attached demo shows.  Simple fix.  Mini demo: 
[AssignClaimDemo.zip](https://github.com/department-of-veterans-affairs/caseflow/files/894736/AssignClaimDemo.zip)

**Comment by kierachell** [comment]
**PASSED**
