### ISSUE TITLE
AMA Edit | Confirmation for HLR and SC

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7313]
## Story
For any AMA forms, when a user needs to edit issues, they will click the "Edit in Caseflow" button in VBMS to return to the "Add issues landing page" where they will be able to add new issues and/or remove issues added previously. There are a few "are you sure?" type modals to help reduce errors. Entire flow via [Mural](https://app.mural.co/t/workqueue2001/m/workqueue2001/1537791678087/94469b0cdf1a02a7f57a7628702d36db2f079430)

This ticket is focused on the Edit Confirmation page that you get after adding or removing at least one issue and clicking "Save" from the Add Issue Landing page to update it to match the new design and additional copy.

requires #7303 

## Technical Notes
- keep an eye out for test duplication refactors across feature tests, but put any significant new work into a new issue

## Acceptance criteria
- When the edit issues page for a Higher Level Review or Supplemental Claim is submitted:
  - The confirmation page should be styled according to the mock below
  - When an EP will be canceled due to the edit (see: https://github.com/department-of-veterans-affairs/caseflow/issues/6214) then show that on the confirmation page according to the copy below.
  - When an EP will be created due to the edit (see: https://github.com/department-of-veterans-affairs/caseflow/issues/6213) then show that on the confirmation page according to the copy below.
  - When the contentions on an EP are updated due to the edit (see: https://github.com/department-of-veterans-affairs/caseflow/issues/6212), then show that according to the copy below.

## Notes
- The ordering of these messages is not particularly important.
- The styling of the confirmation page should match the styling of the original intake confirmation page (see: https://github.com/department-of-veterans-affairs/caseflow/issues/7303)
- Out of scope: confirmation page for Appeals
## Copy

[Veteran name]’s (ID #XXXXXXXXX) Request for [FORM NAME] (VA Form XX-XXXX) has been processed. Go to VBMS claim details and reload to view updates.
Edit the notice letter to reflect the status of requested issues.

[if an EP was canceled]
[ep_type] EP is being canceled.
[subtext] All contentions on this EP were removed

[if an EP was created]
A [ep type] EP is being established:
[subtext for each contention]
Contention: [contention text]
[if informal conference tracked item was added]
Informal Conference Tracked Item

[if the contentions on an EP were updated]
Contentions on [ep_type] EP are being updated:
[subtext for each contention]
Contention: [contention text]

(ep_type is the name of the EP type, for example "Higher-Level Review Rating", "Higher-Level Review Nonrating")

## Mocks
__Note__: There should not be a "Begin Next Intake" button.
__Note__: The copy is incorrect, but the design should match this:
<img width="658" alt="screen shot 2018-10-10 at 5 16 48 pm" src="https://user-images.githubusercontent.com/11219417/46766570-59efd380-ccb0-11e8-8a63-da7212e95249.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by shanear** [comment]
So there are a lot of awkward things that make this story weirder than it seems:

1. EPs aren't just updated, they can also be created or removed as a part of this action  (example: If all rating issues are removed as part of the edit, we'd remove the EP)  (another example: If the first non-rating issue was added to the HLR as part of the edit, we'll create a non rating EP)

2. Because of potential conflicts, we won't know the exact modifier (EP code) of the EP code, we will only know that it's in the series (030-039 or 040-049), we might be able to update the terminology here to say "03x" or "030 series" or "030-039 series"  or something like that.

**Comment by suzchap** [comment]
1) so we just need a little alternate language? Something like "The EP is removed..." if all related issues have been removed and the standard "The EP is being established..." if new issues have been added.

2) this bit is from design I inherited from Abby so I don't actually know much about it... do you think it's useful to have non-exact information or should we just cut it out?

**Comment by suzchap** [comment]
@shanear and I talked and decided to just cut the #2 stuff and to keep those headings as "updating" which vaguely applies to all the scenarios in #1. Mocks and copy have been updated.

**Comment by shanear** [comment]
Assigning @allyceh to help with some of the copy for appeals

**Comment by laurjpeterson** [comment]
@shanear - the story says that this flow starts by clicking the `Edit in Caseflow` link in VBMS, and there are mocks for Board appeals. Would a VBA/VBMS user ever be able to Edit issues in VBMS for Board appeals, or only Supplemental Claims and Higher Level Reviews?

I'm thinking you're asking for input on the copy for appeals because that same page could be used for an edit issue flow that a BVA Caseflow user starts from within Caseflow instead of from within VBMS.

**Comment by shanear** [comment]
Breaking confirmation flow for appeals into it's own story

AMA Edit | Confirmation for updating appeal issues #7516

**Comment by shanear** [comment]
<img width="1552" alt="screenshot 2019-01-25 15 08 15" src="https://user-images.githubusercontent.com/1596259/51777720-23996100-20b3-11e9-97ce-816df34dda15.png">
<img width="1552" alt="screenshot 2019-01-25 15 08 44" src="https://user-images.githubusercontent.com/1596259/51777723-25fbbb00-20b3-11e9-8133-1f4fe7f4cb5b.png">
works!
