### ISSUE TITLE
Facility Locator & Geolocation APIs (Research)

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#7507]
**Facility Locator API & Geolocation API (Research)**
Will be updating this ticket with information related to how we'll be matching Veterans to hearing locations. 

At a high level -- we'll match Veterans to the closest hearing location based on geolocation. Hearing locations can be VBA Regional Offices or alternate locations, including VHA Medical Centers, VHA Clinics, and Vet Centers. 

**Facility locator API:** Hearing locations will be matched to locations in the Facility locator API (https://developer.va.gov/explore/facilities/docs/facilities), note that the UI is a different service (although same data set: https://www.vets.gov/facilities/ and this will be moving to va.gov in Nov.) 

**Hearing locations with facility locator ids (Draft spreadsheet):**  
[Consolidated Alt Locations & Facility Locator.xlsx](https://github.com/department-of-veterans-affairs/caseflow/files/2506966/Consolidated.Alt.Locations.Facility.Locator.xlsx) 
Contact on this: @MeredithStewart. Background: We did a data call to the Regional Offices, Meredith did clean up, reached out to ROs for followup. Status: We've put in the request for two addresses to be updated on the facility locator. Board will confirm these locations with the VBA folks (probably through AMO and out to ROs).  

The Facility Locator API does not currently have any geo-matching. That team, including Alex Lohr (VA API leads) and Patrick Vinograd (contractor for DSVA on APIs), are working to expose the Vets360 address validation via their gateway, after we requested it. This work is in progress, but can be tested in advance. The Vets360 address validation will be exposed via the API as-is, so whatever prototyping we are able to do do should be valid in terms of request/response format. 

Access to Vet360's int environment directly in thread here from Patrick Vinograd: 
* You can look at their swagger UI at `Address Validation
https://int.vet360.va.gov:7005/address-validation`. We are working with that team to improve their docs in the course of making them available at developer.va.gov.
* If you just want to do a curl request, you can do something like so:
```
curl -k -v --key /etc/pki/tls/private/vetsgov-vet360.key \
--cert /etc/pki/tls/certs/vetsgov-vet360-dev-cert.pem \
-X POST https://int.vet360.va.gov/address-validation/address/v1/validate \
-H "Content-Type: application/json" \
-H "Accept: application/json" -d @/tmp/address.json
```
where /tmp/address.json contains:
```json
{
  "requestAddress": {
    "addressLine1": "8633 Union Pl",
    "city": "Manassas Park",
    "requestCountry": {
      "countryCode": "USA"
    },
    "stateProvince": {
      "code": "VA"
    },
    "zipCode5": "20111"
  }
}
```
* As you can see in the swagger docs there are options for addressLine2, addressLine3, and I also confirmed it supports international addresses. I tried a Guam address and some Canadian addresses. 

* The other thing to note from the curl request is that you need to provide a client cert. But, any VA-signed key/cert pair will work, the owner of the cert doesn't matter. So if you can pull a VA-signed dev cert from somewhere in the appeals project, that should work fine.  

* Response looks something like this:
```json
{
  "address": {
    "county": {
      "name": "Manassas Park City",
      "countyFipsCode": "51685"
    },
    "stateProvince": {
      "name": "Virginia",
      "code": "VA"
    },
    "country": {
      "name": "United States",
      "code": "USA",
      "fipsCode": "US",
      "iso2Code": "US",
      "iso3Code": "USA"
    },
    "addressLine1": "8633 Union Pl",
    "city": "Manassas Park",
    "zipCode5": "20111",
    "zipCode4": "2434"
  },
  "geocode": {
    "calcDate": "2018-09-20T23:26:19+00:00",
    "locationPrecision": 31,
    "latitude": 38.768185,
    "longitude": -77.450033
  },
  "addressMetaData": {
    "confidenceScore": 100,
    "addressType": "Domestic",
    "deliveryPointValidation": "CONFIRMED",
    "residentialDeliveryIndicator": "RESIDENTIAL"
  }
}
```

* Normalized address, geocoding info, and some metadata about the confidence score and address type. 
* That should get you started, if you get stuck just ping me.

**Comment by MeredithStewart** [comment]
**Background** 

* When we began to do research into the Board taking over scheduling Veterans for hearings, we uncovered that there were about 100 alternate locations in use that weren't in the data in VACOLS.  
*  The Board wasn't aware of the extent of these "multi-point" hearings - where the Judge is in DC, the Veteran Service Organization rep is at the Regional Office, and the Veteran is at a third location, closer to their home address. Some Regional Offices were doing it, many were not.  
* These set ups are better for Veterans, especially those Veterans that have difficulty traveling, because the burden to get to the hearing is reduced if they can attend at a location closer to their home.  
* In order for the Board to schedule hearings, they need to know where to send the Veterans. Today, Regional Offices match Veterans to alternate locations, but as of February 14, 2019, the Board will take over this task for all hearings around the country. In order to continue alternate locations, Caseflow Hearing Schedule needs to be able to automatically suggest closest hearing location.

**Comment by lomaxap** [comment]
Keys for Vet360 validate responses:

Message Key | Message Code | Description/More Info
-- | -- | --
AddressCouldNotBeCorrected | ADDRVAL109 | The Address could not be corrected
AddressCouldNotBeFound | ADDRVAL112 | The Address could not be found
AddressValidationServiceError | ADDRVAL104 | Vet360 Address Validation Service Error
DualAddressError | ADDRVAL111 | This dual address is not in the proper format, please make sure the street address and PO box are valid for the 5 digit zip code entered
InsufficientInputData | ADDRVAL208 | Insufficient data provided for validation process
InvalidRequestCountry | ADDRVAL201 | Only one of either country name or country code is required
InvalidRequestNonStreetAddress | ADDRVAL204 | The request needs at least one address line and one non-address line field populated in order to process the request
InvalidRequestPostalCode | ADDRVAL205 | Only one of either zipCode5 or international postal code is required
InvalidRequestState | ADDRVAL202 | Only one of either state name or state code is required
InvalidRequestStreetAddress | ADDRVAL203 | One of addressLine1, addressLine2 or addressLine3 must be provided
MultipleAddressError | ADDRVAL206 | Multiple matches found for this address
SpectrumServiceAddressError | ADDRVAL102 | The Spectrum Service returned an address error
additionalInput | ADDR307 | Vet360 Validation Failed: Additional Input found please review
deliveryPointNotConfirmed | ADDR305 | Vet360 Validation Failed: Delivery Point is Not Confirmed for Domestic Residence
lowConfidenceScore | ADDR306 | Vet360 Validation Failed: Confidence Score less than 80
requestCountry.countryName.Size | ADDRVAL106 | size must be between 0 and 255
stateProvince.name.Size | ADDRVAL107 | size must be between 0 and 255
