### ISSUE TITLE
Display copy change for when CorpDB does not have a POA

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#7530]
Right now for RAMP appeals where VBMS does not have a POA for a Veteran, Caseflow displays this as:

![image](https://user-images.githubusercontent.com/16781398/47455958-3abd6f80-d7a1-11e8-81f7-d2b08cff6e8f.png)

(For reference, VBMS displays:
![image](https://user-images.githubusercontent.com/16781398/47455994-4f9a0300-d7a1-11e8-86b6-c4e27a05a782.png)

There needs to be a copy change so that when VBMS returns `:` , Caseflow displays "This Veteran does not have a Power of Attorney" or similar, better text.

**Comment by nicholasholtz** [comment]
I would also suggest that the copy underneath, where it says "contact an administrator with access to SHARE", needs to be updated.

- Attorneys will not necessarily know what SHARE is.
- The term "administrator" is misleading - should indicate "co-located support personnel" or the like. Perhaps "administrative professional on the co-located support team".

**Comment by allyceh** [comment]
@laurjpeterson @nicholasholtz and cc: @lowellrex 

Proposed update 1: If the veteran doesn't have a POA, I say we don't display the POA section on Case Details. This is consistent with how we handle the About the Appellant and Hearings sections on Case Details today. Thoughts about this approach?

I also noticed that the POA section for legacy appeals looks the same as the POA section for RAMP appeals. For legacy appeals, this copy is inaccurate until we start pulling POA from the corp DB, so we should also update that to be accurate. 

Proposed update 2: For legacy and RAMP appeals, we could say "To update POA, please contact the co-located support team." Is that accurate?

I removed the bit about VBMS-- do attorneys actually care about this? Let me know what you all think!

**Comment by laurjpeterson** [comment]
1. I want to agree that we can remove the POA section if the Veteran does not have a POA, but I have the slightest bit of hesitation because POA data is so crucial and is often wrong. What if we said something like "Appellant does not have representative data stored in VBMS" or something so it's super clear that there isn't missing data and users don't need to go searching around?

I think we'll be rolling out legacy cases pulling POA data from BGS this week, so it may be ok to not fix that copy right now.

2. I don't know if it's going to be co-located support team indefinitely. I think the copy you have "administrator with access to SHARE" makes sense until we really know that answer.

I think attorneys (and other BVA employees) do care about the bit about VBMS. It puts the data into perspective of what tools they know and what data sources they know and trust. Many people look at multiple places for data now, so I think them being able to see that they DON'T have to check VBMS would be a good thing

**Comment by laurjpeterson** [comment]
<img width="640" alt="screen shot 2018-10-30 at 9 19 16 am" src="https://user-images.githubusercontent.com/27704093/47720709-e85ad380-dc24-11e8-8b01-8a52b2c0b955.png">

@allyceh - you were correct. POA clarifications should be sent to co-located.

**Comment by laurjpeterson** [comment]
This means we may need functionality for BVA dispatchers to create a task and send it to co-located admin. will create another ticket for that. https://github.com/department-of-veterans-affairs/caseflow/issues/7601

**Comment by allyceh** [comment]
Okay! To recap, here is what we're changing: 

- When veterans don't have a POA, we can display copy that indicates that to provide some reassurance for attorneys. Thoughts about "The veteran does not have a representative."? I kept it short and to the point so that it's easy to read and scannable on the Case Details page.

It seems we're still deciding between whether or not we update the instructional text in the POA field. Per @nicholasholtz comment earlier: "Attorneys will not necessarily know what SHARE is.
The term "administrator" is misleading - should indicate "co-located support personnel" or the like." but also considering that we don't know if these requests will go to co-located indefinitely (@laurjpeterson ), what if we say "POA data comes from VBMS. To update POA, please send a request to the co-located support team." In the interim, this reflects what the process is for both attorneys + BVA Dispatchers (soon). We could update it when the process changes again.

Thoughts?
cc: @lowellrex

**Comment by laurjpeterson** [comment]
> POA data comes from VBMS. To update POA, please send a request to the co-located support team.

Completely agree with this!

**Comment by nicholasholtz** [comment]
would this be a situation where they would assign an admin task via caseflow to co-located?

If so, should the text say soemthing about using caseflow (i.e., provide them instructions for a specific avenue, because i am sure some will send email, and then it could get overlooked)

**Comment by allyceh** [comment]
@nicholasholtz Good point. Right now, we are catering to a couple different groups: 1) Attorneys who are able to assign tasks to the co-located team and two BVA Dispatchers who use Caseflow for AMA appeals, but don't have the ability to assign a task just yet. 

Since the attorneys are the majority here, we could say "POA data comes from VBMS. To update POA, please assign an admin action to the co-located support team."

We could always instruct our Dispatch pilot users to send an email and to ignore the admin actions bit for now.

**Comment by laurjpeterson** [comment]
Updating to use the formal name of colocated folks - the VLJ support management branch.

"POA data comes from VBMS. To update POA, please send a request to the VLJ support management branch."

I agree with @nicholasholtz that we should have more instructions, but we don't yet have a way for all users to send tasks to co-located. 

For BVA dispatchers, we'd need to add the `Add admin action` functionality for them, and have them choose POA clarification, to look into POA/edit POA.

Since this is in the COPY.json file and will be easy to chance, can we keep the copy as it is above, and tweak it to "POA data comes from VBMS. To update POA, please send a task to the VLJ support management branch" when we have the above functionality?

**Comment by allyceh** [comment]
That is good with me!

**Comment by lowellrex** [comment]
SMALL. Each field may come back `null` instead of the entire struct being `null`, may be more complex for that reason. Confirm with somebody with production access that it works as expected.
