### ISSUE TITLE
Allow BVA dispatchers to send AMA appeals to judges, vlj support, etc. 

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7601]
The Chairman does not want BVA dispatchers to be able to edit POA. (No one should edit POA address.)

If a BVA dispatcher comes across a POA error, I think we should allow them to:
1. Create a POA clarification task that puts the Dispatch decision task on hold
2. Assign that POA clarification task to Co-located organization
3. Co-located can work the POA clarification task and when complete, the case goes back to BVA dispatchers

@allyceh @lowellrex - what do you think about this?

**Comment by laurjpeterson** [comment]
Agree - I think doing #7528 first makes sense.

> BVA dispatchers currently only interact with Caseflow through the IDT. How would they assign a task to co-located admin? Would they use the Caseflow website? Or would we create some endpoint that the IDT can hit to do this so they never have to leave the IDT?
- BVA dispatchers view the Case details page, and I think they could assign tasks to co-located from there

**Comment by laurjpeterson** [comment]
There are also requests for BVA dispatchers to assign tasks to judges for corrections. LP will look into needed BVA Dispatcher tasks.

**Comment by allyceh** [comment]
The BVA Dispatch branch chief needs to make a decision in conjunction with the DVCs about the circumstances that require BVA Dispatch to return a case to a judge. The process needs to be defined before we turn the functionality on and give BVA Dispatch free reign to use it. 

Email sent to Corey on 4/1:

"A while back, William and Libby requested that they have the ability to assign cases to other individuals at BVA in Caseflow. We can start by giving them the ability to assign cases back to judges so that the Caseflow team doesn’t have to manually reassign cases when there is an issue that requires a judge to take action.
 
Here are the reasons why BVA Dispatch would need to assign a case back to a judge (that I am aware of):  
The IDT isn’t displaying the judge’s signature, and the judge needs to add it before the decision letter can be mailed
The issues on the decision letter don't match what's logged in Caseflow, and the judge needs to update them to reflect the decision document
 
Are there any reasons that I am missing?
 
Before we enable this functionality, are you able to connect with one of the DVCs and define scenarios when BVA Dispatch should be able to return a case to a judge? This will ensure that judges and BVA Dispatch are aligned before we turn on this feature in Caseflow."

**Comment by laurjpeterson** [comment]
Closing. We know now that BVA Dispatchers can send tasks to judges.
