### ISSUE TITLE
Edit document ID in Queue

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7606]
## Background

We've gotten 3 different attorneys asking how to edit Document ID. How might we help attorneys edit Document ID in Case details?

## Mocks

Context: These mocks show what editing individual data points in Case Details could look like. As we're reviewing these designs, let's consider how they would scale across different editing scenarios. 

User first clicks "Edit" from Case details:
<img width="710" alt="screen shot 2018-12-05 at 12 01 08 pm" src="https://user-images.githubusercontent.com/40216950/49530090-80338900-f885-11e8-8217-b489c8427f27.png">

Editing modals in case details consist of a: 
- Header (format: "Edit" + "(data being edited)"
- Optional instructional text to describe what the user is editing and the impact (if applicable)
- Text field pre-filled with the values being edited
- Save/cancel actions

![image](https://user-images.githubusercontent.com/40216950/49316277-62010e00-f4be-11e8-8a24-0ee9656247fc.png)
- When the modal opens, we display a focused view of the text field so that the user can quickly edit. 
- We enable the save button when the user changes something in the text field. This is a visual queue to reinforce that we acknowledge their change. 

![image](https://user-images.githubusercontent.com/40216950/49316548-4a765500-f4bf-11e8-9fae-2d1525df4093.png)
- Error state (above). 
  - Open question: How can we make this error message more helpful? From my understanding of the document ID formats in #5993, they can vary based on new and old cases. Ideally, we would give the user the correct format so they can fix the error. How many possible formats are there?

## AC 

- When a user clicks Edit next to the Decision Document ID field, the modal (above) appears on top of the Case Details page. 
- When the modal appears, the text field is displayed in a focused state.
- When the user makes any edit, we enable the save button. 
- Clicking "Save" validates the document ID field (see #5993 for validations that were implemented in the attorney-judge checkout flow).
  - If the format is invalid, present an error message. 
- Clicking "Save" returns the user to the Case Details page where they will see the change reflected. 
- Clicking "Cancel" or "x" returns the user to the Case Details page where they won't see any change reflected.

**Comment by allyceh** [comment]
@laurjpeterson @sneha-pai @lowellrex I thought through a couple of options here.

1. In-line editing: Document ID is styled like veteran ID field. I created a couple of mocks on the veteran ID field to demonstrate what in-line editing behavior could be. 

We could remove the outline around the document ID and veteran ID fields (for visual consistency).
<img width="157" alt="screen shot 2018-11-06 at 4 05 06 pm" src="https://user-images.githubusercontent.com/40216950/48093740-3308bc80-e1de-11e8-8193-4422c7c8095c.png">

When the user hovers over an editable field, the grey box around document ID would appear, indicating to the user that the field is editable. This would be a new pattern.
<img width="166" alt="screen shot 2018-11-06 at 4 05 13 pm" src="https://user-images.githubusercontent.com/40216950/48093790-529fe500-e1de-11e8-8504-f8f5ad5a5611.png">

When the user clicks into the field, it would turn grey, indicating that it's being edited. A cursor would appear, and they could edit the number. They would press enter to save and update the document ID. 
<img width="148" alt="screen shot 2018-11-06 at 4 05 19 pm" src="https://user-images.githubusercontent.com/40216950/48093824-677c7880-e1de-11e8-9342-f5a2235f8507.png">

Open questions: 
- Is this accessible? 
- Is this a pattern that we would want to continue using across queue?

2. Edit in a modal: Edit document ID in the Edit AOD modal. 

We could move the "Edit" link away from "Type" to next to "About the case". When the user clicks "Edit", they would see a re-designed modal that allows them to either grant AOD or edit the document ID number. 
<img width="195" alt="screen shot 2018-11-06 at 4 06 13 pm" src="https://user-images.githubusercontent.com/40216950/48093953-cb9f3c80-e1de-11e8-9b99-184b87e9feba.png">

Open questions: 
- Granting AOD feels a bit disconnected from editing the document ID number, so I might question putting it all in one modal. However, this design would nest all "the things" that a user needs to edit or take action on in one modal. 

Let's discuss a bit, and then if we go the second route, I can mock something up.

**Comment by laurjpeterson** [comment]
I agree that in option 2, granting AOD seems disconnected from editing document ID. 

I prefer option 1, but how would users know to click to edit it? Would it be too crowded to have the edit pencil icon near the copy icon? When the edit pencil icon is clicked, then the inline edit you designed would be there.

Another note I just thought of - we should have the same validations that exist when the attorney enters the document ID in their checkout flow to ensure it's in a valid format. Could we use the existing Caseflow error patterns if a user inputs a doc ID in the wrong format?

**Comment by allyceh** [comment]
@laurjpeterson @lowellrex Mocks + AC have been updated (above) for document ID editing! I have a couple of open questions documented. 

@sneha-pai Would love your eyes on this too as this is what editing could look like across Case Details.

**Comment by allyceh** [comment]
<img width="710" alt="screen shot 2018-12-05 at 12 01 08 pm" src="https://user-images.githubusercontent.com/40216950/49530090-80338900-f885-11e8-8217-b489c8427f27.png">

Yes! I should've referenced #7903 . The user would trigger this modal by clicking Edit next to the Document ID field.

**Comment by laurjpeterson** [comment]
Thanks! Added this screenshot to the main ticket too. This one's good to go!

**Comment by monfresh** [comment]
Hello! While trying to understand how I would implement this, I came up with a few questions:

- To confirm, this would appear on a page such as http://localhost:3000/queue/appeals/fc17e01c-4469-41a9-9568-1fabf3b71846, right?
- Are the terms "appeal" and "case" interchangeable?
- The mocks on this issue suggest that an appeal/case can only have one Document ID, and that the Document ID is a main attribute of an appeal/case, just like Docket Number, for example. Is that correct? 
- Does this issue apply to both legacy and AMA appeals? If not, which one does it apply to?

If an appeal can only have one Document ID, then the app isn't designed that way currently. From what I can tell, the Document ID is an attribute of an "attorney case review". So, in order to get the Document ID associated with an appeal, we have to go through the appeal's `attorney_case_reviews` which is not a direct association, but a helper method that fetches the attorney case reviews that belong to the appeal's tasks.

So, an appeal has many tasks, and tasks have many attorney case reviews, which have an attribute called `document_id`. Based on the data in the local setup, it looks like all attorney case reviews associated with an appeal's tasks all have the same Document ID. Similarly, it looks like all appeals only have one attorney case review because although an appeal can have multiple tasks, only one task can be an attorney task.

Will that always be the case in real life? If so, would it make more sense to save the Document ID on the Appeal model? It would certainly be more efficient.

Thoughts?

cc @aroltsch

**Comment by aroltsch** [comment]
> To confirm, this would appear on a page such as http://localhost:3000/queue/appeals/fc17e01c-4469-41a9-9568-1fabf3b71846, right?

Yes.
> Are the terms "appeal" and "case" interchangeable?

Yes.
> The mocks on this issue suggest that an appeal/case can only have one Document ID, and that the Document ID is a main attribute of an appeal/case, just like Docket Number, for example. Is that correct?

The document ID lives on the `attorney_case_reviews` table. An appeal can have many `attorney_case_reviews` with the latest being the valid one. 
> Does this issue apply to both legacy and AMA appeals? If not, which one does it apply to?

It applies to both. `attorney_case_reviews` table contains both legacy and AMA attorney reviews. When it comes to legacy, we will also need to update the document ID in VACOLS (`decass` table)

> Would it make more sense to save the Document ID on the Appeal model? It would certainly be more efficient. 

I think it makes perfect sense. I think it also makes sense to have `appeal_id` in attorney_case_reviews` table instead of a `task_id` but we can change that at a later day when we deprecate VACOLS DAS system (`decass`). For legacy cases `task_id` is a pointer to a Vacols decass table, for AMA it is a pointer to Caseflow `tasks` table.

**Comment by aroltsch** [comment]
@allyceh @laurjpeterson Moncef and I chatted about this ticket yesterday and we will tackle this ticket in multiple steps:
step 1. Allow editing of the latest document ID for AMA cases. Attorneys and judges would be able to edit a document ID at any point in time.
step 2. Allow editing of the latest document ID for legacy cases. This will update `attorney_case_reviews` table and `decass` table. 
step 3. Implement restriction till what point attorneys and judges can edit a document ID. 

cc @monfresh

**Comment by laurjpeterson** [comment]
sounds good - thank you!

**Comment by laurjpeterson** [comment]
Related - document ID validations ticket: https://github.com/department-of-veterans-affairs/caseflow/issues/5993

**Comment by aroltsch** [comment]
Opened a new ticket to implement next steps
