### ISSUE TITLE
SPIKE: Investigate BGS Integration for adding a VBMS Note to an EP created in Caseflow Dispatch

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#766]
Investigate the technical feasibility of adding a VBMS note via Caseflow. When a user creates an EP (especially for a Full Grants) adding a VBMS note to the Claim (ideal) or to the Vet Profile (second best) explaining the special issue would help the RO understand why it has been assigned to their station. The note would read: 'The BVA Full Grant decision dated 01/01/2017 for John Doe, ID# [123456789], was sent to the ARC but cannot be processed here, as it contains [special issue category] in your jurisdiction. Please proceed with control and implementation of this grant..

Engineering Note:
- If we add VBMS notes in the same submit as the EP itself (from the EP form), then we must do this as a prerequisite https://github.com/department-of-veterans-affairs/caseflow/issues/1077

**Comment by lakohl** [comment]
Also would be good to know:
1) if VBMS notes are Visible in Share? 
1) which fields from the VBMS EP are visible in Share?

**Comment by joofsh** [comment]
See https://github.com/department-of-veterans-affairs/dsva-vbms/issues/68 for more details

**Comment by joofsh** [comment]
Verified that we are able to pull a Veteran's periods of service from BGS 's `VetRecordWebService` which we already integrate with in production! 

The information exists within the `VetRecordService`'s `find_by_file_number` method. In order to retrieve this information, we will need to make updates to `ruby-bgs` which is done in this PR: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/36#pullrequestreview-54476728

Further information about where we can pull this information can be found in the dsva-vbms issue here: https://github.com/department-of-veterans-affairs/dsva-vbms/issues/89
