### ISSUE TITLE
Incorporate hearing info in case search

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7718]
We think Caseflow Queue users (attorneys, judges, admin support, etc.) will gain value from seeing hearing information in case search results. The Hearing Schedule team has also designed and implemented search results that include hearing data to meet their users' needs. 

This design could also be leveraged in the queue table.

## Requirements
@sneha-pai completed an initial design exploration based on requirements listed in this [comment](https://github.com/department-of-veterans-affairs/caseflow/issues/7016#issuecomment-428678275). 

#### Case search (with appeals AND VBA reviews)
![search results-proposed](https://user-images.githubusercontent.com/31224257/48272942-d390f380-e40d-11e8-8528-50f9fe8dbf7c.png)

#### On Hover or click (if possible)
![search results copy 2](https://user-images.githubusercontent.com/31224257/48272947-d68be400-e40d-11e8-9837-b21916a130ce.png)

**Comment by sneha-pai** [comment]
@mdbenjam @lowellrex 
@MeredithStewart @sharonwarner 
Please review above mocks for feasibility, concerns, feedback.

**Comment by MeredithStewart** [comment]
@sneha-pai -- I think the designs are great. I'm wondering for AMA hearing docket, would we also implement the H tag with the scroll over info? I'm thinking it might be good (even if a bit duplicative). Curious what you thought.

**Comment by lowellrex** [comment]
I don't think this will affect loading/performance at all. We already get all of the information from VACOLS and return it to the frontend so we aren't requesting any additional information.

As for how complex it is to implement, I don't think it will be all that tough. I imagine most of the work here will be concerned with making the visual appearance match the mocks and not finessing the data (since that is probably already in the form we need).

Currently the only thing left in the chute for case search/queue list view this sprint is #6710 (adding HLR and supplemental claims to the search results), so we can tackle this ticket after we complete that puppy (or before if we want to prioritize this ticket?).
