### ISSUE TITLE
Case Details | Schedule hearings task

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#7730]
The Schedule Hearings task is not showing up for Justin, but it is showing up for Meredith. We need to determine why and then fix it so the correct task shows up for the correct people.

**Comment by oscarAtNava** [comment]
I reviewed the data in production and looked at the code that gets all tasks for an appeal to display in CaseDetails. I found the following:

The Task Controller find_for_appeal end point is used to get all tasks for an appeal to display on the top part of the CaseDetails page. The logic in that endpoint has three parts.
- It will return only tasks for VSOs if the user has a VSO role
- It will return judge or attorney tasks if the user role includes these two roles
- Otherwise it returns all tasks for that appeal

My question for @MeredithStewart is: the situation where Justin can see an attorney task and Meredith saw a schedule hearing task, was it for the same appeal? My hypothesis is NOT, and that Justin just happened to choose an appeal that also had a judge/attorney task and that one showed first. We know that is the behavior in CaseDetails.

To better research this issue we need appeal id's or Vacols Id's so we can better document.

**Comment by oscarAtNava** [comment]
After conferring with Mark we know the following:

- Justin is set up as a judge in the VACOLS STAFF table. This is why he fell in the 2nd bullet point logic I documented above. He will never see hearings tasks while he has that setup.

Action Item: Check with Jed and Justin why he has that setup (svlj = 'A') and if it can be removed.

I will follow up for this.

**Comment by oscarAtNava** [comment]
The following PR resolves this issue. https://github.com/department-of-veterans-affairs/caseflow/pull/7798

**Comment by MeredithStewart** [comment]
Confirmed with Justin 11-13-18 -- Sees "Schedule Veteran" now.
