### ISSUE TITLE
Plan for Private Bar access to Caseflow

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7774]
During BVA/DS meeting 11/7/2018, Cheri mentioned we need a plan for the Private Bar to get access to Caseflow, just like VSOs have.

## Questions
- Can we build organizations for this? Are all private bar attorneys part of an organization? (like NOVA)
    - If so, we should clean up how we populate a list of cases in VSO org queues first and replicate that for private bar
- Can Private Bar attorneys complete tasks? (assuming no)
- Can the private bar use the same CSEM function as VSOs or should we create a new one? 
    - They'd get the same search restrictions based on being listed in Corp DB. Does that suffice?
    - But if they can't complete tasks, should we create a new one anyway?
- Do they have any other restrictions that VSOs don't have?

## Assumption
- We can start with just AMA appeals, then legacy like we are doing for VSOs

**Comment by nicholasholtz** [comment]
[still in progress; will edit shortly]

@laurjpeterson as far as making this into a plan, I think this can be turned into an investigation plan and go from there. I think a lot of these questions should be pushed to the Board, rather than us tackling them, as they have the expertise about what sort of access should be provided.

### Caseflow Access Plan for Private Bar
This document is intended to form the basis for providing members of the private bar with access to Caseflow for purposes of reviewing appeal details for their clients. In its initial stage, it is an investigation plan, as Caseflow needs guidance from VA / the Board to determine how access should be provided.

#### Preliminary Limitations
- Access to Caseflow must be limited to accredited representatives.
- Access to Caseflow will only be permitted through the VA network.
- Access to Caseflow must be limited to only provide representatives to their own clients, for whom they have submitted an appropriate VA Form 21-22a. 
- Access to Caseflow will initially be limited to only Appeals Modernization Act (AMA) appeals, as Caseflow moves towards minimum viability for purposes of implementing the AMA in February 2019; members of the bar will continue to use existing VACOLS access for purposes of reviewing legacy appeals. Ultimately, Caseflow will provide access for both AMA and legacy appeals.
- Members of the private bar will only gain access to Caseflow for purposes of reviewing appeal details; members of the private bar will not gain access (at least at this time) to other Caseflow applications, including Caseflow Reader and eFolder Express.

#### Investigation Plan
##### Board Questions
The following open questions will be submitted to the Board to permit their SMEs to provide guidance.
- Do Can Private Bar attorneys complete tasks? (assuming no)
Can the private bar use the same CSEM function as VSOs or should we create a new one?
They'd get the same search restrictions based on being listed in Corp DB. Does that suffice?
But if they can't complete tasks, should we create a new one anyway?
Do they have any other restrictions that VSOs don't have?

##### Caseflow Research Questions
- Should private bar Can we build organizations for this? Are all private bar attorneys part of an organization? (like NOVA)
   - **Answer**: No; each individual attorneys may be part of law firms, and access must be limited to the law firm. Even if an attorney is part of NOVA, that does not mean that all of NOVA has access to that attorney's client data.
   - However, each attorney may have a law firm as an organization, and they can share access to the files. 
- If so, we should clean up how we populate a list of cases in VSO org queues first and replicate that for private bar?
   - **Answer**: This should be possible at the law firm level.

**Comment by laurjpeterson** [comment]
Conversation on 12/17 about how VSOs should view their AMA cases (without relying just on Caseflow tasks) will likely affect how we think about giving private bar attorneys access to Caseflow, too. 

cc: @lowellrex for visibility

**Comment by laurjpeterson** [comment]
In BVA leadership meeting 12/20, we learned that private bar attorneys will only be able to see their own cases, _not_ cases that their firm is working on. So, the assumption that Chisohlm and NOVA would be organizations is no longer true.  

This means individual private attorneys will only have individual queues, and can only search cases for which they are the VSO.
- @lowellrex - could we assign `TrackVeteran` tasks to users based on them being the POA in BGS (instead of assigning it to an organization)

---

Raw notes:

FOR NOW
- private attorneys have to get access individually, accredited individually - through GC - can only be accredited for their Veteran
- law firm as a whole cannot get access 
	- individuals at chisolm cannot see chisolm cases overall

FUTURE - department policy
- admin staff and paralegals can't have access ... applies to VSOs too
- looking at private bar getting access to eFolder express
	- give a CD to them
	- then can't control who can see that CD...

- 21-22a - put in Chisolm, Chisolm Kirkpatrick any attorney = invalid
	- won't be put in place ahead of February

- should be - 1 POA at the top of the form (only that 1 POA should have Caseflow access)
	- Block below, can add more individuals below to act on their behalf
	- as long as they're accredited, it's ok
	- requirement could change this and say - list the person who is accredited for the firm, whoever's got that Veteran

- VSO admin staff no longer having access - hasn't been finalized yet

**Comment by nicholasholtz** [comment]
Slight edit to Lauren's comment. (https://github.com/department-of-veterans-affairs/caseflow/issues/7774#issuecomment-449460436)

What LP described is the future state, which will come into play at some unknown time in the future. It still involves a good bit of wrangling/decision-making, apparent. 

Current state is that organizations can have access.

That being said, NOVA is a unique organization, by my understanding. NOVA is an organization of law firms and individual lawyers (I think). This should be confirmed by talking with Diane (LN can't remember), who is the head of NOVA.

**Comment by nicholasholtz** [comment]
Do we know how to get their participant IDs? Is that something we could ask them for when they file for access?

**Comment by laurjpeterson** [comment]
not sure. since these are BGS participant IDs, maybe @mc-usds would know?

**Comment by mc-usds** [comment]
POAs, whether VSO or individual attorney, will have a participant id in corpDB. The POA call used get the VSO POA should also work for individual attorney POAs.

I did a quick test in pre-prod with a filenumber that has a individual attorney set as POA. The POA participant id is included in the response.

<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:findPOAsByFileNumbersResponse xmlns:ns2="http://org.services.vetsnet.vba.va.gov/"><return><fileNumber>471745180</fileNumber>
<powerOfAttorney>
    <legacyPoaCd>02U</legacyPoaCd>
    <nm>ROBERT S LINGLEY</nm>
    <orgTypeNm>POA Attorney</orgTypeNm>
    <ptcpntId>31171428</ptcpntId>
</powerOfAttorney>
<ptcpntId>31186402</ptcpntId>
</return></ns2:findPOAsByFileNumbersResponse></S:Body></S:Envelope>

**Comment by nicholasholtz** [comment]
@laurjpeterson this changes us back to what we originally thought around providing eX to private bar, yes?

**Comment by laurjpeterson** [comment]
Yep, I think we can move forward with plan of Private Bar attorneys reaching out to VA and requesting access to eX.

**Comment by laurjpeterson** [comment]
Closing because we've got a path forward.

**Comment by nicholasholtz** [comment]
We have been instructed to hold providing additional access pending written guidance from VA.
