### ISSUE TITLE
Desired queue enhancements

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7894]
This github issue keeps track of issues/features/projects/topics that we have felt rushed on, and would like to spend more time finessing post-Feb 14

## Lauren

- Return to the original design (or a new and improved one) for the Review, Assign cases view for judges - LP (note: the original design with tabs was not implemented)

### Case Details
I'd like to put more thought into how the information and UI copy on the Case Details page supports various user groups across BVA. Throughout the past few months, my decisions about UI copy on this page (POA section, in particular) have been very attorney/BVA Dispatch centric because I typically work with them and understand their needs the best. I would like to take time to understand the needs of other groups who will use Case Details to make sure they are being met. 

Opportunity: How might we make the information on the Case Details page (or, the hub for getting information about a veteran's case) work for all Board users?

Open questions to answer: 
- Who are all of the different departments/users who will need to use the Case Details page? (I know we've been starting to answer this question recently.)
- What is their main purpose for using this page? (POA address? Veteran address? Case status in Case timeline?)
- Based on how they're using the information, how can our UI or information support their needs? Is there anything they need to know that we're not showing them?

Something I'm personally curious about: 
- There are nuances between legacy and AMA cases in Caseflow. And, between legacy cases in Caseflow and VACOLS (ex: data source for POA address). What do users need to know about these nuances to be able to do their work effectively? How can we educate them about these differences, if this is a need?

### Drop downs

Some of our drop downs in Queue span the whole screen. But, the inputs in the drop downs themselves are short, and don't require that much screen real estate. 

Open questions: 
- Is this something we want to continue doing?
- Should we have a short drop down component and a long drop down component, i.e... two different lengths? 
  - Needs more research in regards to best practice

### Design/product blueprint

Expressed in retro on 1/4: Step back and create a product/service blueprint to understand, at a larger level, what queue is, who interacts with it at BVA, and how the queue ecosystem works for each team. These flows exist in disparate Murals, so this could be an effort where we are pulling them together into one document or linking documents.

**Comment by allyceh** [comment]
I'd like to put more thought into how the information and UI copy on the Case Details page supports various user groups across BVA. Throughout the past few months, my decisions about UI copy on this page (POA section, in particular) have been very attorney/BVA Dispatch centric because I typically work with them and understand their needs the best. I would like to take time to understand the needs of other groups who will use Case Details to make sure they are being met. 

Opportunity: How might we make the information on the Case Details page (or, the hub for getting information about a veteran's case) work for all Board users?

Open questions to answer: 
- Who are all of the different departments/users who will need to use the Case Details page? (I know we've been starting to answer this question recently.)
- What is their main purpose for using this page? (POA address? Veteran address? Case status in Case timeline?)
- Based on how they're using the information, how can our UI or information support their needs? Is there anything they need to know that we're not showing them?

Something I'm personally curious about: 
- There are nuances between legacy and AMA cases in Caseflow. And, between legacy cases in Caseflow and VACOLS (ex: data source for POA address). What do users need to know about these nuances to be able to do their work effectively? How can we educate them about these differences, if this is a need?
