### ISSUE TITLE
Enable navigation between different queues

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#7904]
Implement navigation between personal task queues and organizational queues for folks who have access to an organizational queue, and between judge and attorney queues for attorneys temporarily acting as judges. This design was originally proposed in #5385 and affirmed in #7503.

## Acceptance criteria:
* Display a dropdown that switches active queues for folks with access to an organizational queue.
* Display a dropdown that switches between judge and attorney queues for folks acting as judges.

![image](https://user-images.githubusercontent.com/32683958/48708543-d9869180-ebd0-11e8-8a53-a421b88733d4.png)

_Note: Let's also explore how it looks--and if it is technically easier--to move the dropdown down into the white container instead of leaving it above that container._

**Comment by joeyyang** [comment]
Hi! Just picking up this task now — couple of clarifying questions:

- @lowellrex:  
  - "_switches active queues for folks with access to an organizational queue_"
    - Does this mean that it will switch between a user's personal queue and the queue(s) of the organization(s) they belong to?
    - What kinds of users are these?
  - "_between judge and attorney queues for **folks acting judges**_"
     - What does this phrase mean?
- @sneha-pai:
  - Is there any styleguide guidance on moving the dropdown inside the "Your queue" container? I'm wondering if putting it inside the container will make it more clear that the dropdown controls just the contents of the container. What are your thoughts?

**Comment by lowellrex** [comment]
1. 
> Does this mean that it will switch between a user's personal queue and the queue(s) of the organization(s) they belong to?

Exactly. These are folks that belong to a team at the board (Quality Review, for example) where the team will have tasks assigned to the whole team, but whose members could also have tasks assigned to themselves as individuals.

2. Updated the text to be a little more clear.
> between judge and attorney queues for folks acting *as* judges

"Acting judges" are attorneys who have been promoted (temporarily?) to oversee a team of attorneys and sign decisions those attorney draft (as a judge would). These "acting judges" may also be members of a different judge's team as an attorney where they are expected to draft decisions to be signed by somebody else. As such, these "acting judges" will need to access both an attorney-centric queue (for drafting decision) and a judge-centric queue (for signing decisions and assigning cases).

Let's delay attacking this second problem (acting judges) for now. As long as we have some way to switch between personal and organizational queues then I think making it work for judge/attorney queues should be dramatically easier.

**Comment by joeyyang** [comment]
Thanks @lowellrex! Quick clarifying question:
> These are __folks__ that belong to a team at the board (Quality Review, for example)
Is "folks" here attorneys, judges, or "colocated" users?

**Comment by lowellrex** [comment]
I really need to use more precise language.

The folks who will belong to teams at the Board could be any Board employee. In the case of Quality Review, those people are attorneys. But we need to support the generic case where the member of a team at the Board (for example VLJ Support or the Privacy team) are not attorneys but simply need to access an individual queue (in the latter example that would be materialized by way of the `ColocatedTaskListView` component).

**Comment by sneha-pai** [comment]
#### What should the dropdown say when a user has a personal queue and an organizational queue?
SP: 
"Your Cases" for individual queues.
"[Team/organization name] Team Cases" for team/org queues.


#### Is there any styleguide guidance on moving the dropdown inside the “Your queue” container? 
SP: There's limited to none styleguide guidance on how containers and interaction elements come together. I've put together a proposed mock below to detail spacing considerations:

![caseflow-switch-views](https://user-images.githubusercontent.com/31224257/49110730-439bd800-f25c-11e8-8daa-9058752922c4.png)


#### I’m wondering if putting it inside the container will make it more clear that the dropdown controls just the contents of the container. What are your thoughts?
SP: I believe this will make it clearer that the container view is changing. The dropdown can always read "Switch Views" as a call to action, because the contents within the dropdown will greatly vary in width (long team names vs short team names). 

The corresponding page header will change based on the different view clicked. If the user were to click on their team's view, the new header of the container would read "Colocated Team Cases"
