### ISSUE TITLE
Fix non-deterministicly failing switch-user test

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#793]
The test: "We can switch between test EP data in dev mode" non-deterministically fails because we check the database before the webserver can respond.

**Comment by nickheiner-usds** [comment]
This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)

Also killing this because the title is mispelt.
