### ISSUE TITLE
Investigate appeals with signed decisions still showing on attorney's case list

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8044]
Looks like these legacy appeals have been signed, but are still showing in attorneys' case lists. Let's investigate if we have another DAS issue.

https://appeals.cf.ds.va.gov/cases/11746
- signed 11/28/18 but still showing on the attys docket

https://appeals.cf.ds.va.gov/cases/29251
- signed 11/1/18 but still showing on attys docket

https://appeals.cf.ds.va.gov/cases/5546
- not yet signed but submitted to judge and showing up on judge docket as well at the attys docket

**Comment by amprokop** [comment]
### 11746
 it's actually an AMA appeal. Looks like it was worked by VACOHAMILD1, I don't see it in his case list at `/queue` though. Looks like the only AttorneyTask for this appeal was completed on 2018-11-19.


### 29251 
the VACOLS id of the appeal is 3041551. It does still appear in the attorney's queue, because the VACOLS location is still the attorney's css id — VACOHAMILD1 (the attorney name is DORIAN HAMILTON). 

here is the VACOLS location history — date charged, person the case was charged to, the person who did the charging. looks like the attorney charged the case to himself after dispatch maybe (dispatch is 4E, right?)

 [[Tue, 05 Jun 2018, "77", "RO04"], [Thu, 07 Jun 2018, "78", "IMBUTLER"], [Thu, 07 Jun 2018, "01", "HDAYS"], [Thu, 30 Aug 2018, "33", "HDAYS"], [Fri, 31 Aug 2018, "81", "THOMAW2"], [Thu, 06 Sep 2018, "LHOWELL", "MJKOROMA"], [Wed, 26 Sep 2018, "VACOHAMILD1", "LHOWELL"], [Wed, 10 Oct 2018, "RCOSTELLO", "VACOHAMILD1"], [Tue, 16 Oct 2018, "VACOHAMILD1", "RCOSTELLO"], [Wed, 24 Oct 2018, "LHOWELL", "VACOHAMILD1"], [Tue, 30 Oct 2018, "VACOHAMILD1", "LHOWELL"], [Thu, 01 Nov 2018, "LHOWELL", "VACOHAMILD1"], [Fri, 02 Nov 2018, "4E", "LHOWELL"], [Fri, 02 Nov 2018, "VACOHAMILD1", "VACOHAMILD1"]]

### 5546

This case was worked by an attorney named Danielle Ragofsky, and does not currently appear in her queue. It's at Quality Review. The judge task is complete too. Not sure where the discrepancy is here.

**Comment by laurjpeterson** [comment]
Just realized this likely has to do with the judge view only. Cases are showing up in the Assign view, Attorney case loads, even though the judge had signed them.

**Comment by laurjpeterson** [comment]
Will be resolved with this issue (https://github.com/department-of-veterans-affairs/caseflow/issues/8318) so closing.
