### ISSUE TITLE
Add badges to Universal Case Title

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8213]
![universal-case-title-expanded copy 8](https://user-images.githubusercontent.com/31224257/49304034-46cfd780-f499-11e8-94ae-f398ae8f6a88.png)

## Acceptance criteria
* [ ] Display badges when applicable in the top right corner of the universal case title

## Non-goal
* Do not display an edit link beside the badges.

**Comment by lomky** [comment]
_[What is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | ||||||||
3 | ||||
5 | 
8 | 
```

Estimating at a 2.

All the info is already on the front end. QueueTableView already displays the badge. Hearings is the only badge, for now. This ticket is just to show existing badges, not create any new ones.
How many badges do we expect to have to fit? There's one now, and one planned. More may come down the line. Let's aim for 3 fitting for now.

2 as the work seems well sscoped and small. Couple be a 3, because front end is scary.
