### ISSUE TITLE
Introduce pagination to all queue tables

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8242]
### Context
Soon, queues will have 100 to 1000s of cases in a queue. This is especially relevant for team queues, like the hearings management branch queue, and when we support both legacy and AMA cases in the same queue. We'd like to introduce pagination to caseflow.

### Principles
- We'd ideally like to retrieve and locally cache on client-side all available cases at once, and conceal them according to the pagination sequencing. (as opposed to retrieving each page freshly). We'll need to test the speed and reliability of this, and @mdbenjam has some ideas that we can pressure test it with hearing schedule data.
- We'd like to build this component once, and reuse it in any table structure across Caseflow. Current needs are for Queue & Hearing Schedule products, but future needs may arise in Intake product.
- We'd like to integrate filtering with pagination, such that when the user has filtered any of the vertical table categories, the pagination should reflect the filtered range, and shall appear truncated until the filters have been cleared.

### User needs
- As a queue user, I need to see 15 cases per page.
- As a queue user, I need to see a case-range and total case count at the top and bottom of the page (Viewing 1 - 15 of 120 total cases) 
- As a queue user, I need to always see the first and last page of the sequence, as well as the previous and next buttons.
- As a queue user, I need to see the active page (the case-range that I'm viewing) as a dark, active square on the pagination component.
- As a queue user, if I'm on page one of the sequence, the previous button should be disabled. Similarly, if I'm on the last page of the sequence, the next button should be disabled.

#### When user is on page 1
![pagination-1](https://user-images.githubusercontent.com/31224257/50658534-b12bda00-0f67-11e9-89e5-26155b5c9ecc.png)

#### When user is somewhere in the middle of the page-range
![pagination-2](https://user-images.githubusercontent.com/31224257/50658535-b12bda00-0f67-11e9-88e4-9636638842d9.png)

#### When the user is on the last page available
![pagination-3](https://user-images.githubusercontent.com/31224257/50658536-b12bda00-0f67-11e9-8d2a-0474b07ebf86.png)

**Comment by laurjpeterson** [comment]
@lowellrex @sneha-pai - FYI, hearing schedule would be ready to use pagination of individual and team queues for the hearings management branch by friday, january 11th cc: @MeredithStewart @sharonwarner

**Comment by laurjpeterson** [comment]
Looks great! I agree we may not need Last if we always show the last page number.

I’m curious as to how many cases we should have per page. It might depend on how many cases could be in a queue as well as performance, so wonder what Lowell and Mark think here.

@meredithstewart - i think you mentioned this before, but how many cases do you think could be in hearings management branch’s team queue?

**Comment by mdbenjam** [comment]
First, an ode to why Reader doesn't have pagination. I advocated against us using paging in Reader since I thought displaying "infinite-scroll" was better. My reasoning is why click when you don't have to 🤷‍♂️ . I generally think providing searching/filtering/sorting is more powerful. If folks are clicking through all of the pages to find something that seems no better, and maybe worse, than just infinitely scrolling for something. So one question I'd ask is do we definitely need pagination? What does pagination achieve? I generally think of pagination as an option when we have performance problems showing everything in a single list.

If we do think it's necessary some thoughts. There are two ways to do pagination. Serverside and clientside.

Clientside: The client has all the data and just shows it page by page.
Serverside: Every time we click on a new page we make a server request to get the next set of results.

I'd like to do things clientside, it's easier. But if there's a tonnnnn of stuff, we might need to implement serverside paging.

If we're doing clientside paging, then we should build it right into the `table` component. Even, serverside paging, if we decide it's necessary, should be built into the `table` component as callbacks.

The design looks straightforward enough to me. No concerns there.

**Comment by lowellrex** [comment]
➕to all of @mdbenjam's thoughts. I agree that we should try to handle all pagination the client side, but I also think it makes sense to consider how we will add pagination on the server side up front since it may inform how we implement pagination on the client side (I'm thinking specifically about how we deal with the hand off between client and server when we are paginated on both sides).

**Comment by sneha-pai** [comment]
@annekainicUSDS can we show the left side page range information, but hide the component?

**Comment by annekainicUSDS** [comment]
@sneha-pai Yep, I can do that! Thank you!
