### ISSUE TITLE
Need to capture when untimely evidence was received in attorney check-out

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#8340]
Section 5 sub (t) of AMA requires that we capture data on how frequently a Veteran submits evidence at a time when it can't be considered. This includes:

1) submitting evidence for an appeal on the direct review lane;
2) submitting evidence outside the new evidence 90-day window on the evidence lane;
3) submitting evidence outside the post-hearing new evidence 90-day window on the hearing lane; and possibly, 
4) submitting evidence after having waived the post-hearing new evidence window on the hearing lane.

LRP suggested a check-box in the attorney check-out flow, but will leave it in your capable hands to figure out the best solution here. 

## Mock

![image](https://user-images.githubusercontent.com/40216950/52230423-50a0fd00-2885-11e9-8c3d-ba42bbad46ea.png)

![image](https://user-images.githubusercontent.com/40216950/52230431-5696de00-2885-11e9-9169-7112f473e3e2.png)

**Comment by allyceh** [comment]
@laurjpeterson Are all of these scenerios above (#1-4) considered "untimely" evidence? Or, just #2 and #3?

**Comment by laurjpeterson** [comment]
I think they are all considered untimely - worded as "at a time when it can't be considered". BVA cannot _ever_ consider evidence on the direct review docket. 

I agree that it is confusing language, though. Maybe "ineligible evidence" would be better?

**Comment by allyceh** [comment]
![image](https://user-images.githubusercontent.com/40216950/51859483-3a36f680-2305-11e9-8c93-f13e41b1015d.png)

I took a stab at this. 

Option 1, could be quickest to implement: Add a checkbox to the attorney-judge checkout flow as mentioned above. Updates to this page included moving the "overtime" checkbox to the bottom of the page so that it's next to the "untimely evidence" checkbox (note: the overtime checkbox will go away when we tackle #5445 ). Also added untimely evidence checkbox and description of evidence that's considered untimely. 

Option 2, requires more exploration: We could make untimely evidence a tag or checkbox in Reader so that attorneys can mark ineligible evidence as they review the appeal file. Likely higher effort, and requires more research because attorneys aren't responsible for capturing anything official in Reader today. It's currently used to view and annotate veteran documents. 

cc: @eric-nava for design feedback

**Comment by nicholasholtz** [comment]
I think option 1 is straightforward enough, especially under the timing circumstances we have. 

I would hesitate to go with option 2; those tags/checkboxes in reader would have to be appeal-specific, which (I don't think) matches anything else we are doing in Reader right now with tags/etc.; otherwise, it would create a scenario where every subsequent appeal for that Veteran would be marked with an untimely evidence tag unless someone went back and removed it. There is also a situation where there could be concurrent direct review/evidence lane appeals on different issues, and the tag could become unwieldy.

As for the language, I think it works. LRP might have other thoughts, but I think it's fine.

**Comment by laurjpeterson** [comment]
@allyceh - I agree with Nicholas here. I agree that LRP might want to weigh in - please reach out to Rachel and Laura for their thoughts!

**Comment by allyceh** [comment]
Updated mock per Laura's feedback. Please see the latest mock in the "Mock" section of the ticket.

**Comment by allyceh** [comment]
Note: I've added new mocks above. These updates incorporate a new/proposed design pattern for handling instructional copy. cc: @sneha-pai
