### ISSUE TITLE
Hearing Worksheet | Case Details Link

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8592]
On the hearing worksheet, for both legacy and ama appeals, we need to add a button in the top righthand corner that links to the Case Details page. We should use the Link component stylized as a button.

<img width="1035" alt="screen shot 2019-01-09 at 3 26 44 pm" src="https://user-images.githubusercontent.com/4306128/50926441-feee8980-1422-11e9-94f8-22ca83deee22.png">

**Comment by Sjones352** [comment]
@Chingujo does the Case details page have to open in a new tab. Plus please view current screenshot
<img width="1455" alt="screen shot 2019-01-10 at 12 03 23 pm" src="https://user-images.githubusercontent.com/23080951/50984843-cd33fc00-14d0-11e9-9a6d-f7725926a36f.png">

**Comment by Chingujo** [comment]
@Sjones352 I believe we strayed away from doing things in new tabs meaning I don't think we have a pattern of opening tabs in new links in other products. So,  from my opinion, we can just open in that page assuming it is still the easier technical option and the user can go back to this page through app links or the browser. 

Ccing @ShellySmithDSVA for her thoughts here as well, since this involves her designs and to check my assumption on the above =D

**Comment by ShellySmithDSVA** [comment]
Yes, case details opens in a new window/tab. This is how judges use the claims folder currently and is what they expected during user tests.

**Comment by Chingujo** [comment]
There you go @Sjones352 new tab wins!
