### ISSUE TITLE
Create IHP-writing VSO organizations

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8600]
We've begun working with all IHP-writing VSOs to get their required CSEM access to Caseflow so they can view and work AMA appeals. We'd like to ensure each VSO has an organization row in our DB.

## AC
- Organizations exist for all IHP-writing VSOs:
   - ✅American Red Cross
   - Catholic War Veterans
   - ✅Maryland Department of Veterans Affairs
   - ✅Military Order of the Purple Heart (MOPH)
   - ✅National Veterans Legal Services Program (NVLSP)
   - Navy Mutual Aid Association (NMAA)
   - ✅Wounded Warrior Project (WWP)
   - ✅Blinded Veterans Association  (BVA)
- URLs spell out the full VSO name, in lower case, with dashes (e.g. `/organizations/american-red-cross`) - send to LP
- When users from these organizations have access to the VSO CSEM function, they can view the organization/team queue for their VSO

Note: organization rows already exist for:
   - ✅American Legion
   - ✅Disabled American Veterans (DAV)
   - ✅Paralyzed Veterans of America (PVA)
   - ✅Veterans of Foreign Wars (VFW)
   - ✅Vietnam Veterans of America (VVA)  

## Future scope
- Out of scope for this ticket, but we will soon need to add more VSO organizations for field VSOs

**Comment by lowellrex** [comment]
XS

**Comment by lowellrex** [comment]
Have VSO orgs for the following VSOs:

* American Red Cross -> `/organizations/american-red-cross`
* Maryland Department of Veterans Affairs -> `/organizations/maryland-department-of-veterans-affairs`
* Military Order of the Purple Heart -> `/organizations/military-order-of-the-purple-heart`
* National Veterans Legal Services Program -> `/organizations/national-veterans-legal-services-program`
* Wounded Warrior Project -> `/organizations/wounded-warrior-project`
* Blinded Veterans Association -> `/organizations/blinded-veterans-association`

Still need BGS participant IDs for the following VSOs in order to create their organizations:

* Catholic War Veterans
* Navy Mutual Aid Association (NMAA)

[Related slack thread](https://dsva.slack.com/archives/C6E41RE92/p1549561519128500)

**Comment by msj0nes** [comment]
New Organizations Requests

Organization | POC | Email | BGS Participant ID
-- | -- | -- | --
Texas Veterans Commission | Guenavere McCormick | guenavere.mccormick@tvc.texas.gov |

**Comment by lowellrex** [comment]
Created Navy Mutual VSO organization. Their URL is `/organizations/navy-mutual`.
