### ISSUE TITLE
Bulk Assignment of Tasks to User

### ISSUE THREAD

**Issue by ShellySmithDSVA** [department-of-veterans-affairs/caseflow#8620]
## Acceptance Criteria
- As a caseflow user who has assigning privileges in organization/team queues, I can click on **"Assign tasks in bulk**" link in the **Unassigned tab** to view a modal that allows me to systematically select an appropriate range of tasks to assign to any given user in my organization, including myself.

## Mocks
![colocated-table-your cases-768 copy 4](https://user-images.githubusercontent.com/31224257/52750892-7df35680-2fbb-11e9-8421-eaad2e764628.png)

![colocated-table-your cases-768 copy 5](https://user-images.githubusercontent.com/31224257/52750890-7df35680-2fbb-11e9-855e-8747a4012081.png)

**Comment by lowellrex** [comment]
@ShellySmithDSVA The judge assign cases view has a column with checkboxes so the current user can select which cases to bulk assign. Is the checkbox column something that we would want to replicate here as well?

![image](https://user-images.githubusercontent.com/32683958/51633216-21060280-1f1f-11e9-8ee7-746b8528c509.png)

**Comment by ShellySmithDSVA** [comment]
@Chingujo - Bringing you in on this

**Comment by sneha-pai** [comment]
Archiving original AC and proposal here from main issue container:

## User Stories 
* As a Hearings Branch user, I need the ability to assign multiple tasks to myself so that I don't have to work cases one by one, and can complete many of the same kinds of tasks efficiently, 
* As a Hearings Branch user, I need to assign multiple tasks to others so that we can assign the right tasks to the right people, and work on tasks where we specialize.

## Mocks
See pages 51-54 of the following InVision link for designs https://va-gov.invisionapp.com/share/TUPWZLI7GBP

_Page 52 (blue box is just a hitbox from invision, do not implement)_
![image](https://user-images.githubusercontent.com/32683958/51632961-77bf0c80-1f1e-11e9-91b7-27a3928f9bfe.png)

_Page 53_
![image](https://user-images.githubusercontent.com/32683958/51632979-90c7bd80-1f1e-11e9-8c43-a7dc74e1aba7.png)

_Page 54_
![image](https://user-images.githubusercontent.com/32683958/51633022-b3f26d00-1f1e-11e9-9317-657cfe3e20b6.png)



## Related Epic
See Epic #8618 for the other associated tickets.

## Acceptance Criteria
- [ ] Verify the "Assign Tasks" button is at the top of the Org Queue.
- [ ] Verify user can filter by Regional Office and Task via the table view.
- [ ] Verify the Assign Tasks button opens an Assign Tasks modal that overlays the Org Queue with task assignment options.
- [ ]  Verify the Assign Tasks modal contains drop down for Assign to and lists all the Hearing Branch users in this drop down.
- [ ] Verify the Assign Tasks modal contains a typable drop down where users can choose a Regional Office.
- [ ] Verify the Assign Tasks modal contains a drop down that allows users to select a task type from a list of tasks.
- [ ] Verify the Assign Tasks modal contains a drop down that allows users to assign a number of tasks in the drop down in the following increments: 5 / 10 / 20 / 30 / 40 / 50 
- [ ] Verify the Cancel link brings the user back to the Hearings Schedule Unassigned Queue
- [ ] Verify the Assign button completes the action and brings the user back to the Hearings Schedule Unassigned Queue
- [ ] Verify the confirmation message at the top contains the number and type of tasks assigned.
- [ ] Verify the Unassigned and Assigned tabs update their numbering accordingly. 
- [ ] Verify logic exists for Hearing Schedule bulk assign modal that assigns AOD/CAVC (high priority flagged) cases first.
- [ ] Verify logic exists for Hearing Schedule bulk assign modal that assigns oldest cases first. 

## Related Epic 
* #8618 - EPIC | Queues and Admin Actions

**Comment by annekainicUSDS** [comment]
@ShellySmithDSVA @sharonwarner @sneha-pai I think we're missing some information that would help us complete this ticket:

1. Do you have mock-ups for what each of the dropdowns in the modal should show? I assume they should only show data that's available in the table (e.g., only regional offices that appear in the unassigned table should be listed as options)? Can you explain who "Hearing Branch users" are? I'm not familiar with this group.
2. In terms of where the data goes, I assume these cases should be moved into the tasks table and marked as assigned. That table does not have a column for regional office, so do you know what we're supposed to do with that data?
3. In terms of making determinations of what cases to assign, you described in the acceptance criteria that oldest cases should be assigned first. Is it otherwise random (e.g., all cases are of the same age)?
4. Can you explain the different between the Hearing Admin users and the Hearing Management users? And can you confirm that this feature should only be applied for Hearing Admin users?

I'm new to this product, so there's a lot for me to learn in order to understand this ticket. If this is easier to discuss over the phone, happy to set up a call for us to chat. Thanks!

**Comment by ShellySmithDSVA** [comment]
It was on my list this week to clean up this ticket. Apologies for the confusion. 

1. Here are the mocks of the drop downs for the modal (I'm linking to the specific screen in the larger flow) https://va-gov.invisionapp.com/share/REQ7EOZM6JH#/343428920_Bulk_Assign_1. Let me know if you need further details.

2. Yes on the moving to the tasks table and being marked as assigned. In reply to RO - I'll research this further. 

3. Yes, I believe that it's the oldest cases first, then otherwise just 10 of that type of task. There will likely almost always be a date order for cases. 

4. I believe the Hearings Management users are the same as the Hearings Admin users. They all have access to schedule veterans and work related tasks.

Tagging @MeredithStewart for any further thoughts or clarifications.

**Comment by mdbenjam** [comment]
I can also chime in here:

> Do you have mock-ups for what each of the dropdowns in the modal should show? I assume they should only show data that's available in the table (e.g., only regional offices that appear in the unassigned table should be listed as options)? Can you explain who "Hearing Branch users" are? I'm not familiar with this group.
In this case hearing branch users are just users who have been added to the "Hearing Admin" organization. We'll need to add a line here: https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/seeds.rb#L98 to make our hearing user `BVATWARNER` be a part of that organization.
`OrganizationsUser.add_user_to_organization(hearings_member, HearingAdmin.singleton)`

> In terms of where the data goes, I assume these cases should be moved into the tasks table and marked as assigned. That table does not have a column for regional office, so do you know what we're supposed to do with that data?
The regional office column will appear for anyone in the "Hearing Management" organization right now, but we need to expand this to those in the "HearingAdmin" organization as well. You can see that here: https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/client/app/queue/ColocatedTaskListView.jsx#L105

> In terms of making determinations of what cases to assign, you described in the acceptance criteria that oldest cases should be assigned first. Is it otherwise random (e.g., all cases are of the same age)?
I don't think order matters within dates.

> Can you explain the different between the Hearing Admin users and the Hearing Management users? And can you confirm that this feature should only be applied for Hearing Admin users?
Currently all Hearing Admin users are likely also Hearing Management users. I think building it out just for users in the Hearing Admin organization is good for now. You can use some similar hacky logic like we're using to only show the RO column for the Hearing Management branch.
