### ISSUE TITLE
Manager Dashboard | Current | Change table information and section header to "Work Assignments"

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#867]
*slight updates in the last comment @nikitarockz to verify

As a Dispatch Manager, I would like the "Current" section changed to "Work Assignments" and the table information replaced with the caseworker's work assignment metrics (completion goal, completed, remaining) to so that I am able to see how many claims each caseworker will be responsible for completing today, as well as what they have done and how many are remaining.  

# Acceptance Criteria
1. Verify that the section "Current" has been changed to "Work Assignments".
1. Verify that the "Work Assignments" table contains a listing of all of the Caseworkers who have completed at least one case that reports to the current user Manager.
1. Verify that the table in the new "Work Assignments" section contains the following elements for each Caseworker listed:
     - **_Employee Name_** - the name of the employee establishing claim cases.  
      
          > **_Format_**:     [FirstName] [LastName]
     - **_Cases Assigned_** - total number of cases expected to be completed today.  
      
          > **_Formula_**:     Roundup ([TotalCasesToday] / [TotalCaseworkersToday])
     - **_Cases Completed_** - total number of cases completed by caseworker.
     - **_Cases Remaining_** - total number of remaining cases caseworker is expected to complete.           

          >**_Formula_**:  ([TotalCasesToday] / [TotalCaseworkersToday] ) - [TotalCaseCompleted]
1. Verify that the "Work Assignments" table contains a total row (summation for all employees listed) with the following data element values in **bold type**.:

     **Employee Name** = "Employee Total"  
     **Cases Assigned** = [TotalCasesToday]
     **Cases Completed** = [TotalCasesCompleted]
     **Cases Remaining** = ([TotalCasesToday] / [TotalCaseworkersToday] ) - [TotalCaseCompleted]
1. Verify that after entering a value for _"Number of people"_ and clicking the **_Update_** button, the "Work Assignments" table data  ("_Cases Assigned_" and "_Cases Remaining_") is updated.
1. Verify that when the [TotalCaseworkersToday] value has not been set and no work has been done, the table displays one row with the following data element values:

     **Employee Name** = ""  (empty string)
     **Cases Assigned** = 0
     **Cases Completed** = 0
    **Cases Remaining** = [TotalCasesToday]
1. Verify that the following link and icon is displayed at the top of table (refer to mockup):  **_View Dashboard_**
# Mockups
**_View - Manager Dashboard page - New "Work Assignments" section_**
![image](https://cloud.githubusercontent.com/assets/23063044/22980801/8c753f7a-f368-11e6-8dec-6c78ae1dd833.png)

**_View - Manager Dashboard page - Total Workers not set (Cases Assigned calculated) and no Work Completed_**
![image](https://cloud.githubusercontent.com/assets/23063044/22954148/d3c0f846-f2e2-11e6-8602-268e678cec39.png)

# Related Stories
Manager Dashboard | Update copy of page header and subtext #869
Manager Dashboard | Set number of Caseworkers for today #859
Manager Dashboard | Hide "Work History" section #860

**Comment by nikitarockz** [comment]
Original
As a Dispatch Manager, I want to see how many claims have been established by each of the case workers on my team, and how many they have to go

Verify that table shows Employee Name, Cases Assigned, Cases Completed, Cases Remaining.
## Acceptance Criteria Needs
Round up the total assigned.
See mock below for scenario when
- When no quota has been set for today
- When no cases have been done today?

**_Mock when no cases have been assigned and no work has been done:_**
<img width="803" alt="screen shot 2017-02-12 at 7 44 20 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867747/b276a81c-f15b-11e6-8ddb-8e169a24c67a.png">


**_Mock when cases have been assigned and work has been done:_**
<img width="590" alt="screen shot 2017-02-12 at 7 41 59 pm" src="https://cloud.githubusercontent.com/assets/4975959/22867748/b74e2c0c-f15b-11e6-85cf-49db708224a0.png">

**Comment by lakohl** [comment]
As a Dispatch Manager, I would like the "Current" section changed to the Work Assignments table and the table information replaced with the caseworker's work assignment metrics (completion goal, completed, remaining) to so that I am able to see how many claims each caseworker will be responsible for completing today, as well as what they have done and how many are remaining.  

# Acceptance Criteria
1. Verify that the section "Current" is replaced by the Work Assignments table.
1. Verify that the Work Assignments table contains a listing of all of the Caseworkers who have completed at least one case that reports to the current user Manager.
1. Verify that the Work Assignments table contains the following elements for each Caseworker listed:
     - **_Employee Name_** - the name of the employee establishing claim cases.  
      
          > **_Format_**:     [FirstName] [LastName]
     - **_Cases Assigned_** - total number of cases expected to be completed today.  
      
          > **_Formula_**:     Roundup ([TotalCasesToday] / [TotalCaseworkersToday])
     - **_Cases Completed_** - total number of cases completed by caseworker.
     - **_Cases Remaining_** - total number of remaining cases caseworker is expected to complete.           

          >**_Formula_**:  ([TotalCasesToday] / [TotalCaseworkersToday] ) - [TotalCaseCompleted]
1. Verify that the "Work Assignments" table contains a total row (summation for all employees listed) with the following data element values in **bold type**.:

     **Employee Name** = "Total"  
     **Cases Assigned** = [TotalCasesToday]
     **Cases Completed** = [TotalCasesCompleted]
     **Cases Remaining** = ([TotalCasesToday] / [TotalCaseworkersToday] ) - [TotalCaseCompleted]
1. Verify that when adjusting the value for _"Number of people"_ with the up/down arrows, the "Work Assignments" table data  ("_Cases Assigned_" and "_Cases Remaining_") is updated.
1. Verify that when the [TotalCaseworkersToday] value has not been set and no work has been done, the table displays one row with the following data element values:

     **Employee Name** = ""  (empty string)
     **Cases Assigned** = 0
     **Cases Completed** = 0
    **Cases Remaining** = [TotalCasesToday]
1. Verify that the following link and icon is displayed at the top of table (refer to mockup):  **_View Dashboard_**
# Mockups
**_View - Manager Dashboard page - New "Work Assignments" section_**
<img width="710" alt="screen shot 2017-02-16 at 9 04 52 pm" src="https://cloud.githubusercontent.com/assets/4975959/23049673/a01bbf6c-f48b-11e6-8794-f33dade9fad6.png">


**_View - Manager Dashboard page - Total Workers not set (Cases Assigned calculated) and no Work Completed_**
<img width="734" alt="screen shot 2017-02-16 at 9 05 04 pm" src="https://cloud.githubusercontent.com/assets/4975959/23049678/a773c5e8-f48b-11e6-9ac5-104b3688b184.png">

# Related Stories
Manager Dashboard | Update copy of page header and subtext #869
Manager Dashboard | Set number of Caseworkers for today #859
Manager Dashboard | Hide "Work History" section #860

**Comment by mdbenjam** [comment]
@lakohl Since you requested the main header to be ARC Work Assignments, do you want this secondary heading to also say Work Assignments?

**Comment by lakohl** [comment]
@mdbenjam good question! Sorry for the confusion. Per the AC in the comment above your last one, there is now only one header at the top of the page. Apologies,  the mocks at the top should have updated.

This is the whole page:
<img width="570" alt="screen shot 2017-02-21 at 2 21 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/23180937/1949012a-f841-11e6-9cd4-7bf857681f62.png">

**Comment by mdbenjam** [comment]
@lakohl Thanks for the clarification! Also, AC 6: 

> Verify that when the [TotalCaseworkersToday] value has not been set and no work has been done, the table displays one row with the following data element values:
> 
> Employee Name = "" (empty string)
> Cases Assigned = 0
> Cases Completed = 0
> Cases Remaining = [TotalCasesToday]

Should we still have the footer with the totals? The mock suggests not, but just want to double check.

**Comment by lakohl** [comment]
@mdbenjam There will not be any employee names in this state, so I think we can skip the Totals for now on the state when no cases have been assigned. 

<img width="603" alt="screen shot 2017-02-21 at 2 27 31 pm" src="https://cloud.githubusercontent.com/assets/4975959/23181187/fd6dcd40-f841-11e6-8aba-4a3b8d441613.png">

**Comment by lakohl** [comment]
Sorry you keep getting the issues with moving parts!

**Comment by mdbenjam** [comment]
Moving parts make life fun!! ⚙️ ⚙️

**Comment by astewarttistatech** [comment]
Blocked because there isn't a manager view that is accessible in UAT

**Comment by astewarttistatech** [comment]
**PASSED**

Steps to Validate: 
1.  Select the manager and caseworker roles in dispatch
2. Go to dispatch
3. Validate the mocks match the live view. 
Screenshots: 

<img width="1094" alt="screen shot 2017-02-22 at 12 22 17 pm" src="https://cloud.githubusercontent.com/assets/23038505/23223813/0f79067c-f8fa-11e6-868a-c8473e7a6d1c.png">

**Comment by mdbenjam** [comment]
@astewarttistatech I'm sorry, but what is missing? Isn't that button and field there? As a note, changing the number there, only changes the quota, it doesn't insert that number of rows in the table. People are only shown in the table once they actually work on a case.

**Comment by astewarttistatech** [comment]
@lakohl the buttons on the screenshot you posted last are different from what is currently displayed for "number of people working today". Is that a blocker for this issue?

**Comment by lakohl** [comment]
This is my fault, as I updated the issue in the comments while Mark was working on this.
This issue is exclusively for the table. So discrepancy in the number of workers section is not a blocker.

However, since you asked... what exists in dev today for the 'number of people working today' section  is a bit of a hybrid. We no longer need the update button, such a large box indicating the number of workers, or a label for the number of workers box. Instead that section should just say 'Number of people working today' in regular weight type and be followed by a box with up/down arrows to adjust the number of workers. Zero should be the default at the beginning of the day. Managers should not be able to select a negative number of workers.

**Comment by astewarttistatech** [comment]
**PASSED**

Tested in: UAT
Steps to Validate: 
1. Go to dispatch as a manager after EPs have been created as a caseworker
2. Verify the manager view 

Screenshots: 
<img width="1362" alt="screen shot 2017-02-27 at 11 46 40 am" src="https://cloud.githubusercontent.com/assets/23038505/23370416/99887e42-fce2-11e6-8582-eeb8fcb91a68.png">
