### ISSUE TITLE
Appeal Intake | Create record request task

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8674]
When an appeal intake is processed, if it contains issues for a non-comp non-pension business line, we need to generate a task in their queue to send them documents necessary to process the appeal.

## Acceptance Criteria
- When an appeal intake was successfully processed. If it had any issues of a non-comp non-pension business line, a "Record Request" task should be created in the appropriate business lines queue/queues.
- "Record Request" should be an option in the task filter on the non-comp landing page
 
## Additional Notes
When the board intakes an appeal for a non-VBMS LOB, that LOB must be notified to send the relevant records to the board for review.

To facilitate this:

- Create a "record request" task
- Add the task to the LOB's intake queue
- Link the task to a "record request" confirmation page
- On the confirmation page, allow the user to confirm that they have provided the necessary records
- Once confirmed, mark the task "completed" so that it appears in the Completed tab

Out of scope:
- What happens when you click the link for this task. We will handle the page for this task in a future issue.

**Comment by carolaponce** [comment]
Designs, pending address, will confirms once I have that info confirmed.
As a user, the task here is to verify the records have been sent by clicking on check box.

Copy:
Title - **Request to send Veteran record to the Board**
Description - The Veteran/appellant has filed a Notice of Disagreement at the Board of Veterans' Appeals. In order to decide that appeal, the Board will need the complete records from [BUSINESS LINE]. Please take necessary steps to send this record to the Board.
Mail to: ADDRESS

![non-comp_recordreq_completed](https://user-images.githubusercontent.com/11700545/51857255-99d1d980-22e6-11e9-9671-15c7cfb96eaf.png)
![non-comp_recordreq_completed](https://user-images.githubusercontent.com/11700545/51857257-9b030680-22e6-11e9-8998-b8ac1e36a96d.png)

**Comment by carolaponce** [comment]
![non-comp_recordreq](https://user-images.githubusercontent.com/11700545/51858008-84f64580-22e8-11e9-991e-a84c8a420ccb.png)

**Comment by steve-gov** [comment]
Validated:

<img width="628" alt="screen shot 2019-01-30 at 12 20 09 pm" src="https://user-images.githubusercontent.com/25468689/52010183-ba866480-2489-11e9-9f66-fef77beb3736.png">

<img width="223" alt="screen shot 2019-01-30 at 12 20 54 pm" src="https://user-images.githubusercontent.com/25468689/52010184-ba866480-2489-11e9-97d3-e3900bc9e857.png">

<img width="918" alt="screen shot 2019-01-30 at 12 22 03 pm" src="https://user-images.githubusercontent.com/25468689/52010185-ba866480-2489-11e9-8512-c5ef14d5e82d.png">
