### ISSUE TITLE
Caseworker Dashboard | Show claims established in terms of today's quota

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#868]
As a Caseworker, I want to see on the `Caseworker Dashboard` page how many claims I've established today and how many more I need to meet today's expected goal of assigned cases so that I am aware of what I have done and what still needs to be done.

# Acceptance Criteria
1. Verify that the **_Establish next claim_** button is sentence case.
1. Verify that the **_Establish next claim_** button and its subtext has been re-positioned and justified to the right of the `Caseworker Dashboard` page (refer to mockup).
1. Verify that the **_Establish next claim_** button's subtext has been changed to the following (refer to mockup):

     > [TotalCasesAssigned] cases assigned, [TotalCasesCompleted] completed
1. Verify that when no quota ([TotalCasesAssigned]) has been set, the **_Establish next claim_** button's subtext displays the following:

     > 0 cases assigned, [TotalCasesCompleted] cases completed
1. Verify that when the **_Establish next claim_** button is disabled because there are no more claims, the following subtext is displayed:

     > There are no more claims in your queue.

1. Verify that when no case assignment goal ([TotalCasesAssigned]) has been set and there are cases available in the queue, the **_Establish next claim_** button remains enabled for retrieving next available case.
1. Verify that when the case assignment goal ([TotalCasesAssigned]) has been met and there are cases available in the queue, the **_Establish next claim_** button remains enabled for retrieving next available case. 
1. Verify that after entering a value for _"Number of people"_ , clicking the **_Update_** button and the [TotalCasesAssigned] value has been updated  on the `Manager Dashboard` page, this change is reflected on the `Caseworker Dashboard` page in the instructional and action subtext where the [TotalCasesAssigned] is referenced.
## Mockups
**_View - Caseworker Dashboard - New Establish next claim subtext_**
![image](https://cloud.githubusercontent.com/assets/23063044/22988420/07bb374a-f380-11e6-91b9-268d053d1fe0.png)

# Related Stories
EP Confirmation | Show claims established in terms of today's quota #924
Manager Dashboard | Set number of Caseworkers for today #859

**Comment by nikitarockz** [comment]
As a Caseworker, I want to see how many claims I've established today and how many I need to meet today's expected goal of assigned cases so that I am aware of what I have done and what still needs to be done.

# Acceptance Criteria

**_Historical Comments_**
As a caseworker, I want to see how many claims I've established today and how many I need to meet today's quota (have been assigned to me).

## Acceptance Criteria

- Verify that the phrase '[number] cases assigned, [number] completed', appears next to the Establish Next Claim' button.
- Verify that when no quota has been set, the phrase above displays: '0 cases assigned, [number] cases completed'
1. Verify that when the Establish Next Claim button is disabled because there are no more claims, the following text is displayed (refer to mockup):
     > There are no more claims in your queue.

- Verify that when no cases have been assigned, I can still work new cases by clicking on Establish Next Claim'

- Verify that I can continue picking up new cases, even after I have completed the number of cases assigned to me.

- Verify that on the Congratulations page, the number of cases completed and the number of cases assigned displays as follows: 'Way to go! You have completed [number] out of the [number] cases assigned to you today.'

_**Mocks:**_
<img width="813" alt="screen shot 2017-02-10 at 6 28 02 pm" src="https://cloud.githubusercontent.com/assets/4975959/22847946/ba45da0c-efbe-11e6-9063-c077f595e51b.png">

<img width="749" alt="screen shot 2017-02-10 at 6 57 34 pm" src="https://cloud.githubusercontent.com/assets/4975959/22848480/d5cd6976-efc2-11e6-87a8-353e66d5ff40.png">


<img width="485" alt="screen shot 2017-01-27 at 7 14 27 pm" src="https://cloud.githubusercontent.com/assets/4975959/22392204/dca0b1f8-e4c4-11e6-94c5-9f8cb10811d6.png">

**Comment by kierachell** [comment]
@nikitarockz @lakohl please update AC
![lara_decree](https://cloud.githubusercontent.com/assets/18075411/23574695/254495f0-004f-11e7-8fbc-2299e9c39304.png)

**Comment by lakohl** [comment]
@kierachell I added the sentence case button to the AC above

**Comment by kierachell** [comment]
**PASSED**
Completed some cases:
![screenshot_2017-03-07_16-27-44](https://cloud.githubusercontent.com/assets/18075411/23678688/2f15b666-0353-11e7-9f59-f4e784af1a69.png)


## BONUS:
reassigned and made myself into an overachiever.
![screenshot_2017-03-07_16-28-57](https://cloud.githubusercontent.com/assets/18075411/23678723/474a11fa-0353-11e7-93af-66ac7d52b858.png)
