### ISSUE TITLE
Stop Rails server from hanging in local development environments

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8752]
Since [we upgraded to Ruby 2.5.1](https://github.com/department-of-veterans-affairs/caseflow/pull/6461) in August of 2018, we have been plagued by the Rails server in our local developments hanging frequently. This ticket exists as a thread to collect examples of this hanging behaviour so we can discover patterns, gather reliable steps to reproduce a non-responsive rails server, and ultimately explore avenues to resolve the problem of the hanging Rails server.

In September 2018, [we changed the eager_load config to true](https://github.com/department-of-veterans-affairs/caseflow/pull/6833) in attempt to solve the problem of the non-responsive Rails server. We are still experiencing this issue, so it appears as if that solution was insufficient.

**Comment by sharonwarner** [comment]
My local server freezes pretty infrequently, but whenever it does, the last request in the log is always getting tasks by role (in this case it was `Started GET "/appeals/2687879/tasks?role=Attorney"`.

**Comment by monfresh** [comment]
The hang can usually be reproduced after making a change to a Ruby file, then attempting to reload the browser page. I believe I've seen this happen more often when changing a model, for example, LegacyAppeal (such as adding a `puts` statement), and then reloading an Attorney's queue page.

I believe this is due to threading in Puma and the many simultaneous requests the frontend makes. I am unable to reproduce the hang after running the app with `RAILS_MAX_THREADS=1`. I came to this conclusion after debugging with the [ActionDispatch::DebugLocks](https://api.rubyonrails.org/classes/ActionDispatch/DebugLocks.html) middleware provided by Rails:

1. Add `config.middleware.insert_before Rack::Sendfile, ActionDispatch::DebugLocks` to application.rb 
2. Run the app with the default 5 Puma threads
3. Reproduce the hang
4. Visit http://localhost:3000/rails/locks 
5. Do a browser search for `Waiting in start_exclusive to "load"` that shows up in the stack trace
6. Read the following posts in the search results:
    - https://github.com/rails/rails/issues/27455
    - https://github.com/puma/puma/issues/1085
    - https://github.com/rails/rails/issues/32451

Notice that many of them suggest to only use 1 thread. This seemed to be the only thing that worked.

**Comment by monfresh** [comment]
Some of the posts above also suggest disabling the `wrap_parameters` initializer. Setting `format` to an empty array seems to solve the hanging issue as well, even with 5 threads:
```ruby
ActiveSupport.on_load(:action_controller) do
  wrap_parameters format: []
end
``` 
`params_wrapper` appears in the stack trace when the hang is reproduced.

I'm not sure what the consequences are for not using parameter wrapping for JSON.

**Comment by monfresh** [comment]
Reading about [parameter wrapping](https://api.rubyonrails.org/v5.2.3/classes/ActionController/ParamsWrapper.html), it seems to be a convenience for POSTing with less verbose parameters. The tests are all passing with parameter wrapping disabled, so it doesn't appear we are using it. It's possible other consumers of our APIs depend on it being enabled, but that would surprise me. We should double check.
