### ISSUE TITLE
Manager Dashboard | View Dashboard | Launch Dispatch Stats page

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#883]
As a Manager, I would like to see the `Dispatch Stats` page so that I can monitor how the Dispatch process.  

# Acceptance Criteria
1. Verify that when the link **_View Dashboard_** on the `Manager Dashboard` page is clicked, the `Dispatch Stats` page is displayed in a new web browser tab.
1. Verify that managers have permission to see the Dispatch Stats page and no other stats pages.

## Mockup
**_View - Manager Dashboard - View Dashboard link_**
<img width="716" alt="screen shot 2017-02-16 at 9 11 55 pm" src="https://cloud.githubusercontent.com/assets/4975959/23049806/91a6cc50-f48c-11e6-97b9-6e8570c9e943.png">

**_View - Stats page - Example_**
![dashboard daily](https://cloud.githubusercontent.com/assets/23063044/23275159/680652c0-f9d3-11e6-9f07-e30df1c44ffd.PNG)

# Related Stories
**_Pre-requisites_**
Dsipatch Stats | Display stats charts #819

**Comment by lakohl** [comment]
Add back button to stats

**Comment by astewarttistatech** [comment]
@sharonwarner Please link the stats page to the actual view dashboard page. Pushing back to In Progress. 

Current view:
<img width="1334" alt="screen shot 2017-03-15 at 10 00 51 am" src="https://cloud.githubusercontent.com/assets/23038505/23952009/636813e6-0966-11e7-9ddc-857f48708c7d.png">

**Comment by sharonwarner** [comment]
That is the stats page, the graphs just aren't there yet.

**Comment by astewarttistatech** [comment]
Until page is finished, this issue has failed validation. AC can be changed as a possible solution with @lakohl

**Comment by astewarttistatech** [comment]
Per my conversation with @lakohl this issue is 

**PASSED**

Validated In: UAT
Steps to Validate: 
1. As a manager role, go to dispatch to view it as manager and click the view "View Dashboard" link.
2. Verify that View Dashboard link takes you to the correct page (stats page). 

Screenshots: 
<img width="1334" alt="screen shot 2017-03-15 at 10 00 51 am" src="https://cloud.githubusercontent.com/assets/23038505/23953116/070ef35e-096a-11e7-85ca-2b8ac0d0e5d6.png">
![Uploading Screen Shot 2017-03-15 at 10.27.28 AM.png…]()

**Comment by nemodjuric** [comment]
@sharonwarner Which role should dispatch/establish-claim route check for?
