### ISSUE TITLE
error on COMPLETE_INTAKE_FAIL

### ISSUE THREAD

**Issue by kencheeto** [department-of-veterans-affairs/caseflow#8889]
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/

**Comment by leikkisa** [comment]
This might be related to queue.

**Comment by kencheeto** [comment]
@leikkisa what gives you that impression? this is starting to happen more often now, so i think we should look into this soon

**Comment by kencheeto** [comment]
Similar looking error in https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3618/

**Comment by leikkisa** [comment]
I think this is another example where Sentry errors are getting grouped strangely, because right now this is the latest:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/events/236955/

I think this is the intake-related one:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/events/236466/

**Comment by leikkisa** [comment]
This Sentry error looks similar:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3805/events/250857/
For Intake 133695 this got canceled with a duplicate EP message (note that these are user entered).

**Comment by msj0nes** [comment]
Ticket closure. Sentry +1yr old.
