### ISSUE TITLE
Disable checkout actions for Legacy appeals

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8946]
Per this slack thread these actions also show for active appeals that haven't been distributed for decision yet. The actions are likely on for all Case details pages because of users' roles, regardless of the step in the appeals process, and because these are Legacy appeals.

Tagging @aroltsch.

What happens in DAS and VACOLS when a judge or attorney user tries to "check out" a legacy appeal that isn't assigned to them, or that isn't active?
What's your initial impression of the lift to remove the actions dropdown for legacy appeals outside of the judge-attorney-judge loop? Wondering if there's a quick fix, and future (or more ideal) fix when we're working on transferring Legacy tasks to Caseflow tasks.

**Comment by aroltsch** [comment]
This sentry alert is related to this problem: https://github.com/department-of-veterans-affairs/caseflow/issues/8557
The user who is not assigned this appeal, clicks to create a draft decision and here is what they see: 

![image](https://user-images.githubusercontent.com/3811786/52132681-acf9e780-260d-11e9-819d-99ce26ec556a.png)

**Comment by lowellrex** [comment]
I think the problem here is that [`TasksController.for_appeal()`](https://github.com/department-of-veterans-affairs/caseflow/blob/5e63a4b79bf806f17b75534850c132c33b7ea1cb/app/controllers/tasks_controller.rb#L102) creates an `AtttorneyLegacyTask` for the appeal ID [in `LegacyWorkQueue`](https://github.com/department-of-veterans-affairs/caseflow/blob/5e63a4b79bf806f17b75534850c132c33b7ea1cb/app/models/queues/legacy_work_queue.rb#L20) even if the current user is not the current assignee. First step at solving this might be to modify `LegacyWorkQueue.tasks_by_appeal_id()` to require a user in addition to the appeal ID.
