### ISSUE TITLE
Hide assign to team option from VSOs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8955]
IHP-writing VSOs should not assign cases to BVA teams. They should only complete IHP tasks. 

## AC
- Actions dropdown does not contain `Assign to team`

**Comment by lowellrex** [comment]
VSOs currently do not have the option to assign tasks to teams... don't know why I thought they did last week (maybe our test data was incorrect?). 

```ruby
rails c> Task.all.select { |t| t.assigned_to.is_a?(Vso) }.pluck(:type).uniq
# ["InformalHearingPresentationTask"]
```

The only tasks that are assigned to VSOs are IHP tasks and IHP tasks [do not have the option](https://github.com/department-of-veterans-affairs/caseflow/blob/1e3b6f2f314d299ad6672a9ad9cee87f34305981/app/models/tasks/informal_hearing_presentation_task.rb#L6) to assign cases to Board teams.

Closing this ticket out because the work is already done!
