### ISSUE TITLE
Data Integrity | Add hearings data integrity checks

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#8992]
We should alert in the following situations:
- If there's an appeal with 1) an open root task, 2) the vacols location is 'caseflow', and 3) no open children tasks
- If there's an appeal with an open ScheduleHearingTask that has been in docket range for more than 6 months
- If there's an appeal with an open NoShowHearingTask that has been open for more than 25 days
- If there's an appeal with an open EvidenceWindowTask that has been open for more than 90 days
- If there's an appeal with an open HearingAdminTask that has been open for more than 6 months
- If there's an appeal with an open TranscriptionTask that has been open for more than 6 months

**Comment by MeredithStewart** [comment]
Asked Justin for his thoughts on this -- He thought no Admin Action task should be open for more than 3-4 months.

**Comment by MeredithStewart** [comment]
From conversation with Scott on 2/5/19: 
* For ScheduleHearingTask -- the problem with this task is that it could be open for years because a Veteran is outside of the hearing docket date. However, it would be great if we could see those that are outstanding by years by form 9 date for Legacy and NOD date for AMA. So - Schedule Hearing tasks that are open for by years -- 2005, 2006, 2007, etc. This would help identify the hearings that need to be cleared out ASAP. 
* For Admin Actions -- Scott thought it would be good to have thresholds for each type, but otherwise, if 6 months has passed and an admin action hasn't been closed, that would be good to have on a report. 
* For HoldHearingTask -- Scott's would like this to be tied to any HoldHearingTasks that are open (no disposition marked) past the hearing date. This is preferable. There are some situations where a Veteran might be scheduled long in advance of the actual hearing (if they are coming form out of the country). If this isn't possible, then a report that could show those that are open for longer than 60 days could work. 
* Transcription tasks - any that are open longer than 6 months. Right now the backlog is 4-5 months.

**Comment by lomaxap** [comment]
see [metrics here](https://caseflow-looker.va.gov/dashboards/22). I have not turned on any alerts yet. What's the process for after we get an alert?

**Comment by MeredithStewart** [comment]
Could we add something for Veterans that aren't being geo-matched and aren't getting admin tasks? Or is there a different way to have visibility on those?
