### ISSUE TITLE
Reassign VLJ Support Staff cases to those who are working in Caseflow only

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9236]
There are 9 VLJ Support Staff. So we can allow all attorneys and judges to assign admin actions to their team, and because there are still admin actions being assigned to them for legacy cases in Caseflow, the VLJ Support branch has decided to split their team up into:
- 5 people working legacy and AMA admin actions in Caseflow
- 4 people working legacy admin actions assigned by paralegals in VACOLS, and working through the VACOLS abeyance backlog

We need to reassign tasks assigned to the 4 VACOLS folks among the 5 working in Caseflow, and remove the 4 VACOLS folks from the VLJ Support Staff organization so they no longer are assigned new tasks. When this is done, we can turn admin actions on for all attorneys and judges (https://github.com/department-of-veterans-affairs/caseflow/issues/8757).

In the future, team admins will be able to do this reassigning themselves - #7999 - but we have not yet implemented it.

## AC
- [x] The following users remain in the VLJ Support Staff organization:
   - Tina Hunter
   - Marvin Koroma
   - Randy Seay
   - Modusta Wallace
   - Pam Totten-Browning
- [ ] Reassign `assigned` and `viewed` tasks:
   - Assign Maleka Giovinco, Lofranda Lewis, Lazette Clanton, Maurice Jones, and Andre Johnson's tasks with status `assigned`, `viewed` round robin among Tina Hunter, Marvin Koroma, and Randy Seay. 
   - These tasks should have the status `assigned` and Days waiting should begin again at 0 for the newly assigned user
   - *Note: I've excluded Modusta and Pam because they already have close to 100 tasks on their plate*
- [ ] Ressign `on_hold` tasks
   - Assign Maleka Giovinco, Lofranda Lewis, Lazette Clanton, Maurice Jones, and Andre Johnson's tasks with status `on_hold` round robin among Tina Hunter, Marvin Koroma, and Randy Seay. 
   - These tasks should have the status `on_hold` and Days on hold should remain the same as they were when on the former users' plate. This is because this reassignment should not extend the Veteran's time on hold
   - *Note: I've excluded Modusta and Pam because they already have close to 100 tasks on their plate*
- [x] The following users have been removed from the VLJ Support staff organization
   - Maleka Giovinco
   - Lofranda Lewis
   - Lazette Clanton
   - Andre Johnson
   - Maurice Jones
- Do not move any tasks that with status `completed`

## Resource
Look that has a count of admin action tasks per VLJ Support Staff user - https://caseflow-looker.va.gov/looks/98

<img width="932" alt="screen shot 2019-02-06 at 9 55 45 am" src="https://user-images.githubusercontent.com/27704093/52349888-6d5c4280-29f5-11e9-97e7-834a59b9c9dc.png">

**Comment by marvokdolor-gov** [comment]
- For the first and fourth ACs above, here's a snapshot of the VLJ Support Team page as of 10:15am 02/06/2019:
<img width="1085" alt="screen shot 2019-02-06 at 10 15 04 am" src="https://user-images.githubusercontent.com/31679660/52351228-4f441180-29f8-11e9-915d-c2eaedaff8dc.png">

- I will adjust the VLJ Support Weekly report to reflect the new shape of the team once the other ACs are addressed.

**Comment by lowellrex** [comment]
What I've got so far. Will tackle this next sprint since this should live in code:
```ruby
  rails c> team_members = Colocated.singleton.users
  # Who has ColocatedTasks that need to be reassigned to other folks?
  rails c> reassigned_users = ColocatedTask.where.not(status: "completed").where.not(assigned_to: [team_members, Colocated.singleton].flatten).map(&:assigned_to).uniq
  rails c> reassigned_users.count
  # 5
  # Should only be 4.
  rails c> reassigned_users.pluck(:full_name, :css_id)
  # Maurice Jones is in this list but was not mentioned as somebody who needs their tasks re-assigned
  # Which tasks are assigned to him?
  rails c> u = User.find_by(css_id: "BVAMJONES")
  rails c> maurice_tasks = Task.where(assigned_to: u).where.not(status: "completed")
  rails c> maurice_tasks.count
  # 42
  rails c> maurice_tasks.pluck(:type).uniq
  # ["ColocatedTask"]
  # Confirmed with LP that Maurice should also have been removed. Great success!
  # Do they have any other types of tasks in Caseflow?
  rails c> Task.where.not(status: "completed").where(assigned_to: reassigned_users).pluck(:type).uniq
  # ["ColocatedTask", "GenericTask"]
  # What're those GenericTasks about?
  rails c> generic_tasks = GenericTask.where.not(status: "completed").where(assigned_to: reassigned_users)
  rails c> generic_tasks.count
  # 3
  rails c> generic_tasks.map(&:parent).map(&:parent).map(&:assigned_to)
  # All of these came through either Jessie or the MailTeam (probably by way of Jessie)
  # Not going to reassign those for now.
  rails c> tasks_to_reassign = ColocatedTask.where(assigned_to: reassigned_users).where.not(status: "completed")
  rails c> tasks_to_reassign.count
  # 204
  # Do any of these tasks have children?
  rails c> tasks_to_reassign.map { |t| t.children.count }.sort
  # A few have 1 child task. Let's capture the IDs of those tasks and their child tasks.
  rails c> tasks_with_kids = tasks_to_reassign.select { |t| t.children.count > 0 }
  rails c> tasks_with_kids.count
  # 5
  rails c> tasks_with_kids.map { |t| [ t.id, t.children.first.id] }
  # [[1798, 11836], [1879, 30615], [10093, 11839], [12926, 15789], [25544, 26227]]

  # How many active ColocatedTasks do we have before?
  rails c> ColocatedTask.where.not(status: "completed").count
  # 1038
  # What is the most recent task ID?
  rails c> Task.order(:created_at).last.id
  # 32274

  # Haven't done the copying yet, but it will look something like:
  rails c> ActiveRecord::Base.transaction do
  tasks_to_reassign.each do |task|
    new_task = task.dup.tap do |t|
      t.assigned_to = ColocatedTaskDistributor.new.next_assignee
      t.save!
    end
    task.children.each do |t|
      t.update!(parent: new_task)
    end
    task.update!(status: Constants.TASK_STATUSES.completed)
  end
end
```

**Comment by lowellrex** [comment]
MEDIUM. Let's use the new test-covered rake task pattern.

**Comment by laurjpeterson** [comment]
@lowellrex - since we've released team admins' ability to reassign tasks, should I ask Rolandus and corey to do this instead? I know it's a lot of tasks and it would be tedious...but I could try?

**Comment by lowellrex** [comment]
I think it's worth a shot! Re-assigning 200 tasks will surely be tedious, but they can do it for the higher priority ones for sure.

**Comment by marvokdolor-gov** [comment]
@lowellrex going to assign this to you because we'll need to reassign these cases manually please. Corey and Rolandus aren't able to access their management page. I impersonated both of them today (3/22/19)...
<img width="1045" alt="Screen Shot 2019-03-22 at 2 48 42 PM" src="https://user-images.githubusercontent.com/31679660/54846219-be787b00-4cb1-11e9-8707-f2bda37c61d4.png">

and got this page when I tried to access VLJ Support Staff Cases:
<img width="1277" alt="Screen Shot 2019-03-22 at 2 47 03 PM" src="https://user-images.githubusercontent.com/31679660/54846227-c59f8900-4cb1-11e9-9778-d5f055fd1b64.png">

**Comment by lowellrex** [comment]
The VLJ support staff queue does not load cases because it takes [more than 5 minutes](https://github.com/department-of-veterans-affairs/caseflow/blob/cf6a53532a6b57a7c3bc58ee0d210fdb1b2a2905/client/app/queue/OrganizationQueueLoadingScreen.jsx#L20) for the server to respond to the browser's request for active tasks assigned to the organization (there are currently more than 2,000 active tasks assigned to the VLJ support staff organization). I was able to determine this by simulating the back-end component of this request as follows:

```ruby
rails c> u = Colocated.singleton.users.first
rails c> tasks = GenericQueue.new(user: Colocated.singleton).tasks
rails c> tasks.count
# 2086
rails c> js_tasks = ActiveModelSerializers::SerializableResource.new(
    AppealRepository.eager_load_legacy_appeals_for_tasks(tasks),
    user: u
  ).as_json
```

Below are a chart and table that show how long it takes to execute each phase of that last command which represents the data fetching part of the VLJ support staff organization page load (there are other components of that request, but this is almost certainly the most expensive). I ran this command twice this morning (10:20am eastern and 11:00am) from the production rails console so it is not a precise measurement of the time it takes to get a response to the browser, but it is indicative of where the bottlenecks are in that process.

![image](https://user-images.githubusercontent.com/32683958/55009692-61ced600-4fb9-11e9-9ebb-660b18797de6.png)

Phase | Trial 1 | Trial 2
-- | -- | --
Startup | 14 | 13
Initial VACOLS load (cases and tasks) | 58 | 62
VACOLS::Staff table load | 8 | 10
AttorneyCaseReviews load for serializer | 40 | 31
AttorneyCaseReviews load for serializer | 60 | 48
Total time | 180 | 164

The most expensive phases of the data fetching part of the page load are 1) the initial VACOLS load of cases and tasks, and 2) the individual select statements on [the `AttorneyCaseReviews`](https://github.com/department-of-veterans-affairs/caseflow/blob/cf6a53532a6b57a7c3bc58ee0d210fdb1b2a2905/app/models/serializers/work_queue/task_serializer.rb#L99) and [`AvailableHearingLocations` tables](https://github.com/department-of-veterans-affairs/caseflow/blob/cf6a53532a6b57a7c3bc58ee0d210fdb1b2a2905/app/models/serializers/work_queue/task_serializer.rb#L79) while serializing fields for individual tasks. These two phases (or collection of phases) account for roughly half of the entire execution time.

Using this data we can speculate on ways to reduce the amount of time it takes for the server to respond, allowing the VLJ support staff organization queue to actually load. 
1. *Paginate the request*. The reason we are running into this problem for the VLJ support staff org queue but not other queues (except for hearings queue which we'll get to in a minute) is because of the sheer number of tasks in the queue. If we were to request only the first, say, 100 tasks we could dramatically reduce the amount of time both the serialization and eager VACOLS load phases take. Given the way we've designed other components of the system, this is probably extraordinarily complex though I imagine it will be needed at some point down the line if not now.
1. *Stop loading `AttorneyCaseReviews` and `AttorneyCaseReviews` information in the serializer*. I don't know if this is feasible from a product perspective (haven't yet dug into where this information is used on the front-end) but this is almost certainly the quickest fix.
1. *Return summary task info on queue table views and detailed task info on case details pages*. We do something similar for appeals/appealDetails so this is a pattern we already have. This is certainly possible and maybe not all that complex, but it would require a fairly sizable refactor of the front-end (though maybe our increased reliance on reducers makes this refactor easier?).

There are some hybrid approaches here (for example, [defining `available_hearing_locations`](https://github.com/department-of-veterans-affairs/caseflow/blob/cf6a53532a6b57a7c3bc58ee0d210fdb1b2a2905/app/models/serializers/work_queue/task_serializer.rb#L79) as an "extra field" and [excluding extra fields from being serialized](https://github.com/department-of-veterans-affairs/caseflow/blob/cf6a53532a6b57a7c3bc58ee0d210fdb1b2a2905/app/controllers/organizations/tasks_controller.rb#L10) when there are many tasks: `exclude_extra_fields: !tasks.count > 100`), but these are the distinct approaches I could come up with. Curious to hear if folks have thoughts around different approaches, hybrids, or preferences for which approach to pursue.

**Comment by marvokdolor-gov** [comment]
@lowellrex I don't have any input on the possible options but I do have an ask:
Would you be able to find any time this week to reassign all tasks to the current VLJ Support staff please?
This would mean ensuring that all VLJ Support Staff tasks are assigned to one of the following people/ids and no one else:
- BVAPBROWNING
- BVAMWALLACE
- BVATHUNTER
- BVARSEAY
- BVAMJKOROMA

**Comment by pkarman** [comment]
given the complexity of (1) I think (3) sounds like a fair approach.

**Comment by lowellrex** [comment]
@marvokdolor-gov I reassigned 375 `ColocatedTask`s that were assigned to users who are not in the `Colocated` organization. Let me know if this looks good and we can close out this ticket!

```ruby
  # How many ColocatedTasks are assigned to users who are not a member of the Colocated org?
  rails c> tasks = ColocatedTask.active.where(assigned_to_type: User.name).where.not(assigned_to_id: Colocated.singleton.users.pluck(:id))
  rails c> tasks.count
  # 375

  # Who are those tasks assigned to?
  rails c> non_vlj_assignees = tasks.map(&:assigned_to).uniq
  rails c> non_vlj_assignees.pluck(:full_name)
  # Looks like these folks are members of the VLJ support staff who are just not
  # working AMA cases yet.
  # Let's record their IDs.
  rails c> non_vlj_assignees.pluck(:id).sort
  # [616, 1829, 1885, 2012, 2014, 2227]

  # Let's also record the IDs of the tasks we're about to change.
  rails c> tasks.pluck(:id).sort
  # [1643, 1679, 1684, 1743, 1745, 1767, 1787, 1792, 1796, 1798, 1822, 1828, 1838, 1869, 1879, 1890, 1927, 1939, 1941, 1945, 1947, 1963, 1976, 2000, 2006, 2046, 2048, 2058, 2060, 2099, 2106, 2110, 2118, 3112, 4112, 4160, 4448, 4482, 5100, 5120, 5308, 5331, 6058, 6370, 6495, 7145, 7260, 7721, 7788, 8392, 8528, 8581, 9165, 9282, 9401, 9965, 10028, 10093, 10993, 11087, 11150, 11459, 11552, 11562, 11734, 11921, 11948, 12320, 12331, 12519, 12794, 13009, 13217, 13270, 13274, 13614, 13646, 13860, 15037, 15421, 15544, 15827, 15897, 16065, 16126, 16339, 16363, 16695, 16709, 16715, 16716, 16749, 16750, 16756, 16757, 16805, 16812, 16873, 16940, 17365, 17393, 17505, 17506, 17508, 17509, 17514, 17515, 17517, 17518, 17523, 17526, 17527, 17532, 17536, 18547, 20553, 20606, 20742, 20788, 21864, 22212, 22297, 22328, 22578, 23076, 23149, 23415, 23446, 23998, 24112, 24935, 25261, 25542, 25544, 25594, 26782, 27192, 27222, 27327, 27353, 27623, 27639, 27703, 27705, 27707, 27913, 27927, 28242, 28262, 28522, 28568, 29030, 29032, 29079, 29099, 29320, 29498, 29625, 29656, 29815, 30001, 30027, 30160, 30172, 30573, 30588, 30652, 30713, 31075, 31244, 31259, 31406, 31587, 31589, 31804, 31806, 31808, 31819, 51336, 51343, 51393, 51552, 51555, 51558, 51569, 51866, 51869, 51873, 51887, 51891, 51893, 53200, 54298, 54302, 58145, 58643, 59535, 59886, 62373, 62387, 62543, 63286, 63649, 63660, 63685, 64496, 64521, 64529, 65925, 66147, 66157, 66166, 66254, 66269, 66271, 66273, 66292, 66478, 66569, 66618, 66683, 66686, 66748, 66752, 66848, 66853, 66875, 66895, 66905, 66929, 66936, 66945, 67033, 67038, 67040, 67043, 67055, 67060, 67067, 67082, 67106, 67379, 67404, 67407, 67706, 67713, 67718, 67720, 67724, 67730, 67733, 67753, 67757, 67763, 67771, 67781, 67789, 67801, 67817, 67821, 67823, 68735, 68747, 68761, 68765, 68767, 68788, 68791, 68804, 68806, 68822, 68824, 69649, 69785, 70004, 70011, 70027, 70045, 70049, 70053, 70057, 70064, 70878, 70902, 70908, 70910, 70919, 70921, 70923, 70945, 70959, 71988, 71995, 72054, 72068, 72944, 72946, 72948, 72953, 72980, 72988, 73000, 73020, 73503, 74169, 74172, 74174, 74176, 74179, 74181, 74188, 74207, 74212, 74227, 74232, 74234, 74239, 74677, 74794, 74800, 74853, 74857, 74864, 74870, 74876, 74899, 74901, 74904, 74911, 74913, 74919, 74929, 74932, 74935, 74937, 75000, 75027, 75030, 75038, 75042, 75056, 75076, 75078, 75096, 75139, 75143, 75148, 75156, 75194, 75215, 75217, 75344, 75353, 75355, 75376, 75388, 75401, 76054, 76056, 76078, 76087, 76100, 76107, 76118, 76121, 76126, 76132, 77285, 77306, 77308, 77324, 77340, 77342, 77345, 77349]

  # Because I'm curious let's see what the bounds of these tasks' creation dates are.
  rails c> tasks.order(:id).first.created_at
  # Tue, 20 Nov 2018 16:14:00 UTC +00:00
  rails c> tasks.order(:id).last.created_at
  # Thu, 21 Feb 2019 15:52:57 UTC +00:00

  # Let's count how many active tasks there were before so we can double-check our work after:
  rails c> ColocatedTask.active.count
  # 3876

  # Let's test out strategy out with a single task before we apply it to the whole set.
  rails c> tasks.first.id
  # 31819
  rails c> tasks.first.reassign({assigned_to_type: User.name, assigned_to_id: ColocatedTaskDistributor.new.next_assignee.id}, Colocated.singleton.admins.first)
  # Success!
  rails c> ColocatedTask.active.count
  # 3876. Still have the same number of active ColocatedTasks. Excellent.

  # Let's re-fetch the list of tasks to exclude the one we just reassigned.
  rails c> tasks = ColocatedTask.active.where(assigned_to_type: User.name).where.not(assigned_to_id: Colocated.singleton.users.pluck(:id))
  rails c> tasks.count
  # 374
  # Perfect! One fewer.

  # Let's reassign all of the tasks.
  rails c> tasks.each { |t| t.reassign({assigned_to_type: User.name, assigned_to_id: ColocatedTaskDistributor.new.next_assignee.id}, Colocated.singleton.admins.first) }

  # Were any tasks that we wanted to reassign not reassigned?
  rails c> ColocatedTask.active.where(assigned_to_type: User.name).where.not(assigned_to_id: Colocated.singleton.users.pluck(:id))
  # []. Nope!

  # Is the active ColocatedTask count the same?
  rails c> ColocatedTask.active.count
  # 3876
  # Right on!

  # Let's spot check an old task to see if a sibling was created.
  rails c> task = Task.find(74876)
  rails c> task.status
  # "cancelled"
  rails c> task.parent.children.order(:created_at).pluck(:id, :created_at, :type, :status)
  # [[74876, Wed, 20 Feb 2019 14:12:55 UTC +00:00, "ColocatedTask", "cancelled"], [152367, Tue, 26 Mar 2019 22:57:58 UTC +00:00, "ColocatedTask", "assigned"]]
  # Perfect!
```

**Comment by marvokdolor-gov** [comment]
@lowellrex This looks fab. Thank you very much!
Closing.
