### ISSUE TITLE
Discussion: How to modify data in production

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#9261]
How should we modify data in production? We have two main approaches:
1) Modifying data in the rails console in production
2) Modifying data in a migration

In the five whys discussion around why we had downtime on 2/5/2019 we came up with some provocations:
- We could have a replica of production in either preprod or some other sandbox environment where we could test our migrations.
- We should avoid coupling a schema change and a data change in our migrations
- Are there other patterns we can use to modify data
- Is it okay to use rails console for modifying small number of records, but leave larger changes to migrations

I think the goal here is how do we find simple ways to make our migrations safer, without swinging too far in the other direction and slowing us down.

Discuss!

**Comment by kencheeto** [comment]
Some strategies for validating data migrations / fixes:

* Write queries that you intend to run before and after the data change that validate numbers you'd expect to see in prod
* Test your data migration using a 'dry run' mode
  * Write a 'dry run' flag into your data migration that, when active, skips any writes in your data migration but exercises the rest of the logic
  * Create a read-only user in the prod replica
  * Using the read-only user, passing an active dry run flag, run the data migration against the prod replica
  * Writing a data migration in this way might mean breaking up queries to have more granular control in Ruby, but migrations typically aren't too performance sensitive. It's also not always possible to test with a dry run flag, since a migration might require intermediate writes

**Comment by pkarman** [comment]
An example of doing data change in a migration: #9239

**Comment by aroltsch** [comment]
* Login to production box to validate your assumptions if possible
* Create a separate PR for the data migration - this PR cannot contain any other changes
* Once merged to master, deploy the code to production using Jenkins deploy button and make sure deploy is successful 
* If it is not successful, revert the PR and merge the reverted PR to master

**Comment by alisan16** [comment]
Closing this issue as it doesn't have AC. This issue is still searchable as reference.
