### ISSUE TITLE
Intake | Show the promulgation date and not the profile date on the add issues modal

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9297]
We've been informed by the business to show the promulgation date and not the profile date on the Add Issues modal. Should be a straightforward fix.

**Comment by pkarman** [comment]
@shanear should the DecisionIssue approx decision date use `promulgation_date` as well? see question in https://github.com/department-of-veterans-affairs/caseflow/pull/9345#pullrequestreview-202350148

**Comment by pkarman** [comment]
Testing notes: find a rating with different profile and promulgation dates and verify the promulgation date is the visible "Decision Date" in the Add Issues modal.

**Comment by steve-gov** [comment]
Validated in UAT that rated issue shows promulgated date instead of profile date:

<img width="241" alt="screen shot 2019-02-15 at 12 03 18 pm" src="https://user-images.githubusercontent.com/25468689/52881550-bad55f80-3119-11e9-9462-b35cb135d2f4.png">

<img width="542" alt="screen shot 2019-02-15 at 12 03 11 pm" src="https://user-images.githubusercontent.com/25468689/52881552-bc9f2300-3119-11e9-947a-859f07229265.png">
