### ISSUE TITLE
Decision Sync | DTA Supplemental Claim for second EP will create excessive issues

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9303]
When the second EP of an HLR is cleared, if both the first and the second EP had DTA errors, then the second Supplemental Claim will be created with all of the issues from the first HLR. This is incorrect.

### Validation
- Create a HLR with a rating and nonrating request issue
- Have Colin DTA error both of the issues.  Have him clear the end products at different times (a day apart if possible).
- Check that that the issue one the first one that got cleared does not have a duplicate new request issue on a DTA supplemental claim. They should both have one new request issue (can be on one, or two different supplemental claims).

- Can probably combine this with #9142 since they both require a similar set up

**Comment by leikkisa** [comment]
I propose adding a link to the end product establishment remanded in Supplemental Claim.  Otherwise, an HLR could have two DTA Supplemental claims, both that look somewhat identical except the issues on them.  Kind of like how Appeal can have multiple DTA SCs which are separated by the Benefit Type, HLRs can have multiple DTA SCs which are separated by the end product establishment.

This might also allow us to refactor some more of the remand code to be shared between HLRs and Appeals (the appeals code does already check that an issue isn't already being contested).

**Comment by leikkisa** [comment]
This ended up being harder than expected due to parallel development with the API status, which was using the 1:1 paradigm for dta claims. I didn't do anything with connecting the EPE (mentioned above), I'll leave that for the actual ticket that needs that (also in case there's a different approach).

This might be hard to validate. If the original Higher Level Review has two end products and they get decided at different enough times (for them to get synced separately) or get synced separately somehow. Then check that the DTA supplemental claim doesn't have any duplicate issues.

**Comment by Sjones352** [comment]
Combined with #9142

**Comment by Sjones352** [comment]
Colin validated #9142 and it passes. 
<img width="462" alt="Screen Shot 2019-03-20 at 11 47 57 AM" src="https://user-images.githubusercontent.com/23080951/54699113-d069ea80-4b06-11e9-8f28-4fe39adf367c.png">
