### ISSUE TITLE
Multiple clicks creates multiple tasks

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9332]
We identified an instance of multiple tasks being created when an attorney assigned an admin action to VLJ Support Staff. We think this is an issue with the modal. 

![multiple tasks](https://user-images.githubusercontent.com/27704093/52572014-cefd2200-2de4-11e9-9aaa-ac91dd20293d.jpg)

## AC
- When a user assigns a task, only one task is created, even if the user clicks submit multiple times
- The duplicate tasks are canceled, and no longer assigned to VLJ Support (Randy Seay)

**Comment by lowellrex** [comment]
SMALL. Reproducing this might be the hardest part. Is there a safeguard on the frontend that prevents the request from being sent (inspect `EditModalBase`)? Is it just not working? Is this true for all buttons in the app and we are only seeing it for this one since it results in the creation of one (or more!) tasks?

Feel free to create tickets if this becomes a rabbit hole. Only tackle the multiple task creation issue if it starts to explode.

**Comment by youngfreezyVA** [comment]
have been unable to reproduce this. theory is that attorney actually clicked add another action and then submitted the modal @tomas-nava

**Comment by tomas-nava** [comment]
Can we put together a query that'll help us figure out whether this has happened more than once?

**Comment by youngfreezyVA** [comment]
@lowellrex and I paired and ran multiple queries and verified that this hasn't happened since February 6th. We will keep monitoring, if we need to manually remove the duplicate entries we can, so far have been unable to reproduce locally.

**Comment by lowellrex** [comment]
I think we may be seeing this in a postpone hearing modal: https://dsva.slack.com/archives/C42P25D6H/p1552586097054600

Perhaps Board employees using Caseflow have computers with such little horsepower that the browser can't draw the DOM updates as fast as we'd like and they are firing off simultaneous requests and we aren't able to reproduce this behaviour locally because our computers are just so much beefier? It's a longshot but it's a thought.
