### ISSUE TITLE
API Refactor: Appeals have complete set of docket attributes (post-MVP)

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9418]
## Goal:
Each appeal returned by the Appeal Status API should have the following **additional** docket attributes:
- `allDocketsTotal`
- `total`
- `ahead`
- `eta`

## Related:
- #8839 Appeals have docket attributes

**Comment by cmgiven** [comment]
`allDocketsTotal`: The total number of active appeals on any docket, including legacy and priority appeals.
`total`: The total number of nonpriority appeals on the same docket as this appeal.
`ahead`: The number of nonpriority appeals on the same docket as this appeal that are older than this appeal.
`eta`: An object showing time estimates on each docket (not including legacy) for appeals that were received on the same date as this appeal, rounded to the nearest month. Example:

```
{
  "direct_review": "2020-02-01",
  "evidence_submission": "2024-04-01"
  "hearing": "2024-07-01"
}
```

`eta` can be developed separately. VA.gov is progressively enhanced if all that's available is `allDocketsTotal`, `total`, and `ahead`.

Counting appeals on dockets is an intensive task that can't be done per-request. Instead, we should replicate the `DocketSnapshot` setup that is used for legacy appeals, taking snapshots of the dockets every day. `DocketTracers`, children of `DocketSnapshot` record the number of appeals ahead of appeals from a given month. Grouping appeals in this way is a kind of rounding that we decided was not problematic. What's more important is that these numbers update every day, so that Veterans see progress each time they log in.
