### ISSUE TITLE
Move closest regional office to Appeal objects

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#9425]
We currently store the closest regional office on the Veteran record. There are two problems with this.

1) Sometimes the appellant is not the Veteran. This means we will sometimes provide the wrong closest RO and available hearing locations.
2) It's hard to join Veteran records to Appeal records because Veteran records are tied directly to BGS Veteran records, and this data is messy and sometimes gets deduplicated. Also, in cases where the bfcorlid is not equal to the Veteran's file number, when we try to join between the task table and the veteran table through the legacy appeal table, we will not get any records. This means we might lose a task because it will never be associated with a closest regional office.

I think for these reasons, it might be a good idea to move the association of available hearing locations, and closest regional office to the appeal instead of the Veteran.

**Comment by lomaxap** [comment]
This makes sense.

For 1: do we have logic that already works out whether the appellant is the veteran? And if so, how reliable is the appellant address information (I'm assuming that isn't stored in BGS)? 

For 2: Is there any way to fix the fundamental problem with associating a VACOLs case/ legacy appeal with a Veteran where the bfcorlid is different from the file number? I don't think this decision rests on that answer, but I still don't quite understand how we can have an appeal where we don't know where/what the veteran record is. Doesn't that present problems in other parts of the application?

That said, I also like this because it makes the central office logic easier for legacy appeals. I dislike this only because it requires a rework that we probably will need to get done before the 19th. That makes me really nervous.

**Comment by mdbenjam** [comment]
I don't think this strictly needs to be done before 2/19. The sooner we do it the better, but things work pretty well right now. We just might lose some cases (and might not) until we make this change.
