### ISSUE TITLE
Intake | Fix undefined reference in client JS

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9555]
See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3796/ `Unable to get property 'value' of undefined or null reference`

**Comment by Sjones352** [comment]
@pkarman I tried reproducing this error and checking console for `Unable to get property 'value' of undefined or null reference` but there is nothing.  I enabled the ` FeatureToggle.enable!(:ramp_intake)` because it happens in the SelectForm component. I have a feeling this was a one off or it is no-longer happening. Not sure if we can close it since we disabled RAMP feature toggle.

**Comment by pkarman** [comment]
According to sentry it has happened several times but most recently over a month ago.

I'm happy to believe it was RAMP related and just close this as a won't fix. It it happens again we can re-visit.
