### ISSUE TITLE
Investigate decision issue data

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#9561]
We've noticed some decision issues using acronyms instead of writing out the full decision issue. This will create problems when the decision issues are saved to VBMS and become the next request issue - 

Examples:
* EED TDIU allowed
* Reopen NME BHL
* CUE in 1982 RD

## AC
- Analyze decision issue data in Looker to get a sense for how they are written
- Consider this during issues data project

## Ideas
* Add instruction for attorneys and judges to copy and paste from their decision document - "copy and paste the text from the order"

## Mock

(See notes in comment below)
![image](https://user-images.githubusercontent.com/40216950/57480140-ebd2b580-726c-11e9-8281-b65e5717bb19.png)

**Comment by allyceh** [comment]
![image](https://user-images.githubusercontent.com/40216950/55344697-06e72400-547c-11e9-9a28-a0a44e60f5da.png)

Above is an updated "Add decisions" modal that aims to address this issues along with other usability issues. Updates to this modal include research findings from usability sessions with attorneys. See "AMA Issues Feedback Sessions" in Mural for full takeaways from these sessions. 

Updates include: 
- Removed instructional text at top of modal. Users have same instructions on the page before, and they knew what this modal was for based on the fields (disposition, description, etc)
- Changed "Description" label to "Decision". Description was VACOLS jargon. 
- Added more instructional text to the "Decision" section so that attorneys are guided to copy + paste orders from the decision letter (desired behavior)
- Updated wording in bottom section (adding decision to more than one issue) and added "optional" so it didn't feel mandatory (this is actually an edge case).

**Comment by allyceh** [comment]
Removing myself as sole assignee and assigning to @sneha-pai and @laurjpeterson to prioritize for engineering.
