### ISSUE TITLE
ClaimDateDt invalid value

### ISSUE THREAD

**Issue by jiahuang** [department-of-veterans-affairs/caseflow#9643]
See https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3467/

 "The data value of the ClaimDateDt within the claimToEstablish did not satisfy the following condition: The ClaimDateDt value must be a valid date for a claim"

ClaimDateDt value for this ep is "2019-02-26" which looks correct

**Comment by pkarman** [comment]
This smells like a timezone bug so our tests should exercise some shifting time zones.

**Comment by pkarman** [comment]
Related https://github.com/department-of-veterans-affairs/caseflow/pull/9577

**Comment by leikkisa** [comment]
We need to delay submitting for processing for End Product Establishments if the claim_date is in the future.  This can happen because the claim_date is based on the receipt_date, and for DTA claims, this is based on the approx_decision_date.  This is sometimes entered by users in the UI.

**Comment by leikkisa** [comment]
Related #9794

**Comment by leikkisa** [comment]
Hopefully #9794 and tickets before it fixes this, but we'll need to wait and see if this error continues to pop up.

**Comment by Sjones352** [comment]
Hey Sally can you please provide validation instructions.

**Comment by leikkisa** [comment]
@Sjones352 

I think the best way to validate this might be checking if it happens any more in Prod because it seems to be caused by some timezone differences in the servers that will be difficult to reproduce, so I recommend waiting on this and then we can check the alerts for the last time it happened and see if it has happened after this fix. 

However, here are some instructions we could try also. There's no guarantee that these will reproduce the error though.

### Validation instructions
- Do a noncompensation AMA intake
- Add a request issue
- Go to the Noncompensation review page to make a decision on that request issue
- Give it a DTA error decision
- Give it a decision_date that is several days in the future
- Check on the same day that the decision_issue has a submitted_at of the future decision_date
- Check that the DTA Supplemental Claim doesn't get created until that decision_date

Note - if it tries before the decision date, it should fail with the ClaimDateDt isn't valid error.  However, if this happens it will eventually retry and succeed once the decision_date has come to pass.

**Comment by Sjones352** [comment]
**Currently staged in Uat** 
<img width="1219" alt="Screen Shot 2019-03-18 at 12 21 13 PM" src="https://user-images.githubusercontent.com/23080951/54545749-a71b5400-4978-11e9-9605-2376a2ce72ad.png">
<img width="1336" alt="Screen Shot 2019-03-18 at 12 22 27 PM" src="https://user-images.githubusercontent.com/23080951/54545750-a71b5400-4978-11e9-83f9-c7b68c2ee557.png">
<img width="1424" alt="Screen Shot 2019-03-18 at 12 22 59 PM" src="https://user-images.githubusercontent.com/23080951/54545752-a71b5400-4978-11e9-8dcb-7c714a5f2d9b.png">

I will check on the 03/24/2019 for decision_issue having a submitted_at of the future decision_date

**Comment by Sjones352** [comment]
This has a submitted issue of `establishment_last_submitted_at: "2019-03-18 16:21:20"`. @leikkisa any idea how I can validate this?
<img width="1130" alt="Screen Shot 2019-03-26 at 12 56 26 PM" src="https://user-images.githubusercontent.com/23080951/55017227-aad95700-4fc6-11e9-89a4-c5ddefea8709.png">

**Comment by leikkisa** [comment]
Sorry, I thought I had commented on this earlier, this revealed a bug unrelated to the timing, https://github.com/department-of-veterans-affairs/caseflow/issues/10171

There's a PR in for that one now, so we can try to validate them at the same time, woot.

**Comment by leikkisa** [comment]
Doesn't seem to be working in UAT:
Got this error for a remand supplemental claim
The data value of the ClaimDateDt within the claimToEstablish did not satisfy the following condition: The ClaimDateDt value must be a valid date for a claim.
https://sentry.uat.ds.va.gov/sentry/caseflow-uat/issues/1451/

The claim date is: Fri, 29 Mar 2019
The Sentry date is 12:02AM On March 29th
The establishment_submitted_at is: 2019-03-29 00:02:29

So the submitted_at date is being set correctly. Perhaps the VBMS server is in a different timezone?

**Comment by Sjones352** [comment]
@leikkisa if I were to do an  Appeal intake with a  processed_in_vbms, there is no business_line for compensation and pension.

**Comment by pkarman** [comment]
@Sjones352 you are correct. There are no lines of business records for compensation/pension. Those are processed entirely in VBMS. For an Appeal, if you pick a benefit type per-issue, you should be able to pick compensation or pension one issue, and a non-comp LOB for another.

**Comment by Sjones352** [comment]
@leikkisa I agree this doesn't seem to be working in UAT.  Maybe we can pair on this and figure out if VBMS server is in a different timezone or maybe ask Colin.

**Comment by leikkisa** [comment]
The fix was put in 12 days ago, and the last time we saw this error was in Sentry 13 days ago, so I'm going to consider this validated.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4598/events/300668/
