### ISSUE TITLE
Intake | Add EP comparison to EPE sync

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9784]
Currently an End Product for HLR or SC may change code type upstream in VBMS and the EPE in Caseflow would have the wrong claim type and code. E.g. https://github.com/department-of-veterans-affairs/appeals-support/issues/4332

Add a check as part of the regular status sync that compares the code on the EP against the EPE code and verify they still match. That will at least give us advance notice that something is amiss in the data quality of what Caseflow has.

## Technical Note

* Raise an aptly named exception if a code value mismatch is found. Do not automatically change any values in Caseflow.

**Comment by leikkisa** [comment]
https://dsva.slack.com/archives/CFBLH2LR4/p1553271436099900

**Comment by leikkisa** [comment]
@pkarman I'm reluctant to work on this ticket because it'll add noise to the alerts.  I imagine the updated EP code data being used to triage a specific data issue, or to handle a group of them in batch if they're a problem. The alerts won't help with that, but we could get the info other ways when we need it.

How do you feel about moving this to the backlog or closing it?

**Comment by pkarman** [comment]
I'm concerned that we have data changing upstream that we don't know about. As a result we're discovering things weeks after the fact. I had hoped an alert would spur more immediate action. It's a bit of a chicken-and-egg since
> we could get the info other ways when we need it.
we may not know we need it till long after the fact.

In that sense I wouldn't consider it noise but signal. If we found a pattern in these alerts, we could take action to prevent it happening.
