### ISSUE TITLE
Issues with timeliness exceptions aren't showing up in Queue

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9789]
After migrating all the prior decisions, there are a couple issues remaining that do not have decisions. The thing these issues have in common are that they were untimely, but have exceptions.

It looks like they are not showing up as eligible issues in Queue.

## Technical notes
I believe the reason is because `ineligible_reason` is set, and that's the criteria queue is using to determine whether an issue is eligible.

The affected issues are request issue ids: 4568, 4725

**Comment by leikkisa** [comment]
Issue 4568 is ineligible because it is from before_ama

Issue 4725 has a timeliness_exemption of false, but it does has timeliness_exemption_notes filled out with "This issue was raised in conjunction with the IR claim on appeal in the context of Rice "

There are no request issues with timeliness_exemption set to true that have an ineligible_reason of "untimely".  So there isn't really a bug here, but there are many issues that have timeliness exemption notes, but timeliness exemption set to false.  We are wondering from a usability perspective if this is confusing.

**Comment by leikkisa** [comment]
I would like to close this, but first I want to ask if there are people that we should report these results to, and if there's any desire to ask a product/design person if we should iterate on the design (and if yes, add a ticket for that).

**Comment by leikkisa** [comment]
For the one that has before_ama, if they remove it and re-add it, it should be eligible again for now because we turned off the "before_ama" requirement temporariliy.

**Comment by carolaponce** [comment]
Is part of the issue users writing notes about timeliness even though the veteran has not requested a time extension?

**Comment by leikkisa** [comment]
Yes, we're wondering if it's confusing for folks because there are a bunch of RequestIssues with a note added, but with "no" selected as the option.  This would be relatively easy for me to change too so I can go ahead with it if desired.

![Screen Shot 2019-03-11 at 6.20.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa9b7c9e7d70200133c2088/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206455f26b7191a37ef1102b4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5d33c5d22c33413a5b8d41bbf50bd208b1d87b3bc891ed2f42f67b6d5db1063474f4dcbed5727a19041c95df349e24856a2113765e6732431.png)

**Comment by leikkisa** [comment]
Looks like it could use some spacing above the radio too :-P

**Comment by Sjones352** [comment]
@leikkisa can you please add some validation instructions.

**Comment by leikkisa** [comment]
#### Validation instructions
- Do a HLR or Appeal intake
- Add an old issue. If there's not an old rating issue, add a nonrating issue and make it's decision date a couple of years before the receipt date
- It should ask you if the Veteran requests a timeliness exemption with a radio button, but not have a notes field.  If you select "Yes" it should show the notes field.

That's it!

**Comment by Sjones352** [comment]
**Passes UAT** 

<img width="1431" alt="Screen Shot 2019-03-28 at 9 04 53 PM" src="https://user-images.githubusercontent.com/23080951/55202394-9dc29080-519d-11e9-8ef4-eea2493ef92c.png">
<img width="795" alt="Screen Shot 2019-03-28 at 9 06 11 PM" src="https://user-images.githubusercontent.com/23080951/55202395-9dc29080-519d-11e9-803e-9b9287265eb6.png">
<img width="832" alt="Screen Shot 2019-03-28 at 9 07 02 PM" src="https://user-images.githubusercontent.com/23080951/55202396-9e5b2700-519d-11e9-97d5-e4d03a3c47f8.png">
<img width="1395" alt="Screen Shot 2019-03-28 at 9 07 23 PM" src="https://user-images.githubusercontent.com/23080951/55202397-9e5b2700-519d-11e9-9c0d-3df1a8ec6457.png">
