### ISSUE TITLE
Intake | Bust cache on Veteran multiple phone exception

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9795]
When a Veteran suffers from the multiple active phone exception, bust the cache on the `can_access?` BGS call so that if a user fixes the problem in SHARE, they do not need to wait for 24 hours to proceed in Caseflow.

**Comment by Sjones352** [comment]
@leikkisa please provide validation instructions

**Comment by pkarman** [comment]
Validation instructions:

* identify a Veteran in UAT with duplicate phone number records. IIRC Colin was researching this.
* attempt an Intake for that Veteran
* confirm the special phone number error message
* resolve the duplicate phone numbers in UAT
* immediately try the Intake again in UAT. The error message should not appear.

**Comment by Sjones352** [comment]
Asked Colin to create me a veteran with duplicate phone number.

**Comment by Sjones352** [comment]
This is going to be a hard one to validate as VBMS does not create Veteran with phone number records. @leikkisa do you know anyone at BGS who might be able help us?
<img width="282" alt="Screen Shot 2019-04-25 at 10 21 18 AM" src="https://user-images.githubusercontent.com/23080951/56743246-3bc95c80-6744-11e9-8d3b-072117a8bd54.png">

**Comment by leikkisa** [comment]
@Sjones352 I think we should validate in prod with our users. I asked someone about that, and they're getting an error trying to update the Veteran's phone numbers in VBMS, so we probably can't validate this anyway until that issue is fixed.

**Comment by leikkisa** [comment]
I learned during a BGS/VBMS meeting that users cannot update the phone number themselves, so we won't be able to validate this.  Data clean up is being led by a person named Jack Goldberg.  I've heard that they've merged all instances where the multiple phone numbers matched each other. If they didn't match, but were valid, they picked the newest phone number. The remaining cases have invalid phone numbers.

I am closing this issue since we can't validate it.
