### ISSUE TITLE
Inquire about Converted Backfilled ratings

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9802]
After we get a handful of Converted or Backfilled ratings reported in Sentry, collect them and ask Linda to check in on them and let us know what they are for, and their dates.

Part of the reason for this is because we want to check that they are not converted from the old system, and therefore potentially technically equivalent to promulgated ratings even if they aren't promulgated in the new system.  We should also check if they are super old.

Once we have a better understanding of these and can confirm that these are legitimately not ratings that should be showing up, then we can remove the Sentry alert for them.

**Comment by mc-usds** [comment]
Updating with Linda's findings:

All but 698311 did not have a “real” rating.  The entry of certain decisions in Awards currently updates the Rating Profile.  It has been requested that we eliminate Awards from updating the Rating (due to more than one defect), and we have received approval to start the application design.  It is a very large item, and is not planned until after May.  It will require a lot of work and a lot of testing.
 
939516 - Separate certain Award Decns from Rating Profile  - VETSNET 896075 - (Story) - VBMS Defect_691735
 
That being said, these three are CPD (Compensation and Pension) Claims/Awards that were disallowed.  The only appealable decisions are Awards Decisions.    698311 had an older converted rating but all of these have an empty RatingProfile object – no decisions, no claims attached, nothing.
 
participant ids: 46207149,
This one is interesting.  No rating decisions were created at all.   The CPDS Award is a disallowance
Two Basic Eligibility Decisions (Award Decisions)
Denied-Not entitled to MOD               
Denied-Failed to Furnish Requested Evidence
 
Summary, no ratings exist. 
 
49917308
Same as above
 
698311,
Veteran was originally converted back in 2002.  Now a CPDS claim comes in.
CPDS Award is a disallowance
Eligible for CPDS, but denied due to excess income.  (Award Decisions)
 
These two are veteran CPL awards for Pension that were both denied/a disallowance.  The only appealable decisions are Awards Decisions.   All have an empty Rating Profile object – no decisions, no claims attached, nothing.
 
12258641
No rating decisions were created at all.   The CPL Award is a disallowance
One Basic Eligibility Decisions –
Denied-Failed to Furnish Requested Evidence
 
Summary, no ratings exist. 
50031086
CPL
No Rating Decisions, Award is a Disallowance
Basic Eligibility Decision
Denied-Failed to Furnish Requested Evidence

**Comment by leikkisa** [comment]
I am closing this, with the note that BGS is doing some work to fix bugs with backfilled ratings, so we will want to check in with them again at some point during our meetings to see how that goes.
