### ISSUE TITLE
Paper case notification

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#9887]
We should display the same paper case notification that queue uses in their application in the following places:

### AC

- [ ] Add `<span>{COPY.IS_PAPER_CASE}</span>` to left column of daily docket rows

**Comment by ShellySmithDSVA** [comment]
We are currently speaking with the Queue team since the Paper Case notification seems to have disappeared from the Case Details page. We would like the Paper Case notification to be listed under the Docket Number. See the screenshot below.
![Screen Shot 2019-03-15 at 2 05 49 PM](https://user-images.githubusercontent.com/45463980/54452507-b8bbec00-472b-11e9-88b3-df525b967ca9.png)

**Comment by MeredithStewart** [comment]
What's weird, is that I thought we also had this on the Daily docket before and it's now missing.

**Comment by ShellySmithDSVA** [comment]
We checked with Queue about the paper case listing and I will follow up with them today. Do we need to do anything else with this ticket before moving it over to be worked?

**Comment by MeredithStewart** [comment]
I think this is ready!
