### ISSUE TITLE
Intake Edit | Withdrawal confirmation for Caseflow based decision reviews

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9988]
We need to show a confirmation for users that issues were withdrawn.

All withdrawal/removal mocks: https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens/351540954

requires https://github.com/department-of-veterans-affairs/caseflow/issues/9985

## Acceptance Criteria
- When a save is processed on the Add/Remove issues screen for a Caseflow based review where one or more issues were withdrawn. There should be a notification that there were issue(s) withdrawn on the notification alert on the case details page.
- If an entire decision review is withdrawn, it should behave the same as the "Review Removed" confirmation. Except it should say "Review Withdrawn" (see: https://github.com/department-of-veterans-affairs/caseflow/issues/9734)

## Mocks
<img width="1169" alt="Screenshot 2019-03-14 17 15 31" src="https://user-images.githubusercontent.com/1596259/54399722-ff9ed880-467c-11e9-955e-9501e662a3e1.png">

## Notes
- VBMS based withdraws will be handled here: #9987

**Comment by leikkisa** [comment]
Let's wait until Carola comes back to ask about this. Except for the "this issue:" part, this mock seems to be for withdrawing the entire review.

**Comment by carolaponce** [comment]
Confirmation: This would show the issue withdrawn not the review title

**Comment by carolaponce** [comment]
@leikkisa This is the updated confirmation format - this is the modular confirmation that gets added to the Reviews needing action page for non-comp LOB or if this confirmation is included in queue.

Since we are changing the add/remove title to Edit issues - the confirmation reflects that and the message is simplified.

![simplified_confirmation](https://user-images.githubusercontent.com/11700545/56155455-c6a19e80-5f6f-11e9-8366-0f02d1241e6d.png)

**Comment by leikkisa** [comment]
Validated in UAT:
Could use some space below it though.

![Screen Shot 2019-05-01 at 5.29.13 PM.png](https://images.zenhubusercontent.com/58f6b6eb51aa2c30577bb60e/ba9b66ff-0c37-4265-9393-e50f1a55623c)
